### ISSUE TITLE
downloadFile

### ISSUE THREAD

**Issue by Vo0oX** [yagop/node-telegram-bot-api#1003]
I send some photos to the bot (2-10)
how can i save them all in one go? To then send to another user

**Comment by danielperez9430** [comment]
If you get all the photos as a "gallery" only one message you dont need to download it. You can use the method copyMessage or in the other case you need to download file by file. Because the oficial Telegram Bot API don't have a method to bulk download in only one call

**Comment by Vo0oX** [comment]
> If you get all the photos as a "gallery" only one message you dont need to download it. You can use the method copyMessage or in the other case you need to download file by file. Because the oficial Telegram Bot API don't have a method to bulk download in only one call.
> 
> Example of use`bot.downloadFile(...)` -> [#867 (comment)](https://github.com/yagop/node-telegram-bot-api/issues/867#issuecomment-1172660816)

https://www.dropbox.com/s/k4mzmu7igwenhxb/IMG_2286.MOV?dl=0

**Comment by danielperez9430** [comment]
I see your video @Vo0oX but in Telegram MacOs you need to have enable the this button in blue (the one is near the X)
 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/10388515/188493287-13614b96-c545-4d63-87b8-f8861aeab47c.png">

**Comment by Vo0oX** [comment]
> If you get all the photos as a "gallery" only one message you dont need to download it. You can use the method copyMessage or in the other case you need to download file by file. Because the oficial Telegram Bot API don't have a method to bulk download in only one call.
> 
> 
> 
> Example of use`bot.downloadFile(...)` -> https://github.com/yagop/node-telegram-bot-api/issues/867#issuecomment-1172660816

when I listen to “message” and send 2 photos to the bot, I receive two messages.  when 3 photos - 3 messages.  how can i determine how long i have to wait?  before writing them to the database and sending them to the user ?
