### ISSUE TITLE
media_group_id does not work for PC version

### ISSUE THREAD

**Issue by Vo0oX** [yagop/node-telegram-bot-api#1004]
when I select 2 or more photos from the computer, a message arrives without the media_group_id mark

**Comment by danielperez9430** [comment]
I think you are send your images not as a gallery in the desktop. Because the media_group_id you can only get it when you send 2 or more media (photos/videos/files/..) in 1 message.

**Comment by danielperez9430** [comment]
> > I think you are send your images not as a gallery in the desktop. Because the media_group_id you can only get it when you send 2 or more media (photos/videos/files/..) in 1 message.
> 
> https://www.dropbox.com/s/k4mzmu7igwenhxb/IMG_2286.MOV?dl=0

I see your video @Vo0oX but in Telegram MacOs you need to have enable this button in blue (the one is near the X). When you have this button enabled your message is send as a gallery (Max 10 items per message)
 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/10388515/188493287-13614b96-c545-4d63-87b8-f8861aeab47c.png">

**Comment by Vo0oX** [comment]
> > > I think you are send your images not as a gallery in the desktop. Because the media_group_id you can only get it when you send 2 or more media (photos/videos/files/..) in 1 message.
> 
> > 
> 
> > https://www.dropbox.com/s/k4mzmu7igwenhxb/IMG_2286.MOV?dl=0
> 
> 
> 
> I see your video @Vo0oX but in Telegram MacOs you need to have enable this button in blue (the one is near the X). When you have this button enabled your message is send as a gallery (Max 10 items per message)
> 
>  
> 
> <img width="411" alt="image" src="https://user-images.githubusercontent.com/10388515/188493287-13614b96-c545-4d63-87b8-f8861aeab47c.png">

Thanks for the tip, is it the same for Windows?

**Comment by danielperez9430** [comment]
In windows you have a checkbox for group items, but only works if all the items that you send is from the same type (Only images, only gifs, ...). In Mac you can mix without problem

**Comment by Vo0oX** [comment]
> In windows you have a checkbox for group items, but only works if all the items that you send is from the same type (Only images, only gifs, ...). In Mac you can mix without problem

thanks for the answer!
