### ISSUE TITLE
Telegram Bot posts in channel not returned in getUpdate query

### ISSUE THREAD

**Issue by eviljoen** [yagop/node-telegram-bot-api#1005]
> Question

I'm posting Tradingview triggers into Telegram channel, I then want to retrieve them using https://api.telegram.org/botxxxxxxxxx/getUpdates to be able to place a trade in Bybit.

I find that the entries made by the TelegramBot are not retrieved with this command, only message from users.

My question is what do I need to do to be able to have the bot channel posts in my getupdates?

**Comment by danielperez9430** [comment]
Hi, you use the event `bot.on('channel_post', (msg) => {})`?

**Comment by akash87** [comment]
Doesn't make sense, what if someone wants to list messges and not listen to them ?
