### ISSUE TITLE
Migrate away from request (deprecated)

### ISSUE THREAD

**Issue by danger89** [yagop/node-telegram-bot-api#1007]
Your code is using `request` and `request-promise` packages. However this package is no longer maintained! Please don't use it anymore.

More info: https://github.com/request/request/issues/3142

See alternatives: https://github.com/request/request/issues/3143 !

**Comment by danielperez9430** [comment]
Is planed to change it at some point

**Comment by danger89** [comment]
"At some point", means "never" 🤣 

Hint: Personally I use `axios` with much stability and joy.

**Comment by danielperez9430** [comment]
No never, I'm thinking of doing it when I finish with some things that I have in refactor. Yes, recently in the last update we removed dependencies and included fixes. 

As soon as I can I will put on it one of these weekends

**Comment by danielperez9430** [comment]
Close this issue for the moment I label this other one https://github.com/yagop/node-telegram-bot-api/issues/1038
