### ISSUE TITLE
setMyCommands causes ETELEGRAM: 400 Bad Request: BOT_COMMAND_INVALID

### ISSUE THREAD

**Issue by Ollisteka** [yagop/node-telegram-bot-api#1008]
Hi! I'm trying to set a commands list, like so:
```
bot.setMyCommands([
    { command: 'myInfo',       description: 'Сохранённая информация обо мне' },
    { command: 'countersInfo', description: 'Сохранённые показания' },
    { command: 'fillCounters', description: 'Ввести показания' },
    { command: 'sendCounters', description: 'Отправить показания' }
]);
```

But instead of a successful answer I get `Unhandled rejection Error: ETELEGRAM: 400 Bad Request: BOT_COMMAND_INVALID`

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library, 0.59.0

**Comment by Ollisteka** [comment]
Oh, nevermind, realized, that the letters should've been all lower case, not lowerCamelCase

**Comment by klokovsergei** [comment]
Thanks. Ur advice really helps me 🤗🤗🤗
