### ISSUE TITLE
Sending photo timeout

### ISSUE THREAD

**Issue by ranlandau** [yagop/node-telegram-bot-api#101]
Follow code:
`photoURL = './' + chatId + '.png';
var stream = fs.createReadStream(photoURL);  
bot.sendPhoto(chatId,stream , {caption: 'Ad Example'}, function (msg, err) { console.log(err);});         });

Doesn't work,
few seconds later:

> Unhandled rejection Error: 504 <html>
> <head><title>504 Gateway Time-out</title></head>
> <body bgcolor="white">
> <center><h1>504 Gateway Time-out</h1></center>
> <hr><center>nginx/1.6.2</center>
> </body>
> </html>

 `

Any idea?

Thanks!

**Comment by rusfearuth** [comment]
I have the same problem with sending photo as URL. =/

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>
```
