### ISSUE TITLE
[Question] Can't manage to use protect_content on sending messages.

### ISSUE THREAD

**Issue by tambu22** [yagop/node-telegram-bot-api#1018]
I'm trying to send messages and protect them from forward and save.

My code: 
`bot.sendMessage(chatId, messageText, {
    parse_mode: "Markdown",
    protect_content: true,
    reply_markup: JSON.stringify({
      inline_keyboard: myInlineButtons
    }),
  });`

Lib version:     "node-telegram-bot-api": "^0.56.0",

**Comment by danielperez9430** [comment]
Hi @tambu22 The method works like you did, and also the content have this flag (you can see it on reply to the message in your bot. The problem of the "forward" and "save" is more Telegram Clients (how it works). And yes, a protected content is possible to save in your device.

For example in Telegram MacOs when you forward a protected message you have something like this:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/10388515/200149949-eb94c9ea-f598-4ca7-be64-124b339cfce7.png">

But if you click on retry the client send the message as copy... So yes, the protected content implementation from Telegram is something weired.
