### ISSUE TITLE
[Question] 0.x.x vs 1.x.x

### ISSUE THREAD

**Issue by CrackerakiUA** [yagop/node-telegram-bot-api#1023]
> Question

Why did you use version 0.x.x, usually it's for uncompleted products, which people don't want to use in production.

**Comment by danielperez9430** [comment]
X.0.0 versions is only for mayor version with breaking changes. In this case this repo start at 0.X.X. So we only release for the moment minor and patch versions. 0.X.X is not related to uncompleted products. All depends how you follow the semantic releases rules. Some people start at 0 other at 1...
