### ISSUE TITLE
listen for message deletion

### ISSUE THREAD

**Issue by DarkCoder15** [yagop/node-telegram-bot-api#1029]
> Question
I'm making a bridge bot and I want to listen whether a message is deleted.
is there any way to do so?

**Comment by danielperez9430** [comment]
The Telegram Bot API don't send any event related to the deleted messages. Maybe you can store all the ids of the messages in the database and using a userbot (tdlib or similar) you can do a check every day or similar of the list of the messages... but I think is not too easy

**Comment by adougies** [comment]
I notice TDLib does have an event to listen for message deletion (updateDeleteMessages), can this now be achieved in NTBA? Can't use TDLib due to some issues.
