### ISSUE TITLE
Can't ban with user_id

### ISSUE THREAD

**Issue by mattou78400** [yagop/node-telegram-bot-api#1034]
Hi,

I'm trying to ban a user based on the user_id as per the method: 
https://core.telegram.org/bots/api#banchatmember

<img width="569" alt="image" src="https://user-images.githubusercontent.com/39678117/206934538-d7db2a4a-9a5b-43a8-89ed-e635ade2e299.png">

Here's how I call it

but I keep getting this error
![image](https://user-images.githubusercontent.com/39678117/206934611-19e0e353-addb-4054-89e2-6b91f17a48f1.png)

I'm sending in the ID I get from msg.from.id

Can someone point me what I am doing wrong?

thanks!

**Comment by danielperez9430** [comment]
Because you pass wrong the params. The last param is a object with the optional params

`bot.banChatMember(chatId, userId, { unitilDate })`
