### ISSUE TITLE
TypeError: bot.getChatMembersCount is not a function

### ISSUE THREAD

**Issue by vhforbes** [yagop/node-telegram-bot-api#1049]
I'm trying to get the number of members using getChatMembersCount

I'm getting a typeError saying that  "bot.getChatMembersCount is not a function"

![image](https://user-images.githubusercontent.com/39014716/216840414-d0a6f7eb-b058-4c3a-a1aa-67efb8e3314e.png)

This is my first issue on github, overall I'm really enjoying the bot, if it is my mistake, I would be really glad if someone can point it out!

Really appreciate.

**Comment by VDS13** [comment]
> I'm trying to get the number of members using getChatMembersCount
> 
> I'm getting a typeError saying that "bot.getChatMembersCount is not a function"
> 
> ![image](https://user-images.githubusercontent.com/39014716/216840414-d0a6f7eb-b058-4c3a-a1aa-67efb8e3314e.png)
> 
> This is my first issue on github, overall I'm really enjoying the bot, if it is my mistake, I would be really glad if someone can point it out!
> 
> Really appreciate.


The function is called `getChatMemberCount`, not `getChatMembersCount`.

**Comment by vhforbes** [comment]
Ok, the function works now! But after reviewing the @types of the package, it explicitly says:

`getChatMembersCount(chatId: TelegramBot.ChatId): Promise<number>;`

So typescript throws a error because the typing is wrong when using it in the singular:  `getChatMemberCount`.

**Comment by danielperez9430** [comment]
Yep, we talk about this some days ago in the telegram group, the method is `getChatMemberCount`, not plural. But someone that do the types in the Types repo put the name wrong

**Comment by VDS13** [comment]
> Ok, the function works now! But after reviewing the @types of the package, it explicitly says:
> 
> `getChatMembersCount(chatId: TelegramBot.ChatId): Promise<number>;`
> 
> So typescript throws a error because the typing is wrong when using it in the singular: `getChatMemberCount`.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64271
