### ISSUE TITLE
sendContact function

### ISSUE THREAD

**Issue by SemihAkar** [yagop/node-telegram-bot-api#105]
Hello,

Is there a plan to add sendContact function to api?

**Comment by GochoMugo** [comment]
We are waiting on PR# #124 to add the TelegramBot#sendContact() method. However, [TelegramBot#sendVenue()]() has been added in PR #121, package v0.24.0.

**Comment by GochoMugo** [comment]
This has been added in v0.25.0!

Thanks @SemihAkar for your interest in this library!
