### ISSUE TITLE
How I Can download Gif photo

### ISSUE THREAD

**Issue by AnasAlrini** [yagop/node-telegram-bot-api#1053]
I used photo and documents download way , do't work

**Comment by VDS13** [comment]
> I used photo and documents download way , do't work

yagop/node-telegram-bot-api/blob/master/doc/api.md#TelegramBot+sendAnimation

**Comment by VDS13** [comment]
> > > لقد استخدمت طريقة تنزيل الصور والمستندات ، لا تعمل
> 
> > 
> 
> > yagop / node-telegram-bot-api / blob / master / doc / api.md # TelegramBot + sendAnimation
> 
> 
> 
> Did't open 😭

Fixed.
