### ISSUE TITLE
How to trigger bot function on start? 

### ISSUE THREAD

**Issue by RasmonT** [yagop/node-telegram-bot-api#1063]
Hello guys,

I try to understand how to trigger action on the bot starts, I didn't see anything for this even in the documentation.
How can I trigger let's say console.log once bot is online? 

```
bot.on('ready', () => {

    console.log('Bot started!')

});
```

I was looking for something like this, but I don't know how to do it in this Library. Any ideas?

**Comment by yokkkoso** [comment]
```js
const bot = new TelegramBot(token, {
  polling: false,
});

function start() {
  void bot.startPolling();
  console.log('Bot started');
}

```

**Comment by RasmonT** [comment]
Thanks :-) 

By the way I found another solution and this works also fine for me. 

```
bot.getMe().then((me) => {
    console.log(`Bot started as @${me.username}`);
  }).catch((error) => {
    console.error(error);
  });
  ```
