### ISSUE TITLE
telegram bot API 6.6 support

### ISSUE THREAD

**Issue by pandawengogo** [yagop/node-telegram-bot-api#1066]
> Feature Request
Pls support telegram bot API 6.6
[https://core.telegram.org/bots/api#setmydescription](https://core.telegram.org/bots/api#setmydescription)

**Comment by danielperez9430** [comment]
Today night I can do it, because this weekend I dont have time to do it

**Comment by pandawengogo** [comment]
> 

Thank you.

**Comment by xixi25860** [comment]
Any update on this for API 6.6 and 6.7

**Comment by danielperez9430** [comment]
Only missing to finish the refactor or [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset) and
 [addStickerToSet](https://core.telegram.org/bots/api#addstickertoset)

Thi is the pull request: https://github.com/yagop/node-telegram-bot-api/pull/1069
