### ISSUE TITLE
How can I enable bot status sending a photo 

### ISSUE THREAD

**Issue by 4mlsx** [yagop/node-telegram-bot-api#1067]
I have a bot I need to add bot status sending a photo

**Comment by danielperez9430** [comment]
You need to use the method "sendChatAction"

`bot.sendChatAction(chatId, "upload_photo")`

**Comment by Amalbro07** [comment]
Ok I have the status but it doesn't show when the user generates another image

**Comment by danielperez9430** [comment]
You need to call the sendChatAction and wait some seconds before send the image. Or the status is not show to user. Becuase you send the chatAction + the file at the same time. So the chatAction is not display in the client because you send the media in the end
