### ISSUE TITLE
kickChatMember is not a function

### ISSUE THREAD

**Issue by uris173** [yagop/node-telegram-bot-api#1079]
```
let userId = msg.from.id
await bot.kickChatMember(chatId, userId)
```
kickChatMember function does not work. gives an error message

```
await bot.kickChatMember(chatId, userId)
                ^
TypeError: bot.kickChatMember is not a function
```

**Comment by danielperez9430** [comment]
Hi @uris173 
The method kickChatMember is not exists anymore in the Telegram bot api. Was remove a long time ago.

You need to use now the `"banChatMamber(chat_id, user_id, { until_date: XX })`" for replicate the some logic

https://core.telegram.org/bots/api#banchatmember
