### ISSUE TITLE
Phone keyboard when open web app

### ISSUE THREAD

**Issue by smisyuk4** [yagop/node-telegram-bot-api#1097]
Hi to all.
I have a problem with the phone keyboard in the Telegram web app.

if the page that opens contains a form or fields where you can enter text from the keyboard, then scrolling the open window does not scroll the content

* [demo video](https://youtube.com/shorts/ZeZzLx-FLsg?feature=share)
* 
![IMG_2048](https://github.com/yagop/node-telegram-bot-api/assets/51460801/8c98c46b-242e-4432-9ca1-8ba5f22ebb9b)

the operating system of the phone is ios and android - the result is the same. the phone keyboard closes the content of the web app

if I remove focus from the input, the keyboard hides and I can choose another input field, but this is a bug and not convenient. Not all users will try to do this, so they will simply close the window and leave the bot.

### Example

    await bot.sendMessage(chatId, 'Відправити оголошення', {
      reply_markup: {
        inline_keyboard: [
          [{ text: 'Заповнити форму', web_app: { url: urlReact } }],
        ],
      },
    });

### Question

how can I wrap my page or what should I write in the methods so that the content of the web app is fully accessible when the theophone keyboard is open?

**Comment by vkruglikov** [comment]
This is the usual behavior in WebApp apps. When you focus on input, mobile keyboard always will open

**Comment by smisyuk4** [comment]
thanks for the answer

**Comment by smisyuk4** [comment]
thanks for the answer

**Comment by pavelivanov** [comment]
I faced the same problem, @vkruglikov the question was how to solve the problem that the content of webpage not scrolling when an input focused (and a keyboard is opened)..

**Comment by FedorSherbakov** [comment]
I think the question is to telegram developers, not to the author of this library

**Comment by smisyuk4** [comment]
I made a crutch - increased the distance from the last button on the page to the bottom of the page. this is how a void appeared, which has no useful content and is not overlapped by the keyboard. By the way, nothing interfered with Android.

**Comment by EdVollmond** [comment]
> I made a crutch - increased the distance from the last button on the page to the bottom of the page. this is how a void appeared, which has no useful content and is not overlapped by the keyboard. By the way, nothing interfered with Android.

Дякую, гарний костиль!

**Comment by bohdan-krupa** [comment]
Також зіштовхнувся з цією проблемою 2 роки тому, зараз вирішив повернутись до проекту. @smisyuk4 підкажи будь ласка, як в результаті найкраще зробити?

**Comment by smisyuk4** [comment]
@bohdan-krupa я нового нічого не вигадував, залишив костиль - внизу збільшений відступ. Візуально користувач не бачить змін. Але телеграм браузер прокручує вище мою сторінку і поля форми доступні.
![image](https://github.com/user-attachments/assets/c996dd83-e1d3-4c2a-85d9-304cda033981)

**Comment by zersz2023** [comment]
there's still no good solution?
