### ISSUE TITLE
Process finished with exit code -536870873

### ISSUE THREAD

**Issue by Dr-klo** [yagop/node-telegram-bot-api#1099]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

Telegram bot works properly

### Actual Behavior

Process finished with exit code -536870873

### Steps to reproduce the Behavior

I copied code snippet from main page then made js file, pasted code, apply NTBA_FIX_319 fix and run via node v14.21.1 and process exited unexpectedly

**Comment by danielperez9430** [comment]
Node 14 looks to old. Use node 18 lts or 16 (end of life now)
