### ISSUE TITLE
Sending Gif example

### ISSUE THREAD

**Issue by highfredo** [yagop/node-telegram-bot-api#11]
Currently to send an animated gif you must use the method "sendDocument", but in the example you use "sendPhoto" so it's a little confused...

Anyway, I think the method "sendPhoto" would support sending animated gif, don't you?

Pd: thank you for this wonderful api!!

**Comment by yagop** [comment]
Sorry, the example might be confusing. I am sending a static GIF [`bot.gif`](https://github.com/yagop/node-telegram-bot-api/blob/master/test/bot.gif) as a photo on the examples.

I will change it, thanks.

**Comment by Zig1375** [comment]
When this bug will be fixed?

**Comment by SalamiArmy** [comment]
I was so confused until I found this thread. Just couldn't understand why my bot kept saying "{"ok":false,"error_code":400,"description":"[Error]: Bad Request: there is no photo in request"}"

**Comment by krokofant** [comment]
This should be mentioned in the docs. Very misleading when sending gifs. :-)

**Comment by GochoMugo** [comment]
We have added [some help information](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/help.md#gifs) on this issue!
