### ISSUE TITLE
The sent videos do not display the thumbnail.

### ISSUE THREAD

**Issue by cenosito** [yagop/node-telegram-bot-api#1101]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library:
### Expected Behavior

Every time I send a video to the bot, it is received without displaying the thumbnail.

I have used other bots from other users, and they do show the thumbnail in the videos.

In my case, it shows a black or white screen, depending on whether I view it on mobile or PC.
I have tried different MP4 files downloaded fromdiferents websites, like:

https://file-examples.com/index.php/sample-video-files/sample-mp4-files/

I have also tried using videos downloaded from other users' bots that showed the thumbnail, and the result is the same.

This is the result of a video from a user's bot that does display the thumbnail:

http://imgfz.com/i/Ve2zwXG.png

This is the same video, but uploaded by my bot, which does not display the thumbnail:

http://imgfz.com/i/l4ROSvf.png

The method I use to upload the video is:

bot.sendVideo(chatId, "test.mp4");

**Comment by cenosito** [comment]
After several tests with various types of mp4 files and sizes, I have been unable to make any type of video uploaded by my Telegram bot obtain the automatically generated thumbnail by Telegram. Any ideas?

**Comment by cenosito** [comment]
Solved reading documentation

**Comment by raccoondoggie** [comment]
Can you share the code or the part of document that helped you?
I have had exactly the same problem since February, I really need to solve tihs problem

**Comment by maxikgreat** [comment]
@raccoondoggie 

> Thumbnail of the file sent; can be ignored if thumbnail generation for the file is supported server-side. The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320. Ignored if the file is not uploaded using multipart/form-data. Thumbnails can't be reused and can be only uploaded as a new file, so you can pass “attach://<file_attach_name>” if the thumbnail was uploaded using multipart/form-data under <file_attach_name>. [More information on Sending Files »](https://core.telegram.org/bots/api#sending-files)

from [telegram official docs](https://core.telegram.org/bots/api#sendvideo)

**Comment by ningtt** [comment]
**What is the best solution to this problem? If anyone has solved it, I hope you can let me know. Many thanks**

**Comment by Sagleft** [comment]
## JPEG format and less than 200 kB in size
