### ISSUE TITLE
How can i stop listening for a specific user onText message?

### ISSUE THREAD

**Issue by m0x61h0x64i** [yagop/node-telegram-bot-api#1103]
Hello, i want to stop listening for '/start' command when the user enters '/start', i have tried `bot.removeTextListener(/\/start/)` but this will remove listening for all users, i only want to stop listening for a specific user, how can i do this ?

my code is : 
```
bot.onText(/\/start/, async (msg) => {
    console.log('start listener is working...')
    bot.removeTextListener(/\/start/)
})
```

**Comment by m0x61h0x64i** [comment]
How can i listen for a specific user messages ?! bot.on('message', ...) this will listen for all user messages

**Comment by VDS13** [comment]
```js
var users = new Map();
bot.onText(/\/start/, (msg) => {
    if (users.get(msg.chat.id) === 'undefined') {
        //first "start"
        users.set(msg.chat.id, 1)
        //...
    } else {
        //...
    }
})
```
