### ISSUE TITLE
Applying style/formatting to message depending on user input

### ISSUE THREAD

**Issue by Txxxthless** [yagop/node-telegram-bot-api#1105]
How can I send a message back to user with the given styling?

Example: user is sending a message, which is received with entities field:

<code>entities: [
    { offset: 3, length: 58, type: 'bold' },
    { offset: 110, length: 375, type: 'italic' }
  ]</code>

Is there a way to apply this styling to the message, sent from bot with sendMessage() or sendMediaGroup() methods?

**Comment by VDS13** [comment]
@Txxxthless,
https://core.telegram.org/api/entities
