### ISSUE TITLE
How to add chat_id of private group or channel

### ISSUE THREAD

**Issue by MananKansara09** [yagop/node-telegram-bot-api#1107]
- I want to know on bot.sendmessage() defination we have to mention chatId but in private channel and group we can't send the message.

**Comment by danielperez9430** [comment]
What? You need to have the bot inside the group and in the case of the channel need to be an admin of the channel.

You can use some events like the chat_member update or similar to know when the bot is added is to chat/group and you get the msg object with the chat_id of this chat/group

**Comment by MananKansara09** [comment]
Let me try
