### ISSUE TITLE
bot.on("inline") does not work

### ISSUE THREAD

**Issue by alikhil** [yagop/node-telegram-bot-api#112]
`bot.on('inline_query', function(msg) {
	console.log("inline!!");
});`
Inline mod is set on, but it does not work.

**Comment by rithvikvibhu** [comment]
@alikhil Do the other events work (like onText)?
Do you see the inline text when you mention the bot? (This text would've been set when enabling inline mode.

**Comment by alikhil** [comment]
Other events are working and no I do not see placeholder text when mentioning the bot.

**Comment by rithvikvibhu** [comment]
@alikhil the bot's handle should end with 'bot'. Like @somenamebot. Few days ago, I was trying to use the bot's name :P

Also make sure to give a space after the mention

**Comment by alikhil** [comment]
@rithvikvibhu Yeah, I know about it. But it is still not working

**Comment by icdevin** [comment]
If the placeholder text isn't working, something is wrong with your inline settings registered w/ Telegram. That text will show up regardless of if your bot is setup to receive the inline request.

**Comment by alikhil** [comment]
@icdevin and @rithvikvibhu  Thank you. The problem was on the client side. I just restarted telegram and now it works.
