### ISSUE TITLE
Stop supporting unsupported versions of NodeJS, older than v18.

### ISSUE THREAD

**Issue by Dima-Dim** [yagop/node-telegram-bot-api#1126]
> Question

Judging by https://github.com/nodejs/release#release-schedule, it's safe to use NodeJs no older 18, evrething else is unsupported and potentially dangerous to use. Maybe we shouldn't encourage the use of potentianally dangerous version? After all, the package gains access to authorization tokens and other sensitive data.
I suggest not cheching the performance of the package on NodeJS older that 18 and raising the level of supported NodeJS to version 18. Anyone who wants to put themselves and their users at risk will be able to use previous versions of the package.

**Comment by danielperez9430** [comment]
Support old versions is not a real problem, you can use any node version that you want. But yep, for future release when we refactor the code we need to drop support for some node versions, because if we use native libs that is part of some node versions, in old versions the library dont works.
