### ISSUE TITLE
Failed to receive a reply message with ReplyToMessage

### ISSUE THREAD

**Issue by akaspi** [yagop/node-telegram-bot-api#113]
Hi,
I'm trying to run a simple test code according to the [replyToMessage example](https://github.com/yagop/node-telegram-bot-api/blob/master/examples/replyToMessage.js) and my replyToMessage callback is never called.

``` javascript
var TelegramBot = require('node-telegram-bot-api');
var bot = new TelegramBot(config.botToken, {polling: {timeout: 1, interval: 100}});

var opts = {
    reply_markup: JSON.stringify({ force_reply: true }
)};

bot.onText(/\/search/, function (msg) {
    var fromId = msg.from.id;
    bot.sendMessage(fromId, 'What should I search for?', opts)
        .then(function(sended) {
            var chatId = sended.chat.id;
            var messageId = sended.message_id;
            bot.onReplyToMessage(chatId, messageId, function (message) {
                console.log('OK. I\'ll search for %s', message.text);
            });
        })
});
```

`console.log` (in onReplyToMessage callback) is never called...

Am I doing something wrong?
- I'm using 0.21.1

**Comment by DenisIzmaylov** [comment]
ping

**Comment by mishachesnokov** [comment]
Same problem. Only if I manually reply on the message, them callback is being called.

**Comment by akaspi** [comment]
@mishachesnokov - what do you mean by 'manually replay on the message'?

**Comment by mishachesnokov** [comment]
@akaspi - when I tap on bot's message in chat and press "Reply" then console.log gets my answer

**Comment by akaspi** [comment]
@mishachesnokov  - Thanks. I wasn't familiar with this tapping on bot's message feature....
So, I believe what I need is that my following message after the bot's messages would invoke the callback.

However, if you think of it, the following message after the bot's message won't always be the replay. I don't know what the actual product says... what is considered as reply?

**Comment by mishachesnokov** [comment]
@akaspi - That's the purpose of 'force_reply'. But it doesn't seem to work properly. I suppose the next message after bot's message is a user's reply, since if I asked something I need the answer now - before we proceed further.

Currently I am using another lib for nodejs - there it works fine.

**Comment by firo** [comment]
@mishachesnokov - Which node lib do you currently use ? thanks!

**Comment by mishachesnokov** [comment]
@firo - https://github.com/mdibaiee/node-telegram-api But the author says he can't put enough time in it now. Anyway the things he has done let me do enough. Just a little bit worry about telegram future updates.

**Comment by zigzag-way** [comment]
The same problem. Can not get the reply. My main msg handler recieves the msg but it doesnt look like a response. Response handler is nerver called.

**Comment by raphaklaus** [comment]
Palliative: I'm dealing this way:

```
  regexifyOptions(array){
    return new RegExp(array.toString().replace(/,/g, '|'));
  }

  resetReplyListeners(){
    bot.textRegexpCallbacks = bot.textRegexpCallbacks.slice(0, this.commands);
    // Number of commands listening...
  }

  reply(options){
    return new Promise((resolve, reject) => {
      try {
        bot.onText(this.regexifyOptions(options), (msg, response) => {
          this.resetReplyListeners();
          resolve(response[0]);
        });
      } catch (error) {
        reject(error);
      }
    });
  }
```

**Comment by zigzag-way** [comment]
Whats this?

**Comment by raphaklaus** [comment]
@zigzag-way is a class.

**Comment by Kaos1337** [comment]
@raphaklaus can you kindly create a little working example? I don't understand how to use reply(options) :S

**Comment by Kaos1337** [comment]
@raphaklaus there is a problem, you can't add a listener when needed and remove it if not needed, because if 2 (or more) users at the same time are "enabling" it, the first that end the usage avoid to the second user to use it (the added listener).

**Comment by Kaos1337** [comment]
@raphaklaus there is a problem, you can't add a listener when needed and remove it if not needed, because if 2 (or more) users at the same time are "enabling" it, the first that end the usage avoid to the second user to use it (the added listener).

**Comment by raphaklaus** [comment]
@Kaos1337, thanks for the advice. I edited the code to keep the callbacks, and check user id.

**Comment by moeinrahimi** [comment]
same for me

**Comment by bosslee** [comment]
> You can create a class, and put it within.

HI @raphaklaus 
May I ask in which file did you add the class code?
is it the telegram.js?

Thank you

**Comment by raphaklaus** [comment]
Please check my replies in this issue: https://github.com/yagop/node-telegram-bot-api/issues/108

**Comment by GochoMugo** [comment]
As @mishachesnokov suggests [above](https://github.com/yagop/node-telegram-bot-api/issues/113#issuecomment-216119823), the callback will only be fired if the user **manually replies** to it! Otherwise, you will have to implement, in your application code, a way to **maintain a conversation** *(implies state)* with your user!

However, I believe proper documentation will help users avoid this pitfall! We will close this issue once we update our docs!

**Comment by GochoMugo** [comment]
We have added a [common pitfalls](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/help.md#pitfalls) section in our docs! Please find more information there!

**Comment by makah** [comment]
I solved this problem by creating a onNextMessage(chatId, callback)

Create function onNextMessage()

    this.bot = new TelegramBot(token, options);
 
    this.bot.nextMessage = {};
    this.bot.onNextMessage = (chatId, callback) => {
        let promise = new Promise((resolve) => {
            this.bot.nextMessage[chatId] = { callback: callback, next: resolve };
        });
        return promise;
    }


Then you need to listen to any Message:

    bot.on('message', (msg) => {
      const chatId = msg.chat.id;

      let nextMsg = bot.nextMessage[chatId];
      if (nextMsg) {
        nextMsg.callback(msg);
        nextMsg.next(msg);
        bot.nextMessage[chatId] = undefined;
      }
    });    
    
Finally:
    
    bot.onText(/\/chat$/, (msg) => {
      const chatId = msg.chat.id;
      let fullName = '';

      let resp = `May I take down your name, ${msg.chat.username}`;
      bot.sendMessage(chatId, resp).then(() => {
        return bot.onNextMessage(chatId, msg => fullName = msg.text);
      }).then(() => {
        let resp = `It's a pleasure to meet you ${fullName}`;
        bot.sendMessage(chatId, resp)
      });
    });
