### ISSUE TITLE
[Question] Send large video

### ISSUE THREAD

**Issue by robin-hust** [yagop/node-telegram-bot-api#1134]
Is there any alternative way to send a large file? Suppose I have a 1GB video file with a direct link to it. I intend to download it to my computer and then use the "sendVideo" function (assuming I'm using a [LOCAL SERVER](https://github.com/tdlib/telegram-bot-api)). However, downloading the video consumes time and memory. Are there any alternative methods to accomplish this?

**Comment by danielperez9430** [comment]
If you send the "url" of the video direct to sendVideo method the Telegram Servers have a limit of 20 MB (from download content of the URL).

So if you need to send 1GB, you need to download it first yes or yes. And after that you can upload this file that you have in your local machine. Actually you dont have any other option.
