### ISSUE TITLE
Getting User contact information

### ISSUE THREAD

**Issue by Redskullvue** [yagop/node-telegram-bot-api#1135]
> Feature Request

I have searched for this issue and found none about this

### Introduction
it would be nice to be able to get the user contact information through the "msg" object ;
### Example
like instead of asking user directly to input your number we can just get it from the object if user /starts our BOT

**Comment by VDS13** [comment]
Hello, @Redskullvue.
The `Message` object does not store this information.

https://core.telegram.org/bots/api#message
https://core.telegram.org/bots/api#user
