### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by panp858** [yagop/node-telegram-bot-api#114]
If you run a bot in polling mode over a longer period of time you can run into many different errors like timeouts and some async/promise problems in bluebird.

My main problem is the error handling. As far as I can see there is no proper solution included in this API. So how do you guys handle and/or catch errors so that the bot doesn’t crash after a few hrs?

**Comment by PandaWhisperer** [comment]
Just noticed this as well. Apparently, any exceptions thrown in a message event handler will be silently suppressed.

**Comment by kryptome** [comment]
You can use Forever libraries, so that if your Code throws errors and timeout's then it will restart your bot server.

**Comment by GochoMugo** [comment]
Watch PR #180 for a possible fix on this issue.

However, your application will **not** crash on such unhandled exceptions during polling. An error will be logged to your console. What would be your approach in handling such errors?

**Comment by GochoMugo** [comment]
**Proper Error Handling** is on our TODO list.

We need to:

* Be able to handle distinct type of errors
* Document possible errors that one may encounter, and how to handle them

Related issues:

* Enhancement for bad requests: https://github.com/yagop/node-telegram-bot-api/issues/73
* getaddrinfo ENOTFOUND api.telegram.org: https://github.com/yagop/node-telegram-bot-api/issues/99
* Unhandled rejection Error: read ECONNRESET: https://github.com/yagop/node-telegram-bot-api/issues/244
* Unhandled rejection TimeoutError: operation timed out: https://github.com/yagop/node-telegram-bot-api/issues/170
* Handling invalid token: https://github.com/yagop/node-telegram-bot-api/issues/156
* Unhandled rejection TimeoutError: https://github.com/yagop/node-telegram-bot-api/issues/107
* Sending photo timeout: https://github.com/yagop/node-telegram-bot-api/issues/101

**Comment by GochoMugo** [comment]
Proper Error Handling has been added in **v0.27.0**. Please see the documentation on [error handling](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#error-handling).

Thanks @panp858, @PandaWhisperer, @kryptome, @roccomuso and @GermanBluefox for your time, effort and patience while we worked on this feature. :tada:

**Comment by roccomuso** [comment]
thanks @GochoMugo !
