### ISSUE TITLE
How to send group of photos? I mean to group 2 photos

### ISSUE THREAD

**Issue by internetwarrior** [yagop/node-telegram-bot-api#1147]
I can not send 2 pics
<img width="341" alt="image" src="https://github.com/yagop/node-telegram-bot-api/assets/64087609/18e63975-4dda-4c83-a3e2-1f0e8beed40a">
<img width="423" alt="image" src="https://github.com/yagop/node-telegram-bot-api/assets/64087609/1b0cd8f4-0920-4670-bcf4-7064621b500e">

**Comment by internetwarrior** [comment]
How can I group all of them?

**Comment by PotapIlya** [comment]
const imagesWithCaptions = [
  { path: '/path/to/your/image1.jpg', caption: 'Подпись для картинки 1' },
  { path: '/path/to/your/image2.jpg', caption: 'Подпись для картинки 2' },
  { path: '/path/to/your/image3.jpg', caption: 'Подпись для картинки 3' }
];

// Создание массива объектов InputMediaPhoto
const media = imagesWithCaptions.map(({ path, caption }) => ({
  type: 'photo',
  media: {
    source: path
  },
  caption: caption
}));

// Отправка нескольких картинок с подписями
bot.sendMediaGroup(chatId, media)
  .then(() => {
    console.log('Картинки успешно отправлены');
  })
  .catch((error) => {
    console.error('Ошибка при отправке картинок:', error);
  });
