### ISSUE TITLE
Ability to specify the filename and the content type by sendDocument

### ISSUE THREAD

**Issue by evolun** [yagop/node-telegram-bot-api#115]
In some case can be useful the ability to specify the filename and the content type by `sendDocument`.

In my case for example I have to send documents stored like simple files without extension, someone archive these files with its real name and type in a database.

Now, if I want to send, it is possible by passing a buffer of the data, in this way I loose the original name (this can be fine) but except for the office files (xlsx, docx, pptx) because _file-type_ library can't detect it correctly and the sent file is received as a zip file.

**Comment by evolun** [comment]
Proposed pull request #119

**Comment by frontenddima** [comment]
Yep! Solved with:
process.env["NTBA_FIX_350"] = 1;
At top of the file.

**Comment by frontenddima** [comment]
> In some case can be useful the ability to specify the filename and the content type by `sendDocument`.
> 
> In my case for example I have to send documents stored like simple files without extension, someone archive these files with its real name and type in a database.
> 
> Now, if I want to send, it is possible by passing a buffer of the data, in this way I loose the original name (this can be fine) but except for the office files (xlsx, docx, pptx) because _file-type_ library can't detect it correctly and the sent file is received as a zip file.

Yep! Solved with:
process.env["NTBA_FIX_350"] = 1;
At top of the file.
