### ISSUE TITLE
How to copy text to the clipboard after clicking on it

### ISSUE THREAD

**Issue by aoqilajiao** [yagop/node-telegram-bot-api#1160]
https://core.telegram.org/bots/api#sendmessage
`
[inline URL](http://www.example.com/)
[inline mention of a user](tg://user?id=123456789)
![👍](tg://emoji?id=5368324170671202286)
`

The official MarkdownV2 format only supports these methods and does not have the effect of copying text to the clipboard when the user clicks on it.
https://core.telegram.org/bots/api#sendmessage
But how do I implement this function when I see text sent by other robots?

 `
const reply = `[Test copying text](???)`
bot.sendMessage(from.id, reply,  { parse_mode: 'MarkdownV2' })
`

Can anyone give a hint? Thank you

**Comment by VDS13** [comment]
Hellio, @aoqilajiao,
Can you show a chat screen where copying to clipboard works?

**Comment by aoqilajiao** [comment]
thank you, @VDS13 

That is a screenshot of a lottery, clicking on "keywords" with the mouse will copy it to the clipboard
Similar to setting - username, when clicking on one's own username, it will prompt that it has been copied to the clipboard.
How can this be achieved?

 
![123](https://github.com/yagop/node-telegram-bot-api/assets/146148462/f8657f81-5fda-41d9-995d-ad3f61cb8cf7)
![234](https://github.com/yagop/node-telegram-bot-api/assets/146148462/7700ff8d-41bc-457f-b7d4-9a9e27646f60)

**Comment by VDS13** [comment]
No Markdown required. Monospaced text (` `` `) is copied when you click on it.
Can try:
```js
const reply = bot.sendMessage(from.id, "`copy to clipboard`");
```

**Comment by aoqilajiao** [comment]
Thank you so much! The problem has been resolved!

**Comment by sutaiyi** [comment]
怎么解决的，兄弟
