### ISSUE TITLE
setChatMenuButton not working (Web app)

### ISSUE THREAD

**Issue by un-hongly** [yagop/node-telegram-bot-api#1165]
Below code is not working

```
bot.setChatMenuButton({
      menu_button: {
          type: 'web_app',
          text: 'Order now',
          web_app: {
              url: '....'
          }
      }
  });
```

**Comment by Dhamu143** [comment]
Hi , is there any update on this ?

**Comment by danielperez9430** [comment]
Use example:

```
bot.setChatMenuButton({
        chat_id: USERID,
        menu_button: JSON.stringify({ type: 'web_app', text: 'Hello', web_app: { url: 'https://webappcontent.telegram.org/cafe' } }),
      })
```

**Comment by un-hongly** [comment]
> Use example:
> 
> ```js
> const chatId = "XXXX"; 
> 
> bot.setChatMenuButton({
>         chat_id: chatId,
>         menu_button: JSON.stringify({ type: 'web_app', text: 'Hello', web_app: { url: 'https://webappcontent.telegram.org/cafe' } }),
>       })
> ```

This is work!. In typescript, cast json string to any.

`JSON.stringify({ type: 'web_app', text: 'Hello', web_app: { url: 'https://webappcontent.telegram.org/cafe' } }) as any`
