### ISSUE TITLE
full screen

### ISSUE THREAD

**Issue by Vo0oX** [yagop/node-telegram-bot-api#1168]
bot.sendMessage(chatId, 'Онлайн запись Harley Barbershop',{reply_markup: {
                inline_keyboard: [
                    [
                        {
                            text: "Записаться",
                            web_app: {
                                url: url

                            },
                        },
                    ],
                ],
        }})
        
                Now my app opens in half the screen
![IMAGE 2024-01-29 11:32:11](https://github.com/yagop/node-telegram-bot-api/assets/20887300/a3042909-79c0-45dd-8363-bc3810dd9b25)

How can I make it open in full screen at once?

![IMAGE 2024-01-29 11:32:09](https://github.com/yagop/node-telegram-bot-api/assets/20887300/6cf19ec3-1b24-48b5-9c5f-947f05964079)

**Comment by khacpv** [comment]
import `<script src='https://telegram.org/js/telegram-web-app.js'></script>` into `<head>
then call this function to expand window:

```
window.Telegram.WebApp.expand();
```

**Comment by fitri612** [comment]
> ```
> window.Telegram.WebApp.expand();
> ```

helo when using next js, can you know to solve ?
