### ISSUE TITLE
bot.getChatMenuButton

### ISSUE THREAD

**Issue by Vo0oX** [yagop/node-telegram-bot-api#1169]
not working 

bot.getChatMenuButton(
        JSON.stringify({
            chat_id: msg.chat.id,
            menu_button : {
                text : "www",
                type:"web_app",
                web_app:{
                    url : "https://tg.elevator.com.et",
                }
            },
        }),
    );

**Comment by Dhamu143** [comment]
Hi Is there any update on this ?

**Comment by danielperez9430** [comment]
Use example:

```js
bot.getChatMenuButton({ chat_id: USERID }).then(resp => console.log(resp));
```
