### ISSUE TITLE
Business Mode

### ISSUE THREAD

**Issue by Dani-l4** [yagop/node-telegram-bot-api#1192]
> Question

Since 31 March, 2024 Telegram has feature that bots can be connected to private messages and they can manage communicating with clients. How can I reach that with node-telegram-bot-api? I've tried different ways but bot not even received the message.

bot.on('message') || bot.on('business_message') || bot.onText('') - not working via private messages when bot connected to business account.

Reference: https://telegram.org/blog/telegram-business?ln=r#chatbots-for-business

**Comment by danielperez9430** [comment]
Will be added in the next release. If I have some time this week I will do the update of the library for support it

**Comment by vyacheslavslava** [comment]
Hello, @danielperez9430.

We are eagerly anticipating this update and would greatly appreciate it if you could make it happen at your earliest convenience. 

Thank you!

**Comment by danielperez9430** [comment]
I do it today @vyacheslavslava , so is merge (not release in npm yet).

**Comment by PainfulParse** [comment]
Any updates on when this will be part of the next NPM release?

**Comment by abdoo9** [comment]
> I do it today @vyacheslavslava , so is merge (not release in npm yet).

when it will be released !?

**Comment by danielperez9430** [comment]
Its now release in npm

**Comment by toxfim** [comment]
when it will be released !?
