### ISSUE TITLE
Method getUserChatBoosts doesn't work correctly

### ISSUE THREAD

**Issue by dsvynarenko** [yagop/node-telegram-bot-api#1200]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

`getUserChatBoosts` method works correctly and returns `UserChatBoosts` for a successful request.

### Actual Behavior

`getUserChatBoosts` method always rejects with an error:
```
ETELEGRAM: 400 Bad Request: invalid user_id specified
    at /app/node_modules/node-telegram-bot-api/src/telegram.js:316:15
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
...
```

### Steps to reproduce the Behavior

Just simply call `getUserChatBoosts`.

**Comment by dsvynarenko** [comment]
As a workaround for this issue instead of calling:
```
const userBoosts = await telegramBot.getUserChatBoosts(chatId, userId);
```
the following call can be used:
```
const userBoosts = await telegramBot._request('getUserChatBoosts', {
  form: {
    chat_id: chatId,
    user_id: userId
  }
});
```

**Comment by danielperez9430** [comment]
Is not a issue, all the methods return a promise so you can get the result calling `.then` or use the `aysnc / await`
