### ISSUE TITLE
FileOptions filename and contentType is can't work well

### ISSUE THREAD

**Issue by azickri** [yagop/node-telegram-bot-api#1202]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

I'm trying to send a Document with a custom file name

### Actual Behavior

What happens is that the file name in Telegram becomes the default file URL to be "12345678990.pdf", it should be "file-name.pdf"

### Steps to reproduce the Behavior

I have used the function for .sendDocument using FileOptions in this way

```
const url = 'https://media.com/12345678990.pdf'
const fileOption = {
 filename: "file-name.pdf",
 contentType: "application/pdf",
};

.sendDocument(chatId, url, options, fileOption);
```

**Comment by Sp3rick** [comment]
Seems that similiar behaivor is on telegram by sending from fild_id https://github.com/telegraf/telegraf/issues/1062#issuecomment-659553766

Probably filename can be specifyed only when uploading (from Buffer or Stream), so you should try to download the file and then upload it to telegram with your fileOptions

**Comment by azickri** [comment]
Thanks, i will try it.
