### ISSUE TITLE
TelegramBot configuration doesn't reflect at all

### ISSUE THREAD

**Issue by mcfriend99** [yagop/node-telegram-bot-api#1227]
I can't seem to find any solution to this. No matter what I pass into option when creating `new TelegramBot`, it never reflects. Not the bot token, not the polling option or webhook option. Nothing at all. Just keeps logging the below:

```
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Telegram Bot Token not provided!"}
```

I've even set polling to false, set the baseApiUrl, I managed to log the bot at the point of the error from the source files, and this is what I get no matter what I put in the settings:

```
<ref *1> TelegramBot {
  _events: Events <[Object: null prototype] {}> {},
  _eventsCount: 0,
  token: undefined,
  options: {
    polling: true,
    webHook: false,
    baseApiUrl: 'https://api.telegram.org',
    filepath: true,
    badRejection: false
  },
  _textRegexpCallbacks: [],
  _replyListenerId: 0,
  _replyListeners: [],
  _polling: TelegramBotPolling {
    bot: [Circular *1],
    options: { interval: 300, params: [Object] },
    _lastUpdate: 0,
    _lastRequest: Promise { <pending> },
    _abort: false,
    _pollingTimeout: null
  },
  _webHook: null
}
```

Polling, webhook, baseApiUrl, etc. No configuration reflects.

**Comment by sc0Vu** [comment]
The constructor would be `constructor(token, options = {})` (https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L161). How did you initialize the tg bot?

**Comment by mcfriend99** [comment]
I fixed it already. Long story short, this library is not thread safe.
