### ISSUE TITLE
How to get user profile info?

### ISSUE THREAD

**Issue by Tpona** [yagop/node-telegram-bot-api#123]
Hi everyone!

What method i must to use for retrive user info like first_name and last_name?

Thx/

**Comment by edlvj** [comment]
The Telegram bot api don't have independent method than return information about user but you can get information then when him enter some command or word in telegram
for example:
```javascript
bot.onText(/\/help/, function (msg) {
console.log(msg);    
var fromId = msg.from.id;
bot.sendMessage(fromId, msg.from.first_name + ' ' + msg.from.last_name );
});
```
