### ISSUE TITLE
About webHooks and Certificates

### ISSUE THREAD

**Issue by zigzag-way** [yagop/node-telegram-bot-api#125]
There are two samples of webHooks in examples directory: httpsWebHook.js and openShiftWebHook.js
1. Why there are two samples? Why should OpenShift be different?
2. I completely don`t understand why there is such inicialization difference:
var options = {
  webHook: {
    port: 443,
    key: __dirname+'/key.pem',
    cert: __dirname+'/crt.pem'
  }
};
var bot = new TelegramBot('BOT_TOKEN', options);
bot.setWebHook('IP:PORT/botBOT_TOKEN', __dirname+'/crt.pem'); 

and for OpenShift: 
var bot = new TelegramBot(token, {webHook: {port: port, host: host}});
// OpenShift enroutes :443 request to OPENSHIFT_NODEJS_PORT
bot.setWebHook(domain+':443/bot'+token); 

Where is certificate parameter in OpenShift sample?!? Is it an error or what?
I`m also using it on OpenShift platform.

**Comment by yagop** [comment]
Please for code, use the Markdown syntax for better reading.

In the first example a certificate is provided in the second it isn't. A HTTP server is created. OpenShift uses a proxy to route HTTPS request to HTTP.

**Comment by zigzag-way** [comment]
Sorry, for markdown. I`ll fix it next time.
But I still doest understand why OpenShift doesnt require certificate to initialize webHook?

**Comment by zigzag-way** [comment]
Btw, do you plan to use @tjhorner Bot 2.0 pull request? I tried to use it but failed, wait for your update :-)

**Comment by roccomuso** [comment]
@zigzag-way simply because, as heroku and many other cloud providers, they already provides a valid certificate for their domains. So you don't need to upload a self-signed one.

**Comment by GochoMugo** [comment]
This has been addressed by @roccomuso! Thanks!
