### ISSUE TITLE
Telegram limitation or package problem?

### ISSUE THREAD

**Issue by mohammadrezaprw** [yagop/node-telegram-bot-api#126]
Hi,
We have a problem when sending message increase to telegram servers.
For example we have normal status when sending message to telegram servers less than about 1000 messages per minute(response to user requests), but after increase messages, we have a delay to deliver message between 1 to 4 seconds!
Also we checked our app and delay isn't from our resources or processes.
What's the problem?
@yagop

**Comment by Kaos1337** [comment]
You are limited by telegram servers https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once

**Comment by GochoMugo** [comment]
@mohammadrezaprw If you say your processes are **not** the cause of the delay, doesn't it absolve us from any blame? I mean, isn't this library being used in the process? If possible, you could analyze network traffic between your processes and Telegram servers.

**Comment by GochoMugo** [comment]
As @Kaos1337 suggests, you may be limited by the telegram servers!
