### ISSUE TITLE
Any plan to support KeyboardButton with request_contact and request_location?

### ISSUE THREAD

**Issue by antonrifco** [yagop/node-telegram-bot-api#127]
Any plan to support KeyboardButton with request_contact and request_location?

**Comment by antonrifco** [comment]
resolved. it turns out , already supported:

var options = {
                                                "parse_mode": "Markdown",
                                                "reply_markup": JSON.stringify({
                                                        "keyboard": [
                                                                [{ text: "Send Location", request_location:true }],
                                                                [{ text: "Send Contact", request_contact: true }]
                                                        ],
                                                        "one_time_keyboard" : true
                                                })
                                        };

**Comment by danieltorrer** [comment]
@antonrifco By any chance do you have the full function of how to use this?

**Comment by m1n0s** [comment]
@antonrifco how do you catch this data then?
When I answer with location button - I catch it in promise but `location` field is missing in Message object.

**Comment by troywmz** [comment]
Can your bot get user's location?
If you have found the method, may u share with me?
I've got stuck when I try to build a weather report bot based on user's location.

**Comment by troywmz** [comment]
@antonrifco 
Can your bot get user's location?
If you have found the method, may u share with me?
I've got stuck when I try to build a weather report bot based on user's location.

**Comment by FaRzad-845** [comment]
@troywmz 
The above code that @antonrifco share is correctly working .... 
Please check bot father setting for your location of your bot and then try the above code ....

**Comment by troywmz** [comment]
@FaRzad-845 solved. Thank you!
