### ISSUE TITLE
Support sendVenue

### ISSUE THREAD

**Issue by antonrifco** [yagop/node-telegram-bot-api#128]
any plan to support sendVenue yet https://core.telegram.org/bots/api#sendvenue ?

**Comment by highfeed** [comment]
+1

**Comment by xuchen** [comment]
+1 it's sometimes more useful than sendLocation

**Comment by GochoMugo** [comment]
[TelegramBot#sendVenue()](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/README.md#TelegramBot+sendVenue) has been added in PR #121, package v0.24.0!

**Comment by antonrifco** [comment]
viele Dank!
