### ISSUE TITLE
Guys, I created library to help you use list of middleware with your callbacks easy.

### ISSUE THREAD

**Issue by idchlife** [yagop/node-telegram-bot-api#136]
As title says. I used it for some time now and it became very helpful, so I created repository on github. Will be glad if you will help with usage, bugs, issues and contributions!

https://github.com/idchlife/node-telegram-bot-api-middleware

**Comment by GochoMugo** [comment]
This is valuable information for the community!

@yagop: I suggest a section on the README listing such libraries built on top of us!

**Comment by GochoMugo** [comment]
A section for the community has been added to the README
