### ISSUE TITLE
Can anyone explain me about ES6?

### ISSUE THREAD

**Issue by zigzag-way** [yagop/node-telegram-bot-api#137]
I`m really lost...
Can you explain me the difference between the module I get using "npm i node-telegram-bot-api" and the one I get with "git clone https://github.com/yagop/node-telegram-bot-api"
They are different. The one from NPM is a working nonES6 code, and the one from GIT(HUB) is nonworking ES6.
I really got stuck with it... Feel stupid...

**Comment by infernalmaster** [comment]
So there is `prepublish` command in `package.json` that transforms with babel es6 code to es5  and places taht code to `lib` directory. It runs before code published to npm.

So you can call that manually `npm run prepublish` than  `var TelegramBot = require('./lib/telegram.js');`

**Comment by zigzag-way** [comment]
There is NO prepublish script in NPM distributed module:
  "scripts": {
    "test": "mocha test/index.js",
    "test-cov": "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage",
    "gen-doc": "jsdoc2md --src src/telegram.js -t README.hbs > README.md",
    "jshint": "jshint src test"
  },

**Comment by infernalmaster** [comment]
But it is on github https://github.com/yagop/node-telegram-bot-api/blob/master/package.json

**Comment by w-site** [comment]
@zigzag-way You can install directly from github ex:
npm install https://github.com/w-site/node-telegram-bot-api.git

**Comment by zigzag-way** [comment]
Yes, I know that I can directly install it using npm install https://github.com/w-site/node-telegram-bot-api.git
But, the qn is why the module I get is different in this two cases?

@infernalmaster  "and places taht code to lib directory" - there is no LIB directory when I use "npm i node-telegram-bot-api" command.

I dont need any additional actions because I`m using OPENSHIFT and it does everything automatically (get the needed modules from npm).

**Comment by w-site** [comment]
So if you install from npm install node-telegram-bot-api this is https://github.com/yagop/node-telegram-bot-api/tree/v0.20.1 this release version, but if you install from github you pick the main repository, ant the problem that you can not use npm install https://github.com/yagop/node-telegram-bot-api.git that is lib directory isn't in repo.

**Comment by yagop** [comment]
Can be closed?

**Comment by GochoMugo** [comment]
Before closing this issue, I would like to inquire for some insight in the following query.

[package.json][pkg] has its `"main"` property pointing to `"./lib/telegram.js"` (at [line 5][pkg-l5]). If I delete the 'lib' directory and try load the module, it **succeeds**, despite the Node.js Docs mentioning, in the [folders as modules section][node-docs-folders], that *"Note: If the file specified by the "main" entry of package.json is missing and can not be resolved, Node.js will report the entire module as missing with the default error..."*. Instead, Node.js seems to load the module using [index.js][index].

So, why does the `require()` succeed?

[pkg]:https://github.com/yagop/node-telegram-bot-api/blob/75b36abfeb9e3008a8125254f395e6983044efeb/package.json
[pkg-l5]:https://github.com/yagop/node-telegram-bot-api/blob/75b36abfeb9e3008a8125254f395e6983044efeb/package.json#L5
[node-docs-folders]:https://nodejs.org/docs/latest/api/modules.html#modules_folders_as_modules
[index]:https://github.com/yagop/node-telegram-bot-api/blob/75b36abfeb9e3008a8125254f395e6983044efeb/index.js

**Comment by GochoMugo** [comment]
It seems that Node.js defaults to the `index.js` if `./lib/telegram.js` is **not** found!

@zigzag-way: your earlier remark on "non-working ES6" is being addressed in PR #252!

Closing this now!
