### ISSUE TITLE
Keyboard Button CallBack Query function to get callbacks on clicks

### ISSUE THREAD

**Issue by shankar96** [yagop/node-telegram-bot-api#138]
i want to get callback query from keyboard buttons.
can someone suggest me to get the same using node-telegram-bot-api. i know its not integrated into it can someone give me idea where the callback query is going in api modules or anykind of help

**Comment by Niklv** [comment]
```javascript
var TelegramBot = require('node-telegram-bot-api');
TelegramBot.prototype.__processUpdate = TelegramBot.prototype._processUpdate; 
TelegramBot.prototype._processUpdate = function _processUpdate(update) { 
	const callbackQuery = update.callback_query;
	if (callbackQuery)
		this.emit('callback_query', callbackQuery);
	else
		this.__processUpdate(update);
};
```

**Comment by mironov** [comment]
Check out this package https://www.npmjs.com/package/monkey-patches-node-telegram-bot-api

**Comment by shankar96** [comment]
@mironov @Niklv Thankx a lot

**Comment by GochoMugo** [comment]
Please avoid listening on `callback_query` as [illustrated above](https://github.com/yagop/node-telegram-bot-api/issues/138#issuecomment-223758751). It is unnecessary as `callback_query` event emission is already implemented. Also, you should **not** rely on methods prefixed with one or more dashes (_). They are private (or internal) methods; **not** to be used by library consumers.

TelegramBot already emits `callback_query` when one is encountered. Thus,

```js
bot.on("callback_query", function(callbackQuery) {
    // 'callbackQuery' is of type CallbackQuery
    console.log(callbackQuery);
});
```

See [CallbackQuery](https://core.telegram.org/bots/api#callbackquery) for more information.
