### ISSUE TITLE
Add edited_message event

### ISSUE THREAD

**Issue by iceflash** [yagop/node-telegram-bot-api#139]
Hi all!
In last update Telegram added functionality to edit already sent message in chat (ex. if user make mistake in sended message). In bot API added this data in **Update** object https://core.telegram.org/bots/api#update which returned by **getUpdates** or **webHook**.
But in current version of this module i can't find this implementation.
Can anybody help me with this&

**Comment by GochoMugo** [comment]
`edited_message` event has been added in PR #191, package v0.24.0! Please read the [doc section on events](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/README.md#events).
