### ISSUE TITLE
Setting initial polling offset

### ISSUE THREAD

**Issue by Onfire7** [yagop/node-telegram-bot-api#14]
Would it be possible to set the initial poling offset at startup?
I would really like to be able to store the last processed message id in a database and ensure that I don't miss any messages that come in during down time.

If you want, I could probably figure it out and submit a pull request, if I can find the time.

**Comment by Illyism** [comment]
I believe you can set the **offset** variable.

See: https://core.telegram.org/bots/api#getupdates

**Comment by yagop** [comment]
By default the offset value is null, so Telegram will send all unconfirmed msgs.

`"By default, updates starting with the earliest unconfirmed update are returned."`

**Comment by GochoMugo** [comment]
This feature has been added in **v0.27.0**. See the constructor option, [`options.polling.params`](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#new-telegrambottoken-options).

You would do sth like:

```js
const bot = new TelegramBot(TOKEN, {
  polling: {
    params: {
      offset: getOffsetSomeHow(), // we shall start polling with this value!
    },
  },
});
```

Thanks @Onfire7 and @Illyism for your time and effort in adding this feature.

**Comment by YDJSZY** [comment]
@GochoMugo I did it with you said but not work.what is the problem?
