### ISSUE TITLE
signed msg.chat.id with -

### ISSUE THREAD

**Issue by vinnitu** [yagop/node-telegram-bot-api#141]
I am not sure but msg.chat.id can't stats with minus?

**Comment by iceflash** [comment]
Hi, group chats have minus

**Comment by vinnitu** [comment]
really? is it by spec?

**Comment by iceflash** [comment]
yep, can't find where i see in spec, https://core.telegram.org/bots/api#chat 
But, group chat id negative, normal chat positive

**Comment by yagop** [comment]
That is.

Can I close this?

**Comment by vinnitu** [comment]
Ok, thx
