### ISSUE TITLE
How to remove message ?

### ISSUE THREAD

**Issue by Tpona** [yagop/node-telegram-bot-api#143]
I want to create authorization functional for user by password and password must be hidden from chat.
I needs to remove message from chat.
How to realize this functional?

Thx

**Comment by trashbytes** [comment]
Deleting messages is not possible. You could edit them instead to display _Success_ or something similar.

**Comment by Tpona** [comment]
I can to edit user message? For example, change characters like *****?

**Comment by paOol** [comment]
maybe send the password via inline?

so "@yourbotname (type password)"

**Comment by trashbytes** [comment]
Oh, sorry. Deleting another users messages is not possible. You could however use inline mode, like paOol just mentioned, or simply tell them to delete their message. Or use an auth service via link, but that might be overkill..

**Comment by GinerPlusPlus** [comment]
Switch to private message, get password there.

**Comment by GochoMugo** [comment]
So:

1. It is **not** possible to **delete** any message, mostly another user's. You may want to [request the feature](https://core.telegram.org/bots/faq#will-you-add-x-to-the-bot-api).
1. It is **not** possible to **edit** another user's message. The bot can only edit messages itself sent. See [Updating Messages](https://core.telegram.org/bots/api#updating-messages) for more information.

Therefore, you may:

1. Process such authorization requests in private messages i.e. `msg.chat.type === "private"`. See [Telegram.Chat](https://core.telegram.org/bots/api#chat).
1. Advise the user to edit or delete the message containing the password afterwards.

Hope that helps!
