### ISSUE TITLE
how to get message delivery notifications

### ISSUE THREAD

**Issue by xangel99** [yagop/node-telegram-bot-api#145]
add a callback to the sendMessage method to receive a message delivery notification.

**Comment by trashbytes** [comment]
sendMessage returns the message if sent correctly.

**Comment by xangel99** [comment]
sendMessage return this json for any sent message

 {"isFulfilled":false,"isRejected":false}

**Comment by koloboid** [comment]
sendMessage returns a Promise, you can check success with then() method, and catch an error with a catch(): sendMessage(...).then((msg)=> { }).catch((err)=> {});

**Comment by xangel99** [comment]
ok. i have write this code:

    bot.sendMessage(chat_id, message_text)
        .then( function (msg) {
            console.log('Sent Message');
        })
        .catch(function (err) {
            console.log('Errorr sending message');
        });

but i haven't catch the error even if the destination telegram client is off-line.
When the telegram client come back on-line the message is successfully delivered.
There is a delivery timeout or a time-to-live on the message?
How can I have message delivery notification?
 
thanks a lot.

**Comment by trashbytes** [comment]
```
bot.sendMessage(chat_id, message_text).then(function (message) {
  console.log(message); // this stuff only happens if the message is sent correctly. To catch the error try wrapping sendMessage in a try/catch block
});
```

**Comment by xangel99** [comment]
thanks trashbytes, 
but a message sent correctly is surely delivered to the destination client?
if the telegram client is off-line for how many time the telegram server hold  the message?
il the message is discarded from the server is possible have a notification about this event?
When the client come back on-line the message will be delivered.
Is possible have a notificatione from the telegram server about this event?

**Comment by trashbytes** [comment]
Nope, there is no way of knowing that, since every person can have unlimited clients.

Telegram states in their FAQ:

We don‘t have a ’delivered to device' status for messages because Telegram can run on as many devices as you want. So which particular one would that check mean?

**Comment by xangel99** [comment]
i suppose that is a limitation of the bot.
Indeed in chat with other person i can see 2 green signs in the left down side of the cloud that stay for:
1) received by the user
2) read by the user.
i am in error or can you confirm?

**Comment by trashbytes** [comment]
The first doesn't mean received by the user, it means that the central Telegram server got the message. Even if the user logs off from all of his clients it would show the first check for you.

**Comment by xangel99** [comment]
ok, 
thanks a lot.
