### ISSUE TITLE
force_reply still waiting for a reply in multiple clients

### ISSUE THREAD

**Issue by Kaos1337** [yagop/node-telegram-bot-api#146]
Hi,
I'm having a problem with the force_reply: when I use it and I've two or more clients opened (example: desktop client + android client) when I insert something the force_reply close the input box only in the client where I replied but remains still opened in the other one, how can I "force" che closure of the input box in all clients?
Thank you.

**Comment by GochoMugo** [comment]
Please see [TelegramBotAPI.ReplyKeyboardRemove](https://core.telegram.org/bots/api#replykeyboardremove) for more information.

In your reply, by the user, you may do sth like:

```js
bot.sendMessage(chatId, text, {
    reply_markup: {
        remove_keyboard: true
    }
});
```

Hope that helps!
