### ISSUE TITLE
Way to ban user

### ISSUE THREAD

**Issue by rsboarder** [yagop/node-telegram-bot-api#148]
Hi everyone! Today my bot was under spam attack. I don't know what was the purpose of this attack, but in stats I see many messages with links to porn sites. 
Is there any way to ban user by his id? Now I see one way to do it: filter `from.id` in `_processUpdate` func. Maybe there's more elegant way to solve this problem?

**Comment by colkito** [comment]
Hi @rsboarder, your bot is in a group? did you try with https://github.com/yagop/node-telegram-bot-api#telegrambotkickchatmemberchatid-userid--promise method?

**Comment by GochoMugo** [comment]
Use the [TelegramBot#kickChatMember()](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/README.md#TelegramBot+kickChatMember).

**Comment by Alain00** [comment]
What if the user is't on a group? There is a way to unsubscribe that user?

**Comment by kamikazechaser** [comment]
No. Use a federation bot like rosebot.
