### ISSUE TITLE
when setWebhook cert is passed as string - its incorrectly uploaded

### ISSUE THREAD

**Issue by AVVS** [yagop/node-telegram-bot-api#149]
it should be uploaded as form data, not as qs param, method that should be changed is https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L317-L319

filename should be generated by bot API module and formData value should be equal to passed content

**Comment by GochoMugo** [comment]
I believe this is as a result of poor documentation! TelegramBot#setWebHook(url, cert) accepts cert being:

1. Readable stream, for example from `fs.createReadStream()`
1. Buffer, containing the file's data
1. String, as a path pointing to an actual file
1. String, as a file ID (see [TelegramBotAPI.SendingFiles](https://core.telegram.org/bots/api#sending-files))

Therefore, you can **not** pass your `cert`'s content as a String! Try Buffer instead.

We will close this issue as soon as the docs are updated to be clearer!

**Comment by GochoMugo** [comment]
Updated our docs [on how to send files](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/usage.md#sending-files) using this library!
