### ISSUE TITLE
chosen_inline_result does not work

### ISSUE THREAD

**Issue by alikhil** [yagop/node-telegram-bot-api#151]
Following code does not work, but 'inline_query' works.
```
bot.on('chosen_inline_result', function (msg) {
	console.log(msg);
});
```

**Comment by monkeydave** [comment]
It is working for my bot, have you enabled /setinlinefeedback with botfather?

**Comment by alikhil** [comment]
Thank you, I enabled it and now it works. But now I have another floating bug with inline keyboards. In some cases, they do not appear. And can you explain how to setup /setinlinefeedback, what do mean other variants(1/10, 1/100, 1/1000)?

**Comment by alikhil** [comment]
[Issue 1129](https://github.com/zhukov/webogram/issues/1129) helped me to solve problem with inline keyboards

**Comment by Nior21** [comment]
> Thank you, I enabled it and now it works. But now I have another floating bug with inline keyboards. In some cases, they do not appear. And can you explain how to setup /setinlinefeedback, what do mean other variants(1/10, 1/100, 1/1000)?

Вы спасли уйму моего времени! Спасибо / You've saved a lot of my time! Tnx
