### ISSUE TITLE
[Request] Inline Keyboard Keep history within buttons...

### ISSUE THREAD

**Issue by deadmann** [yagop/node-telegram-bot-api#154]
i'm using inline keyboard to keep history of buttons, creating a form based on that.

when user choose from, i update callback data to "X Y [the place he chose]"
then later i want to read them inside my search button, but the fact is each button return separate data.
so i have to keep history within a session, which may by server failure get lost, while the telegram still shows that keyboard which lead to bug in my code... 
the other is to inject all data to all buttons, which lead to transfer more than required data, and long network timing, and poor performance if it come to have lot of data, also complex code which themselves can lead to introduce bugs to.
So i though it can be good if we be able to read data exists within server, now i have no idea of implementation,
- introducing secondary method: you have to talk twice to telegram apis, mean you have to open connection twice which mean more time, plus user latency, low performance.
- sending all buttons all the time even when they are not required, still somehow it's low on performance, but this time it won't lead to complex application.
- generate secondary keyboard which KeepHistory and have extra field, or even better, introduce 1 (value), 2 (key value) extra field within the keyboard, if they are filled, then telegram sent them back, otherwise api don't returns buttons without these values.

**Comment by GochoMugo** [comment]
I am **not** quite sure I understood your query but it sounds like a feature request for the Telegram Bot API. If so, please [see this FAQ section](https://core.telegram.org/bots/faq#will-you-add-x-to-the-bot-api).

If that is **not** the case, your use-case seems quite specialized. It seems better to implement that in a higher-level library using this package under-the-hood. This library is basically a wrapper around the API without much added niceties.
