### ISSUE TITLE
API 2.1 features are not implemented

### ISSUE THREAD

**Issue by Lemmmy** [yagop/node-telegram-bot-api#155]
Bot methods getChat, leaveChat, getChatAdministrators, getChatMember and getChatMembersCount were added in Bot API 2.1, but are not yet implemented by this module.

**Comment by HorusGoul** [comment]
I just made a pull request with all methods but leaveChat: #158

**Comment by kamikazechaser** [comment]
https://www.npmjs.com/package/node-telegram-bot-api-latest

**Comment by GochoMugo** [comment]
API 2.1 features added in PRs #158 and #186. Available in package 0.24.0!
