### ISSUE TITLE
Inline Keyboard when sending something other than text

### ISSUE THREAD

**Issue by tengotengo** [yagop/node-telegram-bot-api#159]
`bot.sendPhoto(fromUserId, 'test.png',
        {
            reply_markup: {
                inline_keyboard: [
                    [
                        {text: '1', callback_data: '1'}
                    ]
                ]
            },
            caption: 'tetststet'
        }
    );`

For some reason button does not appear

**Comment by trashbytes** [comment]
Yes, I've run into that as well. It doesn't get stringified here.

You can fix the API or just stringify the object like so:

http://paste.ofcode.org/S8vMnpxggtsAH5HQAe4sG2

**Comment by algoni** [comment]
+1 for the issue.
@trashbytes link no longer works, would love to see a workaround.

**Comment by tengotengo** [comment]
@algoni check out my pull request https://github.com/yagop/node-telegram-bot-api/pull/160

**Comment by GochoMugo** [comment]
This has been fixed in PR #133, package version 0.24.0.

Thanks @tengotengo for your bug report.
