### ISSUE TITLE
Can't send files

### ISSUE THREAD

**Issue by Anonomousxxx** [yagop/node-telegram-bot-api#161]
Hello!
I'm currently constantly get this problem, when I try to send a photo/music/any other files I get this error:

> Unhandled rejection TypeError: headers[prop].join is not a function
>     at FormData._multiPartHeader (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request/node_modules/form-data/lib/form_data.js:182:49)
>     at FormData.append (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request/node_modules/form-data/lib/form_data.js:64:21)
>     at appendFormValue (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request/request.js:339:21)
>     at Request.init (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request/request.js:352:11)
>     at Request.RP$initInterceptor [as init](/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/rp.js:123:25)
>     at new Request (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request/request.js:142:8)
>     at request (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request/index.js:55:10)
>     at TelegramBot._request (/Users/Alex/node_modules/node-telegram-bot-api/lib/telegram.js:184:14)
>     at TelegramBot.sendAudio (/Users/Alex/node_modules/node-telegram-bot-api/lib/telegram.js:435:19)
>     at TelegramBot.<anonymous> (/Users/Alex/WebstormProjects/untitled/game.js:24:13)
>     at TelegramBot.emit (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/eventemitter3/index.js:116:35)
>     at TelegramBot.processUpdate (/Users/Alex/node_modules/node-telegram-bot-api/lib/telegram.js:104:14)
>     at /Users/Alex/node_modules/node-telegram-bot-api/lib/telegramPolling.js:52:17
>     at Array.forEach (native)
>     at /Users/Alex/node_modules/node-telegram-bot-api/lib/telegramPolling.js:49:17
>     at tryCatcher (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
>     at Promise._settlePromiseAt (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
>     at Promise._settlePromises (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
>     at Async._drainQueue (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate](/Users/Alex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)

Please help

**Comment by GochoMugo** [comment]
I believe you are using the `TelegramBot.sendAudio()` method. Do you mind providing more information, such as the version of this package you are using, some context such as a snippet of where you are invoking the above-mentioned function, etc ?

**Comment by GochoMugo** [comment]
Stale for 1 month! Reopen only if you respond to earlier queries!
