### ISSUE TITLE
sendMessage: Current maximum length is 4096 UTF8 characters

### ISSUE THREAD

**Issue by phillipadsmith** [yagop/node-telegram-bot-api#165]
It seems that [Telegram has a maximum message length of 4096 characters](https://core.telegram.org/method/messages.sendMessage).

Some implementations have tried to work around it like so:
https://github.com/lukefx/hubot-telegram/blob/d0bc8c115d269a2fb6f292121a163012f1e29fb7/src/telegram.coffee#L74-L102

The biggest issue I'm having is message ordering, i.e., messages doesn't necessarily get delivered in the same order that they are sent, even if sent sequentially.

I'm wondering how others are working around this?

Phillip.

**Comment by GochoMugo** [comment]
I think this would better be implemented in a higher-level wrapper around this library. The wrapper would handle 'paging' and its complexities for different API methods/types, such as 4096 chars for [message.text](https://core.telegram.org/bots/api#message), 200 chars for [message.caption](https://core.telegram.org/bots/api#message), etc.

**Comment by phillipadsmith** [comment]
> I think this would better be implemented in a higher-level wrapper around this library. The wrapper would handle 'paging' and its complexities for different API methods/types, such as 4096 chars for message.text, 200 chars for message.caption, etc.

I'm in agreement, but that could be just because I'm lazy and there are some idiosyncrasies of the way that Telegram seems to handle the order of message delivery.

**Comment by GochoMugo** [comment]
Someone with some energy and time to spare should take the idea and spin up a nice library out of it.

Order of message delivery is quite an issue in **almost all** messaging platforms, particularly due to their distributed architecture, this asynchronous workings of the workers within.

**Comment by GochoMugo** [comment]
See #192 for some relevant information on this issue.

**Comment by GochoMugo** [comment]
Closing this issue as it seems the thread hit rock bottom! Thanks @phillipadsmith for your time.

**Comment by phillipadsmith** [comment]
> See #192 for some relevant information on this issue.

@GochoMugo Yes, quite delayed in my response here... :-/  So, reading that other thread, do you believe that there will be a resolution via the node-telegram-bot-api package?

**Comment by GochoMugo** [comment]
Currently, I do not think there are plans to add such advanced functionality. I would suggest building a library on top of this one. But if you can fit it into this library and draft a PR, we would be better placed to discuss and decide on the way forward.

**Comment by GochoMugo** [comment]
I built a library, [tgfancy][tgfancy], that supports [paging long text][paging].

[tgfancy]:https://github.com/GochoMugo/tgfancy
[paging]:https://github.com/GochoMugo/tgfancy#text-paging
