### ISSUE TITLE
Is it possible to leave a group?

### ISSUE THREAD

**Issue by jaimehrubiks** [yagop/node-telegram-bot-api#168]
I'd like to see if I can make my bot leave certain groups and super groups based on their chat.id 
I see that it is somehow available in the telegram API this feature, but I can't seem to find it in this lib. Is it already implemented? will it be?

Thanks

**Comment by GochoMugo** [comment]
@jaimehrubiks They are not implemented yet. But keep an eye on this PR https://github.com/yagop/node-telegram-bot-api/pull/158. It implements some of the new API methods (but not leaveChat, yet).

**Comment by kamikazechaser** [comment]
https://www.npmjs.com/package/node-telegram-bot-api-latest

**Comment by GochoMugo** [comment]
PR was merged in. See [TelegramBot#leaveChat()](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/README.md#TelegramBot+leaveChat).
