### ISSUE TITLE
How to send photo?

### ISSUE THREAD

**Issue by SirwanAfifi** [yagop/node-telegram-bot-api#171]
I'm using this code for sending photo as stream for the user But it doesn't send the photo:
```
var request = require('request');
        request.get(res.Poster, function (error, response, body) {
            if (!error && response.statusCode == 200) {
                bot.sendPhoto(msg.chat.id, response, { caption: res.Title });
            }
});
```
Any idea?

**Comment by aabreuglez** [comment]
Hi, you are not using streams exactly. request return a stream if you do not provide a callback, so the correct way is:

```
var request = require('request');

var pic_stream = request.get(res.Poster).on('error', function(err) { console.log(err); });

bot.sendPhoto(msg.chat.id, pic_stream, { caption: res.Title }); 
```

Hope it helps

**Comment by GochoMugo** [comment]
Thanks to @aabreuglez for providing [the solution](https://github.com/yagop/node-telegram-bot-api/issues/171#issuecomment-239759818) to this issue.
