### ISSUE TITLE
Not receiving group messages

### ISSUE THREAD

**Issue by gbrian** [yagop/node-telegram-bot-api#174]
Hi there,

My bot is admin on a group created by another user and is not receiving the messages.
Any idea ?

My code:
`
....
// Setup polling way
var bot = new TelegramBot(token, {polling: true});

// Any kind of message
bot.on('message', function (msg) {
...
});
....
`
Thanks in advance

**Comment by ohenepee** [comment]
I also can't recieve group messages (with bot mentions `@botname`) when I added my bot to my group

**Comment by kamikazechaser** [comment]
Have you disabled privacy?

**Comment by ohenepee** [comment]
I've tried all that... ENABLED and DISABLED... I got it to work by changing/editing my group settings from 'Public Supergroup' (supergroup with a public link) to 'Private Supergroup' (supergroup without a public link)

**Comment by Cameri** [comment]
If your bot is not getting messages:

1. Disable privacy mode with @botfather.
2. Kick bot from chat if it's already in it.
3. Invite bot to chat.

The order is important.

**Comment by gbrian** [comment]
Hi,
I followed @Cameri 's list and worked prefectly :+1: 

Thank you very much!

**Comment by krokofant** [comment]
FAQ worthy issue

**Comment by kamikazechaser** [comment]
@krokofant, The issue isn't dependent on this library but rather on Telegram's side.

**Comment by tungnguyenson** [comment]
> If your bot is not getting messages:
> 
> 1. Disable privacy mode with @Botfather.
> 2. Kick bot from chat if it's already in it.
> 3. Invite bot to chat.
> 
> The order is important.

I have 1 group in which not receiving message, the other groups and direct messages are okay. I also tried 3 steps above but still doesn't work. Still couldn't figure out what was wrong
