### ISSUE TITLE
still in development?

### ISSUE THREAD

**Issue by lenny76** [yagop/node-telegram-bot-api#181]
hi,
is this api still in development?

thanks
Lenny76

**Comment by GochoMugo** [comment]
I bet @yagop is busy with life. It happens. In the meantime, if you really really really want to use some of the fixes/features added by the PRs, you can use this 'upfork', https://github.com/GochoMugo/node-telegram-bot-api. It is **not** a replacement, just an up-to-date fork.

Again, this repo is the main source of truth.

**Comment by lenny76** [comment]
thanks!

**Comment by GochoMugo** [comment]
Thanks to @yagop I can now help maintain this project. So, yes! We are still in development. Hoping to maintain a live pulse of the project. Thanks for your interest. Watch the repo for new features and bug fixes.
