### ISSUE TITLE
Override text event with specific text

### ISSUE THREAD

**Issue by kenanchristian** [yagop/node-telegram-bot-api#183]
Hi there, it's a really awesome bot you make :)
I can't seem to find a way to override `bot.on('text')` event with a specific text.
Something like `bot.on(/hello/i)` still gives me response from `bot.on(text)`.

**Comment by GochoMugo** [comment]
That would be `bot.onText()` **not** `bot.on()`!

**Comment by kenanchristian** [comment]
so this is my code
```javascript
bot.on('text', function (msg) {
  var chatId = msg.chat.id;
  bot.sendMessage(chatId, 'hello text text');
});

bot.onText(/\/ping/i, function(msg){
  let chatId = msg.chat.id;
  bot.sendMessage(chatId,"pong");
})
```

when i use `/ping` command on telegram, it also sends `hello text text`

which one should be `onText` and which one should be `on`?

**Comment by GochoMugo** [comment]
The two methods are **not** exclusive. If the bot receives a text message, it **always** fires the `text` event (see [src/telegram.js#L95](https://github.com/yagop/node-telegram-bot-api/blob/96adb918c1e7740bb999924f1c8a3bdd29c77f1c/src/telegram.js#L95)). It then fires the corresponding callbacks for **all** matching regexps (see [src/telegram.js#L106](https://github.com/yagop/node-telegram-bot-api/blob/96adb918c1e7740bb999924f1c8a3bdd29c77f1c/src/telegram.js#L106)).

**Comment by GochoMugo** [comment]
Closing with an [accepted answer](https://github.com/yagop/node-telegram-bot-api/issues/183#issuecomment-243090936).

If the answer does **not** satisfy you, please reopen with more elaborate details and follow-up questions.
