### ISSUE TITLE
Wrong file identifier\/HTTP URL specified

### ISSUE THREAD

**Issue by kenanchristian** [yagop/node-telegram-bot-api#184]
Why do i always get this error after the bot successfully processing the request?

> Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Wrong file identifier\/HTTP URL specified"}
>     at C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\node-telegram-bot-api\lib\telegram.js:186:17
>     at tryCatcher (C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\request-promise\node_modules\bluebird\js\main\util.js:26:23)
>     at Promise._settlePromiseFromHandler (C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:507:31)
>     at Promise._settlePromiseAt (C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:581:18)
>     at Promise._settlePromises (C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:697:14)
>     at Async._drainQueue (C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\request-promise\node_modules\bluebird\js\main\async.js:123:16)
>     at Async._drainQueues (C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\request-promise\node_modules\bluebird\js\main\async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Christian Dimas\Desktop\telegramV2\node_modules\request-promise\node_modules\bluebird\js\main\async.js:15:14)
>     at tryOnImmediate (timers.js:543:15)
>     at processImmediate [as _immediateCallback] (timers.js:523:5)

**Comment by GochoMugo** [comment]
This is a response from the tg bot api. Which method are you using, e.g. sendPhoto ?

**Comment by kenanchristian** [comment]
cannot reply this error anymore, will open the issue if i got it again :+1:  thanks a lot! :grin:

**Comment by infiniti008** [comment]
I have the some problem. I send photo to my bot.
