### ISSUE TITLE
HTML parsing mode doesn't work

### ISSUE THREAD

**Issue by SirwanAfifi** [yagop/node-telegram-bot-api#188]
It seems that parsing mode doesn't work with `HTML`:

```
    bot.sendMessage(msg.chat.id, "<b>bold</b>, <strong>bold</strong>", new { parse_mode: "HTML" }).then(() => {
        // reply sent!
    });
```

**Comment by alexandercerutti** [comment]
You don't have to use "new" before the object. That object is not a class or such.
If I try to use new before, I get the error 
```Unhandled rejection TypeError: (intermediate value) is not a constructor```

**Comment by SirwanAfifi** [comment]
Thanks it works now, One more thing: What If I want to have a link that point to one of the command?
```
bot.sendMessage(msg.chat.id, "<a href='/anotherCommand '" + item1 + ">Hello</a>", { parse_mode: "HTML" }).then(() => {
        // reply sent!
 });
```
Actually it throws an exception:
`Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: URL host is empty"} .....`
It seems that, the URL must be valid, but I want my URL points to another command, So that user can click the like and the command will be executed.

**Comment by alexandercerutti** [comment]
When you print a telegram command, you don't need to print it as URL. When you print /anotherCommand as text, Telegram Clients will interpret it directly as a command. The problem is that you cannot attach a "item1" to the command. I think that the thing you want to do is not possibile.

**Comment by SirwanAfifi** [comment]
The problem is that, the command needs a parameter, suppose that I sent this message:
```
- \Command_1 param1
- \Command_2 param2
- \Command_3 param3
```
Now if user clicks one of the items it just sends the command, I want it to print as this:
`\Command_1 param1`

**Comment by alexandercerutti** [comment]
I'm sorry, but I think that there's no way to do that.

Il 10 set 2016 21:00, "Sirwan Afifi" <notifications@github.com> ha scritto:

**Comment by OVAnechka** [comment]
Hello, community, how should i parse my text if my message contains a js variable with html text inside? it's an actual answer from API, and i want to paste it to my reply?

**Comment by GochoMugo** [comment]
Conclusion:

1. The original query has been answered [above](https://github.com/yagop/node-telegram-bot-api/issues/188#issuecomment-245749268).
1. You can **not** pass parameters when clicking on a command. For example, `/command param` in the clients will allows users to click on `/command`, but it will **not** pass along `param`! You may want to use [Inline buttons](https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating) as suggested [above](https://github.com/yagop/node-telegram-bot-api/issues/188#issuecomment-246156047).
1. @OVAnechka: you may want to have a look at [cheerio](https://github.com/cheeriojs/cheerio#readme), "Fast, flexible & lean implementation of core jQuery".
