### ISSUE TITLE
Problem with "getUserProfilePhotos" method

### ISSUE THREAD

**Issue by coppokim** [yagop/node-telegram-bot-api#189]
The method "getUserProfilePhotos" doesnt work. 
I want to send to user his profile photo. Here is my code:

bot.on('message',function(msg){
    var chatId = msg.chat.id;
    var userId = msg.from.id;
    bot.sendPhoto(chatId, bot.getUserProfilePhotos (userId,1,1));
});

What is wrong with my code?

**Comment by alexandercerutti** [comment]
Premise: I use ES6 syntax, so `msg => { }` is about the same of `function(msg){}`.

`.getUserProfilePhotos` method returns a Promise Object. That means that you have first to invoke `bot.getUserProfilePhotos(userId, 1,1)` and then capture the returned object with a callback using Promise's `.then()` method:

```javascript
bot.on("message", msg => {
    var charId = msg.chat.id;
    var userId = msg.from.id;
    bot.getUserProfilePhotos(userId, 1,1).then( data => {
        console.log(data);
    });
});
```

Data will return you a [UserProfilePhotos](https://core.telegram.org/bots/api#userprofilephotos) object. In my case, I retrieve the following Object with parameters (userId, 1,1);

```javascript
{ total_count: 1, photos: [] }
```

So, you can understand that I cannot proceed ( I don't know why). Photos object is, as described on telegram bot api documentation, a **Array of Array of [PhotoSize](https://core.telegram.org/bots/api#photosize)**.

Instead, If I use getUserProfilePhotos(userId), I get this matrix (I have only one profile picture):

```javascript
[ [ { file_id: 'fileid1',
      file_size: 13781,
      width: 160,
      height: 160 },
    { file_id: 'fileid2',
      file_size: 35481,
      width: 320,
      height: 320 },
    { file_id: 'fileid3',
      file_size: 89428,
      width: 640,
      height: 640 } ] ]
``` 

So, to access to _file_id_, which is the property you need, you will need to access to a think such like this in your callback:

```javascript
data.photos[X][Y].file_id;
```

Where X is the photo you want to access and Y is the size. In fact, "_This object represents one size of a photo or a file / sticker thumbnail._", quoting from Photosize page.
Then, after have retrieved the file_id, you can use in the same callback `.sendPhoto()` method.

```javascript
bot.on("message", msg => {
    var charId = msg.chat.id;
    var userId = msg.from.id;
    bot.getUserProfilePhotos(userId, 1,1).then( data => {
        bot.sendPhoto(chatId, data.photos[X][Y].file_id);
    });
});
```

I hope this helped you. For any other questions, write down here. 😉

**Comment by coppokim** [comment]
alexandercerutti, thank you very very very much bro!!! It helped me)

**Comment by alexandercerutti** [comment]
You're welcome! 😄
