### ISSUE TITLE
How to make bot.on not called when bot.onText is called ?

### ISSUE THREAD

**Issue by ttpro1995** [yagop/node-telegram-bot-api#194]
I want to make a bot, when user type in any message, it reply "Meow meow meow meow". 
But when user type /help, it should reply "type anything to read cat sound" without reply "Meow meow meow meow". However, my bot running by the code below reply both "Meow meow meow meow" and "type anything to read cat meow" when user type /help
 
Here is my code

```javascript

'use strict';

var TelegramBot = require('node-telegram-bot-api');

var TOKEN = 'my telegram ID';
var USER = 'i have no idea what is this';

var bot = new TelegramBot(TOKEN,{polling:true});
console.log("bot is running");


// Matches /echo [whatever]
bot.onText(/\/help/, function (msg, match) {
  var fromId = msg.from.id;
  var resp = match[1];

  bot.sendMessage(fromId, "type anything to read cat sound");
});


// reply to any message
bot.on('message',function(msg){
    var chatId = msg.chat.id;
    var bot_response = "Meow meow meow meow";
    console.log(msg);
    bot.sendMessage(chatId,bot_response);
});

```

**Comment by GochoMugo** [comment]
The `"message"` event is **always** fired when an update of [Message](https://core.telegram.org/bots/api#message) type is received. Therefore, even if a regexp in `bot.onText()` is matched, the event is still fired. [See the method that processes each update](https://github.com/yagop/node-telegram-bot-api/blob/e0e5e9a7b0cbf823e008704b76d614e5da6e2922/src/telegram.js#L82).

Therefore, you may need to do sth like:

```js
bot.on('message', function(msg) {
    let text = msg.text;
    // Stop, if the message is for a '/help' command.
    // You may want to use a proper regexp
    // but for the sake of brevity... :)
    if (text && text === "/help") return;

    // ... snip ...
});
```

**Comment by BeInLife** [comment]
It's better to use not if (text && text === "/help") return;
but if (msg.entities) return;

**Comment by GochoMugo** [comment]
Your issue has been addressed above. It's a design issue that should be addressed in your application.
