### ISSUE TITLE
How to know who executed a command?

### ISSUE THREAD

**Issue by SirwanAfifi** [yagop/node-telegram-bot-api#195]
I want to have a logging mechanism in my application So I want to know who executed a command, for example suppose that I have following command to be sent:
```
bot.onText(/^\/test (.+)$/, (msg, match) => {
   // here I want to know who called this command, for example something like this:
  // console.log(user);
}
```

**Comment by GochoMugo** [comment]
The `TelegramBot#onText()` method handles entities of type [Message](https://core.telegram.org/bots/api#message). Therefore, you can find the sender's [User](https://core.telegram.org/bots/api#user) object, at `msg.from`.

Thus,

```js
bot.onText(/^\/test (.+)$/, (msg, match) => {
    const user = msg.from;
    console.log(user);
}
```

**Comment by GochoMugo** [comment]
See the [accepted answer](https://github.com/yagop/node-telegram-bot-api/issues/195#issuecomment-249872190).
