### ISSUE TITLE
Buttons size in keyboard?

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#196]
I have noticed that buttons are very big among usually.
There is a way to set height of buttons? Thanks!

**Comment by dotcypress** [comment]
You can play with `resize_keyboard` [option](https://core.telegram.org/bots/api#replykeyboardmarkup)

**Comment by GochoMugo** [comment]
@dotcypress' answer hits the spot! Thanks!

**Comment by sachinrajl** [comment]
If you are using laravel library the add below code :  
Add ['resize_keyboard' => true] in make() function. 

$keyboard = Keyboard::make(['resize_keyboard' => true]) ->row( Keyboard::button(['text' => "\xE2\x9C\x8F Register"]), Keyboard::button(['text' => "\xE2\x98\x91 Verify Account"]) );
--

**Comment by BMukhtar** [comment]
Can i put custom size to keyboard? like 1/2 of half screen

**Comment by AlexanderSutul** [comment]
> Can i put custom size to keyboard? like 1/2 of half screen

Hi! Have you done this task? I need an answer for the question of the height of the buttons =)

**Comment by kamikazechaser** [comment]
> Can i put custom size to keyboard? like 1/2 of half screen

No, Telegram fits it optimally on the screen, you don't have finer access to tuning the size.
