### ISSUE TITLE
Return the users list of a group chat

### ISSUE THREAD

**Issue by ivanminutillo** [yagop/node-telegram-bot-api#198]
is it actually possible to get the username of all users in a chat group?

**Comment by alexandercerutti** [comment]
There's no way to do that. Telegram's bot API doesn't provide any method to get something such an array of [User](https://core.telegram.org/bots/api#user).

**Comment by GochoMugo** [comment]
As @alexandercerutti has said, there's **no** way to do this with the Bot API. Please [redirect your query to the Telegram Staff](https://core.telegram.org/bots/faq#will-you-add-x-to-the-bot-api).
