### ISSUE TITLE
Too Many Request

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#199]
Hi, this is my error message, there is a way to set time/request or something else to prevent it?

`Error: 429 {"ok":false,"error_code":429,"description":"Too Many Requests: retry after 134"}`

Thanks!

**Comment by kamikazechaser** [comment]
https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

Use setInterval to avoid this or comeup with a middleware like[ this one ](https://github.com/telegraf/telegraf-ratelimit/tree/develop/lib)

**Comment by GochoMugo** [comment]
Thanks @kamikazechaser for the correct answer to the query above.

Please note that this library does **not** handle rate-limiting for you. You need to handle it on a higher level (with the library being low-level).
