### ISSUE TITLE
Use 0ms as polling interval value

### ISSUE THREAD

**Issue by sekogan** [yagop/node-telegram-bot-api#20]
Hi!

I would like to perform long polling like this:

```js
var bot = new TelegramBot(token, { polling: { timeout: 2000, interval: 0 } });
```

The problem is that 0 is replaced with default 2000ms inside the module. I can use `interval: 1`. It solves the issue but doesn't feel right. Is there any other way to perform long polling?

**Comment by yagop** [comment]
As said on #41 I don't know why people want to do 0ms pooling interval, its really annoying for server and client, its just like DDoSing Telegram.

I will set default polling interval by 300ms

**Comment by sekogan** [comment]
The reason is simple: I want to receive updates from servers immediately, without 300ms or whatever delay. It's not a DDoS because a non-zero timeout is passed to getUpdates calls (I use 5000ms). A server doesn't reply until new messages are available or timeout is reached so I still do 12 requests per minute but get new messages instantly. I am wondering why setTimeout is used to perform polling? Is it OK for you guys to receive messages with a 2000ms delay?

**Comment by yagop** [comment]
You can setup 1ms if you wish but you should consider some things. The precision of [setTimeout](https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_arg) its not guarantee, can't even notice the difference between 1ms. Most of the delay its provided by the HTTP connection itself. Pooling with very few timeout may lead on a client ban and its a waste of requests. Maybe a webHook its more suitable for you.

**Comment by yagop** [comment]
I were testing the getUpdates HTTP method in the past. According with Telegram documentation, if a message arrives when the HTTP is established it will be forwarded to client. The truth is they weren't (at last when I tried). So I recommend to use 0ms as timeout and that is why by [default](https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegramPolling.js#L19) it's set to 0.

**Comment by yagop** [comment]
Allow 0ms as polling interval.
Default timeout 10 seconds.
