### ISSUE TITLE
REPLY_MARKUP_TOO_LONG

### ISSUE THREAD

**Issue by siqueira-ec** [yagop/node-telegram-bot-api#200]
I'm trying to pass a list of cities through keyboard, but i'm receiving: 

`Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"REPLY_MARKUP_TOO_LONG"}
`

Any ideas?

**Comment by sidelux** [comment]
Telegram has a buttons limit of 100 (or 150 can't remember with precision), over this limit return error!

**Comment by siqueira-ec** [comment]
Thanks!
