### ISSUE TITLE
Support of request cancellation

### ISSUE THREAD

**Issue by dimotsai** [yagop/node-telegram-bot-api#202]
I was working on my project, trying to cancel some API requests as following:

``` js
const TelegramBot = require('node-telegram-bot-api');

let telegramBot = new TelegramBot('BOT_TOKEN' , {polling: false})

let doAsync = () => telegramBot.sendPhoto(CHAT_ID, 'wallpaper.jpg');

doAsync().cancel();
```

It seems like that `doAsync()` is not cancellable. The request won't terminate until the photo is sent.
## 

I found the current dependency is `request-promise@v2.0.1`. That will be nice if you could upgrade `request-promise` to the latest version!

A part of changelog from `request-promise`:

```
v4.1.0 (2016-07-30)
* Added cancellation support (Thanks to @not-an-aardvark for pull request #123)
```

**Comment by GochoMugo** [comment]
This has been added in v0.25.0!

Thanks @dimotsai for your interest in this library!

**Comment by dimotsai** [comment]
@GochoMugo Good job! Thanks for supporting. This is a nice library :)
