### ISSUE TITLE
When games api will be added?

### ISSUE THREAD

**Issue by highfeed** [yagop/node-telegram-bot-api#203]
When games api will be added?

**Comment by GochoMugo** [comment]
PR #201 is addressing this. Watch it...

**Comment by GochoMugo** [comment]
Some of the Game API methods have been added. Specifically, [TelegramBot#sendGame()](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/README.md#TelegramBot+sendGame) and [TelegramBot#setGameScore()](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/README.md#TelegramBot+setGameScore). Thanks to @jishnu7!

Also, @jishnu7 [promised us](https://github.com/yagop/node-telegram-bot-api/pull/201#issuecomment-252622527) to implement the remaining methods. :smile:

Will keep this issue open until the remaining methods are implemented and published.

**Comment by GochoMugo** [comment]
This has been added in v0.25.0!

Thanks @highfeed for your interest in this library!
