### ISSUE TITLE
 Get message_id using sendMessage

### ISSUE THREAD

**Issue by omarkdev** [yagop/node-telegram-bot-api#206]
Is there any way to get the message_id when using sendMessage? He is returning a promise.

**Comment by GochoMugo** [comment]
You would do:

```js
bot.sendMessage(chatId, messageText).then(function(msg) {
    // 'msg' is the sent message
    console.log(msg.message_id);
});
```

Ad [documented](https://core.telegram.org/bots/api#sendmessage), the sent [Message](https://core.telegram.org/bots/api#message) is returned.
