### ISSUE TITLE
request-promise causes memory leaks

### ISSUE THREAD

**Issue by desunit** [yagop/node-telegram-bot-api#207]
The current version of request-promise looks like contain a memory leak (related to #52) because of internal cache implementation according to Chrome profile. I've updated `package.json` with request-promise ^4.1.1 and it looks the problem with leaks was mitigated. 

You can reproduce the problem by increasing timer interval to 10 and leave it for an hour.

**Comment by GochoMugo** [comment]
This has been fixed in v0.25.0!

Thanks @desunit for the bug report!
