### ISSUE TITLE
Implement getGameHighScores

### ISSUE THREAD

**Issue by yagop** [yagop/node-telegram-bot-api#208]
Implement method `getGameHighScores`.

https://core.telegram.org/bots/api#getgamehighscores

**Comment by chrisonntag** [comment]
Hi @yagop, I'd like to work on this if you don't mind 😊

**Comment by yagop** [comment]
![https://media.giphy.com/media/l3E6tfijzciPpgCdi/giphy.gif](https://media.giphy.com/media/l3E6tfijzciPpgCdi/giphy.gif)

**Comment by chrisonntag** [comment]
I didn't find any tests for 'games' in general. Should i open an own issue on that? I'd like to test it first.

**Comment by GochoMugo** [comment]
@chrisonntag I think it would be better to have a separate issue (or PR :smile:) for the tests. We really need help in our tests.

**Comment by GochoMugo** [comment]
This has been added in v0.25.0!
