### ISSUE TITLE
Fix travis error on #setWebHook should set a webHook with certificate

### ISSUE THREAD

**Issue by yagop** [yagop/node-telegram-bot-api#209]
It seems the query limit for setWebHook is very low, maybe changing to the second call might works.

https://travis-ci.org/yagop/node-telegram-bot-api/jobs/167039328#L267

**Comment by arpit1997** [comment]
` 1) Telegram #setWebHook should set a webHook with certificate:`
` Error: 429 {"ok":false,"error_code":429,"description":"Too Many Requests: retry after 1","parameters":{"retry_after":1}}`

Above is not an error, It is just a server's response telling that you are sending too many requests. May be you need another `API key` or less requests.
You may refer to [this](https://httpstatuses.com/429)

**Comment by yagop** [comment]
Exactly, my approach is to change the second call to the ending.
I think is an easy task but should be done for passing Travis tests.

**Comment by GochoMugo** [comment]
This was handled in our test suite by retrying requests after the recommended timeout, in case of rate-limiting issues.
