### ISSUE TITLE
ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by anonrab** [yagop/node-telegram-bot-api#21]
Is this api supports ReplyKeyboardMarkup?

**Comment by mrpatiwi** [comment]
Sure, take a look at: https://github.com/yagop/node-telegram-bot-api/blob/master/examples/polling.js#L33

**Comment by anonrab** [comment]
thanks, will look carefully examples next time :)

**Comment by milad145** [comment]
hi,
i want show keyboards in telegrom bot whithout send any text before that
how can i do that?

**Comment by saeedhei** [comment]
Milad "/start" is your first text and after that you can show your keyboards

**Comment by milad145** [comment]
i have this
```
        var chatId = msg.chat.id;
	var fromId = msg.from.id;

	let replyOptions = {
		reply_markup: {
			resize_keyboard: true,
			one_time_keyboard: true,
			keyboard: [
				['yes'],
				['no']
			],
		},
	};
	bot.sendMessage(fromId, null, replyOptions)
```

i want just show keyboards without any message but sendMessage needs text 
how can i do that
