### ISSUE TITLE
Unable to link with Express

### ISSUE THREAD

**Issue by kennetham** [yagop/node-telegram-bot-api#210]
I am trying to integrate this with Express, any idea or samples to how the integration should be like? The polling or webhook would interfere with the current port isn't it?

**Comment by GochoMugo** [comment]
Could you suggest how you would expect the library to integrate with Express? Could you add elaborate code snippets to try explain to us?

**Comment by kennetham** [comment]
I am thinking since telegram supports webhook, possibly using app.use, to map the webhook to setup the webhook for telegram. At the moment, for example, if we have an Express server to serve other endpoints, integrating telegram would be convenient than executing it as an external script.

Please advise.

**Comment by GochoMugo** [comment]
can you write some code just to illustrate?

**Comment by kennetham** [comment]
Sure.

For example,

```node
telegram_webhook = require('./backend/routes/telegram/webhook'),
...
app.use('/webhook', telegram_webhook);
...
app.use(function (err, req, res, next) {
	res.status(err.status || 500);
});

const port = process.env.PORT || SERVER_PORT;
const http_server = require('http').createServer(app);
http_server.listen(port, function () {
	console.log(`${APP_NAME} running on port ${port}.`);
});
```

How can we run Telegram webhook within the webhook for instance?

**Comment by GochoMugo** [comment]
You have to remember that the webhook receives all kinds of updates, for example, new messages, edited messages, callback queries, etc. So you might want to handle this in your Express middleware, probably by re-writing the route for subsequent middlewares.

If that is the case, this package might not be what you want. You will want to get more "low-level", so that you process the actual updates as they are received, rather than work with events.

**Comment by kennetham** [comment]
You are right there! I also figured that I could work around that by just running as a new process.

Thanks! I'll close this thread.

**Comment by yagop** [comment]
I think it would be cool having the possibility to inject the Express router, even using it.

**Comment by kennetham** [comment]
Yes, it would be cool. In fact, it would pretty helpful especially since we have a webhook feature, everything sits nicely in the architecture.
