### ISSUE TITLE
Messages in sequence

### ISSUE THREAD

**Issue by siqueira-ec** [yagop/node-telegram-bot-api#217]
First of all, sorry for my English.

Second, I would like to just send a message after the previous one has been sent to ensure a specific order.

For example, I am using a 'forEach' to send a list of pictures whose links are in an array, but the descriptions of each exceeds 200 characters, so by the time a photo was delivered I would like to send their respective description below.

Thanks.

**Comment by yagop** [comment]
You can't use `forEach` because its an asynchronous operation and you need to wait. I would use Bluebird [each](http://bluebirdjs.com/docs/api/promise.each.html) promise like this:

```js
// Code not tested
const Promise = require('bluebird');
const txts = ['lorem ipsum', 'lalalalala'];

Promise.each(txts, txt => {
  return bot.sendMessage(CHAT_ID, txt);
});
```

**Comment by GochoMugo** [comment]
I have built a wrapper around this library to add higher-level features. Currently, it supports sending messages **in order**. It is called **tgfancy**. See https://github.com/GochoMugo/tgfancy for more information.

I hope it solves your problem. (But it's still a work-in-progress)!

**Comment by siqueira-ec** [comment]
I need to do something like that:

```
var arr_photos = [
    {img: 'url.com/photo1.jpg', desc: 'long description with +200 chars for photo1'},
    {img: 'url.com/photo2.jpg', desc: 'long description with +200 chars for photo2'}
]
//i need to send photo1 + description for photo1 in sequence
```

**Comment by GochoMugo** [comment]
Building on top of @yagop's answer:

```js
const Promise = require("bluebird");

// iterate over 'arr_photos' in series
Promise.mapSeries(arr_photos, function(photo) {
    // 'photo' is an element in 'arr_photos'
    // send the image of the 'photo'
    return bot.sendPhoto(chatId, photo.img)
        .then(function() {
            // after image has been sent, send the description of the 'photo'
            return bot.sendMessage(chatId, photo.desc);
        });
}).then(function() {
    // after all messages have been sent successfully
}).catch(function(error) {
    // handle error!
});
```

See documentation on [Promise.mapSeries()](http://bluebirdjs.com/docs/api/promise.mapseries.html).

**Comment by GochoMugo** [comment]
Your query has been addressed in [comment above](https://github.com/yagop/node-telegram-bot-api/issues/217#issuecomment-257140387).

Feel free to re-open the issue and provide more information, if the above discussion did **not** solve your problem.
