### ISSUE TITLE
Is it scalable? 

### ISSUE THREAD

**Issue by omidh28** [yagop/node-telegram-bot-api#219]
Hi, I've made a telegram bot which does CPU-heavy things.
I wonder, Can I just use pm2 and scale the bot?

**Comment by GochoMugo** [comment]
If you are using **polling**, it is **not** scalable at all! This is because polling uses offsets to retrieve new updates. If your application is scaled to multiple instances, each of these instance will use its **own and separate** offset. Therefore, there exists the chance that different application instances will process the same update.

However, when using **webhooks** it is scalable. How? You would `bot.setWebhook(url)`, where `url` points to a load balancer, such as Nginx, that'd re-route the request to an application instance, depending on set strategy.

**Comment by omidh28** [comment]
@GochoMugo Thanks but I'm a little confused. I don't want some kind of complex load balancer, I just want a simple nodeJs middle-ware to reroute requests randomly. 

I just don't know how to do it or where to start, Can you give me some tips?

**Comment by GochoMugo** [comment]
IMHO, it is better to use an already-established load balancer, rather than re-invent the wheel.

However, you could use [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) to proxy requests to different application instances. [PM2](https://github.com/Unitech/pm2) could help you handle clustering.

**Comment by omidh28** [comment]
I tried to use Nginx but I gave up after a few hours of trying to implement it. So I personally suggest [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) which is more flexible and familiar.

**Comment by ohenepee** [comment]
@omidh28 If you managed to implement your said architecture, could you share with the structural code? i want to run multiple bots with node-http-proxy via the webhook API, but I don't know where to start? As I don't understand how to get the bot both listening on the same port (8443 [non-root])

**Comment by GochoMugo** [comment]
Re-open to ensure this is documented in our help information.

**Comment by omidh28** [comment]
@ohenepee You can't make all bots to listen on the same port but you can make load balancer to listen on port 8443 and use proxy to redirect requests so you can start your bots on any port you want as long as your load balancer is on the right port.

However it's usually overkill and only rational if you want to have the same bot on different servers. If that isn't your case then just use nodeJs cluster (Too many requests error can be safely ignored):

Also note that nodeJs clusters are just seperate processes and do not share memory.
``` javascript
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length;

if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);

  // Fork workers.
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  const token = 'Your Token';
  const options = {
    webHook: {
      port: 8443,
      key: `${__dirname}/PRIVATE.key`,  // Path to file with PEM private key
      cert: `${__dirname}/PUBLIC.pem`  // Path to file with PEM certificate
    }
  };

  const bot = new TelegramBot(token, options);
  bot.setWebHook(`https://${YOUR_SERVER_IP}:8443/bot${token}`, {
    certificate: options.webHook.cert,
  });

  console.log(`Worker ${process.pid} started`);
}

```

Still if you want to make a separate load balancer, you can use [node-http-proxy](https://github.com/nodejitsu/node-http-proxy).

``` javascript
const https     = require('https');
const httpProxy = require('http-proxy');
const fs        = require('fs');
const _         = require('lodash');

const proxy = httpProxy.createServer();
const certification = {
  key: fs.readFileSync(KEYPATH),
  cert: fs.readFileSync(CERTPATH)
};

const servers = ['127.0.0.1:3000', '127.0.0.2:3001'];

function pickOneServer() {
  return _.sample(servers);
}

https.createServer(certification, (req, res) => {
  // check req.url just to be sure that it is a bot request
  const chosenServer = pickOneServer(botKey);
  proxy.web(req, res, {
    target: `https://${chosenServer}`,
    secure: false
  });
}).listen(8443);

```

This is a very simple load balancer. Note that I did not change https to http because node-telegram-bot-api still expects secure connection even though it does not run on the ports such as 443 or 8443 anymore.

Also you need to do some changes on your bot settings.

``` javascript
  const options = {
    webHook: {
      port: 3000, // or any other port you want
      key: `${__dirname}/PRIVATE.key`,  // Path to file with PEM private key
      cert: `${__dirname}/PUBLIC.pem`  // Path to file with PEM certificate
    }
  };

  const loadbalancerAddress = 'LOAD_BALANCER_IP:8443';
  const bot = new TelegramBot(token, options);
  bot.setWebHook(`https://${loadbalancerAddress}/bot${token}`, {
    certificate: options.webHook.cert,
  });

```

**Comment by mahantaf** [comment]
It's helpful thank you

**Comment by ohenepee** [comment]
How about using the Express server example to run multiple bots?

Something like this...
```
/**
 * This example demonstrates setting up a webook, and receiving
 * updates in your express app
 */

const TOKEN_FOR_ACTIONS_BOT = 'YOUR_TELEGRAM_BOT_TOKEN';
const TOKEN_FOR_INFOS_BOT = 'YOUR_TELEGRAM_BOT_TOKEN';
const url = 'https://<PUBLIC-URL>';
const port = process.env.PORT;

const TelegramBot = require('node-telegram-bot-api');
const express = require('express');
const bodyParser = require('body-parser');

// No need to pass any parameters as we will handle the updates with Express
const botForActions = new TelegramBot(TOKEN);
const botForInfos = new TelegramBot(TOKEN);

// This informs the Telegram servers of the new webhook.
botForActions.setWebHook(`${url}/bot${TOKEN_FOR_ACTIONS_BOT}`)
botForInfos.setWebHook(`${url}/bot${TOKEN_FOR_INFOS_BOT}`)

const app = express()

// parse the updates to JSON
app.use(bodyParser.json())

// We are receiving updates at the route below!
app.post(`/bot${TOKEN_FOR_ACTIONS_BOT}`, (req, res) => {
  botForActions.processUpdate(req.body);
  res.sendStatus(200);
})

// We are receiving updates at the route below!
app.post(`/bot${TOKEN_FOR_INFOS_BOT}`, (req, res) => {
  botForInfos.processUpdate(req.body);
  res.sendStatus(200);
})

// Start Express Server
app.listen(port, () => {
  console.log(`Express server is listening on ${port}`);
})

// Just to ping!
botForActions.on('message', msg => {
  bot.sendMessage(msg.chat.id, 'I am alive!... says Actions Bot');
});

// Just to ping!
botForInfos.on('message', msg => {
  bot.sendMessage(msg.chat.id, 'I am alive!... says Info Bot');
});
```

**Comment by wisdomabioye** [comment]
Very helpful issue. Thanks

**Comment by imdkbj** [comment]
Pls share if have working code for that, i am totally confused with nodeJS and multiple bot to listen for single class.

**Comment by melroy89** [comment]
It's causing issues at my side due to Telegram maybe? I get the error:

```
ETELEGRAM: 429 Too Many Requests: retry after
```

How to scale the application across multiple cores using the built-in NodeJS `cluster` package, will not causing this telegram rate limit error. I suspect `setWebHook()` is causing this issue.

**Comment by kamranpirwani** [comment]
> It's causing issues at my side due to Telegram maybe? I get the error:
> 
> ```
> ETELEGRAM: 429 Too Many Requests: retry after
> ```
> 
> How to scale the application across multiple cores using the built-in NodeJS `cluster` package, will not causing this telegram rate limit error. I suspect `setWebHook()` is causing this issue.

Having the same issue here, did you figure this out?
