### ISSUE TITLE
It's a bad idea to check users' text messages against every regex

### ISSUE THREAD

**Issue by omidh28** [yagop/node-telegram-bot-api#220]
Something I noticed while I was creating a bot, That every text message is checked against every regex and even though a match has been found, The program does not stop searching.

This is usually unwanted for a couple of reasons:

1. It reduces program's performance, Regex checking is not a very cheap operation.
2. It makes writing code harder because program flow is unknown, I can't say for sure which one is checked and executed first.

For example, I was making a command to allow users to send plain messages to the developer(Some type of contact us). 

`bot.onText(/\/start/)` to start the conversation and allow the user to send non-command text.
`bot.onText(/\/cancel/)` for the cases that user does not want to contact anymore instead he wants to cancel the conversation.

I have two options for getting the user's plain message

1. `bot.on('message')`
2. `bot.onText(/.*/)`

Choosing any of those does not make any difference, They both have same problems. 
What is the problem? If the user types "/cancel" two thing are going to happen:

1. `bot.onText(/\/cancel/)` is triggered, To declare that the user must not be able to send plain-message anymore. Commands Only. 
2.  `bot.on('message')` Is still executed and it pushes "/cancel" into the database! Why? because `bot.onText(/\/cancel/)` is late and the program does not know the user has canceled the conversation. So instead of a real user conversation, The program pushes "/cancel" into the database as the user's message.

Of course I can stop using `bot.onText()` and instead switch back to `bot.on('message')` However It'd be nice to implement it as a configuration option so other's bots will not break.

A configuration option which checks  `bot.onText()` in definition order until a match has found, If no match has been found, It should fallback to `bot.on('message')`

**Comment by GingerPlusPlus** [comment]
#216 :)

**Comment by GochoMugo** [comment]
The essence of events is to signal all listening objects of an occurrence of something. This means that events **should** always be fired, when their corresponding activity occurs. The text regexps should **not** change this behavior of event emitters.

However, as for the text regexps we can allow stopping after the first match. Which would definitely have to be **opt-in**; ensures backwards compatibility! This stopping after first match would be majorly helpful, for example, when one is trying to re-create the behavior of express routers.

**Comment by GochoMugo** [comment]
This has been added in v0.25.0! See [documentation on constructor](https://github.com/yagop/node-telegram-bot-api#new-telegrambottoken-options) for the `onlyFirstMatch` option!

Thanks @omidh28 for your interest in this library!
Thanks @GingerPlusPlus for your time and effort in the PR!!!
