### ISSUE TITLE
add preview option to message, so we can set it to false

### ISSUE THREAD

**Issue by hems** [yagop/node-telegram-bot-api#221]
I believe setting "preview" to false will hide telegram preview for links which is very useful

I believe [tg has it implemented](https://github.com/vysheng/tg/blob/master/tg-test.py#L49)

**Comment by hems** [comment]
actually, my bad, it already exists:

disable_web_page_preview: false !

**Comment by GochoMugo** [comment]
This issue was opened and closed in less than 2 minutes! That must be a guinness world record! :laughing: :laughing:

**Comment by hems** [comment]
yeah it took me some time to find the link to the documentation and realise the library simply forwarded the parameters :P
