### ISSUE TITLE
How to provide game link?

### ISSUE THREAD

**Issue by heidarmostafa** [yagop/node-telegram-bot-api#222]
Hello guys,

I'm trying to serve an HTML5 game via the new API, I did this so far:
```
bot.on('callback_query', function (msg) {
	console.log(colors.blue('got an callback_query message'), arguments);
});
```

and I get this response when I click on the game button
```
{ '0':
   { id: 'xxx',
     from: { id: 111, first_name: 'xxx', last_name: 'xxx' },
     inline_message_id: 'xxx',
     chat_instance: 'xxx',
     game_short_name: 'xxx' } }
```

Given the game is already uploaded to a url: http://sampleurl/mygame, how can I serve it on the callback?
Thanks
BR
Heidar

**Comment by heidarmostafa** [comment]
I found the solution, I used:
bot.answerCallbackQuery(msg.id, gameLink, true, {url: gameLink});

you can close it

**Comment by yagop** [comment]
Nice. Closed

**Comment by MCSH** [comment]
Could we please document this?

Or add an example?

**Comment by GochoMugo** [comment]
@MCSH  Could you build a **small** HTML5 game we could use for demo purposes?

**Comment by MCSH** [comment]
Sure thing, I'll write an example as well using express for serving the game file (if that's okay)
