### ISSUE TITLE
Message is too long "error_code":400

### ISSUE THREAD

**Issue by EllysahatNMI** [yagop/node-telegram-bot-api#223]
Hi! I was using the simple "bot.sendMessage" api to send messages but I received this error. 

Do you know the limit to the length of the message? Or maybe tell me how I can change the limit.

**Comment by GochoMugo** [comment]
The Maximum number of characters allowed is 4096! You will have to split your messages. (Check out [tgfancy](https://github.com/GochoMugo/tgfancy) for a possible solution)
