### ISSUE TITLE
handling many requests per second

### ISSUE THREAD

**Issue by sabatayebifar** [yagop/node-telegram-bot-api#226]
Hi, I use the api and my bot is polling like this : 
`bot.onText(/blah/, function (msg) {`
`	sessionManager(msg)`
`…..`
`}`
`bot.onText(/foo/, function (msg) {`
`	sessionManager(msg)`
`…..`
`}`

It works fine until request per second goes upper than 4 or 5. Then it seems that my session manager function –which I call in every function that matches regex-  is mixing values of different requests!!!
I don’t know where the problem is. Is this happening because of polling and I should use webhooks? Could it be the problem of the api? Could it be my node ttl map that I am using as a session?

Please help me go through this. Requests per second will go up to 50 or 60 per second! And the bot is completely useless then.

**Comment by vio17** [comment]
Hi, Did you solve this problem ?

**Comment by sabatayebifar** [comment]
hey vio17,
The problem was in my session management actually. I used a global array as session but it seems nodejs does not support modifying same global variable on different threads and it gets all messed up. So i started using Redis-session module as my session.
