### ISSUE TITLE
write EPIPE error !!

### ISSUE THREAD

**Issue by vio17** [yagop/node-telegram-bot-api#229]
hello 
I have create a bot and run it in commandline in centos server . always after one or two days it just hang up , and puts the error "write EPIPE" in console .
and bot stops 

![capture2](https://cloud.githubusercontent.com/assets/19633582/20682601/de88fc5e-b5bd-11e6-9d12-260961a69627.JPG)

**Comment by vio17** [comment]
another screen shot : 
![capture3](https://cloud.githubusercontent.com/assets/19633582/20741330/c776c038-b6de-11e6-908e-d283917522d8.JPG)

**Comment by GochoMugo** [comment]
1. Which version of this library are you using?
1. Could you provide us with more debugging information?

Also, have a look at this thread (https://groups.google.com/forum/#!topic/nodejs/8VBd36dPbnU) discussing such a situation.

**Comment by GochoMugo** [comment]
Stale for 1 month! Reopen only if you respond to earlier queries!
