### ISSUE TITLE
Please fix npm package

### ISSUE THREAD

**Issue by snarknn** [yagop/node-telegram-bot-api#230]
While installing via "npm install node-telegram-bot-api" older version is installed, looks like 0.20.1 or so.
Trying to install "npm install https://github.com/yagop/node-telegram-bot-api" - no actual code is loaded, just almost empty index.js with broken require inside.

**Comment by GochoMugo** [comment]
I can **not** seem to reproduce this error.

1. Installing from npm works perfectly for me:

![yagop-npm-good](https://cloud.githubusercontent.com/assets/4707579/20857643/6fd5d46a-b943-11e6-8033-bf502140b33b.png)

1. Installing from Github will **not** work as the source files are ignored in `.npmignore` file. (PS: we transpile our ES6 code using Babel before publishing to npm)

**Comment by GochoMugo** [comment]
Please provide us with more information on how to reproduce this bug. Otherwise, we will close this issue in some time to come.
