### ISSUE TITLE
A way to catch if user enter or leave chat

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#231]
Is possibile to know when a user enter/leave a chat and so what event is fired?
I can't find anything on README in main page.

I'm sorry if this problem is already solved time ago.

Thanks!

**Comment by GochoMugo** [comment]
Are you looking for the `new_chat_participant` and `left_chat_participant` events?

**Comment by sidelux** [comment]
Exatly, my idk how ti use it.

**Comment by GochoMugo** [comment]
```js
bot.on('new_chat_participant', function(message) {
  // 'message' is a Telegram Message

  // 'user' below is a Telegram User
  const user = message['new_chat_participant'];
});


bot.on('left_chat_participant', function(message) {
  // 'message' is a Telegram Message

  // 'user' below is a Telegram User
  const user = message['left_chat_participant'];
});
```

* Telegram Message: https://core.telegram.org/bots/api#message
* Telegram User: https://core.telegram.org/bots/api#user

**Comment by sidelux** [comment]
Perfect, thanks!

**Comment by mehranrasulian** [comment]
Hi there,

I've used the `new_chat_members` event to know weather a new user joined the bot or not. But seems that this event will not be emitted:
```javascript
    bot.on('new_chat_members', (msg) => {
      const chatId = msg.chat.id;

      bot.sendMessage(chatId, 'Received your message')
    })
```

But using the `message` event I will get the below result:
```json
{"message_id":4,"from":{"id":324299944,"is_bot":false,"first_name":"foo","last_name":"bar","language_code":"en"},"chat":{"id":324299944,"first_name":"foo","last_name":"bar","type":"private"},"date":1513786467,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]
```

How could I handle that?

**Comment by sidelux** [comment]
@mehranrasulian 
If i understood correctly i think you should use this simple method:

```
bot.onText(/\/start/i, function (message, match) {
    bot.sendMessage(message.chat.id, "Welcome!")
}
```

Otherwise, if you want to handle the **first time** that user use /start, i think you can only save this state on database or file and check every time user write /start or reboot bot.

**Comment by SJPiran** [comment]
hi dears ,how to know a user leave the bot in telegraf js, can you help me?

**Comment by bek-shoyatbekov** [comment]
> hi dears ,how to know a user leave the bot in telegraf js, can you help me?

hi , this is another framework's issue section....
