### ISSUE TITLE
The method "endsWith()" is not supported by this library

### ISSUE THREAD

**Issue by Ecron** [yagop/node-telegram-bot-api#232]
Hello! I just started to use this library to create a bot, and I'm not a developer so I'm still learning (a lot) of JS.

**But**, I wanted to use the string method `endsWith()` to check whether a `message.text` ends with a specific set of characters, but I get the following error: `Unhandled rejection TypeError: undefined is not a function`. The code is as simple as `console.log(message.text.endsWith("a"));`.

Do anyone know what I am doing wrong? Or, is it an error with the node-telegram-bot-api?

Thanks in advance ;-)

**Comment by yagop** [comment]
[`endsWith()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) is a Prototype of String. It was included on ECMAScript 2015 (aka ES6). The JavaScript features depends on your Node.JS version.
Make sure you are using a modern Node.js (I use v7) with the [features](http://node.green/) you need.

**Comment by Ecron** [comment]
OMG, thank you very much. Can you believe I installed the version 0.12.2?? 😰 Damn out-to-date distribution packages...
