### ISSUE TITLE
How can I check if the user has started my bot?

### ISSUE THREAD

**Issue by ronald2wing** [yagop/node-telegram-bot-api#233]
Any ways to do it?
I am getting (403 {"ok":false,"error_code":403,"description":"Forbidden: Bot was blocked by the user"}) when the user has not enabled my bot.

**Comment by ronald2wing** [comment]
I fixed it by using a catch to catch errors after the sendMessage();

**Comment by yagop** [comment]
I think Telegram doesn't offer a way to know if a user has started the bot.

You can store in database users and know how have talked to it.
