### ISSUE TITLE
(node:63097) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1)

### ISSUE THREAD

**Issue by kiknag** [yagop/node-telegram-bot-api#236]
<img width="417" alt="screen shot 2016-12-09 at 23 03 05" src="https://cloud.githubusercontent.com/assets/10699135/21066048/b3e8ad06-be63-11e6-9d39-ce4e67ae7ed4.png">

Hello,
I have this kind of error and can you help me what is the problem?
When I'm trying to log this data it works great but when I want to sendMessage this error occurs.

**Comment by yagop** [comment]
Check out documantation better for sendMessage pleae, the chat ID must be present

**Comment by kiknag** [comment]
Thank you, now it works.
