### ISSUE TITLE
Add analytics? botan.io

### ISSUE THREAD

**Issue by Panthro** [yagop/node-telegram-bot-api#238]
I'm curious if you guys plan to add analytics, botan.io is a free and really easy to setup analytics.

If is not already planned, I might send you guys a PR.

**Comment by GochoMugo** [comment]
I might **not** understand what you want to achieve, but I do **not** think it will be the right move to add analytics into this library. We are focused on supporting interactions with the Telegram Bot API. Adding features such as analytics diverts our focus, with the added baggage of bloated code that few programmers might want to use.

With your help, we could improve the library to make it easier to integrate analytics packages. We could also add a section to provide pointers to such platforms that our community might want to use. What are your thoughts?

**Comment by yagop** [comment]
The last time I tried Botan I didn't like it, hope they have improved.

I think I won't add support for Botan or any other platform like that. BUT I think a middleware layer would be very useful and can be added Botan support easily.

**Comment by yagop** [comment]
Closed by https://github.com/yagop/node-telegram-bot-api/issues/242
