### ISSUE TITLE
[Request] support disable_notification option

### ISSUE THREAD

**Issue by kratzky** [yagop/node-telegram-bot-api#241]
It will be great to add support of silent messages [silent messages](https://telegram.org/blog/channels-2-0#silent-messages): controlled by `disable_notification` option available for [forwardMessage](https://core.telegram.org/bots/api#forwardmessage) and all [send*](https://core.telegram.org/bots/api#sendmessage) methods:

**Comment by GochoMugo** [comment]
This is already supported through the [Telegram Bot API](https://core.telegram.org/bots/api). You just need to pass the `disable_notification` option when invoking the appropriate methods. For example, for [TelegramBot#sendMessage()](https://github.com/yagop/node-telegram-bot-api#TelegramBot+sendMessage):

```js
bot.sendMessage(chatId, messageText, {
    "disable_notification": true,
});
```
