### ISSUE TITLE
Add Middleware layer

### ISSUE THREAD

**Issue by yagop** [yagop/node-telegram-bot-api#242]
A middleware layer wold be very useful and not very hard to add. Express design is a nice example.

https://github.com/yagop/node-telegram-bot-api/issues/238#issuecomment-267839398

**Comment by CapacitorSet** [comment]
Is there still interest? I could do this.

**Comment by zandzpider** [comment]
yes there is !

**Comment by kamikazechaser** [comment]
Implemented in an [external library](https://github.com/idchlife/node-telegram-bot-api-middleware) that adds onto ntba.
