### ISSUE TITLE
on personal chat closed

### ISSUE THREAD

**Issue by leo90skk** [yagop/node-telegram-bot-api#248]
Is there a possibility to get informed when a user closes a personal chat or removes the bot from a group?

I searched for it in the function list, but I found nothing. I would like to use it like `onBanned` (in a group) or `onChatClosed` (in personal chats).

**Comment by GochoMugo** [comment]
The API does **not** provide such an update. See [TelegramBotAPI.Update](https://core.telegram.org/bots/api#update) for more information!

**Comment by nyuszika7h** [comment]
When the bot is removed from the group, it does receive a `left_chat_member` event.
