### ISSUE TITLE
editMessageText(text, [options]) function does not work

### ISSUE THREAD

**Issue by anmolgupta** [yagop/node-telegram-bot-api#249]

**Comment by anmolgupta** [comment]
My bad, i was on the previous version

**Comment by GochoMugo** [comment]
Please ensure you are providing all the required parameters as specified in the [documentation](https://core.telegram.org/bots/api#editmessagetext). In particular, you have to provide one of these set of parameters:

1. `chat_id` and `message_id`, or
1. `inline_message_id`

**Comment by GochoMugo** [comment]
Sorry, seems we good here! :+1:
