### ISSUE TITLE
Node Telegram Bot API return error 400

### ISSUE THREAD

**Issue by installerUzb** [yagop/node-telegram-bot-api#254]
{ok: false, error_code: 400, description: Bad Request: Message cant be edited}

not_auth_message(message){
        var text = 'Вы не прошли регистрацию на Myjetbrains.com !!!';
        var link = this.options.authUrl;

        var keyboard = {
            inline_keyboard: [
                [{text: 'Myjetbrains.com', url: link, }]
            ]
        }
        this.native.sendMessage(message.chat.id, text, {parse_mode: 'html', reply_markup: keyboard});
    }

    success_auth_message(message){
        var success_auth = '<strong>Вы успешно прошли регистрацию. \nТеперь вам доступна возможности создать задачу.</strong>\n\n <strong>Вы хотите создать задачу?</strong>';

        var keyboard = {
            inline_keyboard: [
                [{text: 'Нет', callback_data: 'menu-not'}, {text: 'Да', callback_data: 'menu-yes'}]
            ]
        }

        this.native.editMessageText(success_auth, {
            parse_mode: 'html',
            chat_id: message.message.chat.id,
            message_id: message.message.message_id,
            reply_markup: keyboard
        })
    }

**Comment by GochoMugo** [comment]
It seems you are trying to edit the user's message, not your bot's!!!
