### ISSUE TITLE
How can I take the documents (video, photo, music, doc) that the bot's user send ?

### ISSUE THREAD

**Issue by installerUzb** [yagop/node-telegram-bot-api#255]
https://core.telegram.org/bots/api#document

**Comment by Besatnias** [comment]
```
bot.on('message', msg=>{
    if(msg.photo){//process as photo}
    else if(msg.document){process as document}
    else if(msg.voice){process as voice message}
```

all documents contain certain markers that make them different than other doctypes. 

gifs look like this:

```
"document": {
         "mime_type": "video/mp4"
         "thumb": {
            "file_id": "AAQCABOPLYINAAQekClTJqbNiPUWAAIC"
            "file_size": 1267
            "width": 90
            "height": 64
         }
         "file_id": "BQADAgADigADQv4iCdh9vDD6X9thAg"
         "file_size": 40847
      }
```

You can similarly explore the markers of all different kinds of documents by sending them to [@APIDebugBot](http://telegram.me/APIDebugBot)

For videos, for example, just do

```
bot.on('message', msg=>{
    if(msg.document.mime_type === "video/mp4"){//process as gif}
    else if(msg.document.mime_type === "video/webm"){//process as video}
```

You can make this as specific as you want.

**Comment by GochoMugo** [comment]
There are different events for different types of updates. See [Events](https://github.com/yagop/node-telegram-bot-api#events). (Thus eliminates the need for multiple `if`s!)

However, @Besatnias has offered some more insight on how the messages are formatted! See [Message](https://core.telegram.org/bots/api#message).

Please, RTFM!
