### ISSUE TITLE
telegram inlinekeyboard

### ISSUE THREAD

**Issue by a1malek** [yagop/node-telegram-bot-api#257]
hi guys
i want to send new inline keyboard after click event of other inline keyboard
in  "Bot.OnCallbackQuery"
is that possible ?! can you give me some sample code ?!
i'm using c#

**Comment by kamikazechaser** [comment]
@a1malek This is a Node.js Lbrary, not a C# (C Sharp). Anyways, [this](https://github.com/GreyWolfDev/Werewolf/blob/master/Werewolf%20for%20Telegram/Werewolf%20Control/Commands/GeneralCommands.cs#L164) is how you would do it in CSharp.

**Comment by GochoMugo** [comment]
Invalid question. Only Node.js!
