### ISSUE TITLE
Support for PWRTelegram

### ISSUE THREAD

**Issue by rjmunhoz** [yagop/node-telegram-bot-api#258]
It's such a cool API that works exactly with the same syntax etc than the official one does, but it has a lot of cool features, such as "resolving of usernames not only with channels and groups but also with normal users and bots".

There could be an option to use it as the base api url, something like:
```javascript
const bot = new TelegramBot(token, {
    polling: true
    , usepwr: true
});
```

**Comment by rjmunhoz** [comment]
Ok, so it appears I didn't read the docs before.
My bad; closing.

**Comment by GochoMugo** [comment]
Redirect to #259
