### ISSUE TITLE
Inline query's in channel post

### ISSUE THREAD

**Issue by FaRzad-845** [yagop/node-telegram-bot-api#268]
I want to sent a message from bot to channel (no via) , all the things go correct But when i add some buttons in inline keyboard (switch inline query or call back) the buttons don't take any action when i click on them although when i use robot inline mode in private chats and sent message the buttons work correctly .

How can i fix it ...?

**Comment by hamiteza** [comment]
hi 
check sign messages in channel settings

**Comment by kamikazechaser** [comment]
@FaRzad-845 API v3 Documentation states:

> 
Inline keyboards with switch_inline_query and switch_inline_query_current_chat can no longer be sent to channels because they are useless there.


@GochoMugo This issue can be closed.
