### ISSUE TITLE
inline list article example 

### ISSUE THREAD

**Issue by FaRzad-845** [yagop/node-telegram-bot-api#269]
I find in #84
i find a example for inlinePhoto (list of 10 of pics),how can i change 'type' to "article"?
i want to made a list of 10 or 15 items in it , but i cant do it , if possible please share a code example .... 

My code 
[file.txt](https://github.com/yagop/node-telegram-bot-api/files/735906/file.txt)

**Comment by JakobLofgren** [comment]
Hey @FaRzad-845 I don't know the answer to your quesstion but your token is out in the open and people could steal it. Also, if you want to easily display others your code, try to create a Gist instead. It's annoying downloading files. Hope you find an answer!
