### ISSUE TITLE
how to know if bot is blocked by user (catch 403 forbbidden)? 

### ISSUE THREAD

**Issue by hems** [yagop/node-telegram-bot-api#273]
Sometimes users deletes/block the bots and this error shows up:

````
W20170201-07:16:56.291(0)? (STDERR) Unhandled rejection Error: 403 {"ok":false,"error_code":403,"description":"Forbidden: Bot was blocked by the user"}
W20170201-07:16:56.293(0)? (STDERR)     at /home/x/telegram/app/node_modules/node-telegram-bot-api/lib/telegram.js:219:17
W20170201-07:16:56.293(0)? (STDERR)     at tryCatcher (/home/x/telegram/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
W20170201-07:16:56.293(0)? (STDERR)     at Promise._settlePromiseFromHandler (/home/x/telegram/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
W20170201-07:16:56.293(0)? (STDERR)     at Promise._settlePromiseAt (/home/x/telegram/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
W20170201-07:16:56.294(0)? (STDERR)     at Promise._settlePromises (/home/x/telegram/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
W20170201-07:16:56.294(0)? (STDERR)     at Async._drainQueue (/home/x/telegram/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
````

i tried doing ````.catch```` on ````sendMessage```` but it doesn't seem to work, even "old school" ````try/catch```` around ````bot.sendMessage```` curiously didn't seem to work.

**Comment by chiu0602** [comment]
have the user added the bot?

**Comment by GochoMugo** [comment]
@hems could you provide us with a code snippet of how you are trying to catch the error?

**Comment by hems** [comment]
@GochoMugo  Just a regular promise.error ?

````
  promise = bot.sendMessage to_id, text, options
  promise
  .then ->
    console.log "all good"
  .error ( e ) ->
    console.log 'error sending message'
    console.log e
````

**Comment by chiu0602** [comment]
If the exception is expected flow, you can just check it and not printing the stacktrace on the log

**Comment by hems** [comment]
@chiu0602 sorry i don't really understand what you mean here? 
@GochoMugo any idea on how to catch that one?

**Comment by GochoMugo** [comment]
For example,

```js
bot.sendMessage(chatId, text).then(function(resp) {
  // ...snip...
}).catch(function(error) {
  if (error.response && error.response.statusCode === 403) {
    // ...snip...
  }
});
```

**Comment by ro31337** [comment]
The problem with this approach IMO is that exceptions are expensive. It would be better to avoid throwing exception

**Comment by GochoMugo** [comment]
@ro31337 What semantically-correct way do you recommend, in place of exceptions?

**Comment by NikitaSavik** [comment]
Hello, and sorry for bringing this up again, but the soultion above can catch the exception, thus I can remove the user from the DB, but how to know if the user UNBLOCK the bot and start sending messages again?

**Comment by ro31337** [comment]
@GochoMugo > What semantically-correct way do you recommend, in place of exceptions?

Well, in golang the syntax is:

```
result, err = instance.DoSomething();
if err != nil {
   // do something with result
}
```

**Comment by hems** [comment]
exceptions aren't expensive on js, anyway, if you want to avoid try/catch you use "reject" from Promises, which seem like it's already the case? 

That's a non-issue, even if it was a performance issue nobody is running sendMessage on an infinite loop that's supposed to perform.

**Comment by CruiseMan** [comment]
> For example,
> 
> ```js
> bot.sendMessage(chatId, text).then(function(resp) {
>   // ...snip...
> }).catch(function(error) {
>   if (error.response && error.response.statusCode === 403) {
>     // ...snip...
>   }
> });
> ```

I'm surprised Telegram doesn't have any API to listen on when user exits or delete bot.

**Comment by B-Venkatesh7210** [comment]
This worked, it does not throw any error on the server or stops the server even if the users have blocked the bot, removed the bot from a group or deleted a group.
It sends message to the valid users and works smoothly.
Thank You @GochoMugo

**Comment by Bek-Shoyatbekov** [comment]
I have the same problem in telegraf . Did anyone find solution for it?

**Comment by TolibjonFayz** [comment]
Me too have this problem. Have you found a solution to this problem Bek bro?
