### ISSUE TITLE
parse_mode: "Markdown" throws error. parse_mode: "markdown" does not.

### ISSUE THREAD

**Issue by JakobLofgren** [yagop/node-telegram-bot-api#277]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

Using Markdown to parse my chat message.

### Actual Behavior

Getting error  "Can't parse message text: Can't find end of the entity starting at byte offset 3"

### Steps to reproduce the Behavior

```js
bot.sendMessage(chatID, "I will throw the error!", {
	parse_mode: "Markdown"
})

bot.sendMessage(chatID, "I wont throw the error!", {
	parse_mode: "markdown"
})
```

Simply changing `"Markdown"` -> `"markdown"` reproduces this issue.

**Comment by GochoMugo** [comment]
I can **not** seem to reproduce this bug.

**Comment by JakobLofgren** [comment]
I'm sorry, it seems that I must have changed something else beyond uppercasing the M.

You can close this and if I find time to look for what reproduced it, I will get back to you.

**Comment by GochoMugo** [comment]
Okay. We will be waiting.

**Comment by jonathanasquier** [comment]
I'm having the same kind of error `Can't parse message text: Can't find end of the entity starting at byte offset xxx`, and I'm using markdown parsing
It's completely random (I have ~500 events/h on the bot (private company bot))
ex in production:
no errors in the last 7 days
many errors the week before
21 days uptime

cannot reproduce bug in local

I'm essentially here to get updates on the issue...

**Comment by monkeydave** [comment]
There is probably an extra markdown element in the message you are sending. Usernames can contain underscores which has caused my bots to generate this message before I changed to HTML style. https://core.telegram.org/bots/api#markdown-style

**Comment by GochoMugo** [comment]
As @monkeydave suggests, this is probably due to formatting issues with your message text. If you do **not** need markdown support, disable it entirely to avoid such issues.

**Comment by jonathanasquier** [comment]
I need markdown :( I'm gonna try to debug my templates thanks!

**Comment by EmilyLuna** [comment]
Solution 
bot.sendMessage(chatId,message, {parse_mode: 'HTML'});

**Comment by dianjuar** [comment]
What about to scape the [especial characters](https://gist.github.com/VEnis/7465176#backslash) of markdown ?

```js
const specialCharsMarkdownRegex = /[\|\\\`\*\_\{\}\[\]\(\)\#\+\-\.\!]/g;

export const sanitizeMarkDown = (message: string) =>
  message.replace(specialCharsMarkdownRegex, str => `\\${str}`);
```

And an example 
```js
export const funct = (str string) => `
Safe md -> ${sanitizeMarkDown(slug)}
No need to sanitize when using code  \`${slug}\`
`;
```
