### ISSUE TITLE
webHook periodical unsubscription.

### ISSUE THREAD

**Issue by roccomuso** [yagop/node-telegram-bot-api#278]
> Does anybody has ever experienced a webHook unsubscription? It happened to me a few times.. Like once every 25days. And I gotta call .setWebHook() again or restart the bot app.

I'm not sure if this is a Telegram issue or it concerns `node-telegram-bot-api`. Somehow it makes sense to delete not-renewed webHooks calls.

PS. I'm using the `v0.24.0`. Should I update to `v0.26.0`? Are there some breaking changes?

**Comment by GochoMugo** [comment]
We respect semver! So **no** breaking changes! Please update, then tell us the outcome!
