### ISSUE TITLE
Why don't we use  module name`telegram-bot-api` instead of `node-telegram-bot-api`?

### ISSUE THREAD

**Issue by preco21** [yagop/node-telegram-bot-api#279]
> Question

https://docs.npmjs.com/files/package.json

> Don't put "js" or "node" in the name. It's assumed that it's js, since you're writing a package.json file, and you can specify the engine using the "engines" field. (See below.)

Since `npm` recommends that you don't put `node` or `js` in the module name, I guess this is reasonable.

Is there any reason not to do this?

**Comment by yagop** [comment]
It was taken I think

**Comment by preco21** [comment]
I see. Seems I mistaked it, I couldn't see `telegram-bot-api` in https://npms.io but it's exist in registry

**Comment by preco21** [comment]
@GochoMugo @yagop If so, is there any plan to support alias or new name of module? I think current name is fine, but it's too long to type. Thought?

**Comment by GochoMugo** [comment]
If it were possible to remove the `node`, it would have been great. Otherwise, changing the name entirely seems overkill. Can we handle it?

**Comment by preco21** [comment]
I got it. If there no proper reasons (like `jade` renamed to `pug`), I think it's okay.

**Comment by GochoMugo** [comment]
I guess we stuck with this name. Closing this issue.
