### ISSUE TITLE
Express webhook intergration

### ISSUE THREAD

**Issue by kamikazechaser** [yagop/node-telegram-bot-api#282]
>Feature request

It would be good to have a Webhook integration for Express. The advantage of this would be a smooth integration of NTBA with Express.

Inspired By [telegraf](https://github.com/telegraf/telegraf)

```js
/* Just A Theoretical Explanation Of How it Should Function */

// Node Packages
const TelegramBot = require('node-telegram-bot-api');
const express = require('express');

// Telegram Bot
const TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN';
const URL = 'YOUR_DOMAIN';

const bot = new TelegramBot(TOKEN);

bot.setWebHook(`${URL}/bot${TOKEN}`);

// Express
const app = express();

// Use Node-Telegram-Bot-API As An Express Middleware
app.use(bot.webhookCallback((`/bot${TOKEN}`))
// Updates Sent To Route Above

/* Your Bot Code Here */

// Start Express Server
app.listen(443, () => {
    console.log(`Express listening on 443`)
});
```

**Comment by GochoMugo** [comment]
I highly suggest moving that kind of functionality into a separate package, built on top of this one. It can focus on integrating with express solely.

**Comment by GochoMugo** [comment]
It would be helpful to users if we document how one can process updates on their own i.e. without using the builtin polling/webhook capabilities.

**Comment by GochoMugo** [comment]
As @kamikazechaser demonstrated in the example at [`examples/expressWebhook.js`](https://github.com/yagop/node-telegram-bot-api/blob/master/examples/expressWebhook.js), it can be easily done, with the current API.

**Comment by Nastya-Scherbakova** [comment]
Unfortunately, this doesnt work
