### ISSUE TITLE
Implicitly building array of allowed_updates

### ISSUE THREAD

**Issue by GingerPlusPlus** [yagop/node-telegram-bot-api#285]
Follow up to #243, about support for `allowed_updates`.

Forcing users to explicitly specify updates they with to listen for in order to benefit from `allowed_updates` feels like introducing redundancy; don't repeat yourself.

> @GochoMugo, instead of allowing users specify which updates they wanna receive, what about building that list based on the updates they listen to?
> 
> ```js
> this.allowedUpdates = [];
> on(event, callback) {
>     super(event, callback);
>     this.addAllowedUpdate(event);
> }
> addAllowedUpdate(event) {
>     if (!this.allowedUpdates.includes(event) {
>         this.allowedUpdates.push(event);
>     }
> }
> onText() {
>     // other stuff
>     addAllowedUpdate('message');
> }
> ```

> @GingerPlusPlus Sorry, I felt your way being too complex. We would have to coordinate when polling starts and when are done scanning for the allowed updates.

### About polling:

Why do you think it's too complex, @GochoMugo?

I think you think we need to prepare the array with types of updates before making first `getUpdates` call. That's not true.

We can start with empty array and add stuff in `.on` calls (and in `.onText`).
We make first `getUpdades` immiedetly, so we'd pass empty array on first request, but that's not a big deal, because, counter-intuitively,  empty list means "receive all updates, don't filter", so we lose nothing, we only get updates we don't want. It should get sorted out in 2nd request, when listeners should be already in place.

Corner case: when user subscribes to another type of update anytime. No big deal, array gets updated, updated array is send in each `getUpdates` request, and from next one, that update is not filtered out.

We never lose anything, because if user doesn't subscribe to an event, it's safe to filter it out, as it'd be ignored anyway.

### About Webhook:

Here, we indeed need to have the array ready, as we need to pass it in `setWebHook` call.

Solution: just put in the docs of `setWebHook` "don't call before all listeners are set up", or "call only after setting up all listeners", "when setting up additional listeners after `setWebHook call, the behavior is undefined".

We could also set a variable in `setWebHook`, and if it's set, emit a warning if user tries set up any listener after calling `setWebHook`.

I don't see any reason why would anyone under any circumstances want to hot-add listeners in the middle of bot running, though.

**Comment by kamikazechaser** [comment]
This was a good enhancement, unfortunately it has become stale at this point.
