### ISSUE TITLE
Sending .gif's using an URL

### ISSUE THREAD

**Issue by mjanssen** [yagop/node-telegram-bot-api#286]
How am I supposed to send a gif? I'm finding a lot of issues about this and they're all replying with "use the sendDocument function!". But when I'm sending a document using a GIF url, Telegram is returning an error:

`this.bot.sendDocument(chatId, 'http://i.giphy.com/13IC4LVeP5NGNi.gif');`

results in:

```
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: there is no document in the request"
}
```

So am I required to set a MIME-type or something? Or is this some kind of bug, since the Telegram docs state the following: "_In sendDocument, sending by URL will currently only work for gif, pdf and zip files._".

Anyone able to send a gif using sendDocument or help me out :)?

**Comment by GochoMugo** [comment]
I can **not** seem to reproduce this bug:

![screenshot-yagop-bug-286](https://cloud.githubusercontent.com/assets/4707579/22822964/b7ce8a52-ef92-11e6-9a63-d9767511f1e7.png)

Are you using the latest release?

**Comment by mjanssen** [comment]
Current installed version is 0.26.0

**Comment by GochoMugo** [comment]
Please try with the latest code base. I can not seem to reproduce this bug.

**Comment by mjanssen** [comment]
But if I'm trying to do it using an URL (`https://api.telegram.org/<bot:key>/sendDocument?chat_id=<group:id>&gif=http://i.giphy.com/13IC4LVeP5NGNi.gif`)
I'm getting the result: `Bad Request: there is no document in the request`, so there is something going wrong...

How can I check out the latest code base using NPM?

**Comment by GochoMugo** [comment]
Please read the documentation on [TelegramBotAPI.sendDocument()](https://core.telegram.org/bots/api#senddocument). There's **no** `gif` parameter. Also, use the library instead of formulating requests by hand.
