### ISSUE TITLE
Event types?

### ISSUE THREAD

**Issue by preco21** [yagop/node-telegram-bot-api#289]
I remember that previous version of `README.md` had all kind of event types:

https://github.com/yagop/node-telegram-bot-api/blob/eba70cd3d7ab5daf52b35b1093d53ddddb67bd3d/README.md#events

But now, where are they gone?

I guess there is no document describes about events.

**Comment by GochoMugo** [comment]
The README contains a documentation section, with links to various docs of information. Please check it out.

**Comment by preco21** [comment]
Ah I got it. I only saw api documents but not usage examples.

https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#events

It would be nice to have note also in api document, currently there is no mention about events in api docs:

https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md

**Comment by GochoMugo** [comment]
We could add a "navbar" at the top of the documents.

**Comment by GochoMugo** [comment]
A note has been added to redirect users to the right doc (commit [a44eb7f1ee9349920760e2e7d22e3d395b716c56](https://github.com/yagop/node-telegram-bot-api/commit/a44eb7f1ee9349920760e2e7d22e3d395b716c56)).
