### ISSUE TITLE
Users send me a message and I reply to him

### ISSUE THREAD

**Issue by saeedhei** [yagop/node-telegram-bot-api#292]
How Can I Take Users Messages and reply to him?
This is my Code:
```
bot.onText(/\Contact Us/, function ContactUs(msg) {
  const opts = {
    reply_to_message_id: msg.message_id,
    reply_markup: JSON.stringify({
      keyboard: StartKeyboard,
	  resize_keyboard:true,
      one_time_keyboard: true
    })
  };
  bot.sendMessage(msg.chat.id, 'Please Write your Messages:', opts);
});
```

**Comment by GochoMugo** [comment]
@saeedhei Sorry for the long time take to respond. I will have to respond to this at a later date with a more complete solution that will work for you.

**Comment by mawansui** [comment]
Hi @saeedhei,

Maybe this will fit your needs? Actually I am stuck with the kinda the same question right now and this is what I've came up with that far:
```javascript
bot.onText(/\Contact Us/, function ContactUs(msg) {
  const opts = {
    reply_to_message_id: msg.message_id,
    reply_markup: JSON.stringify({
      keyboard: StartKeyboard,
	  resize_keyboard:true,
      one_time_keyboard: true
    })
  };
  bot.sendMessage(msg.chat.id, 'Please Write your Messages:', opts)
    .then(() => {
    bot.on('message', function(reply) {
// do some stuff with reply.text
})
})
});
```

**Comment by GochoMugo** [comment]
UPDATE: check out the issue GochoMugo/tgfancy#5. Am addressing it there.

**Comment by saeedhei** [comment]
How Can I Get Users Reply Messages in My User ID?

**Comment by saeedhei** [comment]
Solved, You Can Find Awnser in Blow Link.
[](https://github.com/saeedhei/Ntba-Message-Receiver)
