### ISSUE TITLE
Unable to receive incoming message (on 'message')

### ISSUE THREAD

**Issue by siutsin** [yagop/node-telegram-bot-api#293]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

I am using 0.27.0 as the bot API library. The bot is only able to receive around 20-50 messages and then stopped, not receiving any incoming message at all.
<img width="353" alt="screen shot 2017-02-15 at 8 39 37 pm" src="https://cloud.githubusercontent.com/assets/904442/22975228/e38e263e-f3c0-11e6-85e2-a04fe073787d.png">
Server up at **Wed, 15 Feb 2017 12:36:35 GMT**
First message to receive at **Wed, 15 Feb 2017 12:39:00 GMT**

Trace log:
<img width="1078" alt="screen shot 2017-02-15 at 9 07 42 pm" src="https://cloud.githubusercontent.com/assets/904442/22975864/30c6dfca-f3c3-11e6-8dfb-009b63249355.png">

As the bot is using in a few hundred groups and is running almost a year, the on 'message' will normally have more than ten messages per second.

### Actual Behavior

The bot is now almost not able to receive any incoming message, including bot commands

### Steps to reproduce the Behavior

This is an open source project, the code is hosted at [GitHub](https://github.com/siutsin/telegram-jung2-bot) Bot id: [@jung2_bot](https://t.me/jung2_bot)

What I did:

1. Listened on both `polling_error` and `webhook_error`, no log from these two events.
2. Turn on server log, no error log found
3. Tested on both server and locally with a private group, and confirmed that the bot is not able to receive my own message
4. Created a new bot with a new API token, encountered the same issue

This happened recently (this few days) and since there is no log for the server due to privacy issue. I am not able to provide any log prior to when I noticed it.

**Comment by siutsin** [comment]
Confirmed this is API issue by Telegram's support

**Comment by GochoMugo** [comment]
Is it possible to disclose the issue? It will really help the community.

**Comment by siutsin** [comment]
They didn't provide much information. I can share some of the trace logs, and I believe this is probably only happened to me.

<img width="1081" alt="screen shot 2017-02-16 at 8 34 18 am" src="https://cloud.githubusercontent.com/assets/904442/23026392/16a22a26-f49c-11e6-958a-825c8f0692ad.png">
<img width="1074" alt="screen shot 2017-02-16 at 8 35 07 am" src="https://cloud.githubusercontent.com/assets/904442/23026389/169befa8-f49c-11e6-9281-d133c3152ccc.png">
<img width="258" alt="screen shot 2017-02-16 at 8 40 17 am" src="https://cloud.githubusercontent.com/assets/904442/23026390/169ecf70-f49c-11e6-9e28-784ccfd15f1a.png">
<img width="540" alt="screen shot 2017-02-16 at 12 18 00 am" src="https://cloud.githubusercontent.com/assets/904442/23026393/16a31c7e-f49c-11e6-8863-c22a1aeb52f1.png">
<img width="613" alt="screen shot 2017-02-16 at 11 07 25 pm" src="https://cloud.githubusercontent.com/assets/904442/23026600/ba1a8ffe-f49c-11e6-8862-b9b97359566f.png">

**Comment by yagop** [comment]
Telegram and theirs servers, the never ending history of failures ...
