### ISSUE TITLE
Question: Groups, get Members and there ChatID

### ISSUE THREAD

**Issue by celevra** [yagop/node-telegram-bot-api#294]
hi,

is it possible to get members of a Group (that the bot is joined to) and send dem private messages?
i want to implement a rock paper scissors game

regards

celevra

**Comment by GochoMugo** [comment]
The [Telegram Bot API](https://core.telegram.org/bots/api) does **not** provide such a method. There go you can **not** get the members of a group, only the number of the group members.

Also, for privacy concerns, Telegram will **not** allow bots contacting arbitrary users on the platform as it would allow abuse, for example, sending spam messages, etc. The user has to `/start` the bot for the latter to be able to send messages to the former.

**Comment by celevra** [comment]
Thank you for the fast answer!
