### ISSUE TITLE
Send emails in messages 

### ISSUE THREAD

**Issue by niko-lay** [yagop/node-telegram-bot-api#295]
I would like to send emails from bot to users
Here is code example
```javascript
var  msg = `<b>New reservation:</b> From: <a href="mailto:${client.email}">${client.email}</a>`;
bot.sendMessage(chat_id, msg, {parse_mode:'html', disable_web_page_preview:true});  
```
But in when Telegram client recieve message – it show it like http://mailto@gmail.com

It is  possible to format message with email link? Is it telegram proto bug?

**Comment by GochoMugo** [comment]
I am **not** quite sure if Telegram supports mailto links. Do you mind asking Telegram Bot Support at @BotSupport?

**Comment by ruslanshestopal** [comment]
Any luck sending e-mail links? Thanks.
