### ISSUE TITLE
Not compatible with Node 5

### ISSUE THREAD

**Issue by jehy** [yagop/node-telegram-bot-api#297]
### Expected Behavior

I expect this package to run on node 5.

### Actual Behavior
`
/home/travis/build/jehy/telegram-test/node_modules/node-telegram-bot-api/src/telegram.js:85
  constructor(token, options = {}) {
                             ^
SyntaxError: Unexpected token =
`

Optional arguments are supported only in node 6+

### Steps to reproduce the Behavior
Run package on node 5

### Steps to fix
Transpile code for node 5 too.

**Comment by lifehome** [comment]
I am using node v7.5.0 and is running fine with this package, have you tried adding `--harmony` flag in the command?

**Comment by jehy** [comment]
Node 7 is fine, node 5 is not...

**Comment by lifehome** [comment]
Oh. Perhaps time to update?

**Comment by jehy** [comment]
I also use node 7 for my pet projects and node 6 for production. But node-telegram-bot-api is compatible with node 4,6 and 7 (for old node versions transpiled version of code is used) so I think that node 5 should also be supported.

**Comment by GochoMugo** [comment]
@jehy I agree with you. We should be working on node 5! Looking at the PR now...

@yagop We are deprecating Node 5 too, right? Please confirm.

**Comment by jehy** [comment]
Fixed via #298
