### ISSUE TITLE
Documentation issue - kickChatMember

### ISSUE THREAD

**Issue by lifehome** [yagop/node-telegram-bot-api#300]
The kickChatMember should accept two parameters:
- an `Integer` or `String` value for `chat_id`
- an `Integer` value for `user_id`

And we can see [Release version of doc](release/doc/api.md#TelegramBot+kickChatMember) is still accepting a `String` for `user_id`. Perhaps we need an update on these fields?

**Comment by GochoMugo** [comment]
I believe that must have been a typo in the documentation. If you wish, you could send us a PR to fix that.

Thanks for noticing that.

**Comment by lifehome** [comment]
May I confirm that the interfaces are accepting the correct type?

**Comment by GochoMugo** [comment]
The library does **not** enforce strict conformance to types of parameters passed in **most** (**not all!**) methods. *TelegramBot#kickChatMember()* is one of those methods. It allows you to pass the parameter as a string or an integer! It will be passed as is to the Bot API. (But the API may reject the parameter of course!)

**Comment by GochoMugo** [comment]
Documentation has been updated.
