### ISSUE TITLE
How to invoke the bot when mentioning it?

### ISSUE THREAD

**Issue by icaroramiires** [yagop/node-telegram-bot-api#302]
Hello guys! I have a doubt!
I would like to invoke the bot by mentioning it
**Ex: @bot** and it responds me with a default message

**Comment by GochoMugo** [comment]
I have understood your use case as sth like this:

![default-message](https://cloud.githubusercontent.com/assets/4707579/23643021/1630fd10-0310-11e7-9fab-899b2de7e441.png)

You would just have to look at the message's text. For example,

```js
bot.on("message", function(message) {
    console.log(message.text); // => @botname
    // checking that the text only includes mention of the bot i.e. @botname
    // this can be improved of course to satisfy your use case! 
    const match = /^@\w+$/.exec(message.text.trim());
    if (match) {
        bot.sendMessage(message.chat.id, "default message");
    }
});
```

**Comment by icaroramiires** [comment]
Thanks @GochoMugo but only works without individual chat with the bot, when the mentioned in group chat happens
