### ISSUE TITLE
Command description

### ISSUE THREAD

**Issue by hosein2398** [yagop/node-telegram-bot-api#309]
Well it seems that we don't have any way to set description for commands, right?
By description I mean those ones that are like autocomplete when you start typing <code>/...</code>  

<img src="https://core.telegram.org/file/811140845/2/rNUxpcGDeQU/05eaaf20b0dbaf9cb3" height="400" width="250"/>

**Comment by omidh28** [comment]
It does not have anything with bot API, you should use bot father's `/setcommands` command
