### ISSUE TITLE
inline keyboard disappeared when message is updated

### ISSUE THREAD

**Issue by sevriugin** [yagop/node-telegram-bot-api#310]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

I am trying to update message with inline keyboard using editMessageText method. The text is updating  ...

### Actual Behavior

... but after update the inline keyboard is disappeared.

### Steps to reproduce the Behavior

there is code example: 

// --- server.js ---
#!/bin/env node
//  OpenShift sample Node application

var TelegramBot = require('node-telegram-bot-api');
var token = 'my token is here';
var bot = new TelegramBot(token, {polling: true});
var menu = require('./menu');

bot.onText(menu.start.name, function (msg, match) {
    var fromId = msg.from.id;
    bot.sendMessage(fromId, menu.start.userNotFound, menu.help.inline);
});

// Any kind of callback_query
bot.on('callback_query', function (query) {

  var queryId   = query.id;
  var fromId    = query.from.id;
  var fromName  = query.from.first_name;
  var msgId     = query.message.message_id;
  var chatId    = query.message.chat.id;
  var data      = query.data;

  bot.editMessageText('Message is updated', {chat_id:chatId, message_id:msgId, reply_markup:menu.help.inline});
  
  bot.answerCallbackQuery(queryId,  'Gocha! ' + fromName + 
                                    ' at message id ' + msgId + 
                                    ' at chat ' + chatId + 
                                    ' data ' + data, true);
});

// --- menu.js ---
'use strict';

module.exports = {
	start : {
		name : /\/start/,
		userNotFound : "Hi, I'm SOS-ka Shop Bot",
		knowUser : "Yes, I am here!"
	},
	help : {
		inline : {
			parse_mode : 'Markdown',
			reply_markup : JSON.stringify({
				inline_keyboard : [
					[{text:'ok', callback_data:'ok'}],
					[{text:'❌', callback_data:'cancel'}]
				]
			})
		},
		inline_update : {
			parse_mode : 'Markdown',
			reply_markup : JSON.stringify({
				inline_keyboard : [
					[{text:'OK', callback_data:'ok'}],
					[{text:'❌', callback_data:'cancel'}]
				]
			})
		}
	}
};

**Comment by pedrofracassi** [comment]
Just a quick suggestion, put your code in between ``` and ```, makes it easier to read

**Comment by kamikazechaser** [comment]
Tlegram doesn't persist inline keyboards like it does with normal keyboards. You should make a custom logic to persist it with every message. Closing for now. Issue is stale.
