### ISSUE TITLE
Bot state machine

### ISSUE THREAD

**Issue by MonsterDeveloper** [yagop/node-telegram-bot-api#312]
Hello! I want my bot to answer questions in order like what's your name (user answers), then how old are you and etc. How do I do this?

**Comment by FaRzad-845** [comment]
@MonsterDeveloper you can use arrays 
Push somewhere and check it in next step ....
Like this 
Register =[ ]
`Bot.on ......
Register.push('1')`
Then check Register array value in another

**Comment by FaRzad-845** [comment]
@MonsterDeveloper you can use arrays 
Push somewhere and check it in next step ....
Like this 
Register =[ ]
```Bot.on ......
Register.push('1')```
Then check Register array value in another

**Comment by FaRzad-845** [comment]
@MonsterDeveloper you can use arrays 
Push somewhere and check it in next step ....
Like this 
Register =[ ]
`Bot.on ...... {

Register.push('1')
}`

Then check Register array value in another
`Bot.on..... {
//If register contain '1'
//Next step
//If not nothing done
}`

**Comment by MonsterDeveloper** [comment]
Okey, thanks)

**Comment by kamikazechaser** [comment]
Checkout Tgfancy or other libraries which integrate with this lib. They have features this kind of scenarios.
