### ISSUE TITLE
Can we read message from bot API. like (messages.getMessages)

### ISSUE THREAD

**Issue by javeedrahman** [yagop/node-telegram-bot-api#316]
> Question

Can we get the message from telegram bot means i want to read the message which is sent from group.
is it possible in bot api.

I see telegram api have these functions https://core.telegram.org/method/messages.getMessages.
 the same function available in telegram.

Thanks in advance

**Comment by GochoMugo** [comment]
This library interfaces with the [**Bot** API](https://core.telegram.org/bots/api). Check out the [docs](https://github.com/yagop/node-telegram-bot-api#documentation), particularly, [API Reference](https://github.com/yagop/node-telegram-bot-api/tree/release/doc/api.md).

**Comment by yagop** [comment]
Close?

**Comment by javeedrahman** [comment]
Oh okay, so from the Bot API can we read the message from particular CHAT or GROUP.
Is there any options like --> [https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+getChat](url).

If not can you please suggest any Telegram API with these functionality. I have searched a lot but no luck.

Thanks in advance.

**Comment by GochoMugo** [comment]
The official Bot API does **not** offer such a method i.e. reading messages from a particular chat. You only receive messages as they're sent by users.

*PS: Check out the [available methods](https://core.telegram.org/bots/api#available-methods) for more information.*

**Comment by yangirekun** [comment]
https://core.telegram.org/method/messages.getMessages
> Bots can use this method

**Comment by Batyodie** [comment]
@yangirekun Has anything changed since then?
Is there a way for
Telegram bots to receive a list of channel messages?

**Comment by 0xluc** [comment]
> @yangirekun Has anything changed since then? Is there a way for Telegram bots to receive a list of channel messages?

bump

**Comment by r37r0m0d3l** [comment]
bump

**Comment by shkhikmatillayev** [comment]
Close?

**Comment by r37r0m0d3l** [comment]
> The official Bot API does not offer such a method i.e. reading messages from a particular chat. You only receive messages as they're sent by users.

It's not clear why the Telegram team wouldn't give the bot the ability to read chat messages for the last 24 hours at least. Unfortunately the “problem” has not been solved.

**Comment by bane-the-dev** [comment]
bump
