### ISSUE TITLE
Webhook won't stick when bot is running

### ISSUE THREAD

**Issue by rjmunhoz** [yagop/node-telegram-bot-api#318]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior
When I call `bot.setWebHook`, it should set the url and leave it there;

### Actual Behavior
The webhok gets set (`.then()` receives `true`), and, if I imediately `getWebHookInfo`, I can see the URL is there, but, if I do it again (on `getWebHookInfo`'s `.then()`, for example), the url is gone!

I tried setting it manually, got the successful response from the server, but, right after, there was no webhook set (checked with API's `getWebhookInfo`);

At first, I thought it was the API's fault, but, when my code's not running and I call `setWebhook` manually, the webhook sticks.

### Steps to reproduce the Behavior
Here's my code, even though I've gone through it a lot of times, and can't find a thing that could cause this problem. Anyway, there it goes:

```javascript
import TelegramBot from 'node-telegram-bot-api';
import * as dotenv from 'dotenv-safe';
import pj from 'prettyjson';
dotenv.load();

const bot = new TelegramBot(process.env.TELEGRAM_TOKEN, {
  polling: true
});

const takeOf = () => {
  
  const WEBHOOK = process.env.LOCAL_URL ? true : false;
  
  const config = {
    onlyFirstMatch: true
  }
  
  if(WEBHOOK) {
    config.webHook = {
      host: process.env.LOCAL_IP,
      port: process.env.PORT
    };
    config.polling = false;
  } else {
    config.polling = true;
  }
  
  console.log(config);
  
  const bot = new TelegramBot(process.env.TELEGRAM_TOKEN, config);
  
  bot.getMe()
  .then(me => {
    if (WEBHOOK) {
      const webHookUrl = `${process.env.LOCAL_URL}:443/bot${process.env.TELEGRAM_TOKEN}`;
      bot
      .setWebHook(webHookUrl)
      .then(() => {
        bot.getWebHookInfo()
        .then(info => {
          console.log(`Webhook set; info:\n${pj.render(info).replace(process.env.TELEGRAM_TOKEN, '[TELEGRAM_API_TOKEN]')}`);
        });
      });
    }
    
    let _info = [];
    const date = new Date();
    _info.push('');
    _info.push('------------------------------');
    _info.push('Bot successfully deployed!');
    _info.push('------------------------------');
    _info.push('Bot info:');
    _info.push(`- ID: ${me.id}`);
    _info.push(`- Name: ${me.first_name}`);
    _info.push(`- Username: ${me.username}`);
    _info.push('');
    _info.push('Server info:');
    _info.push(WEBHOOK ? `- Host: ${process.env.LOCAL_IP}` : '- Polling mode');
    if (WEBHOOK) _info.push(`- Port: ${process.env.PORT}`);
    if (WEBHOOK) _info.push(`- Domain: ${process.env.LOCAL_URL}`);
    _info.push(`- Node version: ${process.version}`);
    _info.push('');
    _info.push('Time Info:');
    _info.push(
        `- Date: ${date.getDay()}/${date.getMonth()}/${date.getFullYear()}`
    );
    _info.push(
        `- Time: ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`
    );
    _info.push('------------------------------');
    console.log(_info.join('\n'));
  })
  .catch(err => console.log(pj.render(err))); 
}

takeOf();
```

**Comment by GochoMugo** [comment]
In the first few lines, you are creating a bot instance, using *polling*. Later on, you happen to create **another, separate** bot instance using a *webhook*. The polling mechanism automatically un-sets an already-set webhook, should the Telegram servers report back an error. The two mechanisms are mutually exclusive. Choose one please.

*Re-open if it does **not** fix your bug.*

**Comment by rjmunhoz** [comment]
Oh man! 
I didn't realize that line was there O.o
Sorry for the unnecessary issue opened
