### ISSUE TITLE
deep linking support

### ISSUE THREAD

**Issue by Rezania815** [yagop/node-telegram-bot-api#322]
Is there any way to do deep linking with this library?
i.e. [deep-linking](https://core.telegram.org/bots#deep-linking)

**Comment by FaRzad-845** [comment]
Yes you can do it ...

**Comment by Rezania815** [comment]
I found nothing in the docs. could you explain how I can do this?

**Comment by GochoMugo** [comment]
Yes, it is possible. As the docs (https://core.telegram.org/bots#deep-linking) say,

> ... your bot will receive a message from that user in this format:
>
> ```
> /start PAYLOAD`
> ```
> 
> `PAYLOAD` stands for the value of the `start` or `startgroup` parameter that was passed in the link.

Therefore, all you've to do is capture the message with the format described above. For example,

```js
bot.onText(/\/start (\w+)/, function(msg, match) {
    const payload = match[1];
    // ....
    // use payload
   // ...
  return bot.sendMessage(msg.chat.id, "bot at your service");
});
```
