### ISSUE TITLE
Missing deleteMessage method.

### ISSUE THREAD

**Issue by vlakam** [yagop/node-telegram-bot-api#323]
See https://github.com/telegraf/telegraf/commit/8186cef87946e53d5df4e1b39d905facb047058c

**Comment by GochoMugo** [comment]
Follow #324.

**Comment by mafia-007** [comment]
hi
How Reply a message is deleted? If the code is correct?
What code is deleted with group messaging? If the code is correct?

bot.onText(/^[\/!#]delete$/, msg => {

bot.deleteMessage(msg.chat.id, msg.reply_to_message.id, form = {});
    });


please guide me

**Comment by GochoMugo** [comment]
**New Release, v0.28.0 :confetti_ball:**
