### ISSUE TITLE
onText global regex only works every second time

### ISSUE THREAD

**Issue by Sirius-A** [yagop/node-telegram-bot-api#325]
> Bug Report

I have read:
* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior
When sending a _/get_ command, the bot replies everytime.

### Actual Behavior
The bot only answers every second time.

### Steps to reproduce the Behavior
1. Register a global regex with capture groups like so: 
`tgBot.onText(/\/get(Today)?(@\w+)?$/gmi,getTodayHandler);`
2. Send _/get_ to bot. (ok)
3. Send _/get_ to bot again. (No reply)

### Reason this happens
From http://stackoverflow.com/questions/11477415/why-does-javascripts-regex-exec-not-always-return-the-same-value:

> A JavaScript RegExp object is stateful.
> When the regex is global, if you call a method the same regex object, it will start from the index past the end of the last match.
> When no more matches are found, the index is reset to 0 automatically.

### Proposed solution
Reset the `lastIndex ` after the regexp.exec() call [here](https://github.com/yagop/node-telegram-bot-api/blob/9a9dfa9560eaf0bddb732868809be4c0e21585c4/src/telegram.js#L472).

I will put a PR together later today 😄

**Comment by GochoMugo** [comment]
We definitely do **not** want the state of the RegExp object to be carried forward between different text messages. Otherwise, strange errors, that are difficult to reproduce, would occur occasionally.  We should reset the state.

Thanks @Sirius-A for this nice catch. Waiting for your PR. :+1:

**Comment by Sirius-A** [comment]
> Otherwise, strange errors, that are difficult to reproduce, would occur occasionally.
That's exactly how I got here 💩

**Comment by GochoMugo** [comment]
Sorry about that :rofl:.  Lemme check out the PR.

**Comment by GochoMugo** [comment]
**New Release, v0.28.0 :confetti_ball:**

**Comment by beshur** [comment]
Reproduces for me on 0.52.0
