### ISSUE TITLE
TelegramBot method throw request-promise-core exception

### ISSUE THREAD

**Issue by alexandercerutti** [yagop/node-telegram-bot-api#329]
Today a was starting my bot in my development envinroment (```npm start -- dev```).
In the previous days it was working but today, it gave the following error: 

> mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/request-promise-core/lib/plumbing.js:145
> 
> return self[promisePropertyKey][methodToExpose].apply(self[promisePropertyKey], arguments);
>                                                    ^
>
> TypeError: Cannot read property 'then' of undefined
>     at Request.RP$exposed [as then] (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/request-promise-core/lib/plumbing.js:145:44)
>     at TelegramBot._request (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/node-telegram-bot-api/src/telegram.js:169:8)
>     at TelegramBot.getUpdates (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/node-telegram-bot-api/src/telegram.js:438:17)
>     at TelegramBotPolling._getUpdates (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/node-telegram-bot-api/src/telegramPolling.js:136:21)
>     at TelegramBotPolling._polling (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/node-telegram-bot-api/src/telegramPolling.js:89:8)
>     at TelegramBotPolling.start (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/node-telegram-bot-api/src/telegramPolling.js:47:17)
>     at TelegramBot.startPolling (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/node-telegram-bot-api/src/telegram.js:266:26)
>     at new TelegramBot (/mnt/c/Users/alexa/repos/Openshift/techbinder/node_modules/node-telegram-bot-api/src/telegram.js:102:14)
>     at Object.<anonymous> (/mnt/c/Users/alexa/repos/Openshift/techbinder/src/utils.js:21:8)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/mnt/c/Users/alexa/repos/Openshift/techbinder/src/manager.js:1:77)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

As you can see, the problem is called from by two my files, ```utils.js``` which contains also the calling for this library, and its caller ```manager.js```. Row one in manager calls utils.js and row 21 in utils instantiate the bot. ```dev``` parameter to node make the bot choose which token it have to use and the token is found correctly. Dev enviroment uses polling. So I call it in the following way:

`bot = new TelegramBot(token, { polling: true, });`

I have also updated today node, npm, this library and some dependencies to the last version after have seen the error but nothing changed. In 3 days I haven't touched anything into my bot application that may corrupt the thing.

EDIT: I tried to uninstall and reinstall the framework and the dependencies, but nothing.
EDIT: tried also to empty npm cache but nothing changed. I'm trying to ask also to request/request-promise creators.

Is there a way to fix this request-promise-core problem? Thank you.

**Comment by GochoMugo** [comment]
Please state how you solved it.

**Comment by alexandercerutti** [comment]
I think I was overwriting the Object.prototype, or maybe it's new assigned function, which was containing literally "this", with no semicolons or anything else, was messing up everything. This was in an another file, index.js, which loads my bot the modules, and so I didn't see the problem before (even if I looked into that file).
