### ISSUE TITLE
Unable to interpret commands in a group/chat

### ISSUE THREAD

**Issue by tregismoreira** [yagop/node-telegram-bot-api#336]
I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

I am using the dummy code for `/echo` command:

```
// Matches "/echo [whatever]"
bot.onText(/\/echo (.+)/, (msg, match) => {
  // 'msg' is the received Message from Telegram
  // 'match' is the result of executing the regexp above on the text content
  // of the message
  const resp = match[1]; // the captured "whatever"

  // send back the matched "whatever" to the chat
  bot.sendMessage(chatId, resp);
});
```

I also added my bot as admin in a chat/group.

### Expected Behavior

While executing the command `/echo` I would expect to have receive the message. But It isn't returning nothing. It only returns if I send the command in pvt to the bot.

I didn't found any issue or documentation about this issue.

Did I miss anything?

**Comment by GochoMugo** [comment]
Try `/echo hello` (*note the `hello`*)

**Comment by tregismoreira** [comment]
Same thing. It's only triggered if I talk privately to the bot :/

I also registered the new command with BotFather.

**Comment by kamikazechaser** [comment]
I have noticed there is no chatId variable in your code block. Try this: 

```js
// Matches "/echo [whatever]"
bot.onText(/\/echo (.+)/, (msg, match) => {
  // 'msg' is the received Message from Telegram
  // 'match' is the result of executing the regexp above on the text content
  // of the message

  const chatId = msg.chat.id;
  const resp = match[1]; // the captured "whatever"

  // send back the matched "whatever" to the chat
  bot.sendMessage(chatId, resp);
});
```

**Also** make sure you disable bot privacy. See this [info](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get) for more details.

**Comment by tregismoreira** [comment]
Actually I didn't use chatId in the method because I already have it outside the method. This is not the reason, otherwise I would get an error.

I am not getting any error, it simply doesn't work if I post the command in a chat/group.

**Comment by GochoMugo** [comment]
For debugging purposes, add the following snippet,

```js
bot.on("text", function(msg) {
    console.log("Received message");
    console.log("  chat ID:", msg.chat.id);
    console.log("  text:", msg.text);
});
```

Now try sending the following messages in the chat/group:

1. `/echo hello`
1. `/echo@BOTNAME hello` (where `BOTNAME` is the bot's username)
1. `hello` 

Now provide us with the output (if any) you receive.

**Comment by dkeulen** [comment]
Hi,

I am facing the same issue actually.
Using the latest code. Bot only gets the bot.on('message') or bot.onText() when chatting 1 on 1 with the bot.

But once added to a group the bot does not respond/get anything at all.
I do have console logs, and none are showing when receiving or sending messages via group chats.

I tried your documents and the bot is added as admin with full rights.
I tried capturing any message and send a response, no luck in group chat (but works in 1on1 chat).

latest nodejs, latest bot code, dev and running on osx 10.12.6
As reported, 1on1 chat is fine, but nothing happens in group chats.
Api and token is working (used postman to check api response).

**Comment by eusfelix** [comment]
disable bot privacy

**Comment by noprobz09** [comment]
Im facing same problem. It does not send message to the group. Im using the `message.chat.id` property.

**Comment by danielperez9430** [comment]
Yes, for get all messages (include the commands without write the bot username) in a group is important disable the bot privacy in botfather. 

In the other case the bot only get updates if the command contains the bot username. Example: `/mycommand@my_bot`
