### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by tregismoreira** [yagop/node-telegram-bot-api#337]
Hey folks,

Is it possible to send a welcome message once a user join the channel/group? I couldn't find any reference on this.

Thanks in advance.

**Comment by kamikazechaser** [comment]
You can use service notifications:

```js
bot.on('new_chat_participant', (msg) => {
  bot.sendMessage(msg.chat.id, 'Welcome');
});
```

**Comment by GochoMugo** [comment]
@kamikazechaser `new_chat_member` over `new_chat_participant`?

**Comment by GochoMugo** [comment]
**!CLOSE**

---

answer: https://github.com/yagop/node-telegram-bot-api/issues/337#issuecomment-303474839

**Comment by ZamoraFTW** [comment]
I'm trying to follow the answer but it doesn't work
`bot.on('new_chat_member', (msg) => {
    bot.sendMessage(msg.chat.id, 'Welcome');
});`

**Comment by kamikazechaser** [comment]
> 
> 
> @kamikazechaser `new_chat_member` over `new_chat_participant`?

@ZamoraFTW

**Comment by NatalieChin80** [comment]
@ZamoraFTW @kamikazechaser I've been trying this as well, and it doesn't work `new_chat_participant` or `new_chat_member`. Have you found a solution?

**Comment by saeedhei** [comment]
`new_chat_members`
Check This: (https://core.telegram.org/bots/api#message)

**Comment by NatalieChin80** [comment]
Thanks for the link, though I've been testing the one from core telegram - `msg. new_chat_members` in particular. Is anyone having any success with getting this value?

**Comment by kamikazechaser** [comment]
@NatalieChin80 Your polling error may have nothing to do with the code. It is most likely that your Bot T=token is incorrect or you are attempting to poll with the same token from a different instance. A network issue may also bring about this error.

@saeedhei Thank you for bringing this into notice. From Telegrams changelog

**Comment by bluetyphoon77** [comment]
Hi guyz, anyone here found the working solution ?
@0xicingdeath ?
Thanks
