### ISSUE TITLE
Sensitive information

### ISSUE THREAD

**Issue by tregismoreira** [yagop/node-telegram-bot-api#338]
Is it possible to store sensitive user informations (or read from a file in a local storage) like api keys?

**Comment by GochoMugo** [comment]
It is possible. You should probably be using environment variables or take a look at [node-config](https://github.com/lorenwest/node-config). It is quite easy to start using.

> **Remember: Do not check in sensitive information into your git history. Do not store credentials in your repo. Basically, add your sensitive files to `.gitignore`.**
>
> See https://help.github.com/articles/removing-sensitive-data-from-a-repository/ for more information.

*PS: This issue should have probably been submitted to StackOverflow (or alike). But since someone was here. :smile:*
