### ISSUE TITLE
Deletet accounts

### ISSUE THREAD

**Issue by telegram-api** [yagop/node-telegram-bot-api#343]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by telegram-api** [comment]
How to clear Deletet accounts in the supergroup?

**Comment by kamikazechaser** [comment]
It is **not** possible to retrieve a list of all members in a chat using the Telegram Bot API. You can only retrieve chat administrator accounts. 

However, you can simple plug in a library I made called [pwrtelegram](https://github.com/kamikazechaser/pwrtelegram) right in your bot code and call the [getMembers](https://github.com/kamikazechaser/pwrtelegram/blob/master/doc/api.md#User+getMembers) method. This will allow you retrieve a list of all members, then you can go ahead sort for deleted accounts.

**Comment by telegram-api** [comment]
It was great thanks

How do I remove accounts that have been deleted account in group

**Comment by telegram-api** [comment]
http://uupload.ir/files/xjy_group.jpg

How Remove all delete acconts

**Comment by kamikazechaser** [comment]
@telegram-api [Here](https://github.com/kamikazechaser/pwrtelegram/blob/master/example/cleanDeletedAccounts.js) is how you would do it.
