### ISSUE TITLE
Send message if user message is not matched at any point.

### ISSUE THREAD

**Issue by kvyb** [yagop/node-telegram-bot-api#344]
> Question

Is there a way to send a message to user if his text does not match any of the regex bot.onText()? Something like the welcome text but only if there is no match for user input.
Is there a built in method, or must I use some sort of logic to acheive this? 
Looking through the documentation has not yielded any results for me. Any help would be greatly appreciated. Thanks.

**Comment by kamikazechaser** [comment]
You can listen to message sub-types shown [here](https://core.telegram.org/bots/api#message). E.g

```js

// listen to any text message
bot.on("text", msg => {
   bot.sendMessage(msg.chat.id, "Hello World!");
});

// listen for new chat members
bot.on("new_chat_member", msg => {
   bot.sendMessage(msg.chat.id, "Welcome to the group!");
});
```

**Comment by kvyb** [comment]
@kamikazechaser thanks, but on message this will send a message for any text + any response to matched text. So if user writes some text which is regex matched to a response, two messages will appear. What if I want to send only if the whole script does not match?

**Comment by FaRzad-845** [comment]
@kvyb
You can put all your regex in one array , and in function you want to send if there is no match , check it with for () or if ()

**Comment by kvyb** [comment]
Thank you! I'll give that a try. An example is most welcome if possible.

**Comment by kamikazechaser** [comment]
@kvyb I did not understand what you meant earlier, but it is now clear. You want to send a message if none of the regex match, right?

**Comment by kvyb** [comment]
@kamikazechaser that's right :+1:

**Comment by kvyb** [comment]
Still not sure about the logic of they way to set this up if you have multiple bot.onText. Is there a way to tie them into some sort of logic which can be carried forward to default text which is given to user if not matched?

**Comment by GochoMugo** [comment]
You could [TelegramBot#onText()](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#TelegramBot+onText) with the [`options.onlyFirstMatch`](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#new_TelegramBot_new) set to `true`. For example,

```js
const TelegramBot = require("node-telegram-bot-api");
const bot = new TelegramBot(process.env.TELEGRAM_TOKEN, {
    polling: true,
    onlyFirstMatch: true,
});

bot.onText(/\/hello/, function(msg, match) {
    bot.sendMessage(msg.chat.id, "Hello, human!");
});

bot.onText(/\/world/, function(msg, match) {
    bot.sendMessage(msg.chat.id, "Welcome to my World!");
});

bot.onText(/.+/, function(msg, match) {
    bot.sendMessage(msg.chat.id, "I got you!");
});
```
Some simple demo:

![demo](https://cloud.githubusercontent.com/assets/4707579/26715352/17886272-477e-11e7-94ed-9cef95786685.png)

**Also**, we have a PR (https://github.com/yagop/node-telegram-bot-api/pull/313) proposing a middleware solution that might be of interest to you.

**Comment by kimpiggy** [comment]
Hi, how can the bot will reply to a message? as I can see, the bot is only 'messaging' not actually reply to the certain msg

**Comment by danielperez9430** [comment]
> a

You need to pass the params "`reply_to_message_id`" to the sendMessage method

```js
  const opts = {
    reply_to_message_id: msg.message_id
  }

  bot.sendMessage(msg.chat.id, 'Reply to other message:', opts)
```
