### ISSUE TITLE
getting bot by @name sign, not by /name

### ISSUE THREAD

**Issue by dorseth** [yagop/node-telegram-bot-api#345]
> Question

Hi, I created a new bot, the only way I can send it a message is using "/my_name_bot",
but I want to be able to send something to it via "@my_name_bot", I've seen this functionality in other bots, since it's quite hard to find something "@" symbol related - can you give me a hint? :)

**Comment by GochoMugo** [comment]
Could you provide us with more elaborate examples; that way we understand which problem specifically you trying to solve.

**Comment by dorseth** [comment]
okay, let's say my bot name is "bot_name".
When I write something in the chat via "/bot_name something" - the bot reacts to the message,

**Comment by kamikazechaser** [comment]
The syntax is usually `/command@bot_name` see [this](https://core.telegram.org/bots#commands).

**Comment by GochoMugo** [comment]
You have to change your bot's privacy settings so that it can listen on ALL messages. By default, bots only see messages which are interpreted as commmands i.e. `/command arg`.

Also, as @kamikazechaser you have to consider the `@bot_name` section when constructing your RegExps.

**Comment by dorseth** [comment]
Oh, thank you, I thought it was something "out of the box" for the bots.
Can be closed :)

**Comment by saeedhei** [comment]
Can this be Closed?
