### ISSUE TITLE
when you create sendInvoice function? or I can do it?

### ISSUE THREAD

**Issue by Shoyad** [yagop/node-telegram-bot-api#347]
Hello 

When you create and update bot. Becuase Telegram api changes add sendInvoice?

**Comment by GochoMugo** [comment]
We have **not** shipped the function yet. Please be patient.

**Comment by GochoMugo** [comment]
Before we ship, have a look at an actual use of the method; in our test suite: https://github.com/yagop/node-telegram-bot-api/blob/master/test/telegram.js#L1219

* Library API Reference: https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#TelegramBot+sendInvoice
* Telegram API Reference: https://core.telegram.org/bots/api#sendinvoice

#ANS

> FYI:
>
> Use the unpublished master branch: `npm install yagop/node-telegram-bot-api#master --save`

**Comment by GochoMugo** [comment]
**New Release, v0.28.0 :confetti_ball:**
