### ISSUE TITLE
 How to run multiple bots with webhook through a proxy

### ISSUE THREAD

**Issue by qunatumwhiskey** [yagop/node-telegram-bot-api#348]
> Question

Hello. 
How i can deploy many bots with webhook updates through local proxy?

**Comment by GochoMugo** [comment]
The bot checks for its token in the path in each request. Therefore, different bots could `setWebHook()` different paths that are handled by the proxy. Imagine this:

**Bot 1**:

```js
bot.setWebHook(`https://custom-url.com/bot${TOKEN_1}`);
```

**Bot 2**:

```js
bot.setWebHook(`https://custom-url.com/bot${TOKEN_2}`);
```

Note the different tokens `TOKEN_1` and `TOKEN_2`. Now you'll have to configure your proxy (listening at url `https://custom-url.com`) to pass requests in path `/bot${TOKEN_1}` to bot 1 and `/bot${TOKEN_2}` to bot 2.

Hope that helps.

**Comment by elie222** [comment]
This doesn't seem to work. Error that two items are running on the same port when you do this.

**Comment by elie222** [comment]
Ah sorry. Do you do set webhook twice on the same bot?

**Comment by GuillermoPena** [comment]
Same issue. Any solution?
 Is only one Bot instance possible by server? (using same port 8443)
