### ISSUE TITLE
Question: Regarding BotAPIv3.0

### ISSUE THREAD

**Issue by sheshvs** [yagop/node-telegram-bot-api#349]
Hi, Thanks for all the work that is getting done to maintain this repository active. Was planning to use some of the features of BotAPI v3.0. Could you please let me know the current release plan for BotAPIv3.0.

Thanks again!.

**Comment by nyuszika7h** [comment]
See #332. There's no released version that supports Bot API v3.0 yet though, so you'll have to clone the git version manually for now:

```
rm -rf node_modules/node-telegram-bot-api
git clone https://github.com/yagop/node-telegram-bot-api.git node_modules/node-telegram-bot-api
```

**Comment by sheshvs** [comment]
Hi, Thanks for the info.

**Comment by GochoMugo** [comment]
Thanks @sheshvs for using this library. Thanks @nyuszika7h for the help.

ANS: https://github.com/yagop/node-telegram-bot-api/issues/349#issuecomment-307565380
