### ISSUE TITLE
Unsupported Buffer file type on sending buffer containing js file

### ISSUE THREAD

**Issue by Hypfer** [yagop/node-telegram-bot-api#350]
I'm using the current master git branch.

### Expected Behavior
Send buffer containing the contents of a .js file

### Actual Behavior
Unhandled rejection Error: EFATAL: Unsupported Buffer file type

telegram.js:249 seems to be the problem.
``` 
const filetype = fileType(data);
      if (!filetype) {
        throw new errors.FatalError('Unsupported Buffer file type');
      }
```

### Steps to reproduce the Behavior
Send buffer containing plain text

**Comment by Hypfer** [comment]
Why exactly are you checking if the document is a "valid file type" anyways?

Since telegram allows any "file" to be sent via document this doesn't seem reasonable to me.

**Comment by yagop** [comment]
It's because `contentType` has to be provided to Telegram. 

It's weird file type isn't detected. Maybe should provide a default content-type (application/octet-stream or text/plain)

**Comment by nyuszika7h** [comment]
I have the same issue with MP3 not being detected. Could you add an option to explicitly specify the MIME type?

**Comment by GochoMugo** [comment]
##### background

It is easier to have the library auto-detect the MIME type, thus abstracting all that from the user. But advanced users may want to handle that on their own.

When using type auto-detection, we should throw an error if it fails. This avoids situations where bots send files to their users using a probably wrong type.

##### suggested fix

1. Allow specifying the MIME type when invoking methods
1. If none is specified, detect the type (as we are currently doing)

**Comment by GochoMugo** [comment]
##### Update:

1. created feature branch: [feature/explicit-mime-type](https://github.com/yagop/node-telegram-bot-api/tree/feature/explicit-mime-type)
    1. check out commit https://github.com/yagop/node-telegram-bot-api/commit/bdc79a4e41e10338b909bcc7dd6b24037c3537cd: allows specifying the MIME type explicitly

**Comment by GochoMugo** [comment]
In **v0.30.0**, the file type of a buffer, if **not** be detectable, defaults to `"application/octet-stream"`.

**NOTE: For now, this has to be manually activated using environment variable `NTBA_FIX_350`.** (It is an API-breaking change!).

See the updated [docs on sending files](https://github.com/yagop/node-telegram-bot-api/blob/v0.30.0/doc/usage.md#sending-files), particularly [here](https://github.com/yagop/node-telegram-bot-api/blob/v0.30.0/doc/usage.md#file-options-metadata).
