### ISSUE TITLE
Unsubscribing from "onText" listeners

### ISSUE THREAD

**Issue by FindYourGrind** [yagop/node-telegram-bot-api#355]
> Question

Hi, 

Is there are a way to unsubscribe from listening for some command?
I mean smth like in the code below:

```
bot.onText(/\/someCmd/, () => {}); //Subscribe for /someCmd event
bot.unText(/\/someCmd/); //Unsubscribe from /someCmd event
```

Thanks,
Ihor T.

**Comment by david1602** [comment]
Are you currently on `release` or `development`?
There is a `bot.removeTextListener`, but it does not seem to be part of the current release yet.

See the documentation:
https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#TelegramBot+removeTextListener

**Comment by FindYourGrind** [comment]
So, you mean that in the future release I will be able to find such feature and it will work with something like listener id? Is it correct?

**Comment by david1602** [comment]
That's a good question. You can see the temporary workaround of mine in that issue, but using the internal API of the bot is definitely not an acceptable solution. In the end it depends on how it's implemented, so I'm not sure what comes out of the development.

**Comment by FindYourGrind** [comment]
Of course, it depends...
Thanks, I've received the answer.

**Comment by david1602** [comment]
I edited my comment with another hint, sorry for the incomplete response.
