### ISSUE TITLE
How to stop the bot

### ISSUE THREAD

**Issue by vpotseluyko** [yagop/node-telegram-bot-api#357]
I'd like to crash my bot without killing whole process.
In fact, I'd like to have full control over bot lifecycle.
Somewhere on api docs you mentioned, that it's possible, but no certain details.

I use polling.
Best regards

**Comment by vpotseluyko** [comment]
Okay, it seems to me that
`bot._polling.stop()`
stops polling and makes bot unactive. After that I suppose it's enough to delete it and all?
Am I right?

**Comment by GochoMugo** [comment]
You can stop polling using [TelegramBot#stopPolling()](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+stopPolling). If using webhook, there's [TelegramBot#closeWebHook()](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+closeWebHook). The bot will no longer poll/receive Telegram updates.

#ANS
