### ISSUE TITLE
Problem with method getChatAdministrators

### ISSUE THREAD

**Issue by Extar93** [yagop/node-telegram-bot-api#359]
There is a problem with the getChatAdministrators method, you need to get the conversation participants in the Telegram, from the documentation for the API and the bot documentation came out like this:     
```
   var test = bot.getChatAdministrators(chatId);
        console.log(test);
```
But this code does not work, it should output the json-object ChatMember, but it does not output it.
Or am I doing something wrong?
Current output: 
> Promise {
>   _bitField: 0,..etc

**Comment by alexandercerutti** [comment]
A Promise is a sequence of instruction which your application will execute on Async answers (a Promise is a promise, isn't it?).
Then (literally), where in the documentation you see written such like `=> Promise`, you can use
`.then(callback) for successful async operation and .catch(callback) for errors where Callback is a function with a parameter.

So, you cannot assign the result to variable `test`. 

Please, refer to https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Promise for more.

https://core.telegram.org/bots/api#getchatadministrators will give you all the information about the method. In this case, the method says

> returns an Array of ChatMember objects that contains information about all chat administrators except other bots.

So as .then() callback function you will have a variable containing An array of [ChatMember](https://core.telegram.org/bots/api#chatmember).

**Comment by Extar93** [comment]
Something I do not quite understand how the promises work, in this particular case. Could you make an example with this method? If you make a request to api simple GET request, then json object with the data about the administrators of the group is successfully displayed.

**Comment by david1602** [comment]
your code should look something like that

```javascript
bot.getChatAdministrators(chatId)
.then( function(data) {
    console.log(data);
} )
```

assuming you would want to print the return value of the function. of course you could write that as arrow function

```javascript
bot.getChatAdministrators(chatId).then(data => {console.log(data);});
```

Promises contain asynchronous code and only give you a proper return value when they are resolved. Once they're resolved, they will call the function you throw into `then`. If they are rejected (like an error is thrown for example), you could add another `.catch` and pass a function to it that will be called when the promise is rejected.

**Comment by Extar93** [comment]
Thanks for the help. I will understand.

**Comment by GochoMugo** [comment]
Thanks a lot everyone for helping out a colleague. :+1:
