### ISSUE TITLE
Dialog context

### ISSUE THREAD

**Issue by azat-io** [yagop/node-telegram-bot-api#360]
Hello!

Could you help me please. I cannot find answer of my question in your documentation. What's the best way to work with context of the dialog?

This is an **ugly solution** of the problem:

```js
// This code works good
let context

bot.onText(/^(Hi!)$/, msg => {
    context = true
    bot.sendMessage(msg.chat.id, 'What\'s your name?')
})

bot.on('message', name => {
    if (context) {
        name = name.text
        bot.sendMessage(name.chat.id, `Hello, ${ name }!`)
        context = false
    }
})
```

**Comment by GochoMugo** [comment]
I had started working on a solution for this issue: https://github.com/forfuturellc/mau

Unfortunately, I have not found time to get back on it. It is a bit alpha so mind the code!

**Comment by azat-io** [comment]
@GochoMugo Okay. Thanks for the quick response, this is important thing

**Comment by GochoMugo** [comment]
@azat-io Will definitely do so. :+1:
