### ISSUE TITLE
Support Bot API v3.1

### ISSUE THREAD

**Issue by Lord-Protector** [yagop/node-telegram-bot-api#361]
New methods:
- [x] `restrictChatMember` (https://core.telegram.org/bots/api#restrictchatmember) (prs: #362)
- [x] `promoteChatMember` (https://core.telegram.org/bots/api#promotechatmember) (prs: #362)
- [x] `exportChatInviteLink` (https://core.telegram.org/bots/api#exportchatinvitelink) (prs: #362)
- [x] `setChatPhoto` (https://core.telegram.org/bots/api#setchatphoto) (prs: #362)
- [x] `deleteChatPhoto` (https://core.telegram.org/bots/api#deletechatphoto) (prs: #362)
- [x] `setChatTitle` (https://core.telegram.org/bots/api#setchattitle) (prs: #362)
- [x] `setChatDescription` (https://core.telegram.org/bots/api#setchatdescription) (prs: #362)
- [x] `pinChatMessage` (https://core.telegram.org/bots/api#pinchatmessage) (prs: #362)
- [x] `unpinChatMessage` (https://core.telegram.org/bots/api#unpinchatmessage) (prs: #362)

Already supported:
- Field `until_date` for `kickChatMember` method (but here we can do it more comfortable for use). 
- Fields `photo`, `description` and `invite_link` for `Chat` object.
- Fields `until_date`, `can_be_edited`, `can_change_info`, `can_post_messages`, `can_edit_messages`, `can_delete_messages`, `can_invite_users`, `can_restrict_members`, `can_pin_messages`, `can_promote_members`, `can_send_messages`, `can_send_media_messages`, `can_send_other_messages` and `can_add_web_page_previews` for `ChatMember` object.

**Comment by Lord-Protector** [comment]
Just send PR #362. There is no tests and docs, only code. Can @yagop upload it to `yagop/node-telegram-bot-api#master`. But someone should check code at first... I think there are some mistakes.

**Comment by GochoMugo** [comment]
I love this issue!!! Well organized with the appropriate references. Thanks @Lord-Protector. Let me look at the PR. :+1: :100:

**Comment by kamikazechaser** [comment]
Added tests #369

**Comment by mnb3000** [comment]
I think this issue can be closed

**Comment by GochoMugo** [comment]
@mnb3000 Label added. :+1:

**Comment by GochoMugo** [comment]
**New Release, v0.28.0 :confetti_ball:**
