### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by GochoMugo** [yagop/node-telegram-bot-api#365]
##### fix tests:

* [ ] sendVideoNote

##### improve docs:

> P.S. I didn't manage to run your tests because I have no idea how to get 
> `TEST_PROVIDER_TOKEN` / `TEST_GAME_SHORT_NAME` / `TEST_GROUP_ID`
> It would be nice to have a description how to get these in your docs :)
>
> &mdash; https://github.com/yagop/node-telegram-bot-api/pull/364

**Comment by software2Daniel** [comment]
these are the five greatest exponents of the graphic design of our era
Enter now

https://sites.google.com/aprendizajesignificativo.org/exponentesdiseografico/p%C3%A1gina-principal
