### ISSUE TITLE
show_alert should be an optional parameter for answerCallbackQuery()

### ISSUE THREAD

**Issue by nyuszika7h** [yagop/node-telegram-bot-api#367]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

According to the [Telegram API documentation](https://core.telegram.org/bots/api#answercallbackquery), `show_alert` is an optional paramter for `answerCallbackQuery`, and this is also true in practice, so it should be specified in `options`.

### Actual Behavior

`show_alert` is a separate parameter to `answerCallbackQuery()` in `node-telegram-bot-api` and cannot be specified in `options`.

Maybe the library could support both, at least for some time, to avoid breaking existing code.

**Comment by mnb3000** [comment]
Fixed this in PR #368

**Comment by GochoMugo** [comment]
**New Release, v0.28.0 :confetti_ball:**
