### ISSUE TITLE
Telegram bot no answer

### ISSUE THREAD

**Issue by Hostile** [yagop/node-telegram-bot-api#370]
Hi, just installed it, followed all 

Created flow as in example, but bot not responds at all no matther what I do

How I put my username  ?  "username"  or "@username"   I even tried my numeric ID "1234567" none worked

Yes i got token right

What it can be ?

**Comment by Lord-Protector** [comment]
@Hostile Where you want to put your username? I don't understand. You started bot, wrote it and it didn't respond?

**Comment by GochoMugo** [comment]
<p align="center">
  <img src="https://user-images.githubusercontent.com/4707579/27861352-353be986-6189-11e7-94ed-d1daa3d14d3b.png"/>
</p>

**Comment by GochoMugo** [comment]
*OP left us in the cold. :disappointed:*
