### ISSUE TITLE
Error catch

### ISSUE THREAD

**Issue by angelokofficial** [yagop/node-telegram-bot-api#372]
How can I catch an error with code in node-telegram-bot-api? For example, unhandled rejection error. Help me and show example, please. :)

**Comment by alexandercerutti** [comment]
Catching a rejection is made by using ```Promise.prototype.catch```.
So, when you do
```method( ... ).then(function(returnedElems) { ... });```
you simply have to append ```.catch()```:

```javascript
method( ... )
    .then(function(returnedElems) {
        /* your code on successful */
    })
    .catch(function(e) {
        /* your code on failure, 'e' contains data it passes to you on failure */
    });
```

For more details about Promises, please refer to https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Promise. :)

**Comment by GochoMugo** [comment]
Answered by @alexandercerutti [above](https://github.com/yagop/node-telegram-bot-api/issues/372#issuecomment-313931643). Thanks :+1: 

#ANS: https://github.com/yagop/node-telegram-bot-api/issues/372#issuecomment-313931643

**Comment by angelokofficial** [comment]
@alexandercerutti Thanks!!!

**Comment by alexandercerutti** [comment]
You're welcome!

**Comment by angelokofficial** [comment]
@alexandercerutti Do you have Telegram? I want to contact you and ask something about JS.

**Comment by alexandercerutti** [comment]
I can try. Remove the 2nd 'e' from my github nickname and that's my Tg one.
