### ISSUE TITLE
Reemplace :emoji: codes as theirs unicode representation

### ISSUE THREAD

**Issue by jacopocappelli1989** [yagop/node-telegram-bot-api#38]
Hi,
i try to use emoticon/emoji in sendMessage i try ":name:" format and this format: http://pythonhosted.org/python-telegram-bot/telegram.emoji.html
But not work, can you help me? We need to develop some components?

Thanks,
J

**Comment by yagop** [comment]
There is no such feature on this module, but I think you can use emoji as its UTF8 code. Just copy and paste the emoji. I also think you can use the UTF8 code like:

```js
console.log("\u{1F604}");
```

http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by lenny76** [comment]
I solved using 
npm install node-emoji

var emoji = require('node-emoji').emoji;
bot.sendMessage(chatId, 'HI! ' + emoji.heart);

**Comment by GochoMugo** [comment]
@jacopocappelli1989 This library is mostly focused on interacting with the Bot API i.e. providing low-level access to the API. This seems like a high-level feature that is better suited in a high-level library, or in your application code as @lenny76 suggests above.

Side note: you may be interested with [tgfancy](https://github.com/GochoMugo/tgfancy), as soon as I add emoji support (issue https://github.com/GochoMugo/tgfancy/issues/3).

**Comment by MarketingAgencybyYeremenkoAndrii** [comment]
lenny76  - it work ) thanks/
