### ISSUE TITLE
please add the new chat methods

### ISSUE THREAD

**Issue by abbddo** [yagop/node-telegram-bot-api#380]
please add the new groupchat methods like 

 [restrictchatmember](https://core.telegram.org/bots/api#restrictchatmember)
 [promotechatmember](https://core.telegram.org/bots/api#promotechatmember)

**Comment by GingerPlusPlus** [comment]
They're already on Github, they'll be published to npm on next release.

**Comment by GochoMugo** [comment]
We shall publish a new release soon. Before then, you can install the latest code from Github, using npm:

```bash
$ npm install github:yagop/node-telegram-bot-api
```

See https://github.com/yagop/node-telegram-bot-api/issues/361 for more information.

#ANS
