### ISSUE TITLE
Create a telegram group for live interactions

### ISSUE THREAD

**Issue by ghost** [yagop/node-telegram-bot-api#381]
Well having a telegram group for all these interactions will be very helpful .

**Comment by yagop** [comment]
@GochoMugo shall we open "run_nodejs" or create a new group?

**Comment by Dinnerb0ne** [comment]
Lol,I mwant create a new group.

**Comment by GochoMugo** [comment]
@yagop Let's create a separate group for this. We will need to:

* [ ] Add link to group in Readme
* [ ] Announce its formation on the channel
 
We may also consider automatically pushing channel posts to the new group. We can have a bot do that for us.

**Comment by Dinnerb0ne** [comment]
Hey Thanks a lot for considering this request!

**Comment by alexandercerutti** [comment]
So? When will be created the group?

**Comment by sumitsingh1698** [comment]
does now live session is working??

**Comment by sumitsingh1698** [comment]
can i contribute by developing a live session group in telegram ?? @kamikazechaser @GochoMugo

**Comment by GochoMugo** [comment]
Just created the group. Here's the invite link:

https://t.me/joinchat/A3jy8Ula0FGc4LVU04ICQA

Share widely to get more people involved.

**Comment by GochoMugo** [comment]
I will close this issue since the main task has already been handled.

The group can be found at https://telegram.me/ntbasupport.
