### ISSUE TITLE
Get user ID by username?

### ISSUE THREAD

**Issue by abbddo** [yagop/node-telegram-bot-api#383]
is there a way to get the user id using the username?

**Comment by GochoMugo** [comment]
Using the official Telegram Bot API, there is **no** clear way to do that. However, if the bot has an *open* chat with the user, you may use the [getChatMember](https://core.telegram.org/bots/api#getchatmember) method.

Also, you may want to take a look at https://github.com/kamikazechaser/tg-resolve.

**Comment by mnb3000** [comment]
You may want to look at https://github.com/kamikazechaser/tg-resolve or
https://github.com/GochoMugo/tgfancy

**Comment by abbddo** [comment]
thank you guys It works but its very slow 
to resolve a username I need to wait 3 minutes

**Comment by abbddo** [comment]
@GochoMugo @GochoMugo 
guys tg-resolve is not working, do you have some alternatives to it? I need it in my bot

**Comment by GochoMugo** [comment]
This is a long shot but you could run your own instance of  [PWRTelegram](http://pwrtelegram.xyz/). Some time back, we had an issue with load on the primary server.

**Comment by GochoMugo** [comment]
Closing this issue as the original question has been answered. Feel free to continue with the discussion.

---
#CLOSE
#ANS: https://github.com/yagop/node-telegram-bot-api/issues/383#issuecomment-316770512

**Comment by justinvforvendetta** [comment]
@abbddo tg-resolve isnt working, did you find a solution?

**Comment by jerry061023** [comment]
hi there
who can help me?

**Comment by jerry061023** [comment]
how to set TELEGRAM_TOKEN?
I was set it.
But Telegram token required.
please help me.
