### ISSUE TITLE
broadcast message

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#386]
hi,
i want to send message to array of chat ids

```
var chatIds = [ 123456, 654321, 147852 ]
bot.sendMessage( chatIds, 'hi!' )

```
is it possible?
i can do this

```
_.each(chatIds , x => {
    bot.sendMessage( x, 'hi!' )
})

```

but i don't like loop

**Comment by ac1dr3d** [comment]
you will get 429 error.
https://core.telegram.org/bots/faq#broadcasting-to-users

**Comment by saeedhei** [comment]
Hello Milad.
You can use this😉
(https://github.com/saeedhei/Ntba-Bulk-Message)
