### ISSUE TITLE
no exportChatInviteLink method

### ISSUE THREAD

**Issue by ac1dr3d** [yagop/node-telegram-bot-api#387]
https://core.telegram.org/bots/api#june-30-2017  
+ https://core.telegram.org/bots/api#july-21-2017

/**
   * Export an invite link to a supergroup or a channel.
   * @param  {Number|String} chatId Unique identifier for the target group or username of the target supergroup (in the format @supergroupusername)
   * @return {Promise}
   * @see https://core.telegram.org/bots/api#exportChatInviteLink
   */
  exportChatInviteLink(chatId) {
    const form = {
      chat_id: chatId
    };
    return this._request('exportChatInviteLink', { form });
  }

**Comment by GochoMugo** [comment]
We shipped this method in **v0.28.0**. See documentation: [TelegramBot#exportChatInviteLink(chatId)](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+exportChatInviteLink).

Thanks. :+1:
