### ISSUE TITLE
send message to group or channel

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#388]
when i search about this topic in google, people says just send group or channel name insist of chatID
like this

`
sendMessage('@testGroup','message')
`

but it's not work .
how can i send message to a channel ro group by my bot
thanks

**Comment by Assada** [comment]
use chat_id as first argument. 
Like:
```
bot.sendMessage(-102324354, 'Hello World!');
```

**Comment by milad145** [comment]
@Assada 
but how can i find channel ID?

**Comment by GingerPlusPlus** [comment]
@milad145 @milad145: bot.getChat('@username')

**Comment by GingerPlusPlus** [comment]
Also, tgfancy [supports `sendMessage('@testGroup','message')` out of the box](https://www.npmjs.com/package/tgfancy#chat-id-resolution)

**Comment by milad145** [comment]
@GingerPlusPlus 
thanks, it was helpfull

**Comment by milad145** [comment]
Hi again,
i create a message with inlineKyboards
and one of keyboards is `sendToAnother`
is it possible when i click `sendToAnother`, i can choose user from my contacts
and bot get the member id?

**Comment by GochoMugo** [comment]
@milad145 Please create a new issue for this new query, to avoid much confusion for devs exploring issues.
