### ISSUE TITLE
forwardMessage

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#390]
Hi,
i have a message with inlineKeyboards and i want forward it to another channel
but when i use 

`bot.forwardMessage(chatID,from_chatID,messageID)`

just the message sent without any keyboards

is it possible to forward a inlineKeyboards message with all keyboards?

**Comment by GingerPlusPlus** [comment]
@milad145 no, it's not possible with Telegram bot api in general, not only using this library. Just send the message again to another channel.

**Comment by milad145** [comment]
@GingerPlusPlus 
thanks

**Comment by kamelorac** [comment]
Hello, how are you?
When I click inline keyboard on telegram, I want to forward message to another users.
How to do it?

**Comment by kamelorac** [comment]
![1](https://github.com/yagop/node-telegram-bot-api/assets/129031543/7bf946dd-d307-4c34-8bb1-2199e2ef6099)
