### ISSUE TITLE
get channel or group admin

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#391]
how can i find channel or group admins

**Comment by milad145** [comment]
or when somebody send a message to bot 
by from.id , chat.id can we know that he/she is admin of channel or no

**Comment by GingerPlusPlus** [comment]
@milad145 sure. use getChatMember to obtain user's status.
Or, if you want to get all admins, there's method for that too, getChatAdministrators.

**Comment by milad145** [comment]
@GingerPlusPlus 
thank you
it was helpfull

**Comment by Mongo71** [comment]
Buy Our Telegram Groups/Channels Scraper & Adder Software..
Buy Our Telegram Groups/Channels Bulk Private Direct Members Messenger/Sender Software.
Watch Our Videos..
Telegram Groups/Channels Scraper & Adder Software..
https://www.youtube.com/watch?v=pL8dO_1QVf0

Telegram Groups/Channels Bulk Private Direct Members Messenger/Sender Software.
https://www.youtube.com/watch?v=t3j3N4xYwpA

Order From Our Website..
http://telegram-groups-scraper-adder.com/
