### ISSUE TITLE
edit inlineKeyboard message

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#393]
hi,
how can i edit inlineKeybordd message's keyboards?
when i use 
```
var opts = {
	reply_markup: JSON.stringify({
		inline_keyboard: [
			[{text: 'mine', callback_data: 'mine'}],
			[{text: 'all', callback_data: 'all'}]
		]
	})
}
bot.editMessageReplyMarkup(opts, {
	chat_id: answer.message.chat.id,
	message_id: answer.message.message_id
});

```
the keybords disappeared

**Comment by milad145** [comment]
sorry, i find that
```

var message = 'its edited'
var opts = {
     inline_keyboard: [
                    {text: 'Add Option', callback_data: 'addOption'},
                    {text: 'Send', callback_data: 'send'},
                    {text: 'Delete', callback_data: 'delete'}
      ]
 }
bot.editMessageText(message, {
   chat_id: chatId,
   message_id: message_id,
   reply_markup: opts,
});

```

**Comment by qadirsuh** [comment]
This is not working for me. 

here is my error log

`editMessageText err { Error: ETELEGRAM: 400 Bad Request: message can't be edited
    at BaseError (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/node-telegram-bot-api/src/errors.js:10:5)
    at TelegramError (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/node-telegram-bot-api/src/errors.js:56:5)
    at request.then.err (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/node-telegram-bot-api/src/telegram.js:245:15)
    at tryCatcher (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/qadirhussain/Desktop/Development/nodeJS/qRoomCleaningBot/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
  code: 'ETELEGRAM',
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Object],
        close: [Object],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 1438,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 1438,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { server: 'nginx/1.12.2',
        date: 'Thu, 28 Dec 2017 08:43:53 GMT',
        'content-type': 'application/json',
        'content-length': '82',
        connection: 'keep-alive',
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'Content-Length,Content-Type,Date,Server,Connection' },
     rawHeaders: 
      [ 'Server',
        'nginx/1.12.2',
        'Date',
        'Thu, 28 Dec 2017 08:43:53 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '82',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Content-Length,Content-Type,Date,Server,Connection' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'Bad Request',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 1438,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /bot480062068:AAEZn6rAMo9c03XRADAZwSk0Dzz48A0UBeM/editMessageText HTTP/1.1\r\nhost: api.telegram.org\r\ncontent-type: application/x-www-form-urlencoded\r\ncontent-length: 334\r\nConnection: keep-alive\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/bot480062068:AAEZn6rAMo9c03XRADAZwSk0Dzz48A0UBeM/editMessageText',
        parser: null,
        res: [Circular] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        simple: false,
        resolveWithFullResponse: true,
        forever: true,
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Object],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Object],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.telegram.org',
        body: 'chat_id=-269600145&message_id=1062&reply_markup=%7B%22inline_keyboard%22%3A%5B%5B%7B%22text%22%3A%22Add%20Option%22%2C%22callback_data%22%3A%22addOption%22%7D%5D%2C%5B%7B%22text%22%3A%22Send%22%2C%22callback_data%22%3A%22send%22%7D%5D%2C%5B%7B%22text%22%3A%22Delete%22%2C%22callback_data%22%3A%22delete%22%7D%5D%5D%7D&text=OKay%20Fine',
        path: '/bot480062068:AAEZn6rAMo9c03XRADAZwSk0Dzz48A0UBeM/editMessageText',
        httpModule: [Object],
        agentClass: [Object],
        agentOptions: [Object],
        agent: [Object],
        _started: true,
        href: 'https://api.telegram.org/bot480062068:AAEZn6rAMo9c03XRADAZwSk0Dzz48A0UBeM/editMessageText',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: 'api.telegram.org',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 
      { ok: false,
        error_code: 400,
        description: 'Bad Request: message can\'t be edited' } } }
`

**Comment by rezamasrori** [comment]
@milad145
You must use JSON.stringify 
example :  
 bot.editMessageText(message ,{ 
                    chat_id:  msg.chat.id,
                    message_id : msg.message_id,
                    reply_markup :JSON.stringify({ // Added JSON.stringify()
                        inline_keyboard: [[
                        {
                            text: 'item',
                            callback_data: 'item'
                        },{
                            text: 'item 2',
                            callback_data: 'item 2'
                        }
                        ]]
                    })

                })

**Comment by rezamasrori** [comment]
`@milad145
You must use JSON.stringify
example :
bot.editMessageText(message ,{
chat_id: msg.chat.id,
message_id : msg.message_id,
reply_markup :JSON.stringify({ // Added JSON.stringify()
inline_keyboard: [[
{
text: 'item',
callback_data: 'item'
},{
text: 'item 2',
callback_data: 'item 2'
}
]]
})`
