### ISSUE TITLE
delete message

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#394]
hi,
when i use 
`
bot.deleteMessage(chatId,message_id)
`
it comes with error

> bot.deleteMessages is not a function

**Comment by abbddo** [comment]
make sure that the bot is an admin with  permission to delete message

**Comment by milad145** [comment]
@abbddo
hi dear abbddo,
i get that error in bot page, and i think  bot must can delete message in own page

**Comment by abbddo** [comment]
aha I think you have the old version of the bot 
use the newest release of node-telegram-bot-api 
I think you should run this command in the root of your project 
`npm update node-telegram-bot-api`

**Comment by milad145** [comment]
@abbddo 
hi,
i update node-telegram-bot-api

but i get error

>  bot.deleteMessage is not a function

**Comment by milad145** [comment]
hi,
Does anyone have an idea?

**Comment by milad145** [comment]
@GingerPlusPlus 
@yagop 
can u help me?

**Comment by GingerPlusPlus** [comment]
@milad145 It's already on Github, but not yet published to npm.
You can install from github (#380), or manually use [`_request`](https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L178) directly.

**Comment by GochoMugo** [comment]
Sorry guys, we will be pushing a new release soon. We have been unavailable for some time now. Will close this issue as soon as we push to npm.

**Comment by GochoMugo** [comment]
**New Release, v0.28.0 :confetti_ball:**

**Comment by StarCanada** [comment]
Can someone show me how to use DeleteMessage in my Telegram Bot? I need to have this function defined in my file, is this right?
