### ISSUE TITLE
how to find member nationality

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#395]
is there any option to find members nationality?

**Comment by GingerPlusPlus** [comment]
@milad145 yes. msg.from.language_code.

**Comment by milad145** [comment]
@GingerPlusPlus 
hi dear GingerPlusPlus,
language_code comes wrong,
when you create a telegram account , telegram ask your country in the first to input phone number,
and i want to get than country
is it possible?

**Comment by GingerPlusPlus** [comment]
@milad145 Afaik, language_code is based on the device someone is using. I noticed my language_code changing when using different device. I know no way of knowing country of phone number. Assume that language_code is correct, but give your users opportunity to override it if it's not.

**Comment by milad145** [comment]
thanks

**Comment by youseftear** [comment]
Hi. please send for me your telegram ID.(@youseftear1) 

    On Tuesday, August 8, 2017 10:54 AM, milad145 <notifications@github.com> wrote:
 

 Closed #395.—

**Comment by milad145** [comment]
@GingerPlusPlus 
hi,
sorry again,
can you look this issue
#394
