### ISSUE TITLE
How do I write an attachment to a message handler?

### ISSUE THREAD

**Issue by tapinambur0508** [yagop/node-telegram-bot-api#397]
Hello. I'm writing the simplest telegram bot. There is a small problem. Here is the code:

```
bot.onText(/\/test/, function(msg) {
    bot.sendMessage(msg.chat.id, 'Hello')
	.then(function(msg)
	{
		bot.on('message', function(msg) {
                        console.log(msg);
                });
	})
	.catch(function(e)
	{
		console.log(e);
        });
});
```

When I write / test this code works and the bot responds to me with the same message (the bot has asked something). Then I answer and the message is displayed in the console. Ideally, it should exit this handler and just go there without the test command. But if I write any message it again outputs it to the console. How can I fix this? Thank you

**Comment by danielperez9430** [comment]
You can use bot.once('message', (msg) =>  ... ) this listener is only execute 1 time
