### ISSUE TITLE
switch_pm_parameter and switch_pm_text methods are missing!!

### ISSUE THREAD

**Issue by abbddo** [yagop/node-telegram-bot-api#398]
I've tried to use these two methods in my code but they didn't work 
then I've searched the whole library but I did not find anything related to these methods 
can you help me please ? 
[this is the link of the telegram API which contain these methods](https://core.telegram.org/bots/api#answerinlinequery)

**Comment by zumoshi** [comment]
hi,

as you can see [here](https://github.com/yagop/node-telegram-bot-api/blob/4ed6d945ab4596a92aff294a47e3440576c835fa/src/telegram.js#L592), the `answerInlineQuery` method takes a third parameter, an object containing extra parameters for that method.

both `switch_pm_parameter ` and `switch_pm_text` are parameters (not methods) that must be sent alongside `results` to the `answerInlineQuery` method.

example code:
```js
bot.answerInlineQuery(query_id, results, {switch_pm_text:'test',switch_pm_parameter:'x'});
```

**Comment by abbddo** [comment]
thank you very much @zumoshi

**Comment by GochoMugo** [comment]
Thanks @zumoshi for helping out. :+1: 

#ANS: https://github.com/yagop/node-telegram-bot-api/issues/398#issuecomment-321573519

**Comment by bogdyak** [comment]
Thank you @zumoshi 
But in your example what will be `query_id`?
This one? 
```
{ update_id: 3810271,
  inline_query: 
   { id: '777328921826354429',
     from: 
      { id: 180985993, // ------ THIS ----------
        is_bot: false,
        first_name: '',
        last_name: '',
        username: '',
        language_code: 'en-us' },
     query: 's',
     offset: '' } }
```
Am right?
