### ISSUE TITLE
sendDocument returns 400 if URL has query param

### ISSUE THREAD

**Issue by reyy** [yagop/node-telegram-bot-api#40]
I'm trying to send out a document/ photo/ audio file from a URL that query parameters behind its path (eg. http://example.com/getfile.php?id=101) and its returning me an Error 400.

``` javascript
bot.sendDocument(chatId, request('http://www.ilsny.com/mysite/viewfile.php?id=35'));
```

```
{
  "ok": false,
  "error_code": 400,
  "description": "Error: Bad Request: there is no document in request"
}
```

Conversely the same call with a URL that doesnt have parameters works just fine:

``` javascript
bot.sendDocument(chatId, request('http://upload.wikimedia.org/wikipedia/en/4/45/ACDC_-_Back_In_Black-sample.ogg'));
```

The only work around I have is to make a request for the file, write to fs, and call sendDocument with that local filename. It works but its not ideal as its much slower and eats my bandwidth.

**Comment by yagop** [comment]
I will take a look on this.

The bandwidth will be the same and time more or less.

**Comment by yagop** [comment]
Its not possible to know which file type is if not provided on the name.
There is an other way to use the response Buffer on the sendDocument (and others) methods

**Comment by reyy** [comment]
I have a fix/workaround, but its not very elegant. I'll clean it up a bit and submit a pull request soon.

**Comment by GochoMugo** [comment]
Is this bug still persistent? And if so, please provide us with such a URL for reproduction purposes!

**Comment by GochoMugo** [comment]
I believe this bug does **not** exist anymore. I have tested with the latest version of the codebase and I can **not** seem to reproduce this bug.

Feel free to re-open this issue if you believe the bug still exists.
