### ISSUE TITLE
chosen_inline_result event doesn't work!

### ISSUE THREAD

**Issue by abbddo** [yagop/node-telegram-bot-api#400]
chosen_inline_result doesn't work 
I've created inline query and answer it 
but when I choose one of the results I didn't get any event 

```
bot.on('chosen_inline_result', function(msg)
{
    console.log('Chosen: ' + msg);
});
```

console show no thing about this code
and there is no errors

**Comment by GingerPlusPlus** [comment]
@abbddo Make sure you enabled receiving those in @Botfather

**Comment by abbddo** [comment]
thank you it's working now @GingerPlusPlus
