### ISSUE TITLE
How to get and console.log Super Group ID?

### ISSUE THREAD

**Issue by saeedhei** [yagop/node-telegram-bot-api#401]
How Can I get and console.log Super Group ID?
I'm Getting `ETELEGRAM: 400 Bad Request: chat not found`

**Comment by GochoMugo** [comment]
Try using [*TelegramBot#getChat()*](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+getChat):

```js
bot.getChat("@channelusername").then(function(chat) {
    // 'chat' is a Chat object
});
```

See [API getChat()](https://core.telegram.org/bots/api#getchat) method and [Chat](https://core.telegram.org/bots/api#chat) object.

Hope that helps.

**Comment by saeedhei** [comment]
Dear @GochoMugo  my Super Group hasn't any username, Just has `Group name` and `Group Description`
and my Channel Is Private too and It has `Channel name` and `Channel Description` too, Then What Should I put in `bot.getChat("@channelusername"` to getting  super Group and Provate Channel ID?

**Comment by GingerPlusPlus** [comment]
@saeedhei please
console.log messages
and take a look

**Comment by saeedhei** [comment]
Dear @GingerPlusPlus , Do you mean in
```
bot.on('message', (msg) => {
  const chatId = msg.chat.id;
});
```
I Should console.log messages ? and How It Can Get my Super Group ID? 
My Problem is my Super Grout Hasn't any username and I Don't know How to get ID

**Comment by yagop** [comment]
AFIK the Super Group ID is the `chat.id`.

Can this be closed?

**Comment by saeedhei** [comment]
Thank you.
