### ISSUE TITLE
Sending document returns RequestError: TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by F1ks3r** [yagop/node-telegram-bot-api#402]
### Expected Behavior

Trying to send document with `bot.sendDocument(chatId, 'src/giphy.gif')` (i use longpoll)
Path is fine, git is fine, tried million other documents, buffers, streams, million other paths, still doesn't work.

### Actual Behavior

Im getting `RequestError: TypeError: The header content contains invalid characters`
The thing is that with the same code previously everything worked, somehow slight differences in file structure are getting in the way, that i don't understand....

### Steps to reproduce the Behavior

Just try to send file
```
const bot = new TelegramBot(prod_token, {polling: true})
bot.on('message', (msg) => {
    const chatId = msg.chat.id
    bot.sendDocument(chatId, 'giphy.gif')
});

**Comment by F1ks3r** [comment]
Somehow having 
```
Object.prototype.query_string = function () {
 	return Object.keys(this).map(e=>{
         return `${e}=${this[e]}`
     }).join('&')
}
```
blocked the request....

**Comment by GingerPlusPlus** [comment]
@F1ks3r why are you reimplementing that functionality? Plus, why, oh why, are you attaching it to `Object.prototype`?

Use builtin [`querystring.stringify`](https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options)
