### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by cyrus-za** [yagop/node-telegram-bot-api#403]
> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

Be able to build the bot so that it can be deployed on services such as ZEIT's `now` where there's no access to run `mkdir` in the `start` script. 

### Example

package.json
```javascript
"script:" {
    "build" : "telegram-bot build",
    "script" : "node index.js"
}
```

**Comment by GochoMugo** [comment]
Could you elaborate on this?

**Comment by cyrus-za** [comment]
Not really much to elaborate on other than the fact that we need a way to build the bot with some CLI command

**Comment by GochoMugo** [comment]
Could you give some examples?
