### ISSUE TITLE
telegram bot url with parameters

### ISSUE THREAD

**Issue by milad145** [yagop/node-telegram-bot-api#406]
i saw a bot with this link

> http://telegram.me/example_bot?id=456856

so i want to create link like this

> http://telegram.me/myExample_bot?command=sendMessage

and i want when a user click on this link bot get the command and send him message 
is it possible?

**Comment by GingerPlusPlus** [comment]
@milad145 yes, it is possible. It's called deep linking, read about it in docs.

**Comment by milad145** [comment]
@GingerPlusPlus
thank you,
but 
this is my code
```
bot.onText(/\/getCommand (\w+)/, function(msg, match) {
   callFuction(msg.chat.id , match[1]);
});

var callFunction = function(chatid,text){
   bot.sendMessage(chatid,text)
}
```
and my link is

> http://telegram.me/myExample_bot?getCommand=123456

i want when a user click on bot link then `callFunction` run automaticly
how can i do that?

**Comment by GingerPlusPlus** [comment]
@milad145 read about deep linking again.
I'd use a link like http://telegram.me/myExample_bot?start=getCommand-123456
and a regex like /start getCommand-(\d+)
or add a general route like (it's Livescript, I can't be bothered to rewrite to JS):
bot.on-text command('start', "([\\w-]+)"), (msg, [,, command]) ->
  bot.process-update(message: msg with {text: '/' + command.replace(/\-/g, ' ')})

**Comment by milad145** [comment]
@GingerPlusPlus
thanks,
i do that, in this case if user click on link ,the start button do correctly
but if user clear bot cash and then press on start button the start button doesn't work

**Comment by GingerPlusPlus** [comment]
@milad145 
> if user clear bot cash
What's "bot cash"?

What do you mean by "doesn't work"?

**Comment by milad145** [comment]
```
bot.onText(/\/start (\w+)/, function (msg, match) {
	console.log(msg)
	console.log(match)
})
```
if you click on link and then press start you can see the console.log
but if you press on start without clicking on link you can't see console.log

**Comment by GingerPlusPlus** [comment]
That's the expected behavior.

The handler is called only when bot it started from a link.

**Comment by milad145** [comment]
but what happend if some one start bot without clicking on link
or what happend if some one clear bot history and then press start button again?

**Comment by wildangunawan** [comment]
I found out how to do this. I don't know if this is safe or not. We can use RegEx: "/\/start(.*)/". This way our bot will read "/start" with or without any parameter.

```javascript
bot.onText(/\/start(.*)/, (msg, match) => {
	console.log(msg)
	console.log(match)
});
```

But the drawback is matching pattern will have space before the actual parameter.

This is match when user send "/start": [ '/start', '', index: 0, input: '/start', groups: undefined ]

This is match when user send "/start haha": [ '/start haha',  ' haha',  index: 0,  input: '/start haha',  groups: undefined ]

There is space before "haha". So we need to carefully remove that.

**Comment by GatsbyFuture** [comment]
thanks so much for any example

**Comment by iliyaZelenko** [comment]
If you want to use URL params with bot like this: `action=delete&userId=123`

1. Convert payload to base64: `btoa('a=123&b=gdfgd-gdfgdfgdf')`
2. Pass it to the bot: https://telegram.me/MY_COOL_BOT?start=YT0xMjMmYj1nZGZnZC1nZGZnZGZnZGY=
3. Handle

``` js
  bot.onText(/\/start/, (msg) => {
    // Removes /start prefix
    const payload = msg.text!.substring(6);

    if (payload.length) {
      const url = Buffer.from(payload, 'base64').toString();
      const params = Object.fromEntries(new URLSearchParams(url).entries());

      // Result: { a: '123', b: 'gdfgd-gdfgdfgdf' }
      console.log(params);
    } else {
      // Start bot without payload
    }
  });
```
