### ISSUE TITLE
Expose the message type to on('message')

### ISSUE THREAD

**Issue by jlsjonas** [yagop/node-telegram-bot-api#409]
> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

Especially useful for logging/tracking purposes, expose the message type to the `message` event, avoiding code duplication just to find out the message type

### Example

```js
bot.on('message', function onMessage(msg) {
  botan.track(msg, (msg.text)?msg.text.split(' ')[0]:msg.type);
}
```
(example using botanio, but would be applicable to pretty much any tracking library/system, the msg.text part is added as a more complete example, to track commands)

**Comment by GochoMugo** [comment]
**v0.30.0** passes metadata to the `message` event. For example,

```js
bot.on("message", function(message, metadata) {
    console.log(metadata.type); // e.g. "photo"
});
```
