### ISSUE TITLE
Bot API 3.3.

### ISSUE THREAD

**Issue by telegram-api** [yagop/node-telegram-bot-api#411]
https://core.telegram.org/bots/api-changelog#august-23-2017

**Comment by GingerPlusPlus** [comment]
@telegram-api It doesn't new any new methods, only data fields and new formatting

You can access that from any version, no code changes neccesary.

**Comment by GochoMugo** [comment]
No work is required to support this new version. We'll close this as soon as we make the next release and announcement. Particularly, we need to close #407 first.

**Comment by GochoMugo** [comment]
Added in **v0.29.0**.
