### ISSUE TITLE
How to separate commands

### ISSUE THREAD

**Issue by GatoPresto** [yagop/node-telegram-bot-api#414]
Hi!

How to separate commands from main file like routes in express?
I want to store commands in different files in "commands" dir.

**Comment by GingerPlusPlus** [comment]
@GatoPresto export command handler and possibly its regex from a file, and attach them all im main

**Comment by GatoPresto** [comment]
@GingerPlusPlus I had an error `bot.sendMessage is not a function` when I try to export bot from main and use it in command file like `bot.sendMessage`

**Comment by GatoPresto** [comment]
@GingerPlusPlus ok, I did something like this:
```javascript
bot.onText(/\/start/, (msg) => startCommand(msg, bot));
```

Can I implement it better or different way?

**Comment by GingerPlusPlus** [comment]
@GatoPresto it's fine
if you're better approach, I'd make a separate bot file exporting bot, which can be required by both main and your other files

**Comment by GatoPresto** [comment]
@GingerPlusPlus ok, thanks
