### ISSUE TITLE
To detect if another instance is polling

### ISSUE THREAD

**Issue by oscarcalvo** [yagop/node-telegram-bot-api#415]
> Question

Hi, exists any way to detect if another instance is polling with same token? I have tried things like 

`    this.bot
        .getMe()
        .then(x => {          
          this.bot
            .startPolling()
            .then(x => {
              console.log("Bot started");
            })
            .catch(x => {
              console.log("Error in bot");
              this.bot.stopPolling();
            });
        })
        .catch(x => {
          console.log("Error");
        });`

but doesn't works and says by console the error. We have a bot for testing in our application but when two or more of us start the  application, start to poll with same token so maybe there are a elegant way of to detect it.

Thanks.

**Comment by GingerPlusPlus** [comment]
@oscarcalvo elegrant way is to use mutliple tokens.

**Comment by GPlay97** [comment]
I'm facing the same problem.

I've created a seperated token - but the node js server is running in cluster mode - so multiple instances will be created. The bot then crashes (or fires an error every few ms). How can I prevent this? I've tried to stop polling on polling error - or only start polling if bot.isPolling() is false - but this doesn't changes anything.

Thanks in advance!

**Comment by GingerPlusPlus** [comment]
@GPlay97 If you want to run a cluster, you have to use Webhook

**Comment by GPlay97** [comment]
@GingerPlusPlus Thank you for your fast reply! I'll try using webhooks :+1:
