### ISSUE TITLE
How to stop spinning loader on inlineKeyboards buttons

### ISSUE THREAD

**Issue by nicolocarpignoli** [yagop/node-telegram-bot-api#416]
> Question

Hi, I'd like to know if it is possible to stop the spinning loader on the top right corner of the inline Keyboards buttons. In my implementation they last some seconds but they don't disappear when bot responds to the callback as I was expected. This is my code for inline keyboards and callback_query handling 

```
    exports.generateInlineKeyboard = function (options){
        let inlineOptions = [];
    options.forEach(function(element) {
        inlineOptions.push([
                {
                    text: element.name, 
                    callback_data: element.name
                }
            ]);
    }, this);
    return {
        "parse_mode": "Markdown",
        "reply_markup": {
            "inline_keyboard": inlineOptions
        }
    };
};
```

```
bot.on('callback_query', (msg) => {
        var userInput = msg.data;
        bot.sendMessage(msg.from.id, Common.message(userInput));
    }
```

[
![cc38b296-a2d4-40f6-8264-946d3108cbca](https://user-images.githubusercontent.com/22395670/29823642-90a19df4-8ccf-11e7-8f5a-ec5305fd47bf.jpg)
](url)

**Comment by GingerPlusPlus** [comment]
@nicolocarpignoli you have to answerInlineQuery
when you pass empty sting, it won't show any message, it'll just hide the spinning loader

**Comment by nicolocarpignoli** [comment]
@GingerPlusPlus how can I exactly can do that? I tried
```
bot.on('callback_query', (msg) => {
        var userInput = msg.data;
       bot.answerInlineQuery(msg.id,[]);
    }

```
But it said:
`
Unhandled rejection Error: ETELEGRAM: 403 Forbidden: USER_BOT_INVALID
`
I am obviously missing something

**Comment by GingerPlusPlus** [comment]
@nicolocarpignoli callback query and inline query are 2 different things.
Re-read the docs.

**Comment by GingerPlusPlus** [comment]
@GingerPlusPlus oh, my bad, I told you to use anserINlineQuery, lol
answerCallbackQuery is what you need

**Comment by nicolocarpignoli** [comment]
@GingerPlusPlus thanks you man, works like a charm
