### ISSUE TITLE
How delete message?

### ISSUE THREAD

**Issue by Vabery** [yagop/node-telegram-bot-api#417]
How delete message/
I write code
bot.on('message', (msg) => {

    bot.deleteMessage(msg.chat.id, msg.message_id);

    console.log(msg);
});
but in console return ETELEGRAM: "400 Bad Request: message can't be deleted"

**Comment by voed** [comment]
Make sure your bot has privilegies to delete messages

**Comment by Vabery** [comment]
@voed 
In my group, the bot has administrator rights
