### ISSUE TITLE
poblem with set title in a chat

### ISSUE THREAD

**Issue by angelokofficial** [yagop/node-telegram-bot-api#419]
When I try to change chat title via a bot, I get error like `TypeError: bot.setChatTitle is not a function`
I have a non-supergroup chat with disabled all users are admins feature. Bot is a admin.
Part of my code:

`	bot.onText(/\/title (.*)/, function (msg, match) {`
`	var chatid = msg.chat.id;`
`	var resp = match[1];`
`	bot.setChatTitle(chatid, resp)`
`});`

What's wrong? It's a bug or my mistake?

**Comment by GochoMugo** [comment]
Are you using the latest version of the library?

**Comment by angelokofficial** [comment]
Dear @GochoMugo sorry. I updated the library and now everything works.
