### ISSUE TITLE
Token of appreciation

### ISSUE THREAD

**Issue by SegersIan** [yagop/node-telegram-bot-api#420]
Hi Guys

I do not have an actual issue to report, due to the nature of GitHub I am a bit forced to take the issue way to deliver this message.

I just wanted to express my gratitude and thousands of thanks for this library. This library helped me to bootstrap my Telegram Bot integration in less than an hour in my existing solution. It's thanks to the great effort of you all the contributors that I am able to do my job and focus on what really matters, that is building features.

My apologies for opening an issue for this but I just wanted to say big thanks and keep up the great work. 

Best Regards

**Comment by kamikazechaser** [comment]
🙌 Papa bless

**Comment by GochoMugo** [comment]
Thank you @SegersIan for the appreciation. It's great developers like you that keep the open source community going. We hope to continue providing a quality library for your Telegram Bot development.

FYI, we just released **v0.30.0**. Hope you enjoy it.

Ooh, Happy Holidays! :gift:
