### ISSUE TITLE
SyntaxError: missing ) after argument list, When using async

### ISSUE THREAD

**Issue by saeedhei** [yagop/node-telegram-bot-api#423]
Why am I getting this error When I use `async`?
Is there any way to use async/await in node.js 6?

**My Code:**

    bot.onText(/\/start/, async  msg => {
      const opts = {
        parse_mode: 'Markdown' ,
        reply_markup: JSON.stringify({
          keyboard: StartKeyboard,
          resize_keyboard: true,
          one_time_keyboard: true
        })
      };
      await bot.sendMessage(msg.chat.id, 'Hi', opts);
    });
**Error:**

    bot.onText(/\/start/, async  msg => {
                          ^^^^^
    SyntaxError: missing ) after argument list

	
I'm using node.js v6.11.0 with "dependencies": 

    { "babel-polyfill": "^6.23.0",
      "cheerio": "^1.0.0-rc.2",
      "dotenv": "^4.0.0",
      "firebase": "^4.1.2",
      "firebase-admin": "^5.0.0",
      "node-telegram-bot-api": "^0.27.1",
      "request": "^2.81.0" },

**Comment by yagop** [comment]
As far I know Node 6.11.0 doesn't have support for async / await. Use newer version.

http://node.green/#ES2017-features-async-functions

**Comment by saeedhei** [comment]
Is there any module to solve that? I Mean I need to use node.js 6 and async. Someone  Said me to use babel.

**Comment by GochoMugo** [comment]
As @yagop says, Node.js v6 does **not** support `async`. You may use babel to transpile your `async`s: https://babeljs.io/docs/plugins/syntax-async-functions.
