### ISSUE TITLE
Inline keyboard without URL, just text

### ISSUE THREAD

**Issue by dehghani-mehdi** [yagop/node-telegram-bot-api#424]
Seems like `url` parameter is optional in `inline keyboard` [ref](https://core.telegram.org/bots/api/#inlinekeyboardbutton), but I could not use inline keyboard without that.

> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

Can use inline keyboard without `url`

### Actual Behavior

I got this error message:

>Can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard

### Steps to reproduce the Behavior

Sample code:

```
bot.sendMessage(msg.chat.id, 'Hello', {
        reply_markup: {
            inline_keyboard: [
                [{
                    text: 'my button'
                }]
            ]
        }
    });
```

With `url` code works.

```
bot.sendMessage(msg.chat.id, 'Hello', {
        reply_markup: {
            inline_keyboard: [
                [{
                    text: 'my button',
                    url: 'www.somewhere.com'
                }]
            ]
        }
    });
```

Thanks.

**Comment by alexandercerutti** [comment]
Use an empty `callback_data` in text button. That should work.

```javascript
{
    reply_markup: {
        inline_keyboard: [
            [{
                text: "my button",
                callback_data: "",
             }]
        ]
    }
}
```

**Comment by AntonioTsai** [comment]
According to [Telegram Official Bot API](https://core.telegram.org/bots/api#inlinekeyboardbutton),
> **InlineKeyboardButton**
> This object represents one button of an inline keyboard. You **must** use exactly one of the optional fields.

You need to choose one from `url`, `callback_data `, `switch_inline_query `, `switch_inline_query_current_chat `, `callback_game `, `pay`.

**Comment by dehghani-mehdi** [comment]
@alexandercerutti  your code doesn't work, but helped me, thanks. working code is as follow:

```
{
    reply_markup: {
        inline_keyboard: [
            [{
                text: "my button",
                callback_data: "whatever",
             }]
        ]
    }
}
```

**Comment by alexandercerutti** [comment]
Well, okay, I wrote it without watching the documentation ahah. You are welcome 👍

**Comment by dehghani-mehdi** [comment]
@alexandercerutti I'm sorry, do you know how I can figure out `my button` is selected by user (I have multiple buttons/options, so I need to know user's select)
