### ISSUE TITLE
Openshift 2 is going to be shutted down.

### ISSUE THREAD

**Issue by alexandercerutti** [yagop/node-telegram-bot-api#426]
The webhook example on Openshift 2 is obsolete due to closed subscriptions to OS 2 (mmm, about over a year ago). RedHat now has Openshift 3, which is a mix of Docker and Kubernetes and on september 30th, OS 2 will be shutted down.
After have understood a bit how Openshift 3 works, setting up a bot with polling is quite easy, but creating a Webhook is more difficult, since it requires the setup of routes and many more that I'm trying to understand from about two weeks... and the enviroment variables are not the same, since the concept of "gear" is disappeared.

So what I suggest to do, is adding a message on the Openshift webhook example to inform users.

**Comment by GochoMugo** [comment]
Done in commit https://github.com/yagop/node-telegram-bot-api/commit/455a93cacb0ca2c1ddd679e29d46a781f0d782e8.

Thanks @alexandercerutti.
