### ISSUE TITLE
sendMessage method has high delay time

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [yagop/node-telegram-bot-api#433]
Hello.

I'm using my bot via webhooks and incoming messages from telegram are being handled by express js:

     app.post(`/bot${token}`, (req, res) => {
            bot.processUpdate(req.body);
            res.sendStatus(200);
     });

Then I'm trying to respond to telegram by using `sedn message` method

    bot.on('message', (message) => {
          let startTime = (new Date()).getTime();
          bot.sendMessage(message.chat.id, 'Some text').then(payload => {
              let endTime = (new Date()).getTime();
              console.log(`Send time ${endTime - startTime} milliseconds`);
          });
    });

My bot receives messages very fas. However, responding via `sendMessage` takes from **2-5** seconds.

i'm using NodeJS v.8.6.0
OS is RHEL 7
Bot is launched via PM2

My remote machine internet access works via proxy. However, it has no delay, because I have made `curl` requests to telegram API and it responsd very fast.

Did I miss something?

**Comment by AliSawari** [comment]
Why are you using express for handling ??

**Comment by AliSawari** [comment]
Use setWebhook instead and provide a crt.pem file with open-ssl

**Comment by SuperMasterBlasterLaser** [comment]
@AliSawari using express js will provide more control of webhook endpoints.

If you wont be using express you should install Nginx, to make routing to your webhook url.

I have solved my problem regarding slow send time. It was because of proxy that is used to get access to internet. My virtual machine providers intentionally made it slow for their own reasons.

**Comment by AliSawari** [comment]
@SuperMasterBlasterLaser so now the bot is doing fine ? can I use express just like you for routing?

**Comment by SuperMasterBlasterLaser** [comment]
@AliSawari Yes. Bot works fine. If you open [this example](https://github.com/yagop/node-telegram-bot-api/blob/master/examples/expressWebhook.js) you can see how express is being used for handling Telegram's data.

**Comment by AliSawari** [comment]
Thanks a lot :)

**Comment by jjhesk** [comment]
@AliSawari @SuperMasterBlasterLaser i have done the same by running other websockets in the system and it drives the api slow. how do we resolve that?
