### ISSUE TITLE
Add .on() to the API docs

### ISSUE THREAD

**Issue by Wilfred** [yagop/node-telegram-bot-api#436]
`myBot.on()` is not mentioned in api.md, and it's a very useful API. There are some useful notes in usage.md, but I was expecting api.md to list all the functions defined on a bot instance.

**Comment by cawa-93** [comment]
@Wilfred https://nodejs.org/api/events.html#events_emitter_on_eventname_listener

**Comment by GochoMugo** [comment]
[TelegramBot#on()](https://github.com/yagop/node-telegram-bot-api/blob/v0.30.0/doc/api.md#TelegramBot+on) has been documented.
