### ISSUE TITLE
Support Live Locations

### ISSUE THREAD

**Issue by kucherenkovova** [yagop/node-telegram-bot-api#438]
> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/live%20locations) and found none

### Introduction

Since Telegram core bot api supports them it would be nice to have this feature for node.js as well.
### Example
I didn't look if any other language port supports it but we have Bot API docs [here](https://core.telegram.org/bots/api#editmessagelivelocation)

> Question
I plan to use this kind of functionality in my next telegram bot so I'm interested in having this feature asap. I can even help you to implement this kind of stuff but last time I wanted to contribute I found out that I'm not able to run your tests. See [here](https://github.com/yagop/node-telegram-bot-api/pull/364).

**Comment by kamikazechaser** [comment]
I'll send in a PR for this asap.

**Comment by kamikazechaser** [comment]
PR #439 will address this issue.

**Comment by GochoMugo** [comment]
Live Locations supported in **v0.30.0**.
