### ISSUE TITLE
Downloading file to memory stream (feature request)

### ISSUE THREAD

**Issue by Xaqron** [yagop/node-telegram-bot-api#442]
Currently the only available option for downloading a file from Telegram servers is `downloadFile` which writes file to the disk. If the file is not needed for long then (i.e. you need file for one second) a write and read from disk plus a delete should be done.
If there be a `getFileStream` method which returns a memory stream, then such a problem does not happen.

Thanks

**Comment by AliSawari** [comment]
yeah, thats true, we'll need streaming

**Comment by yagop** [comment]
You can use [getFileLink](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#telegrambotgetfilelinkfileid--promise) to get the link and create an stream with [your favourite HTTP request module].

**Comment by GochoMugo** [comment]
@yagop I think we can work on adding a `getFileStream` method. It would be quite helpful for most users I presume.

**Comment by GochoMugo** [comment]
Just added [TelegramBot#getFileStream()](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#TelegramBot+getFileStream) on **master** branch. Please try it out and give us feedback.

**Comment by GochoMugo** [comment]
Shipped in **v0.30.0**.
