### ISSUE TITLE
How to check if sender is admin? 

### ISSUE THREAD

**Issue by adv-zl** [yagop/node-telegram-bot-api#444]
I added bot to supergroup and created event that listen all messages.
```
bot.on('message', (msg) => {
  const chatId = msg.chat.id;
  
  bot.deleteMessage(chatId, msg.message_id);
});
```

How can I check if admin sent this message?

**Comment by sidelux** [comment]
I use this workaround and seems to work.

```
bot.getChatMember(message.chat.id, message.from.id).then(function(data) {
    if ((data.status == "creator") || (data.status == "administrator")){
        // I'm admin or creator, so delete message
    }
});
```

**Comment by DestroyerIV** [comment]
Where do you add that paragraph?

**Comment by sidelux** [comment]
@DestroyerIV 
bot.onText(/^\/ban/, function(message, match) {
	bot.getChatMember(message.chat.id, message.from.id).then(function(data) {
		if ((data.status == "creator") || (data.status == "administrator")){
			bot.sendMessage(message.chat.id, "I'm admin!");
		}else{
			bot.sendMessage(message.chat.id, "I'm not admin");
		}
	});
});

**Comment by DestroyerIV** [comment]
Thanks bro, How can I join it to kickChatMember?

**Comment by sidelux** [comment]
```
bot.onText(/^\/ban/, function(message, match) {
	// Easy way is use this command via reply, so:
	if (message.reply_to_message == undefined){
		// Not used via reply
		return;
	}
	var username = message.reply_to_message.from.username;
	var userid = message.reply_to_message.from.id;
	bot.getChatMember(message.chat.id, message.from.id).then(function(data) {
		if ((data.status == "creator") || (data.status == "administrator")){
			bot.kickChatMember(message.chat.id, userid).then(result => {
				bot.sendMessage(message.chat.id, username  + " has been banned!");
			});
		}
	});
});
```

**Comment by DestroyerIV** [comment]
Thanks bro, good job

**Comment by yagop** [comment]
Thanks @sidelux !

Can this be closed then?

**Comment by sidelux** [comment]
I think yes ;)

**Comment by danielperez9430** [comment]
I have a question. Example I ban a person, then I use /unban to remove the ban. But if that person is inside the group and is not banned by using the command /unban the banea. I leave the code:

```
bot.onText(/^\/unban/, function(message) {
	if (message.reply_to_message == undefined){
		return;
	}
	var username = message.reply_to_message.from.username;
	var userid = message.reply_to_message.from.id;
	bot.getChatMember(message.chat.id, message.from.id).then(function(data) {
		if ((data.status == "creator") || (data.status == "administrator")){
			bot.unbanChatMember(message.chat.id, userid).then(result => {
				bot.sendMessage(message.chat.id, message.from.first_name + " has been unbaned!");
			});
		}
	});
});
```

Could you tell me how it can be solved? And if it is an insure?

**Comment by DestroyerIV** [comment]
@danielperez9430 we agree completely, in my case with the same code, using / unban, ejects the user, withdraws the ban and allows him to enter the group again
