### ISSUE TITLE
how to print of getMe output to chat

### ISSUE THREAD

**Issue by sarih** [yagop/node-telegram-bot-api#447]
I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

> Question
how to print of getme output to chat?

my code : 
const TelegramBot = require('node-telegram-bot-api');
const token = 'Token';

const bot = new TelegramBot(token, {polling: true});

bot.onText(/\/echo/, (msg) => {
  bot.getMe().then(console.log);

});

**Comment by CapacitorSet** [comment]
```
const TelegramBot = require('node-telegram-bot-api');
const token = 'Token';

const bot = new TelegramBot(token, {polling: true});

bot.onText(//echo/, (msg) => {
    bot.getMe().then((me) => {
        console.log(me);
    });
});
```

**Comment by sarih** [comment]
@CapacitorSet
your and my code only print it in console not show this to user

**Comment by CapacitorSet** [comment]
Replace `console.log(me)` with `bot.sendMessage(msg.chat.id, JSON.stringify(me))`.

**Comment by sarih** [comment]
thank you 👍 
can i have your telegram id?
