### ISSUE TITLE
Message error 

### ISSUE THREAD

**Issue by kirillrybin** [yagop/node-telegram-bot-api#45]
With 1st sample from readme.md
![Error om message](http://i.imgur.com/1S4yzKK.png)

**Comment by yagop** [comment]
Take a look on the example, when a message arrives, it will sends an image called `cats.png`
```
// Any kind of message
bot.on('message', function (msg) {
  var chatId = msg.chat.id;
  // photo can be: a file path, a stream or a Telegram file_id
  var photo = 'cats.png';
  bot.sendPhoto(chatId, photo, {caption: 'Lovely kittens'});
});
```
If it doesn't exits it will fail

**Comment by GochoMugo** [comment]
This has been fixed by replacing it with a simpler example (commit 75d940c473c6ec252ee24ba4a788ecf458227a68)!

Thanks @kirillrybin for your interest in this library! :+1:
