### ISSUE TITLE
Temporary ban (kickChatMember until_date)

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#454]
Hi,
there is a way to temporary ban a user from specific chat?
As described in https://core.telegram.org/bots/api#kickchatmember for until_date parameter.

Thanks a lot!

**Comment by hootsy** [comment]
I'm also interested

**Comment by DestroyerIV** [comment]
Another interested here

**Comment by GochoMugo** [comment]
**v0.30.0** supports specifying additional parameters for [TelegramBot#kickChatMember()](https://github.com/yagop/node-telegram-bot-api/blob/v0.30.0/doc/api.md#TelegramBot+kickChatMember). For example,

```js
const ms = require("ms");

bot.kickChatMember(chatId, userId, {
    until_date: Date.now() + ms("7 days"),
}); 
```

**Comment by sidelux** [comment]
Perfect! Thanks!

**Comment by sidelux** [comment]
@GochoMugo 
sorry but after lots of tests your example seems does not work :(
It ban successfully but until 'forever' instead of one week.

How can i fix that?

`bot.kickChatMember(message.chat.id, message.reply_to_message.from.id, {until_date: Date.now() + ms("1m")}).then(function (result) {
    console.log("ok");
});`

**Comment by sidelux** [comment]
Ok! Solved :D
_until_date: Date.now() + ms("7 days")_ return unix in milliseconds, but is a mistake.
Telegram api needs "unix time" but not in ms, so it can be fixed with:
`until_date: Math.round((Date.now() + ms("7 days"))/1000)`

This issue can be closed now.

**Comment by DestroyerIV** [comment]
in my case, however much you add the line you mention, there is no way to keep the restriction for X days

This is my code:

```
if (msg.chat.type.toString().toLowerCase()=="supergroup"){
	if (msg.reply_to_message.from.username == undefined){
		bot.getChatMember(msg.chat.id, msg.from.id).then(function(data) {
	if ((data.status == "creator") || (data.status == "administrator")){
			bot.kickChatMember(msg.chat.id, userid, {until_date: Math.round((Date.now() + ms(1523059200))/1000)}).then(function(result){
				bot.deleteMessage(chatId, messageId);
				bot.sendMessage(msg.chat.id, firstname + " has been banned")
	})}
		})
	}
}
```
Time based in Unix
`{until_date: Math.round((Date.now() + ms(1523059200))/1000)})`

**Comment by DestroyerIV** [comment]
I still give polling error

**Comment by sidelux** [comment]
Debug with:
```
bot.on('polling_error', function(error) {
	console.log(error);
});
```

**Comment by DestroyerIV** [comment]
It works, is it possible to store the blocking time in buttons?

Thanks in advance. Great Job

**Comment by sidelux** [comment]
It's a bit complicated but you can save in a database then get whenever you need.

**Comment by DestroyerIV** [comment]
Could you dispense with the database and store it in a JSON?
