### ISSUE TITLE
Hide 'deprecation of cancellation promises' message

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#459]
Hi, from today update every reload my bot i see this message:

Tue, 14 Nov 2017 14:05:53 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:571:32

There is a way to hide? There is only a notice i think, so...

**Comment by GochoMugo** [comment]
As documented [here (issue #319)](https://github.com/yagop/node-telegram-bot-api/issues/319#issuecomment-324963294), you may use process environment variable `NTBA_FIX_319` to
fix the issue (and consequently hide the  deprecation message).
