### ISSUE TITLE
How to send HTML tags on messages

### ISSUE THREAD

**Issue by boanergepro** [yagop/node-telegram-bot-api#460]
Hola necesito enviar un mensage un poco largo.
pero quiero enviarlo formateado a html.! ya que intento añadir etiquetas html y no son interpretadas.!
Que puedo hacer.?

**Comment by GochoMugo** [comment]
Please use English.

**Comment by boanergepro** [comment]
Hello, I need to send a long message.
but I want to send it formatted to html.! since I try to add html tags and they are not interpreted.!
What I can do.?

**Comment by yagop** [comment]
Use [sendMessage](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/api.md#telegrambotsendmessagechatid-text-options--promise) with `parse_mode` as `html`. Only some tags are valid: https://core.telegram.org/bots/api#formatting-options

**Comment by boanergepro** [comment]
Gracias.
