### ISSUE TITLE
How to export invitation link?

### ISSUE THREAD

**Issue by DestroyerIV** [yagop/node-telegram-bot-api#467]
I've been trying for days to get the group link and print it so that other users can share it without I exist.

All the attempts ended with this message:
This is the group's link: undefined

I show you the code that I have established for this function, but I need help:

bot.onText(/\!link/, (msg) => {
var inviteLink = msg.chat.invite_link;
var chatId = msg.chat.id;
bot.exportChatInviteLink(chatId, inviteLink)
bot.sendMessage(chatId, "This is the group's link: " + inviteLink)
})

Any ideas? Thanks in advance

**Comment by NexKo** [comment]
hi. I have a problem with exportChatInviteLink. 
my code: 
```javascript
    bot.onText(/\/link/, (msg) => {
        const chatid = msg.chat.id
        var link = bot.exportChatInviteLink(chatid)
        bot.sendMessage(chatid, "il link della chat è: " + link)
    })
```
no log error and the bot send this message in chat:
il link della chat è: function String() { [native code] }

I have seen the documentation, looked for other issues on this, tried with https://github.com/yagop/node-telegram-bot-api/issues/387#issue-246489855 but I can't solve

**Comment by alexandercerutti** [comment]
@NexKo lol, Italian mixed to English, I love this 😂.
Please note that all bot-provided interfaces, return a Promise. So you have to use them like this:

```javascript
bot.onText(/\/link/, (msg) => {
        const chatid = msg.chat.id;
        bot.exportChatInviteLink(chatid)
            .then((link) => {
                bot.sendMessage(chatid, "il link della chat è: " + link);
            });
});
```

Or using async/await:

```javascript
bot.onText(/\/link/, async (msg) => {
        const chatid = msg.chat.id;
        var link = await bot.exportChatInviteLink(chatid);
        bot.sendMessage(chatid, "il link della chat è: " + link);
    })
```
