### ISSUE TITLE
Sending images with captions

### ISSUE THREAD

**Issue by Saeed-Ataee** [yagop/node-telegram-bot-api#469]
I am going to send some images with caption to users.

first I used this

`bot.sendPhoto({
                chat_id: this.chatId,
                caption: 'This is my test image',
                photo: img //replace your image url here
            });`

no image sent and I got this error : 

> Unhandled rejection Error: ETELEGRAM: 400 Bad Request: there is no photo in the request

then i used this:
`bot.sendPhoto(this.chat_id, img);`
it worked and sent image, but i can't send caption.
is there any way?

**Comment by saeedhei** [comment]
You can use photo link or ID.            
`bot.sendPhoto(msg.chat.id, 'AgADBAADQ6oxG1OMuVNqzZRzqjvhuJET4xkABNRI8HYrlUEu2YwDAAEC', { caption: "Hi" });`

**Comment by Saeed-Ataee** [comment]
thanks for fast and good replication. it worked <3
