### ISSUE TITLE
Stable status - colorful deprecation?

### ISSUE THREAD

**Issue by Phoscur** [yagop/node-telegram-bot-api#474]
> Question

After reading the issue #319 , I still don't understand why I can't disable the colorful deprecation warning about promise cancellation. It's always there, conditionless?! Wasn't able to turn it off.
Which version would be considered more stable without this deprecation?

Just switched from node-telegram-bot to node-telegram-bot-api, just to notice I can't get rid of the  deprecation warning on startup, going to switch to Telegraf now - unsure if it's actually better.

**Comment by sidelux** [comment]
At first line:
`process.env["NTBA_FIX_319"] = 1;`
