### ISSUE TITLE
Need help, error

### ISSUE THREAD

**Issue by Osiris124** [yagop/node-telegram-bot-api#476]
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:660:30

**Comment by sidelux** [comment]
Add this line in top of js file.

`process.env["NTBA_FIX_319"] = 1;`

**Comment by Grenguar** [comment]
@sidelux Thank you so much!

**Comment by CodingDevHub** [comment]
You mean this file? module.js

**Comment by sidelux** [comment]
In your js file (where you have coded your bot).

**Comment by daletfrehley** [comment]
> Add this line in top of js file.
> 
> `process.env["NTBA_FIX_319"] = 1;`

it's works , thanks so much !!!!!!!!!

**Comment by alexandercerutti** [comment]
@kamikazechaser what about closing and locking this discussion?

**Comment by kamikazechaser** [comment]
@alexandercerutti Yeah I think all question issues should be closed asap otherwise this repo may became another Stackoverflow.
