### ISSUE TITLE
on message not call if i send message from https://api.telegram.org/file/bot<token>/sendMessage

### ISSUE THREAD

**Issue by derakhshanfar** [yagop/node-telegram-bot-api#479]
hi guys.
why when i send message from URL like (_https://api.telegram.org/file/bot<token>/sendMessage_) the _message_ event not call?

**Comment by sidelux** [comment]
The bot.on('message') function is called when bot _receive_ a message, not when _send_.

**Comment by derakhshanfar** [comment]
@sidelux thanks for response but do you know how can i understand when somebody called sendMessage api?
