### ISSUE TITLE
[Question] Bold text

### ISSUE THREAD

**Issue by zavoluk** [yagop/node-telegram-bot-api#480]
Hi there!
I have a code like:

bot.sendMessage(number,
  'Title ' + TitleFromApi
);

Is there a way to make TitleFromApi bold or italic? Not all message, only variables.

**Comment by saeedhei** [comment]
Hellow @zavoluk           

```bot.sendMessage(msg.chat.id, `*${TitleBold}*, NormalText😉`, {parse_mode: 'Markdown'});```        

Can This be Closed?

**Comment by zavoluk** [comment]
Yes. Thx a lot!
