### ISSUE TITLE
get and save user_id

### ISSUE THREAD

**Issue by sarih** [yagop/node-telegram-bot-api#481]
hi i want get and save user_id in redis or json
can anyone give me a sample code?
tnx

**Comment by saeedhei** [comment]
Hi

```
// Putting in Redis
client.set("foo",[{id : 1}]);

// Getting from Redis
client.get("foo", function(err, reply){
   console.log(reply); 
});
```

**Comment by sarih** [comment]
tnx
but i want when someone joined to bot save informition from user
agar alaghe dari be chandta az soalam javab bd in id telegramame @sarih

**Comment by saeedhei** [comment]
That is very easy You Should get user Id and put that in redis, in you /start block, `{id: msg.chat.id}`

**Comment by mehranrasulian** [comment]
@saeedhei but a user can enter the `/start` as many times as they want. So do you think weather there is a better solution or not?

**Comment by saeedhei** [comment]
No problem, You Can Check if user is exist  in your db, Then don't need to save, just with if condition.        

Can this be Closed?

**Comment by sarih** [comment]
@saeedhei another qus
when i use this code:
`bot.onText(/\/start/, (msg) => {

  redisClient.set("user",msg.chat.id, function(err,reply){
    console.log(err);
    console.log(reply);
  });
  redisClient.get("user", function(err,reply) {
    console.log(err);
    console.log(reply);
  });

    bot.sendMessage(msg.chat.id, `wlc to bot`);
});
`
replace in redis with new user id and last user id is destroyd
after this i close this issues

**Comment by saeedhei** [comment]
No no that was an example to store, you Should Check redis db documents for Store each user id unique.        
Just a simple search.

**Comment by mehranrasulian** [comment]
@saeedhei Yeah, there's seems no better way for that. So the `new_chat_members` is for when a user joins a group where the bot manages it,  not the bot itself.
No problem to close it.

**Comment by sarih** [comment]
@saeedhei if i found that after search dont asked from u
but tnx and close this issues
