### ISSUE TITLE
Content-type deprecation message

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#482]
Hi,
how can i hide this message or fix the issue?
I can't see how to disable message in linked url. 

`node-telegram-bot-api deprecated In the future, content-type of files you send will default to "application/octet-stream". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether.`

Thanks!

**Comment by parrel** [comment]
Same here. Did you find a solution for this? Thanks.

**Comment by yagop** [comment]
See #350

**Comment by sidelux** [comment]
Yep! Solved with:
`process.env["NTBA_FIX_350"] = 1;`
At top of the file.
