### ISSUE TITLE
Error: deprecated Automatic enabling of cancellation of promises is deprecated

### ISSUE THREAD

**Issue by michael2517** [yagop/node-telegram-bot-api#484]
hello
i've received message like this:
Sat, 23 Dec 2017 13:20:55 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:660:30
I've got the same problem but I don't know how to solve it
I'm beginner so please help me to solve this problem

**Comment by saeedhei** [comment]
+1

**Comment by YuryKorovko** [comment]
Put this on the top of your js file `process.env["NTBA_FIX_319"] = 1;`.

**Comment by Cyberpunk2027** [comment]
I have this problem too, but I have module.js:662:30 instead module.js:660:30
Help me please!

**Comment by Cyberpunk2027** [comment]
When I writing `process.env["NTBA_FIX_319"] = 1;` it's writing on terminal "starting..." and nothing happens
Заколебался я короче, помогите(

**Comment by maxaquentin99** [comment]
Та же фишня

**Comment by proweb4all** [comment]
Error
Deprecated automatic enabling of cancellation of promises is deprecated...
![image](https://user-images.githubusercontent.com/33453060/41313963-ff72d080-6e93-11e8-9c77-beac28a845ee.png)
module/js:571:32
Что делать? Help! )

**Comment by CodingDevHub** [comment]
Приветы! Кто скажет где этот файл module.js

**Comment by Cyberpunk2027** [comment]
@CodingDevHub , через поиск поищи)))0) А так либо в директории нода, либо в папке с проектом где то

**Comment by danielperez9430** [comment]
You can remove this "message error(is not a real error is more like a warning)" if you add this line `process.env.NTBA_FIX_319 = 1;` before the declaration of the new TelegramBot(....)
