### ISSUE TITLE
Get the @ of the bot

### ISSUE THREAD

**Issue by dylanryan81** [yagop/node-telegram-bot-api#487]
Hello,

is there any way to actually get the @ of the bot?
I am asking because if have a /price command, and I wanna check if there was added a currency to the /price.

My way doing it:
`bot.onText(/\price/, (msg) => {
    if (msg.text == '/price' || msg.text == '/price@botname_bot') {    
        bot.sendMessage(msg.chat.id, 'You actually have to add a currency.');
    }
});`

But I don't want to change this manually, so maybe there is a way to getting the bots @?
Or maybe some of you guys have another solution?

**Comment by TiagoDanin** [comment]
See the API `getMe`  => [node-telegram-bot-api/doc/api.md](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#telegrambotgetmeoptions--promise)

Example:
```javascript
async function getMeInfoBot() {
	var data = await bot.getMe({})
	console.log(data)
	/*
	{
		id: 123456789,
		is_bot: true,
		first_name: 'mytestbot',
		username: 'mytestbot'
	}
	*/ 
}
getMeInfoBot()
```

**Comment by dylanryan81** [comment]
Oh, my bad. Thanks, @TiagoDanin!

This can be closed.
