### ISSUE TITLE
messageId type wrong

### ISSUE THREAD

**Issue by james58899** [yagop/node-telegram-bot-api#490]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

Type should be Number
https://github.com/yagop/node-telegram-bot-api/blob/119d892c3490e79c45f0e1d314fb41d3ecfb81cd/src/telegram.js#L1614-L1626
https://github.com/yagop/node-telegram-bot-api/blob/119d892c3490e79c45f0e1d314fb41d3ecfb81cd/src/telegram.js#L1077-L1092

**Comment by tryshchenko** [comment]
Verified, it's true.
You can find it in documentation https://core.telegram.org/bots/api#updating-messages
I have fixed it in PR https://github.com/yagop/node-telegram-bot-api/pull/491

**Comment by GochoMugo** [comment]
Fixed in PR #491.
