### ISSUE TITLE
sendMediaGroup method is not working properly

### ISSUE THREAD

**Issue by wwwaiser** [yagop/node-telegram-bot-api#492]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

I am trying to send media group (2-10 photos).
Important: Using only file_id as `media` parameter (all files/file_ids already exists at telegram side).
Expecting for success.

### Actual Behavior
`Error: EPARSE: Error parsing response: <head><title>504 Gateway Time-out</title></head> ...`
`

### Steps to reproduce the Behavior

`bot.sendMediaGroup(msg.chat.id, [{ type: 'photo', media: FILE_ID_1 }, { type: 'photo', media: FILE_ID_2 }]);`

after quick source review of `sendMediaGroup` method for my specific case I found empty `formData` object at `request` options. And it is a problem. We should not define formData option if we are not going to upload anything, because for some reason it is not working.

**Comment by hufan-akari** [comment]
I met the same problem when I send file from url.

related code:
```js
bot.sendMediaGroup(chat_id, [
  {
    type: "photo",
    media:
      "https://konachan.com/sample/1272a96e6c4cbeb3fcd0acc298875e3f/Konachan.com%20-%20259979%20sample.jpg"
  },
  {
    type: "photo",
    media:
      "https://konachan.com/sample/f725edd137a3e07e16cf659541f31013/Konachan.com%20-%20259961%20sample.jpg"
  }
]);
```

**Comment by Exlord** [comment]
I think This is a telegram bot api bug, I got the same error with my own library. The file captions are not working either.
