### ISSUE TITLE
How to realize question/answer sequence and feel object with data

### ISSUE THREAD

**Issue by ApayRus** [yagop/node-telegram-bot-api#497]
I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

> Question

Hello. Thanks for library. 
I'm stuck on the problem... I need to write sequence of questions/answers. Like: 

Enter your phone number
answer (phoneNumber)
Enter your address 
- answer (address)
Enter your issue 
- answer (issue)

And then I want to save answers to the db in object: `{ phoneNumber, address, issue }`

I don't like Force_replay way, because it looks like double all questions (first sends message, and then repeat it in "force_replay" attached message. 
Is there a  way to get all information from chat?

**Comment by sidelux** [comment]
Best way is store where user is in a db or file, so:

```
var user_part = "get this from db";

bot.on('message', function (message) {
    if (user_part == ""){
        // save phone number
        user_part = "address"; // save to db
        bot.sendMessage(message.chat.id, "Thanks! Now enter your address");
    }else if (user_part == "address"){
        // save address
        user_part = "issue"; // save to db
        bot.sendMessage(message.chat.id, "Thanks! Now enter your issue");
    }else if (user_part == "issue"){
        // save issue
        user_part = ""; // save to db
        bot.sendMessage(message.chat.id, "Thanks! Use /start to enter another issue");
    }
});

bot.onText(/^\/start/, function (message) {
    user_part = ""
    bot.sendMessage(message.chat.id, "Welcome! Please enter your number...");
});
```
