### ISSUE TITLE
There is no reply_to_message event

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [yagop/node-telegram-bot-api#498]
Hello.

This event does not work:

    bot.on(''reply_to_message', (msg) => {
        // do something
    }) 

[This method](https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L576) does not emit anything that is connected to `reply_to_message` event.

@yagop Is it made by design or will you accept pull request?

**Comment by sidelux** [comment]
You must listen msg.reply_to_message and test if is undefined.

```
bot.on('message', function (message) {
    // code...
    if (message.reply_to_message != undefined)
        console.log(message.reply_to_message);
});
```

**Comment by SuperMasterBlasterLaser** [comment]
@sidelux Yes, I know. Is it good idea to separate this to different event?

**Comment by sidelux** [comment]
For readability i suggest to use the same event
