### ISSUE TITLE
Minimize data consumption

### ISSUE THREAD

**Issue by anthoferd** [yagop/node-telegram-bot-api#500]
> Question

Hello,

I want to use the node-telegram-bot-api on a mobile router (2G/3G/4G) and it is important to minimize the data consumption. When I use the default polling option it takes some megabytes per day and this is too much. On my iPhone the telegram app take only some megabytes per month. 

How is it possible to reduce the data consumption?

Thanks!

**Comment by MikaelMello** [comment]
My guess is that you should change to long polling, here are some resources:

[Use this method to receive incoming updates using long polling](https://core.telegram.org/bots/api#getupdates)
[Wikipedia on Long Polling](http://en.wikipedia.org/wiki/Push_technology#Long_polling)
[This package's reference regarding long polling](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#new_TelegramBot_new)

**Comment by anthoferd** [comment]
Thank you. I will try this
