### ISSUE TITLE
Text styling

### ISSUE THREAD

**Issue by mbrammer** [yagop/node-telegram-bot-api#502]
> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

In Telegram you can style text like this `**bold text**` or `__italic text__`.
The node-telegram-bot-api seems not to support this.
On the other hand, Emojis are working.

**Comment by saeedhei** [comment]
Use ```parse_mode: 'Markdown',``` 👍

**Comment by drGOD** [comment]
As it mention in telegram documentation, you just need to add `parse_mode` to options. As in the example below: 
`bot.onText(/\/start/, function onStart(msg) {
  const opts = {
    reply_markup:{
      keyboard: [
        ['FAQ'],
        ['Buy']
      ]
    },
    parse_mode: 'Markdown'
  };
  bot.sendMessage(msg.from.id, "*You are welcome!*\nWe would like to introduce you our new [product](https://xxx.yyy/zzz)", opts);
});`

**Comment by mbrammer** [comment]
Perfect! Will try this today. Thank you!
