### ISSUE TITLE
Listen to all messages.

### ISSUE THREAD

**Issue by airbone42** [yagop/node-telegram-bot-api#503]
I tried to listen to all messages in a group to generate some statistics from our group.

Therefore I implemented following super easy code snippet:

```
bot.onText(/(.+)/, (msg, match) => {
  console.log(msg);

});

// Listen for any kind of message. There are different kinds of
// messages.
bot.on('message', (msg) => {
  console.log(msg);
 
});
```

Unforutnately, even when listening on message and having a regexp which should match all messages the console.log in both cases is only triggered then the messages starts with a `/`. Is there any way to actually listen to all messages not just commands?

**Comment by steamhammer** [comment]
https://core.telegram.org/bots#privacy-mode
https://core.telegram.org/bots/faq#what-messages-will-my-bot-get

You definitely need to enable "privacy" option in your bot. It could be done via BotFather settings update for particular bot.

**Comment by airbone42** [comment]
Thanks!

**Comment by NavruzbekNoraliev** [comment]
How to delete the message that's sent from bot by using bot.sendMessage(id, "message") i know how to use deleteMessage() but i can't get the id of message that's sent by bot
