### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kapanov** [yagop/node-telegram-bot-api#505]
Hi there!
Guys, how i can saw how many people use my telegram bot? Thanks

**Comment by saeedhei** [comment]
You Should Store your users in a Database or when a user started your bot, you Can get his id and forward to your temporarily log Channel.
But better way is a db.

**Comment by Kapanov** [comment]
Please, help me with database or other method. ='(

**Comment by david1602** [comment]
Is it just about the amount of people who use your bot? Or do you also want to store other informationß
Do you need to make this persistent or not?

**Comment by Kapanov** [comment]
@david1602 
who use my bot only

**Comment by david1602** [comment]
So you care about *who* now? What do you want to save? Their name? Their ID?
There are so many questions to ask.

**Comment by Kapanov** [comment]
@david1602 
i think first_name enough. I just want to know how many people use my bot, for statistic.

**Comment by david1602** [comment]
You have multiple ways of doing that. If you wanted to keep it simple, you could just write the data to a csv file.

In that example, I'm using a `data.csv` file containing the following content:
```
1234;David
5412412;Anton
```

Upon starting your script, you could load the file by doing this:
```javascript
const fs = require('fs');

if (!fs.existsSync('data.csv'))
    fs.writeFileSync('data.csv', '');

const data = fs.readFileSync('data.csv', {encoding: 'utf-8'}) // Read file
                .split('\n') // Split by newline
                .reduce( (acc, current) => {
                    const s = current.split(';');
                    acc[s[0]] = s[1];
                    return acc;
                }, {});
```

And then data would be your object containing your user data: `{ '1234': 'David', '5412412': 'Anton' }`.

Upon receiving a message, you could do:

```javascript
const writeToData = (id, name) => {
    data[id] = name;
    fs.appendFileSync('data.csv', `${id};${name}`)
}

bot.on('message', msg => {
    const {id, first_name} = msg.from;

    if (!data[id])
        writeToData(id, first_name);

    // ...
});
```

And your CSV file would always contain all the data. This isn't as extensive as a database and obviously limits your in your querying capabilities, but in my opinion this should work. It's just something I hacked together quick, you'll of course have to adjust it to your needs. Feel free to ask further questions.

**Comment by Kapanov** [comment]
@david1602 
 Thanks dude!

**Comment by david1602** [comment]
Hope that helps!
