### ISSUE TITLE
Problem with sending a MP4 video file as a VideoNote to a channel by bot

### ISSUE THREAD

**Issue by PakanAngel** [yagop/node-telegram-bot-api#506]
I am trying to make a bot that get .mp4 videos and send them as video-note to a specific chat or channel.   Ho do I have to proceed?
I realized that sendVideoNote needs a stream to a .mp4 file, so I converted my uploaded file to a stream and then passed it to sendVideoNote, but get some errors.
This my code:
```
if(msg.video != null)
    {
        bot.getFile(msg.video.file_id)
        .then(function (video){
            videoPath= "https://api.telegram.org/file/bot" + TOKEN + "/" + video.file_path;
            console.log("Source File path is: ", videoPath);
            videoStream = fs.createReadStream(videoPath);
            console.log("videoStream is: ", videoStream );
            bot.sendVideoNote(chatID,videoStream);
        })
    }
```
What is wrong with my code?

**Comment by sidelux** [comment]
Try to send with file_id, is supported.

```
if (msg.video != undefined){
    bot.sendVideoNote(chatID, msg.video.file_id);
}
```

By the way, can you post error log?
