### ISSUE TITLE
how to send and recieve messages in order?(Like a form in a webpage)

### ISSUE THREAD

**Issue by ars2062** [yagop/node-telegram-bot-api#507]
> Question
So I wonder how can i get information from a couple of users about address and phone number.
but i don't know how to get them and save them in order.
i want something like this:
BotMessage : Please Set Your Address  
UserMessage : User's address
BotMessage : Your Address Is Set.
BotMessage : Please Set Your Phone Number
UserMessage : User's Phone Number
BotMessage : Your Phone Number Is Set.
and it should manage multiple users

**Comment by david1602** [comment]
You'd have to store the results per user and by the results, you could determine which question to ask or message to send

**Comment by ars2062** [comment]
thanks for your comment, David but i want my bot to have custom messages and every message that bot can't recognize is a custom message to application in this way that you mentioned i can't have that.

**Comment by david1602** [comment]
I'm not sure what you mean by that. The only way to do what you want is to do it in a specific order. And you need to define that order in one way or another.
