### ISSUE TITLE
sendAudio title and performer

### ISSUE THREAD

**Issue by supercyanhero** [yagop/node-telegram-bot-api#508]
I tried to send audio with url

bot.sendAudio(chatId, url, {
	performer: 'test',
	title: 'test2'
	})

but audio doesn't use it. It's name is the name of downloaded file
What can I do?

**Comment by danielperez9430** [comment]
> d even with other files, same error.

You can **only replace the metadata from the files upload from your computer**, the telegram bot api internally (**Telegram** servers) **ignore** your settings if you upload a file from a **url**.

For resolve this problem you can download the file and pass to method `sendAudio`
