### ISSUE TITLE
Calling a function from out of index via javascript

### ISSUE THREAD

**Issue by saeedhei** [yagop/node-telegram-bot-api#511]
I have 2 page, 1 index page and 2 function page, In index page I have `msg` a TelegramBot parameter.         
How Should I use `msg.chat.id` in my Function page and then use That Function in index page?  

**index Page:**

```js
    const uid = require('./functions');

    bot.onText(/\/start/, (msg) => {
      const opts = {
        reply_markup: JSON.stringify({
          keyboard: StartKeyboard,
          resize_keyboard: true,
          one_time_keyboard: true,
        }),
      };
      bot.sendMessage(msg.chat.id, 'Hello World', opts);
    });
```
**Function Page:**  

```js
    function user() {
      const userId = `${msg.chat.id}`;
      console.log(userId);
    }
    module.exports = uid; 
```

  
**Error in Function Page:**  
> [eslint] 'msg' is not defined. (no-undef)

**Comment by droidmanspace** [comment]
you must pass msg  from index page to function page. In your function page, you are trying to `module.exports = uid; `  but there is  no function named uuid to export.

**Comment by saeedhei** [comment]
How Can I make msg global?

**Comment by droidmanspace** [comment]
U can't make msg as global variable . 
 `bot.onText(/\/start/, (msg) => {
//logic
}`
msg variable is only accessible on every incoming message to the bot . Actually can you please explain your purpose ?

**Comment by saeedhei** [comment]
I want to make a token maker function and add that  in /start ,

**Comment by saeedhei** [comment]
We Can't because that is Static
