### ISSUE TITLE
How to use this framework as continous notification bot ?

### ISSUE THREAD

**Issue by droidmanspace** [yagop/node-telegram-bot-api#512]
I would like to build a bot which can send notification as per values of some real-time API data.Can I use this framework?

**Comment by sidelux** [comment]
You can make a loop or a request every n seconds, parse api then send message in telegram.
This framework use Node Js, so you can do everything with api or similar.

**Comment by droidmanspace** [comment]
Thats not a good programming practice. Because node.js  is baaed a event loop. So multiple calls will make a queuing problem.
