### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by bjesus** [yagop/node-telegram-bot-api#52]
Hi!
I'm running two bots on the smallest droplet on DigitalOcean (512MB), and I'm hitting 100% memory usage almost constantly. I noticed that even just running the following code causes the node process to start consuming more and more memory:

```
var TelegramBot = require('node-telegram-bot-api');
var nconf = require('nconf');
nconf.argv().env().file({ file: 'config.json' });
var token = nconf.get('bot_token');
var bot = new TelegramBot(token, {polling: true});
```

After initializing `bot` in the fifth line - the process's memory usage starts to grow and never stops.

I'm not sure how to debug it further. Any ideas?

I tried limiting node with `--max_old_space_size` but it doesn't seem to work (same behavior). Both bots are just rarely used, and anyhow it seems like the leak starts before my own code is even reached.

**Comment by crisbal** [comment]
I am interested in this too. I also notice a small but constant memory usage increase.

**Comment by yagop** [comment]
The leak might be on https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegramPolling.js#L50 there is an infinite loop which I should fix ...

**Comment by crisbal** [comment]
Could this be fixed by replacing the timeout with a set interval?

**Comment by yagop** [comment]
Could be if its called outside. The matter of using an interval is that the function could be called before the previously one haven't finished. That behavior must be avoided.

**Comment by yagop** [comment]
> I tried limiting node with --max_old_space_size but it doesn't seem to work (same behavior). Both bots are just rarely used, and anyhow it seems like the leak starts before my own code is even reached.

Seems the option is `--max-old-space-size`.

Which NodeJS version are you using? Seems v4 have improved in memory usage. I changed the `_polling` method a bit, seems the memory still increasing in node v0.12.4 but slowly and hope it converge to smaller number. With v4.2.4 increases till 50MB and stops.

**Comment by bjesus** [comment]
I tried both `--max-old-space-size` and `--max_old_space_size` before, none seemed to work.

Anyhow, I just upgraded Node.JS's version to 5.4 (was running 0.10.25...) and upgraded node-telegram-bot-api, and the problem seem to be gone. it's been 24 hours I can't recognize no signal for the leak.

Thank you!

**Comment by GochoMugo** [comment]
With the recent changes, I believe this issue might be fixed. We are also running bots using this library, and we do **not** have any memleak problems.

If this issue still persists for you (with the new versions, of course), please provide us with more information, such as, the average number of users your bot is serving, RAM size in your server, etc.

Otherwise, am marking this issue as **stale** to be closed at a later date, should **no** activity be seen in this thread!

**Comment by GochoMugo** [comment]
Issue went too stale...
