### ISSUE TITLE
how can send message after webpage complete

### ISSUE THREAD

**Issue by azizkhani** [yagop/node-telegram-bot-api#524]
I have telegram bot that make payment with webpage ,customer click on inline_keyboard and open webpage with url and finish payment . 
I want send message to bot after page close ? 
I don't  know my question is clear or not . my backend is implement with java and i am run bot using Botpess . I want after payment verified , send message to customer in bot

**Comment by sidelux** [comment]
Detect when webpage is **closed** is not possibile.

At least you can detect when payment is complete and send message to bot.
I think you can simply setup a mini-bot on payment page that only send a message when it completed so: main bot send payment data and message.from.id to payment page -> user end payment -> that page send a message to message.from.id with 'payment complete!'.

PS Why not use telegram payments instead?

**Comment by azizkhani** [comment]
can i do that  with webhook?

**Comment by sidelux** [comment]
Why not, same method as long polling i think

**Comment by azizkhani** [comment]
i read some document about Webhook in telegram , but i do not know how can use it in this use case.can you describe how can i do that?

**Comment by sidelux** [comment]
You are talking about Telegram Payments? Or an example to detect complete payment etc..?

**Comment by azizkhani** [comment]
detect complete payment etc, i dont use telegram payment

**Comment by sidelux** [comment]
So i tell you a method that i'd use.

**in js bot**
```
var customUrl = "http://www.website.com/pay.php?amount=10&userId=" + message.from.id;
bot.sendMessage(message.chat.id, "Click Pay to Pay ;)", {
	parse_mode: 'HTML',
	disable_web_page_preview: true,
	reply_markup: {
		inline_keyboard: [[{text: "Pay", url: customUrl}]];
	}
});
```
**in php page** with [php-telegram-bot](https://github.com/php-telegram-bot/)
```
$amount = $_GET["amount"];
$userId = $_GET["userId"];

// payment...

if ($payment == "completed"){
	// bot connect **without** handleGetUpdates, otherwise main bot conflict with getUpdates...
	$result = Request::sendMessage(['chat_id' => $userId, 'text' => 'Payment of ' . $amount . ' completed!']);
	// bot disconnect
}
```

This is a draft but make an idea.

**Comment by saeedhei** [comment]
Hi @sidelux  , I want to run php-telegram-bot in a a cpanel host, First I download via composer and uploaded to cpanel but I'm Getting This Error:
```
Warning: require_once(/home3/apppresserer/public_html/example-bot-master/vendor/autoload.php): failed to open stream: No such file or directory in /home3/apppresserer/public_html/example-bot-master/set.php on line 9

Fatal error: require_once(): Failed opening required '/home3/apppresserer/public_html/example-bot-master/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home3/apppresserer/public_html/example-bot-master/set.php on line 9
```

**Comment by sidelux** [comment]
@saeedhei follow this instructions: https://github.com/php-telegram-bot/core, anyway, check if there is a file called autoload.php in that directory, otherwise check file permission to read files and dirs.
