### ISSUE TITLE
Can a bot execute a slash command?

### ISSUE THREAD

**Issue by brianmituka** [yagop/node-telegram-bot-api#526]
I have a command /events. and I have a keyboard text: `RETURN TO EVENTS`, I want that if a user clicks this keyboard, the /events command is executed. but in my case it's not working. Here is the code:
```
bot.on("message", (msg) => {
    if(msg.text === 'RETURN TO EVENTS'){
        bot.sendMessage(msg.chat.id, "/events")
    }
})
```

**Comment by jobtorres** [comment]
Hi, how did you eventually solve this? I am trying to do exactly this and I don't know if it is the correct way or if there is a more accurate solution

**Comment by imdkbj** [comment]
Is something like this...

```
switch(msg.text){
	case ('/RETURN TO EVENTS'):
	case ('/events'):
		bot.sendMessage(msg.chat.id,'events msg');
		break;

	case ('xyz'):
		bot.sendMessage(msg.chat.id,'do something');
		break;
}
```
