### ISSUE TITLE
.setWebHook Only working without options

### ISSUE THREAD

**Issue by patrickdundas** [yagop/node-telegram-bot-api#530]
I am attempting to use WebHooks for my Telegram Bot. I have run into an interesting phenomenon where `.setWebHook()` only works if I do not supply options, even though I am using a self signed certificate. 

Here is my code that does not work:

```
const options = {
  webHook: {
    port: 443,
    key: '/telegram-sslcerts/MYDOMAIN/cert.key', // Path to file with PEM private key
    cert: '/telegram-sslcerts/MYDOMAIN/cert.pem' // Path to file with PEM certificate
  }
};

var TelegramBot = require('node-telegram-bot-api'),
// Be sure to replace YOUR_BOT_TOKEN with your actual bot token on this line.
telegram = new TelegramBot(serverConfig.key, options);

// This URL must route to the port set above (i.e. 443)
var webhookurl = 'https://DOMAIN/'+serverConfig.key;

// This informs the Telegram servers of the new webhook.
telegram.setWebHook(webhookurl, {
  certificate: options.webHook.cert,
});
```

And here is my code that does work - note that the difference is that I did not supply options to the function.

```
var TelegramBot = require('node-telegram-bot-api'),
// Be sure to replace YOUR_BOT_TOKEN with your actual bot token on this line.
telegram = new TelegramBot(serverConfig.key);

// This URL must route to the port set above (i.e. 443)
var webhookurl = ServerIP+'/'+serverConfig.key;

// This informs the Telegram servers of the new webhook.
telegram.setWebHook(webhookurl);
```

I am mainly wondering, why does my webhook work when I don't supply the certificate? Also why doesn't it work when I do supply the certificate? It seems like it should be the other way around, so I am pretty confused. The certificate is self signed with openssl from Let's Encrypt, and I do have a certificate installed via nginx on my node server for the domain that the webhook is applied to. Is that why this issue is arising?

**Comment by sidelux** [comment]
Add this lines at top:
```
process.on('uncaughtException', function (err) {
	console.error(err.stack);
});
process.on('unhandledRejection', function (reason, p) {
	console.log(reason.message);
});
```
So you can see specific error that happen and post it here.
