### ISSUE TITLE
How can I get Update object via setWebHook method?

### ISSUE THREAD

**Issue by alexanderyegioya** [yagop/node-telegram-bot-api#537]
Hello, i have a question about using setWebHook method. I setted up webhook via ngrok on 8443 port with 'https' url. Bot works. I want to get Update object(https://core.telegram.org/bots/api#update) and see it in my terminal. How can I do it? I saw many tutorials about telegram bots, but didn't found this decision. Thank you in advance!

**Comment by sidelux** [comment]
You are using this node module?
Anyway, this is the method you want i think.
```
bot.on('message', (msg) => {
  const chatId = msg.chat.id;

  // send a message to the chat acknowledging receipt of their message
  bot.sendMessage(chatId, 'Received your message');
});
```
