### ISSUE TITLE
deprecated Automatic enabling of cancellation of promises is deprecated.

### ISSUE THREAD

**Issue by Cyberpunk2027** [yagop/node-telegram-bot-api#540]
In the future, you will have to enable it yourself.
See yagop/node-telegram-bot-api#319. module.js:662:30

This code: process.env["NTBA_FIX_319"] = 1;. don't help me. Help me please!

**Comment by sidelux** [comment]
That code works, put it into very first line of your bot.

**Comment by Cyberpunk2027** [comment]
@sidelux I did it. But when I put it into top and written in terminal `npm run start` terminal show me "starting..." and nothing else... 
Or maybe I waited very little)

**Comment by saeedhei** [comment]
Temporarly Remove All code from your index.js and test with this Code:

```js
process.env.NTBA_FIX_319 = 1;

const TelegramBot = require('node-telegram-bot-api');

// replace the value below with the Telegram token you receive from @BotFather
const token = 'YOUR_TELEGRAM_BOT_TOKEN';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});

bot.on('message', (msg) => {
  const chatId = msg.chat.id;

  // send a message to the chat acknowledging receipt of their message
  bot.sendMessage(chatId, 'Received your message');
});
```

**Comment by mrdimaan** [comment]
@saeedhei  Thanks it helped me to remove that message

**Comment by saeedhei** [comment]
@mrdimaan Never mind,

@Cyberpunk2027 Can This be Closed?

**Comment by Cyberpunk2027** [comment]
Interesting, I have [polling error] in terminal, but in Telegram my bot reply me to command /start!
![default](https://user-images.githubusercontent.com/32849700/37436540-1a706260-27f1-11e8-8dee-eef9bbcca7d5.JPG)

**Comment by saeedhei** [comment]
@Cyberpunk2027 in @BotFather /revoke and make new token and check again.

**Comment by Rotimi-Best** [comment]
```process.env.NTBA_FIX_319 = 1```
I agree that this solves this problem. But can someone explain what the problem was in the first place and why does this specific line and no other line solves the problem?

**Comment by DmitryVengerov** [comment]
> @Cyberpunk2027 in BotFather /revoke and make new token and check again.

> `process.env.NTBA_FIX_319 = 1`
> I agree that this solves this problem. But can someone explain what the problem was in the first place and why does this specific line and no other line solves the problem?

1) i revoke bot in not father
2) make code on your example.
3) still have this problem on lib version ^0.30.0

**Comment by sidelux** [comment]
@Cyberpunk2027 replace:
`bot.on('message', (msg) =>`
with
`bot.on('message', function (msg) {`

**Comment by DmitryVengerov** [comment]
> bot.on('message', function (msg) {

still have polling_error even after generate new token

**Comment by Cyrill4505** [comment]
so, anybody else have same issue. Just i also change ny token into bot father, nothing help

**Comment by ReyFall** [comment]
yes, i have same issue to

**Comment by garyc2232** [comment]
still have the issue too

**Comment by rotimi-best** [comment]
> still have the issue too

1. Install this package `npm i dotenv`
2. Create a file called `.env` at the root of your project.
3. Add to that file this `NTBA_FIX_319=1`
4. Add to the top of your `index.js` file (or whatever file that contains you bot instance): `require('dotenv').config()`
5. Restart your bot.

So your code will look like

```js
require('dotenv').config();

const TelegramBot = require('node-telegram-bot-api');

// replace the value below with the Telegram token you receive from @BotFather
const token = 'YOUR_TELEGRAM_BOT_TOKEN';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});

bot.on('message', (msg) => {
  const chatId = msg.chat.id;

  // send a message to the chat acknowledging receipt of their message
  bot.sendMessage(chatId, 'Received your message');
});
```

**Comment by garyc2232** [comment]
@rotimi-best thx it works now.

What i did before is
```
const TelegramBot = require('node-telegram-bot-api'); 
process.env.NTBA_FIX_319 = 1; 
const bot = new TelegramBot(token, {polling: true});
```
but it should be

```
process.env.NTBA_FIX_319 = 1; // or require('dotenv').config();
// put the code above the import
const TelegramBot = require('node-telegram-bot-api'); 
const bot = new TelegramBot(token, {polling: true});
```
For those who still got the issue, you may try.

**Comment by brunoalfred** [comment]
There is a problem happening after even after adding 
```process.env.NTBA_FIX_319 = 1;```

at the top of the index.js file

**Comment by kamikazechaser** [comment]
This feature has been deprecated? @brunoalfred Any reason why you would want to override it?

**Comment by brunoalfred** [comment]
so how do I fix it because I am stack.

**Comment by masterbaco** [comment]
Hey guys, this line at the beginning of my program works and solve the issue, but can anyone explain please what it does to fix it? Will there be future problems..? 
process.env.NTBA_FIX_319 = 1;

**Comment by lordraw77** [comment]
> > still have the issue too
> 
> 1. Install this package `npm i dotenv`
> 2. Create a file called `.env` at the root of your project.
> 3. Add to that file this `NTBA_FIX_319=1`
> 4. Add to the top of your `index.js` file (or whatever file that contains you bot instance): `require('dotenv').config()`
> 5. Restart your bot.
> 
> So your code will look like
> 
> ```js
> require('dotenv').config();
> 
> const TelegramBot = require('node-telegram-bot-api');
> 
> // replace the value below with the Telegram token you receive from @BotFather
> const token = 'YOUR_TELEGRAM_BOT_TOKEN';
> 
> // Create a bot that uses 'polling' to fetch new updates
> const bot = new TelegramBot(token, {polling: true});
> 
> bot.on('message', (msg) => {
>   const chatId = msg.chat.id;
> 
>   // send a message to the chat acknowledging receipt of their message
>   bot.sendMessage(chatId, 'Received your message');
> });
> ```
work fine tnx

**Comment by huynguyencong** [comment]
I have this problem when using TypeScript:

```
this.bot.on('message', this.handleMessage);
```

Then the problem is fixed when I change it to:
```
this.bot.on('message', (msg) =>{
        this.handleMessage(msg)
});
```

**Comment by kozubskyi** [comment]
put `process.env.NTBA_FIX_319 = 1` into very first line - doesn't help, app always stays in 'starting...'
also tried to put `NTBA_FIX_319 = 1` into `.env` file and wrote `require('dotenv').config()` into very first line in `index.js` before `require('node-telegram-bot-api')` - also doesn't help, app still stays in 'starting...'

nothing helps - app always stays in 'starting...' and then crashes

**Comment by danielperez9430** [comment]
> put `process.env.NTBA_FIX_319 = 1` into very first line - doesn't help, app always stays in 'starting...'
> also tried to put `NTBA_FIX_319 = 1` into `.env` file and wrote `require('dotenv').config()` into very first line in `index.js` before `require('node-telegram-bot-api')` - also doesn't help, app still stays in 'starting...'
> 
> nothing helps - app always stays in 'starting...' and then crashes

Hi, in the next realease the problem of the promises will be eliminated. Since we will remove bluebird and use the native Nodejs promises.

About your problem, could you open a new issue and put the code you have written?

Because the message itself is just a warning, it does not cause the library to crash. So to be able to go deeper, put the version of Nodejs you are using and your code.

**Comment by kozubskyi** [comment]
When I run command "nodemon index.js" process becomes "[nodemon] starting 'node index.js'" and then switches to "... restarting ..." and then again (screen 1). My bot still works even in this endless starting process, but when I deployed my bot to Heroku bot crashed (screen 2).

<img width="1440" alt="vscode" src="https://user-images.githubusercontent.com/73562477/179385184-6cbe2aa4-4122-44ec-a112-eb0fe396720a.png">
<img width="1219" alt="Heroku" src="https://user-images.githubusercontent.com/73562477/179385536-87adc5ad-4c00-41fd-b80b-055ba25f13c9.png">

**Comment by danielperez9430** [comment]
> When I run command "nodemon index.js" process becomes "[nodemon] starting 'node index.js'" and then nothing changes (screen 1). My bot still works even in this endless starting process, but when I deployed code to Heroku it also trying endless starting process and after 1 minute crashes (screen 2). Node version 16.15.1.
> 
> <img width="1440" alt="vscode" src="https://user-images.githubusercontent.com/73562477/179386431-dcbd0fca-831d-42ed-b7da-d3200686ad4e.png">
> 
> <img width="1219" alt="Heroku" src="https://user-images.githubusercontent.com/73562477/179385536-87adc5ad-4c00-41fd-b80b-055ba25f13c9.png">

Hi, your problem is that you use Heroku with polling.

Since your bot does not respond to HTTP requests it should not be deployed as a web process. You need to deploy as a worker. And setup the webhook (https://github.com/yagop/node-telegram-bot-api/blob/master/examples/webhook/heroku.js).

Other option is search for other "hosting"  for your bot like https://railway.app/ of or others

**Comment by kozubskyi** [comment]
> > When I run command "nodemon index.js" process becomes "[nodemon] starting 'node index.js'" and then nothing changes (screen 1). My bot still works even in this endless starting process, but when I deployed code to Heroku it also trying endless starting process and after 1 minute crashes (screen 2). Node version 16.15.1.
> > <img alt="vscode" width="1440" src="https://user-images.githubusercontent.com/73562477/179386431-dcbd0fca-831d-42ed-b7da-d3200686ad4e.png">
> > <img alt="Heroku" width="1219" src="https://user-images.githubusercontent.com/73562477/179385536-87adc5ad-4c00-41fd-b80b-055ba25f13c9.png">
> 
> Hi, your problem is that you use Heroku with polling.
> 
> Since your bot does not respond to HTTP requests it should not be deployed as a web process. You need to deploy as a worker. And setup the webhook (https://github.com/yagop/node-telegram-bot-api/blob/master/examples/webhook/heroku.js).
> 
> Other option is search for other "hosting" for your bot like https://railway.app/ of or others

Thanks, yes. I added Procfile to my project root with code `worker: npm start` and changed Dyno at Heroku and it works.

**Comment by ManiShankar09** [comment]
> Temporarly Remove All code from your index.js and test with this Code:
> 
> ```js
> process.env.NTBA_FIX_319 = 1;
> 
> const TelegramBot = require('node-telegram-bot-api');
> 
> // replace the value below with the Telegram token you receive from @BotFather
> const token = 'YOUR_TELEGRAM_BOT_TOKEN';
> 
> // Create a bot that uses 'polling' to fetch new updates
> const bot = new TelegramBot(token, {polling: true});
> 
> bot.on('message', (msg) => {
>   const chatId = msg.chat.id;
> 
>   // send a message to the chat acknowledging receipt of their message
>   bot.sendMessage(chatId, 'Received your message');
> });
> ```


This is the basic setup for Telegram Bot. EveryOne can excute this..

**Comment by danielperez9430** [comment]
> > Temporarly Remove All code from your index.js and test with this Code:
> > 
> > ```js
> > process.env.NTBA_FIX_319 = 1;
> > 
> > const TelegramBot = require('node-telegram-bot-api');
> > 
> > // replace the value below with the Telegram token you receive from @BotFather
> > const token = 'YOUR_TELEGRAM_BOT_TOKEN';
> > 
> > // Create a bot that uses 'polling' to fetch new updates
> > const bot = new TelegramBot(token, {polling: true});
> > 
> > bot.on('message', (msg) => {
> >   const chatId = msg.chat.id;
> > 
> >   // send a message to the chat acknowledging receipt of their message
> >   bot.sendMessage(chatId, 'Received your message');
> > });
> > ```
> 
> 
> This is the basic setup for Telegram Bot. EveryOne can excute this..
> 
> 

You now dont need to use process.env fix. Version 0.59.0 is now publish in npm and get rid of the problem by internally using native promises.
