### ISSUE TITLE
ReplyKeyboardMarkup selective boolean doesn't seem to be working

### ISSUE THREAD

**Issue by EmilianoTalamo** [yagop/node-telegram-bot-api#541]
### Expected Behavior

I have the following code

```
bot.onText(/regexp/, (msg, match) =>
{
	var options = {
		"reply_to_message_id" : msg.message_id,
		"selective" : true,
		"reply_markup": JSON.stringify({
			"keyboard": keyboardArray
		})
	};
	bot.sendMessage(msg.chat.id, "Some text", options);
});
```

Whenever the regexp matches, a custom keyboard should only show up **only for the person who invoked the command** (as the selective boolean indicates).

> Use this parameter if you want to show the keyboard to specific users only. Targets: 1) users that are @mentioned in the text of the Message object; 2) if the bot's message is a reply (has reply_to_message_id), sender of the original message.

### Actual Behavior

The custom keyboard shows up for everyone in the group.

### Steps to reproduce the Behavior

Get a bot with a custom keyboard and selective on true to a group, and send the command that it makes it appear. Everyone in the group will see it.

**Comment by sidelux** [comment]
If your bot print a keyboard in a **group**, the keyboard will show to everyone, in private it works fine.
I don't think there is a way to avoid it.

**Comment by EmilianoTalamo** [comment]
@sidelux Well, that's not the intended behavior If the "selective" boolean is on true.

**Comment by planecore** [comment]
This issue is still present.

**Comment by kamikazechaser** [comment]
Use `msg.user.id` instead on `msg.chat.id`
