### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [yagop/node-telegram-bot-api#542]
How to exit the survey?

`bot.onText(/\/(.+)/, function (msg, match) {`
`bot.sendMessage(chat_id, 'Ok');`
`//exit`
` });`

**Comment by sidelux** [comment]
You can't.
You must play with onText to catch only where you need to.

**Comment by Tecnonucleous** [comment]
hi @saeedhei  
First Question; The bot with the user join or left the bot no send message and returnt error: [polling_error] {}

Code:

```
bot.on("new_chat_member", function(message) {
   bot.sendMessage(message.chat.id, "Welcome to the group!");
});

bot.on("left_chat_member", function(message) {
  bot.sendMessage(message.chat.id,  message.from.first_name + "left");
});
```

![imagen](https://user-images.githubusercontent.com/31259651/37305629-5d4fb210-2635-11e8-82d5-e8ebb23c9679.png)

Second question: How to exportChatInviteLink a link group 

Code but no work: 
bot.onText(/!link/, (msg) => {
var inviteLink = msg.chat.invite_link;
var chatId = msg.chat.id;
bot.exportChatInviteLink(chatId, inviteLink)
bot.sendMessage(chatId, "This is the group's link: " + inviteLink)
})

I waiting fot answers, And Thanks you :)

**Comment by sidelux** [comment]
@Tecnonucleous Next time create a separate Issue...

So, _bot.on("new_chat_member", ..._ is deprecated, now you can catch with:
```
if (message.new_chat_members != undefined) {
    bot.sendMessage(message.chat.id, message.new_chat_member.username + " joined!");
}
```
Same with _left_chat_member_.

**Comment by DestroyerIV** [comment]
@sidelux 
```
bot.on('message', function(msg) {
	if (msg.new_chat_members != undefined) {
		bot.sendMessage(msg.chat.id, msg.new_chat_member.username + " Bienvenido");
	}
});
```

Is the code well implemented?

**Comment by sidelux** [comment]
@DestroyerIV i think yep, try it first.

**Comment by DestroyerIV** [comment]
@sidelux Does not work, some other idea?

**Comment by sidelux** [comment]
I use that way for my bot with 25.000+ members, it works 100%.

Check if your bot can read messages in group, then _console.log(msg)_ all messages then check.

**Comment by DestroyerIV** [comment]
the command would start with bot.on ('message', (msg) ?

**Comment by ritsuyan** [comment]
@DestroyerIV  have u fixed this. I just simply run a demo code on a US vps. 
```
const bot = new TelegramBot(token, {polling: true});

bot.on('message', function(msg) {
	if (msg.new_chat_members != undefined) {
		bot.sendMessage(msg.chat.id, msg.new_chat_member.username + " Bienvenido");
	}
});
```

when I send the message to bot it consoles log polling error.

**Comment by DestroyerIV** [comment]
It should not give any problem, it works perfectly. Does not generate any polling error

**Comment by bluetyphoon77** [comment]
Hi @DestroyerIV ! What was the working solution ? It would help since I'm facing nearly the same problem.
thanks

**Comment by bluetyphoon77** [comment]
> @Tecnonucleous Next time create a separate Issue...
> 
> So, _bot.on("new_chat_member", ..._ is deprecated, now you can catch with:
> 
> ```
> if (message.new_chat_members != undefined) {
>     bot.sendMessage(message.chat.id, message.new_chat_member.username + " joined!");
> }
> ```
> 
> Same with _left_chat_member_.

Left chat member is working for me !! why do you say it is deprecated ?
But new_chat_members only works for test bots created under my account. Weird BUG.
