### ISSUE TITLE
How to get when the bot was added to the group?

### ISSUE THREAD

**Issue by SilencerWeb** [yagop/node-telegram-bot-api#543]
How to get when the bot was added to the group?

**Comment by sidelux** [comment]
Catch _/start_ message from a negative chat_id :)

**Comment by tyt34** [comment]
I understand
I use https://api.telegram.org/bot<pass>/getUpdates and I get: "chat":{"id":-1001382271711
I use in my program:


```
var chatId = 307167071;
bot.sendDocument(chatId, 'img.png');
```
and see erorr => _400 Bad Request: wrong file identifier/HTTP URL specified_
Where I do mistake?

**Comment by sidelux** [comment]
@tyt34 Replied in #539
