### ISSUE TITLE
sent voice waves are not ok

### ISSUE THREAD

**Issue by mrdimaan** [yagop/node-telegram-bot-api#544]
When I send any voice it will not show the waves looks like the voice is broken. does anyone know how to fix that?

**Comment by danielperez9430** [comment]
Convert the audio to ogg for view the waves. If you send the audio in mp3 no show waves.

**Comment by saeedhei** [comment]
To use sendVoice, the file must have the type audio/ogg
Ref:(https://core.telegram.org/bots/api#inputfile)

**Comment by mrdimaan** [comment]
@danielperez9430 @saeedhei 
Ahanks. the problem solved. 

> audio must be in an .ogg file **encoded with OPUS**

And also the .ogg file must be without image (that maybe is from mp3 input cover that you have converted)

**Comment by ahmadnagilu** [comment]
how i can convert mp3 to ogg with libopus ?
