### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AOleksenko** [yagop/node-telegram-bot-api#546]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by yagop** [comment]
What is the question?

**Comment by Aleks97** [comment]
hello, how can i make function when my bot clears chat history with every user every 2 hours?

**Comment by tyt34** [comment]
Aleks97, 
Why you not add chat history in individual file? 
Then you can clear and do anything with it.

**Comment by Aleks97** [comment]
but in this case user will have him conversation with bot,isnt it?

**Comment by tyt34** [comment]
Now, I dont undrestand what you want.

**Comment by Aleks97** [comment]
okay. How can i add chat history in individual file?

**Comment by tyt34** [comment]
```
bot.on('message', (msg) => {
    // get Data
    let now = new Date();
    let c = now.getFullYear();
    let m = now.getMinutes();
    let s = now.getSeconds();
    console.log(msg.text+" "+m+":"+s);
    let before = fs.readFileSync("YOUR_FILE" , "UTF-8");
    fs.writeFileSync("YOUR_FILE" , before+"Text => "+msg.text+"\nUser => "+msg.from.first_name+" "+msg.from.last_name+"\n\n")
});
```
My code

**Comment by Aleks97** [comment]
i wrote this code in my bot, and every time when i click every button on my keyboard i saw in console 57:24
error: [polling_error] {} and figures are different all time

**Comment by tyt34** [comment]
I dont know. This code in begin file. I dont have erorr. I can send img with console and display telegramm chat for proof.

**Comment by Aleks97** [comment]
please do it and please add code's photo

**Comment by tyt34** [comment]
<a href='https://hostingkartinok.com/show-image.php?id=3d75d62e96c291acaa0f81f70527aa45' title='imagehost'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2018/03/3d75d62e96c291acaa0f81f70527aa45.png' alt='Yes' /></a>

**Comment by Aleks97** [comment]
thank you and now How can you delete this message?

**Comment by tyt34** [comment]
From chatHistory.txt file?

**Comment by Aleks97** [comment]
вы говорите по русски?

**Comment by tyt34** [comment]
Конечно

**Comment by Aleks97** [comment]
блин,давай-те я по русски напишу,просто я наверное на английском не понятно описал,что у меня не получается. Смотрите я написал телеграм бота,с помощью вашей библиотеки и у меня возникла проблема. Я не знаю как написать такую функцию, чтобы бот удалял историю переписки с каждым человеком, допустим каждые два часа или может можно прописать,чтобы я удалял в ручную?

**Comment by Aleks97** [comment]
bot.on('message', (msg) => {
    // get Data
    let now = new Date();
    let c = now.getFullYear();
    let m = now.getMinutes();
    let s = now.getSeconds();
    console.log(msg.text+" "+m+":"+s);
    let before = fs.readFileSync("название файла в котором пишу бота.js" , "UTF-8");
    fs.writeFileSync("название файла куда должно все отправляться.txt" , before+"Text => "+msg.text+"\nUser => "+msg.from.first_name+" "+msg.from.last_name+"\n\n")
});

a.bot.onText(/\Qq/, (msg) => {
        fs.writeFileSync("название файла куда должно все отправляться.txt" , "");
 })
так должно быть?

**Comment by tyt34** [comment]
1) Используйте функцию "Insert code";
2)
`let before = fs.readFileSync("название файла в котором пишу бота.js" , "UTF-8");
`
Нет, не в файле бота, а в файле где ваша переписка. Вы читали про библиотеку "fs"? Вот, почитайте.

**Comment by Aleks97** [comment]
вы путь прописывали через __filename или __dirname?
/Qq 51:23
error: [polling_error] {"errno":-4058,"code":"ENOENT","syscall":"open","path":"D:\\front\\bot\\index.js\\fileAleks.txt"}

**Comment by Aleks97** [comment]
можете пожалуйста отправить пример
что вы пишете в ковычках let before = fs.readFileSync("название файла в котором пишу бота.js" , "UTF-8");

**Comment by tyt34** [comment]
https://www.google.ru/search?q=fs+js&oq=fs+js&aqs=chrome..69i57.3230j0j7&client=ms-android-sonymobile&sourceid=chrome-mobile&ie=UTF-8

**Comment by Aleks97** [comment]
да,я это читал,спасибо большое,но если я пишу сообщение /Qq ничего не удаляется, в консоле мне выходит эта команда,но все сообщения на месте. А сообщения выходят корректно как у вас

**Comment by Aleks97** [comment]
спасибо большое за совет,все прочитал все сделал,работает,в консоли выдает ответ как у вас на скриншоте, и в отдельный файл все смс выходят. Но мне не это нужно было,смотрите, если я вам отправлю своего бота вы сможете по нажимать разные кнопки,он отправит вам картинки и так далее, но если вы нажмете /Qq то вся история удалиться,но у меня(в текстовом документе который я указал) а не у вас в чате с ботом,верно?

**Comment by Aleks97** [comment]
я имею в виду,допустим у вас очень много в чате смс с ботом,если у вас андроид,то в правом верхнем углу будет три точки,там есть кнопка очистить историю, и все сообщения удаляются,могу ли я прописать такую функцию или команду? Допустим, чтобы при сообщении /Qq все смс в этом чате удалились?

**Comment by tyt34** [comment]
не знаю

**Comment by Aleks97** [comment]
вы когда прописали ваш код,я имею в виду, все что вы мне отправили у вас в самом чате удалились сообщения?

**Comment by tyt34** [comment]
нет

**Comment by tyt34** [comment]
вот почитайте, может поможет https://core.telegram.org/bots/api#deletemessage

**Comment by Aleks97** [comment]
спасибо,я это читал,как я понял то бот может удалить любое сообщение,если он администратор чата(то есть какого-то телеграм канала,где бот является админом)а если это просто бот,то он как бы создает свой  чат с каждым человеком отдельно и получается,что я могу это контролировать просто получая информацию из каждого чата используя webhook или poling, но удалить сообщение допустим из вашего чата с моим ботом я не могу.(не могу сделать телеграм канал и поставить его админом, так как делаю тест бот) Извините за кол-во вопросов,просто никогда не писал на js, не давно начал заниматься

**Comment by Aleks97** [comment]
возможно, я что-то неправильно понимаю
