### ISSUE TITLE
QUESTIONS TELEGRAM BOT

### ISSUE THREAD

**Issue by ghost** [yagop/node-telegram-bot-api#548]
Hi. I created my first Telegram bot.
Now I`m improving it and i have any questions, because i don`t know how to do some things:
I want after pressing the button, example "Day 1",  the bot automatically sent  first message with button " ready. i want to continue" and after pressing this button the user is sent a message the next day at 10 o`clock with button  " ready. i want to continue" and so seven days of the week only for 7 day the button will be called "done. what`s next"

**Comment by sidelux** [comment]
Is not so clear but i think you need to setup a time system.
Use a file or db to store time when you click "Day 1", and use a loop to check if time is elapse.
Example:

When click "Day1"
Save date wherever you want (now + 1 day at 10:00)
Send "Ready..."

```
callNTimes(60000, function () {
	var now = new Date();
	if (savedDate < now){
		Send "Ready..."
		Save date again... etc..
	}
}

function callNTimes(time, fn) {
	function callFn() {
		if (1 < 0) return;
		fn();
		setTimeout(callFn, time);
	}
	setTimeout(callFn, time);
}
```
