### ISSUE TITLE
new GIF method required?

### ISSUE THREAD

**Issue by paOol** [yagop/node-telegram-bot-api#55]
https://telegram.org/blog/gif-revolution

I had my bot doing a search on Giphy,
then returning the direct url for the GIF, 
saving the gif with node FS, 
sending the gif using bot.sendDocument( fromID, gif);

That was working until they pushed the update today.

**Comment by kersten** [comment]
I have the same problem right now

**Comment by yagop** [comment]
Seem its working with sendDocument but current Telegram Apps can't view the files
```
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.
```

**Comment by kersten** [comment]
The post was from 2015 by the way. Maybe a problem? Why does no client work with this?

**Comment by kersten** [comment]
I didn't get any app update on any platform. Why should they update somethin, if its not working?

**Comment by yagop** [comment]
In Telegram Android its coming with 3.4.0
Hahahahah didn't realized they set the year wrong

**Comment by yagop** [comment]
I can confirm in Telegram 3.4.0 its working

**Comment by paOol** [comment]
how did you download 3.4.0?

on the playstore i see

"What's new
v. 3.3.2"

**Comment by yagop** [comment]
Its closed beta
