### ISSUE TITLE
getUpdates ETELEGRAM 409 Conflict: terminated by other getUpdates request;

### ISSUE THREAD

**Issue by ricustr** [yagop/node-telegram-bot-api#550]
```object
 {"code":"ETELEGRAM","message":"ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}
```
I'm getting this error some times on restart bot.
Does somebody know more information or how to check running instances? <br/>
I see more people catch the same error, but nobody can response. 
#488

**Comment by sidelux** [comment]
I think that the session is not properly terminated, so getUpdates continue get updates after CTRL-C or similar, you can solve it by terminate process maybe.
Can you provide server, platform and other infos?

**Comment by ricustr** [comment]
Do you mean, session as running instance of bot?
I think so, because this error appear not every time.
How terminate session correctly, or how can I catch getUpdates events to see what happens, if it is possible.
Of course, I use a dev bot on my laptop (Ubuntu 17.04) and another for prod on physical server (Ubuntu 16.04.4 LTS) for prod.

**Comment by sidelux** [comment]
That error means: "There are two or more bots that listen updates at same bot token"
So i think you can check process list in your server, what system you use to keep bot alway on? (for example i use pm2)

To print all exception use:
```
process.on('uncaughtException', function (error) {
	console.log("\x1b[31m", "Exception: ", error, "\x1b[0m");
});

process.on('unhandledRejection', function (error, p) {
	console.log("\x1b[31m","Error: ", error.message, "\x1b[0m");
});
```
But ETELEGRAM means an error printed by telegram server, you can't get other infos.

**Comment by ricustr** [comment]
Thank for you response. 
I use pm2, but i will check processes for bot instance.
Okay. I will add methods and see more info and add here.
thank you again.

**Comment by askucher** [comment]
but how to run 2 instances of the bot on one server?

**Comment by sidelux** [comment]
@askucher Only one istance can listen for updates, otherwise you must use two different bot token

**Comment by ricustr** [comment]
@sidelux Unfortunately, I can't catch 
 `process.on('uncaughtException', function (error) {
	console.log("\x1b[31m", "Exception: ", error, "\x1b[0m");
});

process.on('unhandledRejection', function (error, p) {
	console.log("\x1b[31m","Error: ", error.message, "\x1b[0m");
});`
, but the ETELEGRAM 409 Conflict: is still persist. I will try again to check processes after stoped running instance. Thanks.

**Comment by nvcken** [comment]
@sidelux as Telegram only allow on instance can listen for updates, then how can we scale that instance service what happen if that process handle large messages requests

**Comment by saeedhei** [comment]
@vjrj Should I have 2 index.js for 2 bot and 2 `pm2 start` ?

**Comment by vjrj** [comment]
@saeedhei Yes.

I have the same code base that I pull from my github repo in two different directories and different `settings.json` on each with bot credentials, and sensible API data, etc.

I recommend you to play with `pm2 start`etc with two simple `hello world` apps.

Also, I don't use it, but maybe this yeoman generator is useful for you:
https://github.com/ashneo76/generator-telegram-bot

**Comment by saeedhei** [comment]
@vjrj Is this process.yml ok for 2 bot?
```
apps:
  - script   : src/index1.js
    instances: 1
    exec_mode: cluster
  - script   : src/index2.js
    instances: 1
    exec_mode: cluster
```

**Comment by mutantcornholio** [comment]
I guess telegram engineers didn't want to make complex API with message balancing or synchronization tokens, or whatever.

If you want to run several node.js instances in one node.js cluster, I'd recommend polling events in master process and sending them to workers in process.send()
If you want to run your bot on several servers, I would recommend creating a lightweight balancing proxy (possibly, with a failover instance waiting nearby) that sends updates to workers. You could do balancing on your own, or use some job queue, like RabbitMQ. 
The idea stays the same, basically =)

**Comment by ozodrukh** [comment]
This can be caused by manual `startPolling()` calling, due to polling start automatically if you passed `{polling: true}` when creating a bot

**Comment by sutangu** [comment]
Hi, everybody. It was fixed. Maybe it can be temporarily, but I have mistakes stopped:

#https://github.com/benjick/meteor-telegram-bot/issues/37#issuecomment-389669310

**Comment by rotimi-best** [comment]
> Hi, everybody. It was fixed. Maybe it can be temporarily, but I have mistakes stopped:
> 
> #[benjick/meteor-telegram-bot#37 (comment)](https://github.com/benjick/meteor-telegram-bot/issues/37#issuecomment-389669310)

Mine didn't stop. Still have the same problem.

**Comment by AndrewMZ6** [comment]
> This can be caused by manual `startPolling()` calling, due to polling start automatically if you passed `{polling: true}` when creating a bot

tyvm I commented the startPolling() line and it worked!

**Comment by AndrewMZ6** [comment]
Had the same problem. The first bot listener was running in the background. Solved it with task manager (Ctr + Shift + Esc) -> "Python" process -> right click -> remove the task

**Comment by jonit-dev** [comment]
I solved it by manually starting and ending my pooling once my function starts and ends (and removed: { polling: true } option from the bot object instantiation). I also did a check to stop the polling if by any reason its active before we're trying to start a new poll.
eg.

`if(bot.isPolling()) {
await bot.stopPolling();
}

await bot.startPolling();

[SOME CODE]

awiat bot.stopPolling();`

**Comment by newCodeUz** [comment]
i after millions of hits. I decided to php the bot

**Comment by defendson** [comment]
Hi there.
It looks like you try running the bot with token that is already in use.

I solved it when changed token value, created new one bot for development and testing, because previous bot had already been working in production.

const token = 'SET YOUR ANOTHER TOKEN HERE';
const telegramBot = new TelegramBot(token, { polling: true });

then, it should work

**Comment by Shrikshel** [comment]
I understand it's quite a late reply to this thread, in my case (and I think for most others) the issue is, pm2 tries to start  loadbalancer with ` instances: 'max'` , and when more than 1 (pm2) instance is possible then, for polling on both the instances telegrams complains this error which is logical.

**Comment by AnimeKraze** [comment]
> That error means: "There are two or more bots that listen updates at same bot token"
> So i think you can check process list in your server, what system you use to keep bot alway on? (for example i use pm2)
> 
> To print all exception use:
> 
> ```
> process.on('uncaughtException', function (error) {
> 	console.log("\x1b[31m", "Exception: ", error, "\x1b[0m");
> });
> 
> process.on('unhandledRejection', function (error, p) {
> 	console.log("\x1b[31m","Error: ", error.message, "\x1b[0m");
> });
> ```
> 
> But ETELEGRAM means an error printed by telegram server, you can't get other infos.

How can I see what bot is using my commands

**Comment by marshalmax888** [comment]
“ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running”
Maybe you are running your local bot project, and the telegram think that is 2 bot instance...so you need to close that and then vist the https://api.telegram.org/bot....../getUpdates

**Comment by Yonny24** [comment]
Great this solved my issue thanks.
Just created a new bot and new token. 
I have nodered with telegram bot on 1 linux server and another on windows docker. Shame we can't use the same bot though.

**Comment by emremrah** [comment]
> Had the same problem. The first bot listener was running in the background. Solved it with task manager (Ctr + Shift + Esc) -> "Python" process -> right click -> remove the task

Do you know what process called on a Linux system? I have stopped all my scripts by I'm still getting this error. Which process do I have to kill?

**Comment by MCPEBlocker** [comment]
The Telegraf examples section on github has a [piece of code](https://github.com/telegraf/telegraf/blob/develop/docs/examples/example-bot.ts) that can solve this problem for me.


`// Enable graceful stop`
`process.once('SIGINT', () => bot.stop('SIGINT'))`
`process.once('SIGTERM', () => bot.stop('SIGTERM'))`

**Comment by andrey-pavlenko** [comment]
Works with `nodemon` in my case. Separate build process used with `tsc -w` to `dist` folder.

`package.json`
```json
{
  "scripts": {
    "start:w": "NODE_ENV=development nodemon --signal SIGQUIT -w dist dist/index.js"
  }
}
```

`index.ts`
```ts

let telegramBot: TelegramBot | null = null;

async function start(token: string): Promise<void> {
  telegramBot = new TelegramBot(token);
  await telegramBot.startPolling({ restart: true });
}

async function stop(): Promise<void> {
  if (telegramBot != null) {
    await telegramBot.stopPolling({ cancel: true });
    telegramBot = null;
  }
}

start();
process.on('exit', async () => await stop());
```

**Comment by ZoeMohamed** [comment]
Pusing bot

**Comment by evgeniy2702** [comment]
I also have this error when I use a Telegram bot extending from LongPollingTelegram.
My bot is written in SpringBoot version 2.6.4, java version 1.8.0_271, which is deployed on tomcat version 9.0.56 under linux.
I used the following dependencies for the Telegram bot :
`<dependency>
			<groupId>org.telegram</groupId>
			<artifactId>telegrambots-spring-boot-starter</artifactId>
			<version>5.6.0</version>
		</dependency>

		<dependency>
			<groupId>org.telegram</groupId>
			<artifactId>telegrambots</artifactId>
			<version>5.6.0</version>
		</dependency>`

I use the following code to initialize my bot : 
` @EventListener({ContextRefreshedEvent.class})
    public void init() throws TelegramApiException{
        consoleLogger.info("Start initializer MediaBot .");
        TelegramBotsApi telegramBotsApi = new TelegramBotsApi(DefaultBotSession.class);
        try{
            BotSession session = telegramBotsApi.registerBot(bot);
            bot.setSession(session);
        } catch (TelegramApiException e) {
            consoleLogger.error("Error occurred: " + e.getMessage());
        }
    }`

And my bot has the following PreDestroy method to close and release all resources: 
` @PreDestroy
    public void preDestroy(){
        consoleLogger.info("Stop bots session .");
        this.onClosing();
        this.getSession().stop();
        consoleLogger.error("Bot session was stopped .");
    }`

But when I deploy my bot from tomcat, I get the following error : "409 Conflict: completed by another getUpdates request;".
And this error repeats every second. What am I doing wrong? I can't figure it out.
The support of Telegram is not answer for my email.

**Comment by evgeniy2702** [comment]
The way I was see it, the reason was using the telergambots-spring-boot-starter dependency. It automatically does telegram bot registration and if you try to create TelegramBotApi to register bot in the code - you actually do bot registration twice and end up with two bots with one token.
And second - using this dependency I can't figure out how I can get BotSession (this is only for LongPollingBot) for closing my bot correctly and I got a memory leak error when removing my application from tomcate.
Solution: I use the org.telegram.telegrambots dependency and then I can make my bot register by creating TelegramBotApi and as a result I get access to ExecutorService to release the executor resources and plus for LongPollingBot i get access to BotSession  for close the session correctly.

**Comment by ELHart05** [comment]
Same problem, any fix?

**Comment by dopil** [comment]
I solved the problem using 'BotFather.' I went into the menu, requested my bot's token, updated the token, and the issue disappeared

**Comment by Cosmits** [comment]
`const TelegramBot = require('node-telegram-bot-api');

// Use environment variables for the token and webhook URL
const token = process.env.TELEGRAM_TOKEN;
const url = process.env.WEBHOOK_URL;

const bot = new TelegramBot(token, {webHook: {port: process.env.PORT || 443}});

// Set the webhook to the URL provided by Render
bot.setWebHook(`${url}/${token}`);

bot.on('message', (msg) => {
  const chatId = msg.chat.id;
  bot.sendMessage(chatId, 'Received your message');
});`

This code is work,when I deploy code on www.render.com

**Comment by mielpl** [comment]
Finally, I found the cause of this problem in my situation. I created the telegram bot service and initialized it there. I used it in my Telegram bot service constructor and in the application service (injected it). Because of this, it was initialized twice when the application was launched. It was my mistake. I also tried telegraf.js and grammy.js, there also appeared this conflict error message. You should initialize TelegramBot once and in another file from service file. I hope it will be useful.

**Comment by lipe-pepe** [comment]
> This code is work,when I deploy code on [www.render.com](http://www.render.com)
> 
> `index.js`
> 
> ```ts
> const TelegramBot = require('node-telegram-bot-api');
> 
> // Use environment variables for the token and webhook URL
> const token = process.env.TELEGRAM_TOKEN;
> const url = process.env.WEBHOOK_URL;
> 
> const bot = new TelegramBot(token, {webHook: {port: process.env.PORT || 443}});
> 
> // Set the webhook to the URL provided by Render
> bot.setWebHook(`${url}/${token}`);
> 
> bot.on('message', (msg) => {
>   const chatId = msg.chat.id;
>   bot.sendMessage(chatId, 'Received your message');
> });
> ```

Hey, do you have more information on this? How do we set up the web hook for render?

**Comment by Cosmits** [comment]
> > This code is work,when I deploy code on [www.render.com](http://www.render.com)
> > `index.js`
> > ```ts
> > const TelegramBot = require('node-telegram-bot-api');
> > 
> > // Use environment variables for the token and webhook URL
> > const token = process.env.TELEGRAM_TOKEN;
> > const url = process.env.WEBHOOK_URL;
> > 
> > const bot = new TelegramBot(token, {webHook: {port: process.env.PORT || 443}});
> > 
> > // Set the webhook to the URL provided by Render
> > bot.setWebHook(`${url}/${token}`);
> > 
> > bot.on('message', (msg) => {
> >   const chatId = msg.chat.id;
> >   bot.sendMessage(chatId, 'Received your message');
> > });
> > ```
> 
> Hey, do you have more information on this? How do we set up the web hook for render?

show my code here ...
https://github.com/Cosmits/test-telegram-bot

**Comment by its-dibo** [comment]
one reason is to instantiate the class twice, make sure you create the instance as singleton

```
let instance1 =  new Telegram(this.token, { polling: true });

// in another place
let instance2 =  new Telegram(this.token, { polling: true });
```

**Comment by Comandante7s** [comment]
> ```
>  {"code":"ETELEGRAM","message":"ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}
> ```
> 
> Recibo este error algunas veces al reiniciar el bot. ¿Alguien sabe más información o cómo comprobar las instancias en ejecución? Veo que más personas detectan el mismo error, pero nadie puede responder. #488



> ```
>  {"code":"ETELEGRAM","message":"ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}
> ```
> 
> Recibo este error algunas veces al reiniciar el bot. ¿Alguien sabe más información o cómo comprobar las instancias en ejecución? Veo que más personas detectan el mismo error, pero nadie puede responder. #488

Hola, asegurate que en tu archivo que creaste package.json, haga referencia en main hacia el archivo creado manuelmente bot.js.

Esa fue mi solución. Saludos.

**Comment by markpumpkin** [comment]
> ```
>  {"code":"ETELEGRAM","message":"ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}
> ```
> 
> I'm getting this error some times on restart bot. Does somebody know more information or how to check running instances? I see more people catch the same error, but nobody can response. #488

=>> The **main issue** lies in the fact that you are initializing the bot (new TelegramBot) multiple times, but you should only initialize it once for each bot_token

**Comment by RasulovN** [comment]
bot.on('polling_error', (error) => {
    bot.startPolling(); 
    console.log('bot pollling error: ' + error);  // Print the error to the console
});


 **bot.startPolling();**  after i added this line the error stopped
