### ISSUE TITLE
Share button under the message

### ISSUE THREAD

**Issue by MrAnsheff** [yagop/node-telegram-bot-api#551]
How can I do inline button, that can share message to another chat?

**Comment by sidelux** [comment]
You can use [switch_inline_query](https://core.telegram.org/bots/api#inlinekeyboardbutton):

```
var iKeys = [];
iKeys.push([{
	text: "Share",
	switch_inline_query: "Shared message"
}]);

bot.sendMessage(rows[i].chat_id, "Question", {parse_mode: 'HTML', reply_markup: {inline_keyboard: iKeys}});
```

**Comment by DestroyerIV** [comment]
a clear example is to share with a button, a button with different links and publish it on a channel. I hope to have explained to me the best possible. Thanks in advance

**Comment by DestroyerIV** [comment]
Hello, I have several questions: I have tried to create a button that is responsible for sending a post to another chat. I have tried to modify the example code that is above this section without getting results. I would like if it were possible that they would explain to me quickly the operation of the online keyboards or guide me in the creation of a similar button. 

Many thanks in advance

**Comment by sidelux** [comment]
I think you need that:
```
var code = "test";
var iKeys = [];

iKeys.push([{
	text: "Share query",
	switch_inline_query: code
}]);
bot.sendMessage(message.chat.id, "Click below to share your code", {
	parse_mode: 'Markdown',
	reply_markup: {
		inline_keyboard: iKeys
	}
});
```

**Comment by danielperez9430** [comment]
@sidelux I continue with the same doubt. And that example I still can not make it work. You could explain it a little more if it's not too much trouble. We've been trying to make it work for a week and it's impossible for me.

Check many tutorials by Google, but it was not helpful. So if you can explain it a little more I would appreciate it

**Comment by danielperez9430** [comment]
Some like this:
<a href="https://ibb.co/gRa2j8"><img src="https://preview.ibb.co/n55PxT/IMG_20180713_160224.jpg" alt="IMG_20180713_160224" border="0"></a><br />

For example send a Message with share botton and send inline to other chats

**Comment by DestroyerIV** [comment]
Exactly how Daniel explained it, I have a database with which to work but I do not show results

**Comment by sidelux** [comment]
I don't know which part are not clear to you, anyway i provide you an example related to my workflow.
1. User use a command like /create to generate an element, bot assign a random code to user for that element
2. User can print element in inline mode using that code with `@botname <code>`
3. Also that user can call that element in inline mode with function provided two messages ago.

So:
```
bot.onText(/^\/create/, function (message, match) {
    var code = Math.random()*1000;
    // save code to database
    var iKeys = [];
    iKeys.push([{
        text: "Share query",
        switch_inline_query: code
    }]);
    bot.sendMessage(message.chat.id, "Click below to share your code", {
        parse_mode: 'Markdown',
        reply_markup: {
            inline_keyboard: iKeys
        }
    });
});
```

Then:
```
bot.on("inline_query", function (query) {
    var code = parseInt(query.query);
    // check if the code is in database and user can use it (valid var)
    if (valid == true){
        bot.answerInlineQuery(query.id, [{
                                id: '0',
                                type: 'article',
                                title: 'New item',
                                description: "Publish item",
                                message_text: "Details of your item base on code..."
        }]);
    }else{
        bot.answerInlineQuery(query.id, [{
                                id: '0',
                                type: 'article',
                                title: 'New item',
                                description: "Publish item",
                                message_text: "Code not found"
        }]);
    }
});
```

![image](https://user-images.githubusercontent.com/18572941/42696207-c8f60752-86b7-11e8-85b8-5002dcd81190.png)

Then, after user selected chat

![image](https://user-images.githubusercontent.com/18572941/42696225-d79cf036-86b7-11e8-901d-894b0cccbe0c.png)

Now, if you not understand yet, please give me a valid example so i can explain you in a more detailed way.

**Comment by DestroyerIV** [comment]
@sidelux  In the third line of code, it says to save the code in the database ... the buttons? send Message?

The var variable that would be referenced in the database?

Thanks in advance

**Comment by danielperez9430** [comment]
Thanks for your time mate.

I was using the inline keyboards, but I was wrong. I was missing the bot.on. That's why he did not finish answering

and I have another question that database you use because I see that you put "save code to database".
If I understand well what you keep is the message and the id of it, right?

**Comment by sidelux** [comment]
@DestroyerIV For me is the random generated code:
```
...
var code = Math.random()*1000;
connection.query("INSERT INTO list VALUES (" + code + ")", function (err, rows, fields) {
    if (err) throw err;
});
var iKeys = [];
....
```
```
var code = parseInt(query.query);
var valid = 0;
connection.query("SELECT 1 FROM list WHERE code = " + code, function (err, rows, fields) {
    if (err) throw err;
    var cnt = Object.keys(rows).length;
    if (cnt > 0)
        valid = 1;

    if (valid == true){
    ...

});
```

**Comment by sidelux** [comment]
@danielperez9430 Nope, is the data i want to use in inline mode (number, string, etc).

**Comment by danielperez9430** [comment]
Okey Thanks for the information mate,  😍😍 and thanks for your time
