### ISSUE TITLE
How to make the bot can only be added to groups by its creator?

### ISSUE THREAD

**Issue by danielperez9430** [yagop/node-telegram-bot-api#555]
My question is how to make only the creator or the people who are authorized to add the bot to the groups. And on the other hand bring a group count. Any idea?

**Comment by sidelux** [comment]
It's easy :)

If you want to allow add bot to groups to specific username:
```
bot.on('message', function (message) {
	if (message.chat.id < 0){    // is a group
		if (message.new_chat_member.username == "botusername"){
			if (message.from.username != "username_authorized"){
				bot.leaveChat(message.chat.id).then(function (res) {
					if (res == true)
						console.log("Leaved chat");
				});
			}
		}
	}
});
```

If you want to allow add bot to groups to group creator/admin:
```
bot.on('message', function (message) {
	if (message.chat.id < 0){    // is a group
		bot.getChatMember(message.chat.id, message.from.id).then(function (data) {
			if ((data.status == "creator") || (data.status == "administrator")) {
				if (message.new_chat_member.username == "botusername"){
					bot.leaveChat(message.chat.id).then(function (res) {
						if (res == true)
							console.log("Leaved chat");
					});
				}
			};
		});
	}
});
```

**Comment by DestroyerIV** [comment]
I receive output errors as error polling. Any ideas? In addition, the command, after a few hours stops working.

Thanks in advance

**Comment by sidelux** [comment]
Is not tested, try to debug with console.log in every code line.
What do you mean with "stops working"?

**Comment by danielperez9430** [comment]
Hi sedelux and thanks for your answer. I test it work, but time before the bot no response of other messages or events and get polling error.
If I delate this code the bot works. But if I put it the bot gets error polling and no response

**Comment by sidelux** [comment]
@danielperez9430 Try with error handling suggested in #550
