### ISSUE TITLE
[QUESTION] Inline Query group

### ISSUE THREAD

**Issue by gochi-dot** [yagop/node-telegram-bot-api#557]
I added bot to a group as a member.
Then, I am using Inline Query inside the group (i.e. `@mybot hello world`) .
How can I connect result that user choose from Inline Query with the group ?
Also, I can't define target group from response of `chosen_inline_result` event.

**Comment by sidelux** [comment]
The answer is easy, you can't. Chat_id is not provided by inline_query and there is no way to pass it through inline_query.

Btw you can send message in the group where you have called inline query with:

```
bot.on("inline_query", function (query) {
    bot.answerInlineQuery(query.id, [{
        id: '0',
        type: 'article',
        title: 'Preview Title',
        description: 'Preview Description',
        message_text: 'Message Text'
    }]);
});
```

**Comment by sidelux** [comment]
inline_query return this:
```
{ id: 'id',
  from: 
   { id: msg_id,
     is_bot: false,
     first_name: 'name',
     username: 'nickname',
     language_code: 'en' },
  query: 'query_id',
  offset: '' }
```

and chosen_inline_result return this:

```
{ from: 
   { id: msg_id,
     is_bot: false,
     first_name: 'name',
     last_name: 'lastname',
     username: 'nickname',
     language_code: 'en' },
  inline_message_id: 'msg_id',
  query: 'query_id',
  result_id: '0' }
```

So how can you store chat_id if none of these function return it? 🤔

**Comment by dvlasenko96** [comment]
@sidelux I am thinking about adding `on('message')` handler before and cache group id. Then in `chosen_inline_result` we can match message with chosenInlineResult and get group id

**Comment by sidelux** [comment]
I tried with your theory but i can't see nothing that match (except user data obv).

on('message')

```
{ from: 
   { id: 20471035,
     is_bot: false,
     first_name: 'Edo ⚡️',
     username: 'fenix45',
     language_code: 'it' },
  inline_message_id: 'AgAAANiiAAByR5i-R_7-JY-FgyY',
  query: '81180365025',
  result_id: '0' }
```

chosen_inline_result

```
{ message_id: 41688,
  from: 
   { id: 20471035,
     is_bot: false,
     first_name: 'Edo ⚡️',
     username: 'fenix45',
     language_code: 'it' },
  chat: { id: -1001097316494, title: 'Loot Negozi', type: 'supergroup' },
  date: 1523350789,
  text: 'Negozio di fenix45!' }
```

**Comment by dvlasenko96** [comment]
@sidelux I am matching
`chosenInlineResult.query` and `message.text`, but for do it, you need to show any `key` for user. I didn't find a way how to do it without any trash

**Comment by sidelux** [comment]
You can't do in that way, if a bad user create an inline bot that send same query he can do whatever he want. Is not a safe method because you can't check from what bot the query come.

**Comment by dvlasenko96** [comment]
@sidelux Yes, it is not safety, but possible solution. We can set limits of 1s between handle message and chosenInlineResult and close the thread 👯
