### ISSUE TITLE
How to deal with russian telegram blocking?

### ISSUE THREAD

**Issue by IzaGz** [yagop/node-telegram-bot-api#562]
How to bypass the telegram block in russia?

**Comment by sand123** [comment]
I quickly looked through code, and found that all API interactions rely on `request-promise` package, which supports connection through proxy

```javascript
var request = require('request-promise').defaults({
    proxy:'http://username:password@host:port',
    strictSSL :false
  });
```

**Comment by sand123** [comment]
`request-promise` is a wrapper around request - see [proxy settings](https://github.com/request/request#proxies)  
You should try this in /src/telegram.js at line 10:
```javascript
const request = require('request-promise').defaults(/* http proxy settings here */);
```

**Comment by bortnikov** [comment]
Thank you. This works

> You should try manually edit in /src/telegram.js at line 10:

**Comment by samohovets** [comment]
Also you can use TelegramBot options like this:
`const bot = new TelegramBot(config.get('telegram_token'), {
  polling: true,
  request: {
    proxy: 'http:/***',
    // Proxy settings here
  }
});`

**Comment by bortnikov** [comment]
@samohovets Thank you. This doesn't work for me.

**Comment by IzaGz** [comment]
Please suggest which proxy to use?Is there any good free proxies?
@samohovets , @sand123  which proxies do u use? Do you use chargeable proxies?

**Comment by Osrx** [comment]
Please add support of SOCKS5 proxy.
Socks proxy used as standard proxy method in Telegram app, so it will be more easy to find.

**Comment by nskondratev** [comment]
@Osrx 
You can use SOCKS5 proxy with the [socks5-https-client](https://www.npmjs.com/package/socks5-https-client) lib. Example:

```js
const TelegramBot = require('node-telegram-bot-api')
const Agent = require('socks5-https-client/lib/Agent')

const bot = new TelegramBot(process.env.TELEGRAM_API_TOKEN, {
	polling: true,
	request: {
		agentClass: Agent,
		agentOptions: {
			socksHost: process.env.PROXY_SOCKS5_HOST,
			socksPort: parseInt(process.env.PROXY_SOCKS5_PORT),
			// If authorization is needed:
			// socksUsername: process.env.PROXY_SOCKS5_USERNAME,
			// socksPassword: process.env.PROXY_SOCKS5_PASSWORD
		}
	}
})
```

I use this solution to continue developing bot on my local PC (I'm in Russia, so without proxy I can not start bots) and it works.

**Comment by nskondratev** [comment]
@IzaGz I set up proxy server on DigitalOcean droplet, which costs 5$ per month.

**Comment by Balanar300hp** [comment]
@nskondratev Is it working with sendAudio?

**Comment by telegrambotdeveloper** [comment]
I use proxy how @nskondratev supposes and have the error: "Unhandled rejection RequestError: Error: connect ECONNREFUSED 127.0.0.1:1080". How can the library call localhost?

**Comment by baitun** [comment]
@IzaGz you can use [Tor Browser](https://github.com/TheTorProject/gettorbrowser) as SOCKS5 proxy.
Jast start Tor Browser and use `127.0.0.1:9150` as proxy adress.

**Comment by IldarMurzenkov** [comment]
@nskondratev 
This code works correctly:

`var options = {
    url: "https://api.telegram.org/bot1111111...11/getMe",
    agentClass: Agent,
    agentOptions: {
        socksHost: config.proxy.socksHost, 
        socksPort: config.proxy.socksPort,
        socksUsername: config.proxy.socksUsername,
        socksPassword: config.proxy.socksPassword
    }
}

request(options, function (error, res, html) {
  if (!error && res.statusCode == 200) {
    console.log(html)
  }else {
    console.log(error)
  }
})`

But when i am trying to use "socks5-https-client" with 'node-telegram-bot-api':
`const bot = new TelegramBot(config.bot.token, {
    polling: true,
    request: {
        agentClass: Agent,
        agentOptions: {
            socksHost: config.proxy.socksHost,
            socksPort: config.proxy.socksPort,
            // If authorization is needed:
             socksUsername: config.proxy.socksUsername,
             socksPassword: config.proxy.socksPassword
        }
    }
});`
timeout error occurs.

Could you please help to understand why proxy is not working with 'node-telegram-bot-api'?

**Comment by VeeDock** [comment]
this code good work for me: 

`const TelegramBot = require('node-telegram-bot-api');
const token = '123456789:asdf234fdsf-asdfdsafdsewr23';
var Agent = require('socks5-https-client/lib/Agent');
const bot = new TelegramBot(token, {
    polling: true, 
    request: {
        strictSSL: true,
        agentClass: Agent, 
        agentOptions: {
            socksHost: '123.45.67.89', 
            socksPort: 1234,
            socksUsername: 'login',
            socksPassword: 'pass'
        }
    }
});`

**Comment by likeavenus** [comment]
@IldarMurzenkov hi, what is the "config" ? Have same problem "error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ECONNREFUSED 127.0.0.1:1080"}"
