### ISSUE TITLE
Sending photo by HTTP URL with proxy returns 400 Bad Request 

### ISSUE THREAD

**Issue by vladostsk92** [yagop/node-telegram-bot-api#563]
I'm trying to send photo by HTTP URL and proxy socks5 using the .sendPhoto method.

sending this photo: 
http://barguzin.net/upload/filmbase/posters/movie_image_path_big_1292_1968.jpg 
i get "Error: ETELEGRAM: 400 Bad Request: wrong file identifier/HTTP URL specified", 

but sending this photo: 
http://barguzin.net/upload/filmbase/posters/1302_big_6016.jpg 
everything is good, photo comes

**Comment by sidelux** [comment]
Try to write here parts of code interested :)

Btw maybe second file has been uploaded to telegram so it have file_id set and available to been sent, instead first file not (?).
I'll wait for a code snippet.

**Comment by vladostsk92** [comment]
poster = config.site + '/upload/filmbase/posters/' + res.rows[0].movie_image_path_big;
bot.sendPhoto(chatId, poster);

**Comment by vladostsk92** [comment]
and now i can't send photo from local directory
fs.createReadStream('logo.png')

these problems began after the telegrams were blocked in Russia. We began to use a proxy for the bot

**Comment by sand123** [comment]
I guess that all API methods ```send*``` ignore proxy settings and try to conenct directly, using ```request``` module.
I also connected through proxy this way https://github.com/yagop/node-telegram-bot-api/issues/562#issuecomment-382313307 and none of the send files\documents methods work
