### ISSUE TITLE
difficulties with callbacks

### ISSUE THREAD

**Issue by DestroyerIV** [yagop/node-telegram-bot-api#574]
I am creating a keyboard with different options regarding ban. Following the example of the file polling.js, I can not get a button to execute an action, in this case to ban a user one day. I show how I carry the code:

```
bot.onText(/\!ban/, function (msg) {
	
if(msg.reply_to_message == undefined){
	return;
	}
  const opts = {
    reply_markup: {
      inline_keyboard: [
        [
          {
            text: '1 Day',
            callback_data: 'ban1d'
          },
          {
            text: '1 Week',
            callback_data: 'ban7d'
          }
        ]
      ]
    }
  };
  bot.sendMessage(msg.chat.id, "Select the ban time", opts);
});

bot.on('callback_query', function onCallbackQuery(callbackQuery) {
  const action = callbackQuery.data;
  const msg = callbackQuery.message;
  const ms = require("ms")
  const opts = {
    chat_id: msg.chat.id,
    message_id: msg.message_id,
  };

if (action == 'ban1d') {
bot.kickChatMember(msg.chat.id, userid, {until_date: Math.round((Date.now() + ms("1 days"))/1000)}).then(function(result){
bot.sendMessage(msg.chat.id, "You have been banned for 1 day");
})
}

if (action == 'ban7d') {
bot.kickChatMember(msg.chat.id, userid, {until_date: Math.round((Date.now() + ms("7 days"))/1000)}).then(function(result){
bot.sendMessage(msg.chat.id, "You have been banned for 7 days");
})
}

  //bot.editMessageText(action, opts);
});
```

I can not find a way to make it work, any idea is well received. Thanks in advance

**Comment by sidelux** [comment]
(Hey you again :D)
What is the error? Btw i can provide an example:
```
bot.onText(/\/ban/i, function (message) {
    if (message.reply_to_message != undefined) {
        var iKeys = [];
	iKeys.push([{
		text: "1 Day",
		callback_data: "1d:" + message.reply_to_message.from.id
	}]);
        iKeys.push([{
		text: "1 Week",
		callback_data: "1w:" + message.reply_to_message.from.id
	}]);
        bot.sendMessage(message.chat.id, "Select the ban time",  {
		parse_mode: 'HTML',
		disable_web_page_preview: true,
		reply_markup: {
			inline_keyboard: iKeys
		}
	});
    }
});

bot.on('callback_query', function (message) {
    var text = message.data;
    var func = message.data.split(":")[0];
    var userid = message.data.split(":")[1];
    if (func == "1d"){
        bot.kickChatMember(message.chat.id, userid).then(function (result) {
	    bot.sendMessage(message.chat.id, "User banned");
        });
    }
});
```

Let me know if it helped you.

**Comment by DestroyerIV** [comment]
The buttons remain thinking without getting to perform any action. I do not know what can happen in both cases. Thanks for your help, I appreciate the help

**Comment by alexandercerutti** [comment]
The code should work. Anyway, you are not calling anywhere `answerCallbackQuery`, which is necessary to remove the "thinking behavior".

**Comment by DestroyerIV** [comment]
What would that option you are talking about?

The answerCallbackQuery is created but I do not know what type / method you reference

**Comment by DestroyerIV** [comment]
and within that method, do you reference cache_time?

**Comment by alexandercerutti** [comment]
No. You have just to call that method to avoid the situation described in your [comment above](https://github.com/yagop/node-telegram-bot-api/issues/574#issuecomment-386638910).

**Comment by DestroyerIV** [comment]
Oh, I understood, I'm going to try. Thanks mate

**Comment by alexandercerutti** [comment]
You're welcome. Give us some updates here later. :)

**Comment by DestroyerIV** [comment]
> No veo `bot.answerCallbackQuery`en el código que publicaste.
> 
> Estoy haciendo referencia a este método: [método answerCallbackQuery en Telegram](https://core.telegram.org/bots/api#answercallbackquery)

hello, after so much time I still do not understand where to put bot.answerCallbackQuery ().

Another one of my doubts is, because when I run a bot.onText () for the first time with buttons, it does not multiply my results and when I use it for the second time it repeats results.

**Comment by DestroyerIV** [comment]
Everything was fixed using the `bot.removeListener('callback_query')` method
