### ISSUE TITLE
how can I get the group history message ?

### ISSUE THREAD

**Issue by YDJSZY** [yagop/node-telegram-bot-api#577]
I use node to get group message。when I start node and how can I get the group history message ?

**Comment by YDJSZY** [comment]
@sidelux I knew it. you are right!

**Comment by saberShenFeng** [comment]
@sidelux Hello,do you know how to delete a message from a bot ? I get a troblue that need to delete messages sent by other robots in a telegram group. I have tried the bot.on('message',msg=>{}) , but it can not listen any message from  bots . can you help me , please .

**Comment by saberShenFeng** [comment]
@sidelux Hello,do you know how to delete a message from a bot ? I get a trouble that need to delete messages sent by other robots in a telegram group. I have tried the bot.on('message',msg=>{}) , but it can not listen any message from rebot. can you help me , please .

**Comment by sidelux** [comment]
@saberShenFeng You can delete only message sent after your bot is added in the group.
Then you can use this function:
```
var chat_id = 12345;
var message_id = 12345;
bot.deleteMessage(message_id, message_id);
```
For chat_id usually you can use message.chat.id, to message_id instead you should save all messages ids in a database and get later when you need.
Like this for example:
```
bot.on('message', function (message) {
    // save message.message_id somewhere...
});
```

**Comment by sidelux** [comment]
That function is the only that can listen messages...
Maybe you must set bot privacy to listen all messages and not only commands. To do that use `/setprivacy` in @BotFather and follow instructions.

**Comment by saberShenFeng** [comment]
thanks , I have set /setprivacy  to disable , but the function still can not listen the message from other bots.

`bot.onText(/123/, (msg) => {
    let chatId = msg.chat.id;
    let messageId = msg.message_id;

    console.log('did receive listen msg->'+JSON.stringify(msg,null,100));

    bot.sendMessage(chatId,'bot did receive your message ');
    
    setTimeout(function () {

        let deleteMessageId = messageId + 1;
        bot.deleteMessage(chatId,deleteMessageId).then(msg=>{

            console.log('deleteResult:',msg);
        }).catch(error=>console.log(error));
    },1000 * 5);
});` 
I write this function and it works ,can delete message from rebot,but in fact, due to the network delay, the messageId of the reply does not necessarily increase by 1. so ..you know ,this question is depending on whether i can get the messageId of other rebots reply to？

**Comment by sidelux** [comment]
Oh wait, bots can't listen messages sent by other bots (or itself).
You can read it [here](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots).

Btw in your case you should use something like this:
```
bot.sendMessage(chatId,'bot did receive your message').then(function (message) {
    bot.deleteMessage(chatId, message.message_id).then(msg=>{
        console.log('deleteResult:', msg);
    }).catch(error=>console.log(error));
});
```

**Comment by saberShenFeng** [comment]
it works !!!!!!! Thanks,Thanks,Thanks,Thanks!
