### ISSUE TITLE
Spamming

### ISSUE THREAD

**Issue by kayrosik** [yagop/node-telegram-bot-api#578]
I have simple code. 
`bot.on('message',(msg) =>{
     const {chat:{id}}=msg;
     bot.sendMessage(id,"Sometext");
})`
When someone starts spamming messages, I have error in console "400 Bad Request...".
Has api any functions for blocking spam? I can't find.

**Comment by sidelux** [comment]
I wrote this function that return false is user flooding.
```
var timevar = [];
function checkSpam(message) {
	var isOk = true;
	var diff = 0;
	if (timevar[message.from.id] != undefined) {
		diff = new Date() / 1000 - timevar[message.from.id];
		if (diff < 0.8) {
			isOk = false;
		}
	}
	timevar[message.from.id] = new Date() / 1000;
	return isOk;
}

bot.onText('test', function (message) {
	if (!checkSpam(message))
		return;
	// your function...
});
```

**Comment by mrvuit** [comment]
I based on the idea of **sidelux**, I edited it to store with a log file.
`	function checkSpam(chatId) {
		var filePath = "folder/" + chatId + ".log"
		var isOk = true;
		var diff = 0;
		if (fs.existsSync(filePath)) {
			diff = new Date() / 1000 - fs.readFileSync(filePath).toString();
			if (diff < 1) {
				isOk = false;
			}
		}
		fs.writeFileSync(filePath, new Date() / 1000);
		return isOk;
	}`

**Comment by sidelux** [comment]
You can also do with a Database (poor filesystem :'))

**Comment by mrvuit** [comment]
> You can also do with a database (poor filesystem :'))

The query time will slow down your bot, I tried the database but failed.
