### ISSUE TITLE
bot doesn't detect removal of itself inside a group, no events fired

### ISSUE THREAD

**Issue by mikesmarter** [yagop/node-telegram-bot-api#579]
bot doesn't detect removall of itself inside a group, it doesn't fire any events not even these:

`telegram.on("message", function(message) {..});`

nor 

`telegram.on("left_chat_member", function(message) {...});`

But telegram API states this:

> left_chat_member | User | Optional. A member was removed from the group, information about them (this member may be the bot itself)

Ok, i just found it this only doesn't work with supergroups, with groups i receive the event from the bot

**Comment by sidelux** [comment]
You can't detect with an events.
You should "ping" a group with a command, for example getChatMembersCount, if this function return false or with errors, your bot can't access group members so is blocked from the group.

**Comment by mikesmarter** [comment]
> You can't detect with an event.
> You should "ping" a group with a command, for example getChatMembersCount, if this function return false or errors, your bot can't access group members so is blocked from the group.

But i receive an event for groups, only supergroups not, is that a bug in telegram, where did you find that information?

**Comment by sidelux** [comment]
It’s a “feature” of telegram, cause api could emit too much events i think.
In normal group there are less people ;)

**Comment by thexbasic** [comment]
@sidelux having the same problem... 
`Error: 403 {"ok":false,"error_code":403,"description":"Forbidden: bot was kicked from the group chat"}`
what would be the best way to handle it? do a `try {} catch(e) {}` around or append `.catch(e => {}) ` to the send method?
Gotta do this at alot of code places, so I'm asking...

**Comment by sidelux** [comment]
Well, with try catch you handle also "deleted user", "no permission", etc. so you should filter by description... But it should be work.
Btw i suggest always to save list of groups where your bot is and eventually "ping" all list to know when you has been kicked.
