### ISSUE TITLE
How to RESTART bot

### ISSUE THREAD

**Issue by dotnrx** [yagop/node-telegram-bot-api#580]
I know, how to stop bot. It's - bot.stopPolling(); than bot will off.
But how to restart my bot? Is There any ways?

**Comment by sidelux** [comment]
.[startPolling](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+startPolling) :)

**Comment by NeroxFB** [comment]
i tried it, no result(, another idea?

**Comment by sidelux** [comment]
Use a package like pm2 or forever and use [pm2](http://pm2.keymetrics.io/) restart or [forever](https://github.com/foreverjs/forever) stop and next start. But startPolling must work, what error prints?

**Comment by timothe** [comment]
I think the idea is to restart the script here. We can shut it down with `process.exit()` and `forever` will resurrect it.

However when I try to use a command like `/die` with the bot, then restart it, it seems it keeps the last message in memory, and the script shuts down immediately (same if I ask it to send a message then die: the message is sent and the process exits).

Full example below:
```
teleMessenger.startPolling();
teleMessenger.on("text", msg => {
  switch (msg.text) {
    case "/die":
      teleMessenger.sendMessage(msg.chat.id,'I died 😵')
        .then(() => {
          process.exit();
        });
      break;
    default:
  }
});
```

Do you know a workaround for that?

**Comment by ouya99** [comment]
+1 
@timothe did you find a nice solution to restart the bot without keeping last message in memory?

**Comment by timothe** [comment]
Hi @ouya99 !

I did, using the `forever` package and killing the process with a message as in the example below:
```
Utils.teleMessenger.on('text', msg => {
  if (Date.now() - msg.date * 1000 < 1000) {    // Check if the message is not old
    switch (true) {
      // Text example with "die now" in the msg
      case /die now/iu.test(msg.text):
        Utils.teleMessenger.sendMessage(msg.chat.id, 'I dieded 😵').then(() => {
          process.exit(); // Kill the node process, forever will restart it
        });
        break;
      default:
    }
  }
});
```
