### ISSUE TITLE
Can't send message with photo now

### ISSUE THREAD

**Issue by iMrPoopybutthole** [yagop/node-telegram-bot-api#582]
Guys please help, at now I cant send message with any photo, they all are just blank, here is my code:

`var post_html = post_text+'<a href="'+post_img+'">&#160</a>';`
`bot.sendMessage(config.telegram.chat, post_html, {`
`"parse_mode":"HTML"`
`});`

post_img is simple url like http://website.com/test.jpg

This work a few days ago but not now...

**Comment by saeedhei** [comment]
You Should use: `bot.sendPhoto()`

**Comment by crappyrules** [comment]
PLEASE HELP WITH FLURBO!!!!

**Comment by iMrPoopybutthole** [comment]
crappyrules please write me in telegram to @iMrPoopybutthole

**Comment by jejopl** [comment]
It's because you are sending a link and hard space inside. That's why you can't see it. If you want to see this link you should have some text instead of &#160
If you want to send only a photo you should use 
> bot.sendPhoto(chatId, imageUrl);
