### ISSUE TITLE
Error after deploy on Heroku

### ISSUE THREAD

**Issue by pavlyukpetr** [yagop/node-telegram-bot-api#584]
Hello,
when I launch my app on Heroku it works fine but only about 60 sec. After I have the error:
2018-05-13T17:00:42.322368+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-05-13T17:00:42.322473+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-05-13T17:00:42.445295+00:00 heroku[web.1]: State changed from starting to crashed
2018-05-13T17:00:42.427790+00:00 heroku[web.1]: Process exited with status 137

How can I fix it?

**Comment by sidelux** [comment]
I found a solution in stackoverflow:
"Heroku dynamically assigns your app a port, so you can't set the port to a fixed number. Heroku adds the port to the env, so you can pull it from there. Switch your listen to this:
`.listen(process.env.PORT || 5000)`
That way it'll still listen to port 5000 when you test locally, but it will also work on Heroku.
You can check out the Heroku docs on Node.js here."

[Source](https://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of)

**Comment by pavlyukpetr** [comment]
@sidelux  thank you, i will try

**Comment by lbltavares** [comment]
> Fixed the issue.
> Instead of web: node index.js I use worker: node index.js

how did you change this?

**Comment by thihenos** [comment]
> > Fixed the issue.
> > Instead of web: node index.js I use worker: node index.js
> 
> how did you change this?

@lbltavares on Procfile on project path, you need this file to create a heroku applicatiob
