### ISSUE TITLE
[question] cancellation of Promises

### ISSUE THREAD

**Issue by 7twin** [yagop/node-telegram-bot-api#587]
I am getting the deprecated message of #319, even after moving the requires to the very top and even after removing any promises to the bot instance, is it just displayed for everybody? to make sure they see the change?

**Comment by sidelux** [comment]
What you mean with 'everybody'?
Only you from console can see deprecations...

**Comment by 7twin** [comment]
@sidelux I mean every developer that has it required, is the deprecation message shown, even if you're not using promises before requiring it? since looking at the commit it seems the message would only appear if the variable is set, but as said, I removed all promises and put the require at the very top but the message still appears

**Comment by sidelux** [comment]
You have used this line?
`process.env["NTBA_FIX_319"] = 1;`
I am at 100% sure that works, i used in 5 bots i have.

**Comment by 7twin** [comment]
@sidelux I didn't, because I thought I don't need to have promises before I include the library, but yet it still shows the message for some reason, I guess I could set the variable to make it stop, but I wanted to know if it just shows the deprecated message to everybody, even if I am not directly affected by it

**Comment by sidelux** [comment]
I think it shows regardless of how bot do, if you see in this [complete file commit](https://github.com/yagop/node-telegram-bot-api/blob/f4f015a6219fc8efdb521dad72fb860361235de8/src/telegram.js#L53) you can notice that there are no condition to not print that message error (except the process.env "line").
Same problem to #350.

**Comment by 7twin** [comment]
@sidelux oh, I actually missed the negation yesterday, when quickly hovering over the changes, thank you!
