### ISSUE TITLE
Telegram bot cannot see messages from group

### ISSUE THREAD

**Issue by samumeur** [yagop/node-telegram-bot-api#591]
Hello, 

I created a little nodeJS application that listen to messages send to my telegram bot, then answere.
All is right for that, it's working well.
But after that, I wanted to link my bot to the IFTTT telegram bot, to make them "discuss" into a telegram group.
So I created a group with me, my nodeJS bot, and the IFTTT bot. When I send a message in the group, my nodeJS bot see it, and reply correctely.
But when the IFTTT bot send a message into the group, I don't receive anything in the "on message" event.

This is my code:

```
const TelegramBot = require('node-telegram-bot-api');
const token = 'XXXXXXX:XXXXXXXXXXXXXXXXXXXXXX';  (= my token)

bot.on('message', (msg) => {
	DecryptFunction(msg.text, function (ReturnResponse) { bot.sendMessage(msg.chat.id, ReturnResponse);})
});
```

I already set my bot privacy to disable then add it to the group as admin.

Thanks in advance for your help

**Comment by sidelux** [comment]
What function is "DecryptFunction"?

By the way before make any complicated operation, try to debug with console.log like this:
```
bot.on('message', (msg) => {
    console.log(msg);
});
```
So you can know if is a problem of bot in general or problem of your function.

**Comment by sidelux** [comment]
Bot can't read other bots messages!
See [Bots FAQ](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots).

**Comment by samumeur** [comment]
Oh actually I didn't saw this point, thanks for your answere!
I was already thinking about a solution like that, I will change my app :)

Thanks!
