### ISSUE TITLE
InlineQueryResultCachedPhoto

### ISSUE THREAD

**Issue by dotnrx** [yagop/node-telegram-bot-api#593]
Is there way to use it? I didn't find it in telegram.js

**Comment by sidelux** [comment]
Can you provide an example to where you should use it?

**Comment by danielperez9430** [comment]
Hi @dotnrx this is not a method in the API, it's `A JSON-serialized array of results for the inline query` for the "answerInlineQuery" method. In the end is create a array with the params of the inlinequery result that you want to send
