### ISSUE TITLE
polling error when running a demo code 

### ISSUE THREAD

**Issue by ritsuyan** [yagop/node-telegram-bot-api#594]
I just simply run a demo code on a US VPS.
```
const bot = new TelegramBot(token, {polling: true});

bot.on('message', function(msg) {
	if (msg.new_chat_members != undefined) {
		bot.sendMessage(msg.chat.id, msg.new_chat_member.username + " Bienvenido");
	}
});
```
when I send the message to bot it consoles log polling error not give a reason .

**Comment by sidelux** [comment]
First try with only a console.log.
const bot = new TelegramBot(token, {polling: true});

```
bot.on('message', function(msg) {
	console.log(msg);
});
```

If it works try to check syntax.

**Comment by amberleitl** [comment]
I'm trying to set up a simple bot for an Instagram engagement group on telegram that moniters comments and engagement is there anyone here that can help me with this even installing one that is already made I've tried to /config a bot and it doesn't send me the list of commands my telegram is Amber Leitl my insta is @amberleitl I would much appreciate some help

**Comment by serembon** [comment]
Try to add this on 1st line:
`process.env["NTBA_FIX_319"] = 1;`

**Comment by amberleitl** [comment]
So when I add the bot to the group I make it an admin and then type that
into the chat?

**Comment by amberleitl** [comment]
I'm so confused because I don't know code you are on telegram right? If I
add you to my group can you install group Butler beta into my group?

**Comment by aorfevre** [comment]
@amberleitl ; group buttler is rather easy to install .
Try to find some tutorials on internet ;) you will succeed !

**Comment by amberleitl** [comment]
I did and I follow the tutorials but it doesn't work for me 😢

**Comment by kenixer** [comment]
Am I the only one confused in this topic?
Are we talking about working on backend nodejs telegram bot, or just adding bot to the group without coding?

**Comment by kenixer** [comment]
I'm looking for the solution cause my node script is just giving me a polling error every time, and looks like many people are having same problem. But seems like nobody has a solution.

**Comment by sergeyrudenko** [comment]
check syntax in your app

**Comment by droidmanspace** [comment]
If you are making two instance of TelegramBot with same token, it will definitely ends in polling error. So check your process and kill all node processes. After that try to run the bot. It will work.

**Comment by droidmanspace** [comment]
@kenixer and @amberleitl, if you still facing the issue. I CAN HELP YOU. Telegram :, https://t.me/droid_man

**Comment by deshmukhsanket** [comment]
Is there any way we can run it without polling?
