### ISSUE TITLE
sendMessage to thousands of persons : How to proceed ?

### ISSUE THREAD

**Issue by aorfevre** [yagop/node-telegram-bot-api#596]
> Question

Hi,
I'm willing to send a Direct Message from my bot to a list of around 30 000 users.

First; I tried a basic loop; hoping that is was going to do well  
```
    for(var i in myArray){
        bot.sendMessage(Number(i),_txt,options)
    }
```
My users did not received my message.

After investigation; someone told me that telegram has a limitation of 25/30 messages / seconds.
I have therefore added the following code to wait
```

var _sleep = function(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){
      break;
    }
  }
}


    for(var i in myArray){
        _count++
        _limit ++


        if(_limit === 25){
          _sleep(1001)
          _limit = 0
        }

         bot.sendMessage(Number(i),_txt,options)


    }
```

Still the same case; my users do not seems to receive my message.

> How do you guys manage sending one message to multiple users ?
> How shall I proceed?

thank you so much for support !

**Comment by sidelux** [comment]
Make a pool via database, then send N in a wave system.
Simply first add all chat_ids in a table, then you can use a function like this:

```
var global_msg = 1;

callNTimes(60000, function () {	//every 1 minute call this function
	checkGlobalMsg();
});

function checkGlobalMsg() {
	if (global_msg == 1){
		connection.query('SELECT chat_id FROM global_msg LIMIT 200', function (err, rows, fields) {
			if (err) throw err;
			if (Object.keys(rows).length > 0) {
				for (var i = 0, len = Object.keys(rows).length; i < len; i++) {
					bot.sendMessage(rows[i].chat_id, "A global message!");
					connection.query('DELETE FROM global_msg WHERE chat_id = ' + rows[i].chat_id, function (err, rows, fields) {
						if (err) throw err;
					});
				}
			}else{
				// set a flag to 0
				global_msg = 0;
			}
		});
	}
}

function callNTimes(time, fn) {
	function callFn() {
		if (1 < 0) return;
		fn();
		setTimeout(callFn, time);
	}
	setTimeout(callFn, time);
}
```

Is not the most optimized way but it works also when you reboot the bot or similar and not load all messages in memory.

**Comment by aorfevre** [comment]
First of all, 

thank you so  much for your returns @sidelux & @saeedhei 

As I firsly see, on both post; you englob your array with setTimeout.
I'll do that.

How many messages do you recommand per minutes ? 20 ? 30 ? more ? less ?

**Comment by saeedhei** [comment]
Telegram Api ref: (https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once)

**Comment by aorfevre** [comment]
@saeedhei in your solution that I like very much, you never kill the setInterval ? 

@sidelux I'll implement your solution in a second time.
Clearly having a database update / control is mandatory when it we speak about bulk messaging !

**Comment by alexandercerutti** [comment]
To manage a bunch of asynchronous operations, I use [async library](http://caolan.github.io/async/) on NPM.
In particular, you may want to use `async.eachOfLimit`, which let you specify an array of elements (in your case the recipients) and execute a function (`iteratee`) for each element, with a limit of operation to be executed together.

**Comment by aorfevre** [comment]
I just closed this issue. 
It has been well replied. 

Thank you for your support !
