### ISSUE TITLE
Example of MTProto Proxies

### ISSUE THREAD

**Issue by saeedhei** [yagop/node-telegram-bot-api#597]
How to Connect Telegram Bot to MTProto Proxies via Node.js?

**Comment by sidelux** [comment]
You can use that library for server side: https://github.com/FreedomPrevails/JSMTProxy
And then follow [this](https://github.com/yagop/node-telegram-bot-api/issues/122#issuecomment-270843109) method.

**Comment by saeedhei** [comment]
What Should I put in `request`?
Secret and port?
```
const bot = new TelegramBot(token, {
  polling: true,
  request: {
    proxy: "http://127.0.0.1:1234",
  },
});
```

**Comment by saeedhei** [comment]
I will check that. But I think that need secrect too
![20180613_202905](https://user-images.githubusercontent.com/25050762/41363287-c656b928-6f48-11e8-866e-0e9ac4841d88.png)

**Comment by aminjoharinia** [comment]
Anyone Solve This Problem?
How could we use secret?

**Comment by sidelux** [comment]
I have found only [this library](https://github.com/dotcypress/mtproxy) that support secret, try it.

**Comment by IlyaSemenov** [comment]
Please correct me if I'm wrong but from I see there is no way to use MTProxy. `options.request.proxy` is passed to [`request`'s options](https://github.com/request/request/#proxies) which only supports http and https (not even socks). After all, telegram bot API uses HTTPS requests, not MTProto connections.

For SOCKS, there's a workaround:

```ts
import Socks5HttpsAgent from 'socks5-https-client/lib/Agent'

const bot = new TelegramBot(telegramBotToken, {
	request: {
		agentClass: Socks5HttpsAgent,
		agentOptions: {
			socksHost: url.hostname,
			socksPort: url.port,
			socksUsername: url.username,
			socksPassword: url.password,
		},
	},
})
```

**Comment by saeedhei** [comment]
https://github.com/sadra/EasyMTProto

**Comment by kamikazechaser** [comment]
@IlyaSemenov Correct, as far as this library is concerned.

**Comment by mostafa8026** [comment]
If anyone uses `SocksProxyAgent`, this config is useful:

``` typescript
import { SocksProxyAgent } from 'socks-proxy-agent';

const options: TelegramBot.ConstructorOptions = { polling: true };
if (proxyType.toUpperCase() === ProxyTypeEnum.HTTP) {
  options.request = {
    url: '',
    proxy: `http://${username}:${password}@${host}:${port}`,
  };
} else if (proxyType.toUpperCase() === ProxyTypeEnum.SOCKS) {
  const agent = new SocksProxyAgent({
    hostname: host,
    port: port,
    auth: `${username}:${password}`,
    type: 5, // socks5
    protocol: 'socks',
  });
  options.request = {
    url: '',
    agent,
  }
}
this.bot = new TelegramBot(token, options);
```
