### ISSUE TITLE
sendMessage with reply_markup

### ISSUE THREAD

**Issue by Illyism** [yagop/node-telegram-bot-api#6]
Having some issues with using [sendMessage](https://core.telegram.org/bots/api#sendmessage) with reply_markup. Were you able to get this to work?

![2015-07-07-165136_517x363_scrot](https://cloud.githubusercontent.com/assets/304283/8548982/7b4d2156-24c8-11e5-8217-fee98d70f532.png)

This is what I send if I inspect using request.bin. Maybe it needs to be a POST instead? I tried that but couldn't get it to work either.

**Comment by yagop** [comment]
I've written an example with `reply_markup`. Your problem might be you aren’t JSON encoding the reply_markup.

f5170c573c2a464061c670925df5ac9d8f98eed2

**Comment by Illyism** [comment]
Jesus christ. Thank you!

**Comment by Illyism** [comment]
That was it, thanks!
