### ISSUE TITLE
Can I get IP for a user ?

### ISSUE THREAD

**Issue by aorfevre** [yagop/node-telegram-bot-api#601]
Hi Everyone,

I'm making some bots that may be used by fake users using the same IP address.

I would like that have a way to determine the IP Address OR Mac address of someone using my telegram bots.

Do you guys know a way to do that ? 
If yes, Can you point me to the direction? 

Thank you for your return ! 

Best regards !

**Comment by sidelux** [comment]
You can't. Telegram not send personal data of users in updates.
