### ISSUE TITLE
Social network API -> Can It be connected ?

### ISSUE THREAD

**Issue by aorfevre** [yagop/node-telegram-bot-api#602]
Hi everyone,

I'd like to connect Facebook Social Network API and Twitter API to encourage and track if my bot users are : 
- like / share my facebook post
- like / retweet my twitter's post

We can definitly do that from a webpage but from a telegram bot; I have some doubts.

Is there someone who succeeded on doing that?  
If yes, Can you point me the direction ?

Best regards,
Alex

**Comment by sidelux** [comment]
You can easely integrate with [this](https://www.npmjs.com/package/fb) library for Node.
