### ISSUE TITLE
[polling_error]

### ISSUE THREAD

**Issue by Yur-ok** [yagop/node-telegram-bot-api#603]
> Question

How to fix this error?

error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ECONNREFUSED 149.154.167.220:443"}

I'am just trying write my first bot.
I'am junior in programming and I try to do this step by step from youtube. In the course author did't have same error.
So I confused how to fix this.

**Comment by hsikhakolli** [comment]
@Yur-ok  How did you solve this ??.If you get it solved how did you do that. If you have a solution can you please explain me

**Comment by JasinYip** [comment]
Same here, how did you solve this??

**Comment by DesTincT** [comment]
@Yur-ok One more)

**Comment by JasinYip** [comment]
I am in China, maybe case the government blocked Telegram, now I run the program on Linode machine and it workds.

**Comment by Ningaro** [comment]
One more xD

**Comment by batych** [comment]
Guys, it's because of Telegramm blocking in Russia, use VPN

**Comment by JasinYip** [comment]
> Guys, it's because of Telegramm blocking in Russia, use VPN

We Chinese are be with you😅

**Comment by xk361** [comment]
有没有解决掉的 我也是这样、

**Comment by rahi62** [comment]
i use v2rayN config as vpn  with warp configuration to change system proxy  however it dose not work and threw same error !
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ECONNREFUSED 10.10.34.35:443"}
dose any body here know the reason and solution?

**Comment by twriad969** [comment]
maybe telegram blocks server ips

**Comment by DucLinh27** [comment]
I have the same issue, and then I change connect internet other. I solved this issue

**Comment by alikhgh80** [comment]
> > Question
> 
> How to fix this error?
> 
> error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ECONNREFUSED 149.154.167.220:443"}
> 
> I'am just trying write my first bot. I'am junior in programming and I try to do this step by step from youtube. In the course author did't have same error. So I confused how to fix this.

if use v2rayN , first run v2rayN run as administrator then  enable tun mode

**Comment by amiramar1368** [comment]
> > > Question
> > 
> > 
> > How to fix this error?
> > error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ECONNREFUSED 149.154.167.220:443"}
> > I'am just trying write my first bot. I'am junior in programming and I try to do this step by step from youtube. In the course author did't have same error. So I confused how to fix this.
> 
> if use v2rayN , first run v2rayN run as administrator then enable tun mode

thanks, it works for me
