### ISSUE TITLE
Preventing url preview with sendMessage()?

### ISSUE THREAD

**Issue by Arlodotexe** [yagop/node-telegram-bot-api#604]
> Question

If you send a URL with sendMessage, it will show up on the other end with a preview of the webpage. Is there some way to prevent this behavior?

**Comment by Arlodotexe** [comment]
I found [this](https://core.telegram.org/bots/api#available-methods), but when trying it, I get the following error:

```
TypeError: Cannot create property 'chat_id' on string
'html'
```
This may have turned into a bug report

**Comment by Arlodotexe** [comment]
I went into the node-telegram-bot .js file where it was erroring, and it turned out that I needed to pass in an object, not additional options like the Telegram API implies. 

So last thing before I close this: 
1. Props for handling optional data this way
2. Please update the documentation. I could not for the life of me find _anywhere_ that this should be passed as an object, or that it was even an option.

**Comment by mcherifi** [comment]
You can do so by using `disable_web_page_preview` option

`bot.sendMessage(chat_id, message, {"disable_web_page_preview": true});`
