### ISSUE TITLE
Question regarding : Cache of Telegram ? Or other thing ?

### ISSUE THREAD

**Issue by aorfevre** [yagop/node-telegram-bot-api#605]
Dear all,

I made a delete function that removes some content based on some rule.
For 99% of my users; it is working fine.
For the remaining 1% ; they still have the content presented on the telegram group.

I assume that it is linked to the cache of Telegram App. I think they are on iOS.
I'm really not sure how to proceed for that as It seems to be linked to Telegram App Cache.

Do you have experienced something like that ?
Do you have any suggestion ? Ideas?  

Best regards,
Alex

**Comment by sidelux** [comment]
It happens something but depends on user situation.
If a phone is turned off then a user turn on after a week (hypothetically), telegram must be process lots of messages and it can happen that some messages (edited, deleted, etc.) could be not correctly processed.
So yes, it's "normal" and i think it's not a definitive solution.
