### ISSUE TITLE
Telegram Limit 30 messages / sec

### ISSUE THREAD

**Issue by aorfevre** [yagop/node-telegram-bot-api#607]
Dear all, 

I discovered a while ago that I can send with my bot only 30 messages / sec.
This is totally fine for bulk messaging.

My question concerns more the behaviour of the bot while using it.

If I have 35 users / seconds having one message sended ; 
how the bot will react ? 
How shall I manage that? 

I do create bots that have a huge traffic and I am worried that some users do not get the desired message.

Thank you in advance,
Best regards,
Alex

**Comment by sidelux** [comment]
I have 1600+ daily users that "spam" commands in my bots and i never had problems like that.
To be more precise, that limit works when lots of messages have same text, in that case my bot not send it after surpass that limit.
So i think there are no problems if you have different text in messages to send in bulk.
Hope it helped you.

**Comment by aner87** [comment]
@sidelux what if you have a keyboard that sends a command to the bot at the press of a button...like "Contact us" button, that generates always the same text response from the bot, and say people keep on clicking it multiple times, what's gonna happen?
You said in that case we would have the problem that @aorfevre described. I feel the limit is very low eheheh
I have a lot of functions in my bot triggered the way I described
