### ISSUE TITLE
How can I get bot's user_id

### ISSUE THREAD

**Issue by feelfreelinux** [yagop/node-telegram-bot-api#609]
> Question

Hi! I my app I need to resolve user_id from my bot instance. How can I do it from this library?

**Comment by alexandercerutti** [comment]
Your question is not so clear for an inconsistency of the issue title with its content. You want to get bot's id or id of a user that contacts your bot?

If the first, it is not possible.
If the second, every `message` structure (received with `bot.on("message", (content) => { ... })` ), contains a substructure `User` (called 'from') which contains the user_id.
If you are trying to get user name ("resolving a user_id") of a user, in the substructure `User` ('from'), as above, there will be available the properties `username` (not available if not setted for that user), `first_name` and `last_name`.

If none of above, please explain better what you are trying to achieve, so we can help you better.

**Comment by saeedhei** [comment]
@feelfreelinux  use `bot.getMe()` and get `id`

**Comment by feelfreelinux** [comment]
@saeedhei Thanks, that did the job!
@alexandercerutti sorry for inconsistency, wanted to get user_id of bot.

**Comment by ibodi** [comment]
You can find out your bot's id here: https://api.telegram.org/bot<bot-token>/getme
