### ISSUE TITLE
Not receiving multiple messages in group chat

### ISSUE THREAD

**Issue by aceslick911** [yagop/node-telegram-bot-api#61]
Hi,

I'm having an issue where a Bot inside a group chat (with privacy mode off) will trigger the event (such as bot.onText) only the first time but not on subsequent messages.

How to reproduce:
1. Create / load a bot which has privacy mode turned off and invite it into a group chat (Use something similar to the example code and long-polling).
2. Trigger the onText event by sending a message to the group-chat room manually.
3. Wait about a minute then try to trigger the bot event again (doesn't have to be the same text). This time the bot's event will fail to fire.
4. Trigger the event by sending a message to the bot directly (This time it will work).
5. Do step 4 again, there is no problem.

Is anyone else able to reproduce this?

**Comment by rickinbsb** [comment]
+1

**Comment by GochoMugo** [comment]
Issues possibly addressing your bug:

1. #174
1. #190 

If information from any of the above issues fixes it for you, please mention it here and close the issue! Otherwise, am marking this issue **stale** to be closed in the future, should **no** activity be seen on this thread!

**Comment by GochoMugo** [comment]
Issue went too stale...
