### ISSUE TITLE
Error while starting node

### ISSUE THREAD

**Issue by CodingDevHub** [yagop/node-telegram-bot-api#611]
All greetings! I'm creating my bot, at file start index.js and error pops up.

![111](https://user-images.githubusercontent.com/40657515/42155096-18f661a0-7df0-11e8-8311-f91da6404207.png)

I read that the error is described in issue 339, but I can not solve anything.

Here is the content of my index.js file:

var TelegramBot = require ('node-telegram-bot-api');
    token = 'xxxxxxx';

var bot = new TelegramBot(token, {

});
bot.on('message', function (msg) {
console.log(msg);

})

**Comment by sidelux** [comment]
#476, btw is not an "error", is a warning and can be ignored.

**Comment by CodingDevHub** [comment]
Thanks understood! :)
