### ISSUE TITLE
ETELEGRAM: 400 Bad Request: location can be requested in a private chats only

### ISSUE THREAD

**Issue by svillegas9** [yagop/node-telegram-bot-api#612]
When I run my group placement request this delivers an error 400

I'm new to this topic and I use the example but it's impossible for me to get the answer in a group, but in the bot

------------------------------------------------------------------------------------------------------
const TelegramBot = require('node-telegram-bot-api');
 
 // API Token Telegram
 const token = 'XXXXXXXX';
 
 // Creamos un bot que usa 'polling' para obtener actualizaciones
 const bot = new TelegramBot(token, {polling: true});
 const request = require('request');

 bot.onText(/start/, (msg) => {
    const opts = {
      reply_markup: JSON.stringify({
        keyboard: [
          [{text: 'Location', request_location: true}],
          [{text: 'Contact', request_contact: true}],
        ],
        resize_keyboard: true,
        one_time_keyboard: true,
      }),
    };
    bot.sendMessage(msg.chat.id, 'Contact and Location request', opts);
  });
  
  bot.on('location', (msg) => {
    console.log(msg.location.latitude);
    console.log(msg.location.longitude);
  });

**Comment by sidelux** [comment]
What is not clear?
Telegram has decided to make location via bot only in private mode...
![image](https://user-images.githubusercontent.com/18572941/42441069-a7020248-8367-11e8-9183-7f8d81ceba31.png)
At least you can try with @BotFather's [/setinlinegeo](https://core.telegram.org/bots/inline#location-based-results) but only works in inline mode and bot request permission to user to allow access to his position.

**Comment by svillegas9** [comment]
There is a way to share the location in a group automatically configure /setinlinegeo but does not work in the group @sidelux Thaks
