### ISSUE TITLE
Set image size

### ISSUE THREAD

**Issue by Reinhadt** [yagop/node-telegram-bot-api#615]
Hi, I'm working with sendPhoto method and I wonder if there is a way in telegram api to set the size of the image I'm sending to user. The photos are sending in 260x260 pixels and the original file size is 50x50.
I readed docs without success. Thanks in advance!

**Comment by sidelux** [comment]
Are you sure that your image is 50x50? Can you send it here?
Anyway, images are store in many [different sizes](https://core.telegram.org/constructor/photoSize).

**Comment by Reinhadt** [comment]
Yes, the original file size (the one I get from the server) is 50x50 but telegram is showing it in 260x260 making it look blurred. I've searched and can't find a way to use photoSize method. have anybody use it before?

Thanks in advance again!

**Comment by sidelux** [comment]
photoSize is not a method, is a component of message.photo response.
I provide you and example:

```
[ { file_id: 'AgADAgADJKkxGxZhKUrjHUno1QPb-1eyqw4ABNGcO7ilfvNvnGgDAAEC',
    file_size: 1319,
    file_path: 'photos/file_2921.jpg',
    width: 90,
    height: 43 },
  { file_id: 'AgADAgADJKkxGxZhKUrjHUno1QPb-1eyqw4ABGFlFbMVw4s2nmgDAAEC',
    file_size: 17724,
    width: 320,
    height: 154 },
  { file_id: 'AgADAgADJKkxGxZhKUrjHUno1QPb-1eyqw4ABA3ywPL86isIn2gDAAEC',
    file_size: 74458,
    width: 800,
    height: 386 },
  { file_id: 'AgADAgADJKkxGxZhKUrjHUno1QPb-1eyqw4ABPH-wgtpV3fsnWgDAAEC',
    file_size: 126689,
    width: 1140,
    height: 550 } ]
```
This is _console.log(message.photo)_, but with sendPhoto i think that your image is not resized...

The correct usage for sendPhoto is that:
```
var url = "https://web.net/img.png"; // or: "/home/user/myphoto.png"
bot.sendPhoto(message.chat.id, url);
```

Hope it help you.
