### ISSUE TITLE
message listener 

### ISSUE THREAD

**Issue by yarosvitkin** [yagop/node-telegram-bot-api#616]
Hi , how I can turn off  message listener in the telegram bot?

**Comment by sidelux** [comment]
You mean getUpdates?

**Comment by yarosvitkin** [comment]
No , I mean "bot.on('message')

**Comment by sidelux** [comment]
Ok then,
if you get updates via polling:
`bot.stopPolling();`
and then if you need:
`bot.startPolling();`

if you get updates via webhook:
`bot.closeWebHook();`
and then if you need:
`bot.openWebHook();`

It should working as you expected ;)

**Comment by aorfevre** [comment]
dear @yarosvitkin 
If @sidelux answer is correct and solving your case; please CLOSE THE ISSUE.

Best regars,
