### ISSUE TITLE
Question: callback from markup keyboard

### ISSUE THREAD

**Issue by kekkokk** [yagop/node-telegram-bot-api#617]
Hi guys,
I'd like to know if is somehow possible to get a callback query when an user press a button in a NON inline keyboard button.

Just an example: 
I am doing a project where if authenticated, the bot will send me a custom keyboard with all my "connected" devices. Once I press on one of them I'd like to have a callback with the id of the device.
So I can display a friendly name on the button, but receive a code whenever this button is pressed.

![screen shot 2018-07-16 at 22 13 27](https://user-images.githubusercontent.com/15072723/42781116-840e9db2-8945-11e8-888c-6b88a05ebdcf.png)

Is it possible? 
thanks.
Francesco

**Comment by sidelux** [comment]
I think you can't but with my projects i have found a simple solution.
`[["1. Device"],["2. Device"],[...]]`
So, in the code you can remove text part and keep initial number to identify the device like this:
```
bot.onText(/^([0-9]). (?:.+)$/g, , function (message, match) {
    var deviceId = match[1];
    if (deviceId == 1)
        ...
    else if (deviceId == 2)
        ...
    else
        // error deviceId not found...
});
```

Hope it helped you.

**Comment by kekkokk** [comment]
Hi @sidelux, thank you, I already did a similar solution using regex but it's kinda ugly and I need to pass "complex" callback stringyfied onjects in callback.
I cannot explain why the normal keyboard can't have callback_data (wtf??).
Thinking to switch to inline one...

Anyway thanks for the reply!

**Comment by aorfevre** [comment]
There is no callback capability for keyboard buttons. 
I have been disapointed too :(
