### ISSUE TITLE
How can I handle sessions on bot?

### ISSUE THREAD

**Issue by aner87** [yagop/node-telegram-bot-api#619]
Hello, I deployed a bot on heroku and I'm testing it.

I have no idea nor I found informations here on how to handle the flux of informations that the users send me when I LISTEN to some text.

For example: 
```
bot.on('message', (msg) => {
  var btnprss = "Button pressed text";
  if (msg.text.toString().includes(btnprss)) {
    bot.sendMessage(msg.chat.id, "Welcome!");
   }
});
```

How do I know here which user's message the bot is listening to?
In other words, how can the bot know which user sent him the text he's looking for?

Should I add something inside the bot.on('message'.....) parenthesis in order to identify the chat.id? 

When I use the send a message method, I assume that "msg.chat.id" before the text I want to send is foundamental in order to direct the message correctly.

Thanks to everybody, kind regards

**Comment by aorfevre** [comment]
You already have an object returned That is MSG

check it out, everything necessary is inside. 
console.log(msg)

**Comment by aner87** [comment]
Thanks for the reply man!
and thanks for the tip!
I just can't figure out what is the best thing to confront: from.id? 
update_id of the message? what's the most secure and unique that is most largely used?

I wanna be sure because I will have lots of user giving the same commands over and over

Thank you =)

**Comment by aorfevre** [comment]
If you are in private with the bot; you should use : `msg.chat.id` that is the user ID that is speaking
If you are on a group; use `chat.from.id `; that is the user speaking

If these answers are solving your case; please; CLOSE THE ISSUE ;)

**Comment by aner87** [comment]
hehe not really...last question I swear :p 
since I have quite a few bot.on listening that have to be referred to the specific user chatting 1vs1 with my bot, can I do something like this in order to control which user is typing?

```
bot.on('message', async (msg) => {
   const currentChatID = msg.chat.id;

   if (msg.from.id == currentChatID){
         var stair1 = "Start 1";
         var stair2 = "Start 2";
         var stair3 = "Start 3";
      
         if (msg.text.toString().includes(stair1)) {
             bot.sendMessage(currentChatID, "do something");
         });

        if (msg.text.toString().includes(stair2)) {
            bot.sendMessage(currentChatID, "do something else");
         });

        if (msg.text.toString().includes(stair3)) {
           bot.sendMessage(currentChatID, "do something different");
         });
    }
}

```

**Comment by aorfevre** [comment]
```
bot.on('message', async (msg) => {
   const currentChatID = msg.chat.id;
// Why do you need that ? IF ? 
//   if (msg.from.id == currentChatID){
         var stair1 = "Start 1";
         var stair2 = "Start 2";
         var stair3 = "Start 3";

// I personnaly do SWITCH or if / else if / else if       
         if (msg.text.toString().includes(stair1)) {
             bot.sendMessage(currentChatID, "do something");
         };
        if (msg.text.toString().includes(stair2)) {
            bot.sendMessage(currentChatID, "do something else");
         };
        if (msg.text.toString().includes(stair3)) {
           bot.sendMessage(currentChatID, "do something different");
         };
  //  }
}
```

There is no real need to do a if msg.chat. 
You do not need to do a specific bot.on for every user.

What you can do storing your user info such as `global.myUsers = []`
and us it as is : `myUsers[msg.chat.id] = XXXX`

**Comment by aner87** [comment]
That is amazing!! thanks :)
I believe is exactly what I need!
I'll put some study on that: do you happen to have any example that use this method to understand which user sent which request? 

Cheers, thanks again

**Comment by aorfevre** [comment]
Why do you need to track where an user is ? :)

**Comment by aner87** [comment]
First of all, thank you man! 😃
I accomplished a lot yesterday thanks to your suggestions.

Now, my goal is making the bot listen on a text that triggers a response containing something like "send me your email now:", and then listen again for the random text the user sends, control it, and reply back with a success or a failure message 😅

**Comment by leodanmendez113** [comment]
Hola tengo el mismo problema alguien me puede ayudar como hago para que mi bot diferencie un usuario de otro pues tengo varios usuarios habiendo peticiones al mismo tiempo y eso marea al bot hace que envíe mensajes donde no son
