### ISSUE TITLE
Pooling vs long pooling vs webhook

### ISSUE THREAD

**Issue by aorfevre** [yagop/node-telegram-bot-api#620]
Dear all, 

I badly need some clarification and advices.

First of all, what is The différence between polling and long polling ? I saw several posts, including in Closed issues suggesting tô do long polling. But in configuration of my bot, i do not see any thing related to That.

Then i do understand how polling and webhook works. 
I am trying to understand what is more efficient for me. 

My bots attract lot of users in a very very short time. To give you métrics, it is around 40/50k users in 3 tô 7 days.

Users are doing some data input on The bot and datas are stored on a local mongodb. 

I face latency issues 
What is more efficient in terms of performances for the end user ?
From my small understanding, i would say That webhook May be better as it only sends necessary updates when polling Still check for updates if not necessary. 

On The other hand, Maybe i need to delay The polling ?

Best regards, 
Alex

**Comment by sidelux** [comment]
Long polling: your server ask telegram servers to get updates (messages)
Webhook: telegram server send you new updates then your server reply with http code 200 (OK)

Usually when you have lots of user Webhook is the best choice, cause your server is not stressed with continue requests to web.
