### ISSUE TITLE
bot.answerCallbackQuery has been deprecated, any other option?

### ISSUE THREAD

**Issue by DestroyerIV** [yagop/node-telegram-bot-api#622]
After testing the answerCallbackQuery method with its associated buttons for long hours, I see in the console that it says the following:

```
node-telegram-bot-api deprecated The method signature answerCallbackQuery([options]) has been
deprecated since v0.29.0
```
There is some other method that handles or has the same functionality as answerCallbackQuery?
I also took a look at the documentation and I do not see anything about it

Thanks in advance

**Comment by sidelux** [comment]
Very easy solution:
`bot.answerCallbackQuery(message.id, {text: 'Your message'});`

**Comment by DestroyerIV** [comment]
I'll try it and I'll tell you, thank you very much :stuck_out_tongue_winking_eye:
