### ISSUE TITLE
Please help to make menu like this

### ISSUE THREAD

**Issue by NeroxFB** [yagop/node-telegram-bot-api#628]
Hello, Who knows how to make auto putting buttons in menu.
For example there are arrays:
[Button1, Button2, Button3]
It will be like this in telegram menu:
[Button1] [Button2]
[         Button3       ]

**Comment by saeedhei** [comment]
Here
```js
const FlagKeyboard = [
  ['1'],
  ['1','2'],
  ['1', '2','3'],
];
```

**Comment by sidelux** [comment]
$key = [[$btn[0], $btn[1]], [$btn[2]]]

**Comment by NeroxFB** [comment]
Okey, but how I can drop it from my BD.
For example:
connection.query('SELECT * FROM buttons', (error, results, fields) => {
   for(let ff = count; ff < results.length; ++ff){ 
      buttn[ff] = results.Buttons;
      .... and than it will drop all buttons in special order;
    if there are 2 buttons:
   [Button1] [Button2]
   or there are 3 buttons:
   [Button1] [Button2]
   [      Button3         ]
   or there are 5 buttons:
   [Button1] [Button2]
    [Button3] [Button4]
     [    Button5        ]
   }
})

**Comment by sidelux** [comment]
Oh well... there are so many different ways.

```
var kb = [];
var data = ["banana","mango","peach","mario","rabbids"];
for (var i=0; i<data.length; i++) {
	if (i+1 < data.length){
		kb.push([data[i], data[i+1]]);
    	i++;
    }else
    	kb.push([data[i]]);
}
console.log(kb)
```
