### ISSUE TITLE
How to integrate with node http, express, koa...?

### ISSUE THREAD

**Issue by maple3142** [yagop/node-telegram-bot-api#629]
> Question

I have an app on heroku, which serve some simple api query.
And `node-telegram-bot-api`'s webhook mode require a port to work, which cause a conflict with the api server.
Is there any way to use `node-telegram-bot-api` as a middleware?

[telegram bot script](https://github.com/maple3142/ytdl/blob/6ec7929251630f6a85154e18e1c0184cd41535a5/tgbot.js)
[koa api server script](https://github.com/maple3142/ytdl/blob/6ec7929251630f6a85154e18e1c0184cd41535a5/webapi.js)

**Comment by dew01ke** [comment]
?
https://github.com/yagop/node-telegram-bot-api/tree/master/examples/webhook

**Comment by maple3142** [comment]
@dew01ke Thanks! It works.
