### ISSUE TITLE
how can share all contact in telegram bot 

### ISSUE THREAD

**Issue by Kasra-S** [yagop/node-telegram-bot-api#635]
Hi
i want sahre name and numberphone my contact whith telegram key
how can?

**Comment by DestroyerIV** [comment]
https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+sendContact

**Comment by Kasra-S** [comment]
i want user enter his contact from contact list in smartphone
sorry my languege is bad

**Comment by DestroyerIV** [comment]
How are you doing that?

**Comment by danielperez9430** [comment]
> Hi i want sahre name and numberphone my contact whith telegram key how can?

The Telegram Bot API don't allow you to add a contact in a smartphone, this thing is need to be done at user level.
