### ISSUE TITLE
How can I pick up a user's response by forcing the answer?

### ISSUE THREAD

**Issue by DestroyerIV** [yagop/node-telegram-bot-api#638]
My case is that when executing a command, the bot makes the user respond with a response in text. I have tried `onReplyMessage(chat_id, message_id, callback)` but it shows me that it is not a function.

Another one of my doubts, is the third parameter of the method. What type of callback do you require?

If you could help me, I would appreciate it. Thanks in advance

**Comment by DtCarrot** [comment]
Hi, I believe you are looking for `onReplyToMessage(chat_id, message_id, callback)`, https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+onReplyToMessage

For the callback, just define a regular callback function: 

```
onReplyToMessage(chat_id, message_id, msg => {
    // What you want to do after user has replied
})
```

**Comment by DestroyerIV** [comment]
It does not work, it does not recognize bot.onReplyMessage as a function. I try to write / start the user is forced to respond with X message, for example, a password

**Comment by DestroyerIV** [comment]
As I read in the documentation, this method does not exist in the API

https://github.com/yagop/node-telegram-bot-api/blob/master/test/telegram.js#L1245

**Comment by DestroyerIV** [comment]
How should I use ForceReply if I want to automatically force the user to respond?

Thanks in advance
