### ISSUE TITLE
i want my telegram bot autostart and send message to a chatid how can do?

### ISSUE THREAD

**Issue by Kasra-S** [yagop/node-telegram-bot-api#642]
i want create telegram bot auto start bot and send message to chatid without  the user clicking on the Start button

**Comment by droidmanspace** [comment]
User needs to enter something to the bot directly or via a group where the bot added . Then only you can able to obtain the unique chat id for particular user

**Comment by DestroyerIV** [comment]
it smells like a spammer

**Comment by kamikazechaser** [comment]
You simply cannot do that, checkout the Telegram API documentation on their website.
