### ISSUE TITLE
Understand getChatMember 

### ISSUE THREAD

**Issue by Atruo** [yagop/node-telegram-bot-api#645]
Im traying to check if a user is in a chat, i just found this fucntion, but i dont know how to work with it.

I try to open in with a log but there is no usefull info, also i try an If/else, but when a user was not the chat it throws an error.

Can anyone help me? Or maybe help me with a diferent function to do that?. 
Thanks

**Comment by droidmanspace** [comment]
Can you please elaborate the problem and copy the snippet please.

**Comment by jejopl** [comment]
You should use this:

`bot.getChatMember(chatId,userId).then(() => {
    console.log("Exist");
    }).catch((e) => {
        if(e.response.body.error_code == 400){
            console.log("Not exist");
        }
    }
);`

**Comment by Atruo** [comment]
> Use this:
> 
> `bot.getChatMember(chatId,userId).then(() => { console.log("Exist"); }).catch((e) => { if(e.response.body.error_code == 400){ console.log("Not exist"); } } );`

Thanks man, it works.

**Comment by kamikazechaser** [comment]
Closing since question is answered. The method returns a promise which has to be resolved.
