### ISSUE TITLE
How to run bot on multi CPUs

### ISSUE THREAD

**Issue by mrdimaan** [yagop/node-telegram-bot-api#646]
Hi is there a way to use something like 4 CPUs to run the bot? I tried pm2 to run 4 clusters and got the conflict error from telegram.

**Comment by sidelux** [comment]
You should rewrite part of your bot (using [this guide](http://www.acuriousanimal.com/2017/08/12/understanding-the-nodejs-cluster-module.html) for example) to work in cluster mode.

**Comment by kamikazechaser** [comment]
Attempting to cluster will form a new instance which will conflict with Telegram servers, since you can only poll from one source at a time.

**Comment by kamikazechaser** [comment]
Yes, webhooks are the best way to scale.
