### ISSUE TITLE
Why am I getting the error of issue #319?

### ISSUE THREAD

**Issue by J4stMart** [yagop/node-telegram-bot-api#648]
I have the following very simple code

```JavaScript
"use strict";

const TelegramBot = require('node-telegram-bot-api');

const token = 'BOT_TOKEN';
const bot = new TelegramBot(token, {polling: true});
```

I'm litterally only running this code, and I get the error reported in #319. Where it says if you start with a require this error shouldn't occur. 
Anyone who knows what I am doing wrong?

**Comment by sidelux** [comment]
If you get deprecation warning you should add this line at top of the file.
`process.env["NTBA_FIX_319"] = 1;`

**Comment by J4stMart** [comment]
This solved it, thank you!
