### ISSUE TITLE
using setWebHook the program just ends in a second

### ISSUE THREAD

**Issue by rxmoein** [yagop/node-telegram-bot-api#649]
I am trying to set webhook and I need some help. I am using the code like this:
```
bot.setWebHook('VPS_IP', {
        certificate: 'public.pem',
    });
```
but when I run the bot is just exiting cleanly without any error or warning. what am I doing wrong?

**Comment by sidelux** [comment]
Try to use this code to debug:
```
process.on('uncaughtException', function (error) {
    console.log("\x1b[31muncaughtException: " + error + "\x1b[0m");
});
process.on('unhandledRejection', function (error, p) {
    console.log("\x1b[31munhandledRejection: " + error.message + "\x1b[0m");
});
```

**Comment by sidelux** [comment]
It's a more complicated system for me, i made a nginx server that redirect all port to the same for all bots.

**Comment by DtCarrot** [comment]
@sidelux Anyway, was replying to @mrdimaan in case you were responding to my message. I have similar configuration as well btw.

**Comment by mrdimaan** [comment]
witch port should the express server listen for?

**Comment by DtCarrot** [comment]
@mrdimaan Most port numbers are good. Port 25000, 25001 or 25002 as what @sidelux mentioned are fine.

**Comment by mrdimaan** [comment]
so does telegram send the updates to all these ports?!

**Comment by DtCarrot** [comment]
It will only send to the url  that you defined in bot.setWebHook(serverURL). 

So for example if your url is serverURL = 'localhost:25000/bot', then it will only send to that url at the given port.

**Comment by mrdimaan** [comment]
this is the URL given to setWebHook function:
`https://x.x.x.x:25000`
but got an error message that webhook can be set on other ports like 443.
then I tried 443 port for URL and made the server to listen on port 443.
I don't have any error but I don't get the updates yet.

**Comment by mrdimaan** [comment]
Ok. now I think the problem is with the certificate. how should I configure it?
I made the request manually by postman and it works fine bu HTTP and not by https

**Comment by DtCarrot** [comment]
Have you gotten a valid SSL certificate? If not, you can use Let's Encrypt to generate one for free.
