### ISSUE TITLE
reply_to_message property absent in group chats

### ISSUE THREAD

**Issue by ts95** [yagop/node-telegram-bot-api#65]
When replying to a message, the message object should look something like this:
```javascript
{ message_id: 35,
  from: 
   { id: 37254959,
     first_name: 'Tom',
     last_name: 'Hansen',
     username: 'tomhansen' },
  chat: 
   { id: 37254959,
     first_name: 'Tom',
     last_name: 'Hansen',
     username: 'tomhansen',
     type: 'private' },
  date: 1453832286,
  reply_to_message: 
   { message_id: 17,
     from: 
      { id: 37254959,
        first_name: 'Hans',
        last_name: 'Tomsen',
        username: 'hanstomsen' },
     chat: 
      { id: 37254959,
        first_name: 'Tom',
        last_name: 'Hansen',
        username: 'tomhansen',
        type: 'private' },
     date: 1453829963,
     text: 'Hello.' },
  text: '/cmd1' }
```

The object above contains the `reply_to_message` property, because the message replies to another message. This works as expected when in a private chat, but *not* when in a group chat.

In a group chat the `reply_to_message` property is absent, even though the message replies to another message:
```javascript
{ message_id: 35,
  from: 
   { id: 37254959,
     first_name: 'Tom',
     last_name: 'Hansen',
     username: 'tomhansen' },
  chat: { id: -25291336, title: 'Group title', type: 'group' }
  date: 1453832286,
  text: '/cmd1' }
```

Is there a reason for this?

**Comment by yagop** [comment]
Did you response a message from the bot?

**Comment by ts95** [comment]
The bot does get all the messages. The problem is that the message object does not have the `reply_to_message` property in group chats (but it does have it when you chat with the bot one on one).
The `reply_to_message` property should be there when the message is a reply to another message. This is illustrated in the image below:
![Illustration](https://u.tonisucic.com/!/Z1RFB3Y.png)
In the illustration above, `/translate` is a reply to `Dette er en test.`. So the `/translate` message object should have the `reply_to_message` property, which contains the message being replied to, which is `Dette er en test.`. As mentioned above, this works fine when you chat with the bot one on one, like you can see in the illustration above, but it doesn't work in groups.The illustration below shows that:
![Second illustration](https://u.tonisucic.com/!/FcvDX.png)
As you can see, the bot didn't react this time, since it's in a group. This is the problem. The bot didn't react because the `reply_to_message` doesn't exist on the message object although it should. It would exist if I chatted to the bot directly, but since I chat to it in a group, it's not there for some reason.

Here's the code, to give you some context.
![Code](https://u.tonisucic.com/!/24pRRc.png)

**Comment by yagop** [comment]
It seems `reply_to_message` is for bot messages only but it wold be good to have for every message too. Try contacting with http://telegram.me/BotSupport

**Comment by ts95** [comment]
For future reference I'd like to inform other users that might have the same problem. The reason for the absence of the `reply_to_message` property was that the bot was in privacy mode. All Telegram bots are in privacy mode by default, which limits them from receiving certain messages. More about that [here](https://core.telegram.org/bots#privacy-mode). When I disabled this mode through the BotFather user, the `reply_to_message` property became present for all messages, which solved my problem.

**Comment by fiatjaf** [comment]
That's not correct. According to Telegram docs bots should get the `reply_to_message` when users are replying to bot messages but that doesn't happen for me. However it does get the `reply_to_message` when users are replying to other messages using a bot command. All this in privacy mode.

The first case (users replying to bot messages) also doesn't include a `reply_to_message` not even when the bot is a group admin (which means the bot gets all the messages) nor in a private conversation between the user and the bot.
