### ISSUE TITLE
Telegram Referral Link

### ISSUE THREAD

**Issue by NateBrown101** [yagop/node-telegram-bot-api#651]
How can i create a Telegram Referral Link like t.me/abcdbot?start=123

**Comment by sidelux** [comment]
First you can generate an unique string, then grab like this and then check existence in your database.

```
bot.onText(/\/start (.+)|\/start/i, function (message, match) {
    var referral_code = match[1];
    if (referral_code != undefined)
        console.log("Referral code: " + referral_code);
    //...
});
```

**Comment by NateBrown101** [comment]
i see.. thanks @sidelux

**Comment by shrinktoken** [comment]
How can I do grab the referral code with php

**Comment by sidelux** [comment]
@shrinktoken This repo is only for node js language, try to ask in [php repo](https://github.com/php-telegram-bot/core)

**Comment by ngdkhoi** [comment]
How can I do grab the referral code with nodejs
