### ISSUE TITLE
Is this repo deprecated?

### ISSUE THREAD

**Issue by sidelux** [yagop/node-telegram-bot-api#655]
Last commit was in 15 May, 153 issue open, so will not be updated anymore with most recent Telegram bot api updates?

**Comment by danielperez9430** [comment]
You can contact in telegram with https://t.me/Yago_Perez he need to check all pull requests https://github.com/yagop/node-telegram-bot-api/pulls

**Comment by yagop** [comment]
Most last work was being done by @GochoMugo as I haven't got much time. I know its important to add new Telegram features, I will try to merge soon.

**Comment by sidelux** [comment]
Thanks a lot!

**Comment by aguiraf** [comment]
thanks @yagop , thanks @GochoMugo ,
please keep updating this wonderful library!

**Comment by kamikazechaser** [comment]
The library is still alive and being regularly updated. A bulk of these issues are mostly questions, some of which are not related to direct issues with the library but rather "how to do this/what is wrong with my code". Thank you @sidelux for answering lots of such questions.
