### ISSUE TITLE
Text Mention

### ISSUE THREAD

**Issue by NateBrown101** [yagop/node-telegram-bot-api#659]
I want to send text mention link like messages instead of username any idea or codes?

**Comment by sidelux** [comment]
Can you make an example?

**Comment by NateBrown101** [comment]
![](https://user-images.githubusercontent.com/42967523/46605657-f5dbdc80-cb02-11e8-9253-1f64c64eeac9.png)

**Comment by sidelux** [comment]
Try with markdown mode then `[Username](t.me/username)`

**Comment by NateBrown101** [comment]
Got it! thanks for your reply @sidelux
