### ISSUE TITLE
create whitelist for my bot

### ISSUE THREAD

**Issue by diegoatsv** [yagop/node-telegram-bot-api#662]
Question

I  only need certain people to have access to my bot, do you have any idea how i would be able to get my bot to respond only to the people that are in my list?

**Comment by saeedhei** [comment]
Use a condition.
If (msg.chat.id === ?){

}

**Comment by sidelux** [comment]
Or `message.from.id` :)

**Comment by diegoatsv** [comment]
@saeedhei  i already tried to use an if codition and it does allow me to keep out people by saying access denied but when the part of the if that should allow me to enter gives me a polling error.

@sidelux  could you help me with an example, i read a little bit about that but i cant fine the exact way to use it

**Comment by sidelux** [comment]
Uhm, easy example:
```
function checkPermission(userid){
    var permissionArray = [123,456,789];
    if (userid.indexOf(permissionArray) > -1)
        return 1;
    return 0;
}

bot.onText('\/command', function (message) {
    if (!checkPermission(message.from.id))
        bot.sendMessage(message.chat.id, "Permission denied for this function");
});
```

**Comment by diegoatsv** [comment]
@sidelux  thanks i will try that, so basically i should put  if (!checkPermission(message.from.id)) in every command of my bot and i would assume that the "else" sentence of this line would be my real response in case de the user is in my permission array

**Comment by sidelux** [comment]
Yep, alternatively use "return" so user exit from that function instead of else, but is your choice.

**Comment by diegoatsv** [comment]
@sidelux  it gives me a polling error, i made a little bot with /start command this is the example i made could you help me to  see if i did something wrong

const TelegramBot = require('node-telegram-bot-api');

const utf8 = require('utf8');


// replace the value below with the Telegram token you receive from @BotFather
const token = 'TOKEN_HERE';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});



function checkPermission(userid){
  var permissionArray = [123,456,789];
  if (permissionArray.indexOf(userid) > -1)
      return 1;
  return 0;
}
  

bot.onText(/\/start/, (msg) => {

  if (!checkPermission(message.from.id)){
        bot.sendMessage(message.chat.id, "Permission denied for this function");
  }
  else
  {
    bot.sendMessage(message.chat.id, "Hello world");
      }
});


bot.onText(/\/restart/, (msg) => {

  if (!checkPermission(message.from.id)){
        bot.sendMessage(message.chat.id, "Permission denied for this function");
  }
  else
  {
    bot.sendMessage(message.chat.id, "Hello world");
      }
});

**Comment by sidelux** [comment]
(next time use 'insert code' button ;))
In `bot.onText(//start/, (msg) => {` the regex `/start` is not valid, you should use `\/start` and i suggest to use `^\/start` to say "at start of string"

**Comment by diegoatsv** [comment]
actually i do use \/ start in the way you say i tried yo use de insert code button bo i dont know why it dosent work would it be ok if i attach mi code file  ?

**Comment by sidelux** [comment]
Select all of you code, then click button and it add some quotes...

**Comment by diegoatsv** [comment]
```
const TelegramBot = require('node-telegram-bot-api');
const mysql = require('mysql');
const utf8 = require('utf8');


// replace the value below with the Telegram token you receive from @BotFather
const token = 'TOKEN';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});



function checkPermission(userid){
  var permissionArray = [123,456,789];
  if (permissionArray.indexOf(userid) > -1)
      return 1;
  return 0;
}
  

bot.onText(/^\/start/, (msg) => {

  if (!checkPermission(message.from.id)){
        bot.sendMessage(message.chat.id, "Permission denied for this function");
  }
  else
  {
    bot.sendMessage(message.chat.id, "Hello world");
      }
});


bot.onText(/^\/restart/, (msg) => {

  if (!checkPermission(message.from.id)){
        bot.sendMessage(message.chat.id, "Permission denied for this function");
  }
  else
  {
    bot.sendMessage(message.chat.id, "Hello world");
      }
});

```

**Comment by diegoatsv** [comment]
@sidelux  sorry this is my first time in github im still trying to learn everything

**Comment by sidelux** [comment]
Don't worry, try to write in a single post or edit to avoid spam :)
Anyway:
you missed `function` from onText
`bot.onText(/^\/restart/, function (msg) {`
instead of 
`bot.onText(/^\/restart/, (msg) => {`

**Comment by diegoatsv** [comment]
Ok i made the change but it stills keeps giving me a polling error

**Comment by sidelux** [comment]
Try only with this code:
```
const TelegramBot = require('node-telegram-bot-api');
const mysql = require('mysql');
const utf8 = require('utf8');

const token = 'TOKEN';
const bot = new TelegramBot(token, {polling: true});

bot.on('message', function (message) {
    console.log(message);
});
```

**Comment by diegoatsv** [comment]
yep it works prints all the info in the console

**Comment by sidelux** [comment]
Try only with this code:

```
const TelegramBot = require('node-telegram-bot-api');
const mysql = require('mysql');
const utf8 = require('utf8');

const token = 'TOKEN';
const bot = new TelegramBot(token, {polling: true});

function checkPermission(userid){
    var permissionArray = [123,456,789];
    if (permissionArray.indexOf(userid) > -1)
        return 1;
    return 0;
}

bot.on('^\/test', function (message) {
    console.log(checkPermission(message.from.id));
});
```

**Comment by diegoatsv** [comment]
now it dosent print anything, it dosent give me an error either

**Comment by sidelux** [comment]
If you write `/test` in your bot you see nothing in console?

**Comment by diegoatsv** [comment]
nop, i tried with and without "/" and it dosent show anything

**Comment by sidelux** [comment]
Uh ops my fault, replace with that:
```
bot.onText(/^\/test/i, function (message) {
    console.log(checkPermission(message.from.id));
});
```

**Comment by diegoatsv** [comment]
No porblem, no the console shows a "0" when i press /test

**Comment by sidelux** [comment]
Now trying with `/start`:
```
const TelegramBot = require('node-telegram-bot-api');
const mysql = require('mysql');
const utf8 = require('utf8');

const token = 'TOKEN';
const bot = new TelegramBot(token, {polling: true});

function checkPermission(userid){
    var permissionArray = [123,456,789];
    if (permissionArray.indexOf(userid) > -1)
        return 1;
    return 0;
}

bot.on('^\/start', function (message) {
    if (checkPermission(message.from.id) == 0){
        bot.sendMessage(message.chat.id, "Permission denied");
        return;
    }
    bot.sendMessage(message.chat.id, "Hello world");
});
```

**Comment by diegoatsv** [comment]
It worked!  thank you so much for your time
