### ISSUE TITLE
Forward a Message From Channel to Group.

### ISSUE THREAD

**Issue by NateBrown101** [yagop/node-telegram-bot-api#664]
I want to make a bot which forward a post from channel as soon as it posted. i used bot.forwardMessages but i am not able to forward without command.

**Comment by sidelux** [comment]
You should get message id before forwarding it, so i think you can't as the message in channel is not sent by your bot.

**Comment by NateBrown101** [comment]
so, i can't execute it without command to get update from channel and post to group chat?
