### ISSUE TITLE
Best way to make and use mysql querys

### ISSUE THREAD

**Issue by diegoatsv** [yagop/node-telegram-bot-api#672]
Question

Hello, i wanted to know wich way would be the most aptimal to make mysql query and send those results in a message to my users, currently i use this method:

```js
bot.on('message', (msg) => {
  const chatId = msg.chat.id;
  var consult= msg.text;


  con.query("SELECT * FROM clients where numero like '%" +consult+ "%' ", function (err, result, fields) {
    if (err) throw err;
    
    for (i = 0; i < result.length; i++) {
    bot.sendMessage(chatId, "✔️ Number: "+result[i]bumber+"\n✔️ Segment: "+result[i].segment+
    "\n✔️ Service: "+result[i].product);
   
}  
```

it works but its a bit tedious using the "for" statement each time i use a new query, i wanted to see if anyone has a better or an optimal way to make these querys, i always need to use specific fields.

**Comment by sidelux** [comment]
If you want to send a broadcast message the only way is to loop.

**Comment by diegoatsv** [comment]
Sorry that's only an snippet of the full code, I do Send the message when they send one to the bot, I'm looking for a better sintax to show the results from my query in a message

**Comment by sidelux** [comment]
Surely extracting only your desired fields:
`con.query("SELECT number, segment, product FROM clients WHERE numero LIKE '%" + consult + "%'", function (err, result, fields) {`
But if you really need a LIKE search like that there is no way to optimize more... Think about to change prospective.
Maybe force user to write the full number instead of a part, idk.

**Comment by diegoatsv** [comment]
Let's say i use numero ='+consult+'  the way I print de results in the message its ok or there is a better way to show the results in the bot.Sendmessage action

**Comment by sidelux** [comment]
I think is the best way
