### ISSUE TITLE
Error on .sendPhoto

### ISSUE THREAD

**Issue by NateBrown101** [yagop/node-telegram-bot-api#673]
i didn't see this error ever before.
```Unhandled rejection Error: ETELEGRAM: 400 Bad Request: wrong remote file id specified: Wrong string length```

my code:
```bot.sendPhoto(msg.chat.id, JSON.stringify(msg.photo.reverse()[0].file_id))```

**Comment by alexandercerutti** [comment]
Why are you applying JSON.stringify on it? `file_id` is already a string. Have you tried without it?

**Comment by NateBrown101** [comment]
yes i tried some other ways. it returns undefined and sometimes polling error.  any other valid way to capture file id?

**Comment by NateBrown101** [comment]
oh, it works without JSON.stringify!!! my bad! thank you @alexandercerutti
