### ISSUE TITLE
Unique link for telegram users

### ISSUE THREAD

**Issue by Stanbear** [yagop/node-telegram-bot-api#675]
i would like to know how telegram referral links work.. how to give special link to users to track their referrals.. code examples would be appreciated.. thanks!

**Comment by alexandercerutti** [comment]
There is not referral for users.
Unique links for users are composed as follow: https://t.me/username or tg://user?id=<user_id> if the user has not a username. Their purpose, anyway, is to bring to user profile.

You can build something by generating a url that bring to the bot with a start parameter, like this:

https://t.me/bot_username?start=xxxxxx

But I don't know how does this work exactly. Or better, how you get your parameter.

**Comment by Stanbear** [comment]
@alexandercerutti thanks for reply..
yes. thats what i was looking for. 
https://t.me/bot_username?start=xxxxxx any idea?

**Comment by sidelux** [comment]
@Stanbear You can grab it with:
```
bot.onText(/\/start (.+)|\/start/i, function (message, match) {
    var invite_code;
    if (match[1] != undefined)
        invite_code = match[1];
});
```

**Comment by Stanbear** [comment]
thanks @sidelux, how can i grab users joined by the link. any code example? thanks..

**Comment by sidelux** [comment]
You should use `message.from.username`.

**Comment by Stanbear** [comment]
thanks @sidelux. i'll figure out starting from your code! 
sorry for the off-topic  :{
