### ISSUE TITLE
Telegram Group(Suggestion)

### ISSUE THREAD

**Issue by Stanbear** [yagop/node-telegram-bot-api#676]
Just as a Suggestion! it would be better if there is a telegram group for this lib. and not everyone would create unnecessarily issues. its easy to contact on telegram and it would be easy to understand this wonderful lib more. thanks

**Comment by kamikazechaser** [comment]
This is a good suggestion since it will eliminate need for creating small and/or redundant issues. I will look into it and see its viability. Suggestions are welcome.

cc/ @sidelux Will you be willing to help moderate and assit users in the group?

**Comment by sidelux** [comment]
@kamikazechaser Uhm i think i can try, but not alone (please!).

**Comment by kamikazechaser** [comment]
Sure, right now its not finalized. Until we feel we can manage it, we will not create a group.

**Comment by aorfevre** [comment]
I think it could be "self regulated".

Moreover; I have developed some antispam / scam bots (using your lib) 
I will gladly add it to the group to help with the auto moderation of the group.
