### ISSUE TITLE
How to use inline query correctly

### ISSUE THREAD

**Issue by diegoatsv** [yagop/node-telegram-bot-api#679]
> Question

Hello i need to use inline querys on my bot, but im having a hard time trying to understand them, i already set inline mode on botfather my question is the next:

by example i have de next command
```
bot.onText(/\/start/, (msg) => {
bot.sendChatAction(msg.chat.id, "typing");    
bot.sendMessage(msg.chat.id, "hello world",);    
});
```
this is a simple command on my bot_A, now the way i understand inline querys is that in my bot_B i should write @bot_A /start and it should show me themessage "hello world".

I understand that i have to use an especific syntax on my original bot to set my message to be used as inline, do i have to make 2 type of messages? one normal and one inline or it still works in either way?

and if you could help me with an example of how i have to make an inline message.

**Comment by sidelux** [comment]
First: inline messages are not catched by onText.
Second: i don't clearly understand the connection between inline_query and your code example.

So i can make you a simple example:
```
bot.on("inline_query", function (data) {
    var content = data.query;
    console.log(content);
});
```
When you have configured inline_mode in botFather, you can use by writing `@yourbot content` in every chat box.

Anyway, pay attention at [this](https://core.telegram.org/bots/inline) article (especially at cache and feedback parts)

**Comment by diegoatsv** [comment]
Sorry that example is a normal onText message it didn't have any inline connection so with the example you used in   ` var content = data.query;` i should put my "hello world" message ?

**Comment by sidelux** [comment]
The object data is:
```
{ id: 'MESSAGEID',
  from:
   { id: USERID,
     is_bot: false,
     first_name: 'FIRSTNAME',
     last_name: 'LASTNEMA',
     username: 'USERNAME',
     language_code: 'it' },
  query: 'CONTENT',
  offset: '' }
```
So you can send a message with:
`bot.sendMessage(data.from.id, "hello world");`

**Comment by diegoatsv** [comment]
so my full code should look lik this?
```

const TelegramBot = require('node-telegram-bot-api');
const mysql = require('mysql');
const utf8 = require('utf8');


// replace the value below with the Telegram token you receive from @BotFather
const token = 'token';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});



bot.onText(/\/start/, (msg) => {
  bot.sendChatAction(msg.chat.id, "typing");    
  bot.sendMessage(msg.chat.id, "hello world",);    
  });
    

  bot.on("inline_query", function (data) {
    var content = data.query;
    bot.sendMessage(data.from.id, "hello world");
    console.log(content);
});

```

**Comment by sidelux** [comment]
Put console.log under `var content` ;)
Anyway yes.

**Comment by sidelux** [comment]
Oh wait i noticed now.
When you use inline mode for A you must configure `bot.on("inline_query", ...` for bot A, the send a message to bot B un a way like:
`**bot2**.sendMessage(...);`

**Comment by diegoatsv** [comment]
Oh im sorry when i say bot_B was an example like saying a chat from x person, the point is that from any chat i invoke @bot_A and write any command it should send the answer to the person, like the youtube bot, you send a video title and in that case it shows you a list of videos, i only need a response from the bot

**Comment by sidelux** [comment]
Anyway i think i have understand your problem.
You want that your bot send a message in the chat instead of the user.
BUT is not easely possibile because as you can see in my object data example comments ago, you not have chat_id but only from.id.

**Comment by diegoatsv** [comment]
i know :/ believe me and thats only the start of what i have to do with the inline messages, well thank you for your time @sidelux  i will try to use what you showed me to make something work.
