### ISSUE TITLE
Error sendPhoto 

### ISSUE THREAD

**Issue by highfeed** [yagop/node-telegram-bot-api#68]
How to send images without the extension?

Code:
`bot.sendPhoto(uid, request('http://jq.forexpf.ru/html/htmlquotes/qimg?s=SP500&h=364&w=728&z=3&gr=2&tt=0&pt=0'))`

Error:

 `Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Photo has unsupported extension. Use one of .jpg, .jpeg, .gif, .png, .tif or .bmp"}`

I changed file telegram.js and photo sends succesfully

![image](https://cloud.githubusercontent.com/assets/8414117/12671625/057f21e8-c682-11e5-95e8-4c4f88800811.png)

**Comment by yagop** [comment]
If you use request ensure that file will be downloaded with the proper extension, its a bug that cant fix now. To work around you can download the image and send the Buffer.
