### ISSUE TITLE
How I can send message to thousand users (~10.000) in one time? 

### ISSUE THREAD

**Issue by NeroxFB** [yagop/node-telegram-bot-api#683]
Hi everyone, I have a problem with my bot. I need to send a message (like notification) to thousands users, but when I send it my bot kills. How I can solve it?

**Comment by alexandercerutti** [comment]
What does it kill?
Can you show us code? Else we won't able to help you.

**Comment by dzek69** [comment]
Telegram doesn't support mass notifications anyway. You need to split your requests in parts.

Also node-telegram-bot-api seems to have a memory leak somewhere. Especially visible (and painful) when sending files (in my case - Audio files from remote locations (http link)).

**Comment by alexandercerutti** [comment]
@kamikazechaser check this out and add a tag.

@dzek69 yeah, you have to send it one by one. Otherwise you'd have to use a channel, which is made for this purpose.

**Comment by dzek69** [comment]
Channels aren't perfect solution too. If my users wants to subscribe to particular kind of events, I'd have to create a channel for each event. Which isn't always reasonable if you have unlimited events number (like getting notified when particular github library has new release).

Currently Telegram has limits like that:

> My bot is hitting limits, how do I avoid this?
> When sending messages inside a particular chat, avoid sending more than one message per second. We may allow short bursts that go over this limit, but eventually you'll begin receiving 429 errors.
> If you're sending bulk notifications to multiple users, the API will not allow more than 30 messages per second or so. Consider spreading out notifications over large intervals of 8—12 hours for best results.
> Also note that your bot will not be able to send more than 20 messages per minute to the same group.

So having a queuing system when dealing with mass notifications is a must or your messages won't be delivered (and I suspect if you keep trying to get over the limits you may even get a temporary (or permanent?) ban).

**Comment by saeedhei** [comment]
@NeroxFB use this: (https://github.com/saeedhei/node-telegram-bot-api-bulk-message)

**Comment by dzek69** [comment]
This example is a memory leak, Interval is never stopped.

**Comment by sidelux** [comment]
I use a method like (for 6k users more or less):
1. Save the users list in a table in my database
2. Get every X minutes N rows from that table
3. Send that messages
4. Repeat until rows in table are finished

**Comment by aorfevre** [comment]
I send 25 messages / seconds. it works like a charm.

**Comment by dzek69** [comment]
The limit is about 30/s, so 25/s will work just fine.

**Comment by kamikazechaser** [comment]
You can use gochomugo/tgfancy which handles the rate limiting for you. Or manually limit it yourself. Other solutions provided are also correct.

**Comment by ABAD81280** [comment]
I have a similar problem. I have more than 1,500 users, and the bot checks the site if products are available and sends you the users if they are available. I set that it checks the site every 50 seconds so that the users can get the notification before the stock runs out, but I faced a problem, which is that it is very late. In the transmitter
