### ISSUE TITLE
switch_pm_text... Am I doing something wrong, or is it something not working?

### ISSUE THREAD

**Issue by maxkudla** [yagop/node-telegram-bot-api#684]
> Question

I'm trying to show a button with specified text that switches the user to a private chat with the bot after user select something from an inline query.

```   
bot.answerInlineQuery(query.id, [{
        id: "some_id",
        type: 'photo',
        photo_url: "https://scontent-frx5-1.cdninstagram.com/vp/....jpg",
        thumb_url: "https://scontent-frx5-1.cdninstagram.com/vp/....jpg",
    }], {
        switch_pm_text: "Text",
        switch_pm_parameter: "test",
        cache_time: 0,
    })

```

But the button doesn't appear. 

Am I doing something wrong, or is it something not working?

**Comment by alexandercerutti** [comment]
@maxkudla how did you solve? Please, don't just close the issue without giving an explanation.
