### ISSUE TITLE
Error: Cannot find module 'node-telegram-bot-api'

### ISSUE THREAD

**Issue by Casper190** [yagop/node-telegram-bot-api#685]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

const TelegramBot = require('node-telegram-bot-api');
{ Error: Cannot find module 'node-telegram-bot-api'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
at Function.Module._load (internal/modules/cjs/loader.js:506:25)
at Module.require (internal/modules/cjs/loader.js:636:17)
at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' }

Not sure how to troubleshoot this error.

**Comment by Casper190** [comment]
{ Error: Cannot find module 'node-telegram-bot-api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' }

Not sure how to troubleshoot this error.

**Comment by alexandercerutti** [comment]
Can you provide your code please?

**Comment by Casper190** [comment]
i executed that in the node.js command prompt with 2 warnings of:
npm WARN c@1.0.0 No description
npm WARN c@1.0.0 No repository field.

followed by entering:
const TelegramBot = require('node-telegram-bot-api');
 in the node.js application? because the node.js command prompt says that:
 'const' is not recognized as an internal or external command, operable program or batch file.

**Comment by alexandercerutti** [comment]
That's really weird. What's your node and npm version? (`node -v` and `npm version`) Also, what's your platform?

**Comment by Casper190** [comment]
Platform: Windows

node and npm version:
c: '1.0.0',
  npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.14.1',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.36',
  zlib: '1.2.11'

**Comment by alexandercerutti** [comment]
Wait, when you tried to execute `const TelegramBot = require('node-telegram-bot-api');`, did you enter in a node session? I mean, you started before node with `node` command?

**Comment by Casper190** [comment]
[
<img width="673" alt="node trouble" src="https://user-images.githubusercontent.com/45672160/49612191-d6680f80-f9de-11e8-8493-69d9c2b3b5d2.PNG">
](url)

**Comment by alexandercerutti** [comment]
No, this is Node Terminal.
Look at this: https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

**Comment by Casper190** [comment]
I'm at the lost at which terminal i should actually be using to write the codes.

**Comment by alexandercerutti** [comment]
No, you are right. I'm used to linux-like terminals, like WSL (bash on windows), that's why I asked. Don't worry 😊

**Comment by Casper190** [comment]
My knowledge of codding only extends to the very basic of C++ so everything feels complicated, even the simplest guide is hard for me to follow. Thought that i could learn to create telegram bot if i just followed the instructions, but looks like it hards if i dont have any background in this lol.

**Comment by alexandercerutti** [comment]
Well, to create a bot, you should at least understand the basics of HTTP requests to see how the communication between telegram bot API and your application work.

Usually, development is better under Linux or mac os, both with the terminal, because it is simpler, but it can be done also under windows, even if sometimes more complicated. For example, in the link I provided you, they gave you a procedure to make it work, but you should at least know how to get in there (and I don't know how to help you here).

You have to write those paths under windows Enviromental 
Variables. Look here: https://www.computerhope.com/issues/ch000549.htm

**Comment by Casper190** [comment]
Ok! I'll just do that and try to fumble around with it until i'm totally stuck again.
Thanks alot for the help!

**Comment by alexandercerutti** [comment]
You are welcome! 😉
