### ISSUE TITLE
Question : Telegram Group Usernames

### ISSUE THREAD

**Issue by aorfevre** [yagop/node-telegram-bot-api#686]
Hi everyone,

I see this 2 functions implementing in nodeJS
.getChatMembersCount(chatId, [options]) ⇒ Promise
.getChatMember(chatId, userId, [options]) ⇒ Promise

Is there a way to scarpe all usernames of a group or list all userid of a group where my bot is admin ? 
Something like Telethon get_participants (https://telethon.readthedocs.io/en/stable/extra/basic/entities.html?highlight=get_participants) 

Thank you for support,
Alex

**Comment by alexandercerutti** [comment]
Hi. Sadly such function is not available in native Telegram Bot API. If I understand correctly, Telethon is an alternative Bot API for Telegram, isn't it?

To do that in native api, you have to "track" all the members that write in a group and track them.
The question is: do you really need to get all the usernames of a group user?

**Comment by aorfevre** [comment]
Well, There is a bunch of scammers that try to copy admins usernames / name.
I want to make a control from time to time. 
Moreover; some accounts gets "Deleted by telegram" ; I would love to kick them out.

**Comment by alexandercerutti** [comment]
Well, I think that is not possible to get that (both).
For the scammers, you may create a /ban command to ban them with the bot and insert them into the chat ban list.

If you want to request a new feature, you could write to @BotSupport on Telegram and ask them this new feature.

**Comment by aorfevre** [comment]
Thank you.
I have already that /ban command but the idea was to be proactive and prevent those scammers from operating

**Comment by alexandercerutti** [comment]
It's not possible. You should maybe look at an alternative for Official Bot API to achieve this, but I don't know how to help you

**Comment by aorfevre** [comment]
Thank you for your return. As I thought. I will close that question then.
