### ISSUE TITLE
Receiving messages is not reliable

### ISSUE THREAD

**Issue by windkh** [yagop/node-telegram-bot-api#69]
The node-telegram-bot-api is used in a node-red node. Obviously receiving messages is not reliable. Is there a way to avoid loosing messages? 

Please have a look at this issue:
https://github.com/windkh/node-red-contrib-telegrambot/issues/1

best regards

**Comment by windkh** [comment]
The code looks like this
this.telegramBot = new telegramBot(this.token, { polling: true });

several of those handlers
telegramBot.on('message', function (botMsg) {
}

Is there a problem with more than one handler attached at the same time?

**Comment by windkh** [comment]
debug('polling error: %j', err);

says

409 {"ok":false,"error_code":409,"description":"[Error]: Conflict: terminated by other long poll or webhook"}

**Comment by windkh** [comment]
Whenever node-red deploys nodes, a new instance is created. This could lead to a situation where two pollings for the same token could run at the same time.
Is there a way to stop this internal polling mechanism?
A stop/start functionality would be nice to have!

**Comment by windkh** [comment]
`
TelegramBot.prototype.stopPolling = function () {
    if (this._polling) {
        this._polling.abort = true;
        this._polling.lastRequest.cancel('Polling stopped');
    }
};
`

**Comment by yagop** [comment]
Simultaneous requests are treated bad by Telegram. A possible solution is setting `options.polling.timeout` to `0`
