### ISSUE TITLE
list within a callback query.

### ISSUE THREAD

**Issue by spark102** [yagop/node-telegram-bot-api#691]
Hi, I was trying to list series of messages. on callback-query. when user click on inline button bot will send the next value. 
![code](https://user-images.githubusercontent.com/45935018/50077491-93cfdf80-01f5-11e9-98ab-8770ca8c523f.png)
The above code sends me the whole result in one message. but i want to separate each message on inline button. like
![code](https://user-images.githubusercontent.com/45935018/50077776-633c7580-01f6-11e9-9c93-dbff3c57e20a.png)

any code example would be appreciated.

**Comment by sidelux** [comment]
I don't understand if you want separate messages with same inline buttons or separate inline buttons in same message.
In the first case you should do something like:
```
for (i in data.results){
    app.sendMessage(chatId, "Results " + i + ":" + data.results[i].original_title ..., {parse_mode: 'HTML'});
}
```
I'm not sure that is that you are looking for...

**Comment by spark102** [comment]
Thanks for the reply @sidelux 
i received data from some API .length of 10. i want to show 1 per each message. on the "next" inline button command the 2nd will be sent.. up to 10th data and on the "previous" inline button command the previous one should be sent.

**Comment by sidelux** [comment]
I can't write the code cause is too long but i think you can do something like this:
- Get the datas from api then save in a database where id is a progressive from 1 to 10
- Make a function that generate the first message with a inline button for "next" that contain "id:1" for example and data from database searching for id=1 for message body
- Then in the callback when you found id:1 (that we'll call `thisId`), next you generate the next message with "previous" with "id:`thisId`-1" and "next" with "id:`thisId`+1" and data from database searching for id=`thisId` for message body
- So when you click the inline buttons callback is called and manage by itself

If you need some part of code ask me

**Comment by spark102** [comment]
its possible to save and clean the table every 24hr else it could flood the database as many users request. anyways thanks for the response and help @sidelux
