### ISSUE TITLE
Keyboard menu when i open che chat

### ISSUE THREAD

**Issue by DeltaFox0018** [yagop/node-telegram-bot-api#698]
### Introduction

I'm creating a bot for managing a website and I have to insert a keyboard menu

is it possible to insert a keyboard  menu levery time the chat is opened with the bot?
If yes, how can I do it? Thanks for your help

**Comment by alexandercerutti** [comment]
To open a keyboard, you have to reply to a message with your bot.
For example, you send `/start` and it replies you with the keyboard.
Please be sure to make the appropriate identity checks. Sometimes people find random bots and try them (I did sometimes lol).

Anyway, to create keyboards, look at my package, it may be useful to you: https://github.com/alexandercerutti/node-telegram-keyboard-wrapper

**Comment by DeltaFox0018** [comment]
OK and how can I see when the bot chat is open and retrieve the id of the person who opened it?

**Comment by alexandercerutti** [comment]
You get all the infos about the user in your callback (msg, which is of type: [Message](https://core.telegram.org/bots/api#message))

```
bot.onText(/\/start/, (msg) => { ... });

**Comment by DeltaFox0018** [comment]
Nono è giusto opened perchè a me serve che lui visualizzi il messaggio ogni volta che apro la chat indipendentemente dal comando /start, tipo trackbot ogni volta che entro nella chat sotto mi fa apparire un menu come questo ma con comandi diversi 
{
"reply_markup": {
    "keyboard": [["Sample text", "Second sample"],   ["Keyboard"], ["I'm robot"]]
    }
}

**Comment by kamikazechaser** [comment]
> is it possible to insert a keyboard menu every time the chat is opened with the bot?

As @alexandercerutti said, hook it with the `/start` message, it will then persist unless you explicitly set the one time keyboard option as true. This only works for normal keyboards and not inline ones.

**Comment by alexandercerutti** [comment]
@DeltaFox008, i know we are both italians but you are pleased to talk in English here. Thank you. 😊
