### ISSUE TITLE
Host my bot on my Https  server

### ISSUE THREAD

**Issue by diegoatsv** [yagop/node-telegram-bot-api#701]
So i been runing my bots on my local machine using pm2 to manage them, but i have acquired a new server with ssl so i have a few questions and i would be happy if you can help me to set up my webhook.

1. Will i have install nodejs on my server an run my bots with pm2 like i do on my local machine?.

2. I have read the example for the Https webhook and i want to know if i have to add only my domain url or the full path to may bot.js for example
 `const url = 'https://my_domain.com';` or it has to be `const url = 'https://my_domain.com/folder_of_my_bot/bot.js';`

3. My host provided me with a .pem file with my certificate and a .key file with my private key, but in the example i see that two .pem files are used, should i change my .key file extension to .pem or is it ok  to use .key

And if anyone knows of a good tutorial for this would be great to.

Thanks by the way

**Comment by danielperez9430** [comment]
1. Yes if you have access to the console or have a vps
2. You need to use expressJS or similar for create a endpoint. Like this example: https://github.com/yagop/node-telegram-bot-api/blob/master/examples/webhook/express.js and you can create a reverse proxy using your webserver for it.
3. You dont need a .pem or key file if you have a url with https and you use a reverse proxy for it. Example `https://mybot.midomain.com/bot/<random letters>/` you redirect it to `localhost:XXXX`
