### ISSUE TITLE
Question, how to quote a message sent by bot in the group

### ISSUE THREAD

**Issue by helxsz** [yagop/node-telegram-bot-api#702]
I have saved all messages ids in a database and get later. 

```
bot.on('message', function (message) {
    // save message.message_id somewhere...
});
```

Now what should I do in order to quote a existing message, I did't see the method in the documentation. any idea?

**Comment by kamikazechaser** [comment]
> Now what should I do in order to quote a existing message, I did't see the method in the documentation. any idea?

````js
bot.sendMessage(msg.chat.id, "...", { reply_to_message_id: msg.id }).then(ctx => //...```

This will send a message, quoting the message id passed as an optional parameter.

**Comment by helxsz** [comment]
oh, thanks, it works.
