### ISSUE TITLE
Receiving an answer from the user for a specific question?

### ISSUE THREAD

**Issue by elboertjie** [yagop/node-telegram-bot-api#704]
Question

An app for donations presents a user with a choice of donation sizes plus an Option called 'Custom' where he can enter his own value to donate. 

How can I ask the question and also receive the Response to that question for processing?

If a user simply enters a value, say the value 12, how can I process this value knowing that this is the answer to a specific question that was asked, in this case how much the user wishes to donate.

So far, I am using inline_keyboards presenting the user with fixed values, but I also wish to give the user the Option to enter his own custom value.

I wish to know how to link to present the user from entering such a custom value and also for the System to catch that Response, knowing it is the answer to that specific question and not just see it as a random message.

Below is the inline_keyboard I'm presenting the user, but I don't know what code to use in the callback_query for the 'Custom' button:
```

 const opts = { 
    reply_markup: { 
      inline_keyboard: [ 
        [ 
          { 
            text: '0.5', 
            callback_data: JSON.stringify({ 
              'command': 'charity', 
              'amount': '0.5' 
            }) 
          }, 
          { 
            text: '1', 
            callback_data: JSON.stringify({ 
              'command': 'charity', 
              'amount': '1' 
            }) 
          }, 
          { 
            text: 'Custom', 
            callback_data: JSON.stringify({ 
              'command': 'charity', 
              'amount': 'custom' 
            }) 
          }
      ] 
      ] 
    } 
  };  // opts 
  telBot.sendMessage(msg.chat.id, 'How much do you wish to give to charity?', opts); 
});  // charity

```

**Comment by elboertjie** [comment]
I know how to catch the callback_query in General and to test what value the user has selected from that inline_keyboard, but don't know what to do when the user selects 'Custom'.

**Comment by sidelux** [comment]
See [in this issue](https://github.com/yagop/node-telegram-bot-api/issues/663#issuecomment-428082783)

**Comment by elboertjie** [comment]
Thanks for your quick reply today; I appreciate it.

I have responded to your original post.  Thanks for assisting.
