### ISSUE TITLE
Question/Bug: BUTTON_DATA_INVALID if callback_data is stringified json

### ISSUE THREAD

**Issue by 360disrupt** [yagop/node-telegram-bot-api#706]
Question

Is it possible to send callback_data as stringified json? Do I have to format it in any way? It would be easier to parse afterward on the hook.

```
const callbackData = {
    action: 'helpRequestInterested',
    userId: user._id,
    helpRequestId: helpRequest._id
};
const stringifiedCBdata = JSON.stringify(callbackData);
const keyboard = {
    reply_markup: {
        inline_keyboard:[[
            { text: "This works", callback_data: `${callbackData.action} ${callbackData.userId}_${callbackData.helpRequestId}` },
            // { text: "This throws the err", callback_data: stringifiedCBdata },
        ]],
        hide_keyboard: false,
        resize_keyboard: true
    }
};
```

I may found two related issues in other repositories:
[Allowed charcters](https://github.com/python-telegram-bot/python-telegram-bot/issues/1267) => maybe `{}` is not allowed?
[Size limitation](https://github.com/edisonchee/slimbot/issues/25) but the stringified json shouldn't be much longer.

**Comment by david1602** [comment]
why not just go `JSON.stringify(your object)` and then `JSON.parse(callback_data)` later in your code? with `callback_data` obviously being extracted from the appropriate place

**Comment by 360disrupt** [comment]
@david1602 I don't quite understand the message is stringified in the second (commented) inline keyboard but it throws an err.

**Comment by 7flash** [comment]
It works when I stringify only two fields, when I try to add another third field it fails with error BUTTON_DATA_INVALID

Looks like it has limitation on value length?

**Comment by 7flash** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/issues/1267

**Comment by 7flash** [comment]
![Screenshot_2020-01-30_14-04-30](https://user-images.githubusercontent.com/4569866/73424318-72827200-4369-11ea-8443-3d3c7871e39c.png)

Limit = 64 bytes

**Comment by kamikazechaser** [comment]
Yes there is a limit, it's not documented because it's a Telegram side issue which can change anytime. We recommend to always cross reference with the official docs when using this library.

**Comment by sudesh1122** [comment]
https://core.telegram.org/bots/api#inlinekeyboardbutton
callback_data | String | Optional. Data to be sent in a callback query to the bot when button is pressed, **1-64 bytes**

**Comment by MadEngineX** [comment]
Faced this issue while using non ASCII characters, so:
```go
tgbotapi.NewInlineKeyboardRow(tgbotapi.NewInlineKeyboardButtonData(h.Title, "Бот-алертинга утилизирует много ко"))
```
Is ok, but:
```go
tgbotapi.NewInlineKeyboardRow(tgbotapi.NewInlineKeyboardButtonData(h.Title, "Бот-алертинга утилизирует много кон"))
```
provokes error:
```
2023/01/30 16:33:36 Endpoint: sendMessage, response: {"ok":false,"error_code":400,"description":"Bad Request: BUTTON_DATA_INVALID"}
ERRO[0005] Bad Request: BUTTON_DATA_INVALID             
```

But actually, it is problem only on my side. Non ACCII character in Golang not equals 1 byte. Maybe it'll help somebody.
