### ISSUE TITLE
Method for sending quick-display message?

### ISSUE THREAD

**Issue by elboertjie** [yagop/node-telegram-bot-api#707]
Question:

What method can I use to send a response to the user that only stays on the screen for a short time and automatically disappear?

I've seen this on GIF examples (without code) and also on other bots, that when the user presses a button or perhaps even makes a mistake, a quick message is displayed ontop / over the rest of the text.

Any ideas?

**Comment by elboertjie** [comment]
I am aware o the sendMessage method, but this is not it, as sendMessage stays on the screen as a normal text message.

**Comment by alexandercerutti** [comment]
Can you provide here those gifs? I don't think these kinds of messages exist.

**Comment by NeroxFB** [comment]
> Question:
> 
> What method can I use to send a response to the user that only stays on the screen for a short time and automatically disappear?
> 
> I've seen this on GIF examples (without code) and also on other bots, that when the user presses a button or perhaps even makes a mistake, a quick message is displayed ontop / over the rest of the text.
> 
> Any ideas?

you mean **bot.answerCallbackQuery**?

**Comment by elboertjie** [comment]
Yes, you got it!  It is the answerCallbackQuery.

Thank you for the reponse.
