### ISSUE TITLE
How to check if a command is executed? - bot.on()

### ISSUE THREAD

**Issue by RFlintstone** [yagop/node-telegram-bot-api#709]
How do I check if a user executed a command? I would like to separate normal text and commands from eachother so I could give them a diffrent tag/type in my database.

Do I need to do something like this?:
```
bot.on('message',(msg)
message = msg.chat.text
check = message.slice(0,1)
if(check = '/'){
//command
} else {
//Normal text
}
);
```

**Comment by kamikazechaser** [comment]
The [message](https://core.telegram.org/bots/api#message) type has an `entity` field to show if its a command. You can inspect the `msg` object for it.

**Comment by RFlintstone** [comment]
> The [message](https://core.telegram.org/bots/api#message) type has an `entity` field to show if its a command. You can inspect the `msg` object for it.

Do you have an example?

**Comment by alexandercerutti** [comment]
```javascript
bot.on("message", (msg) => {
    if (msg.entities && msg.entities.some((e) => e.type === "bot_command")) {
        // here if the message has bot command
    }
});
```

**Comment by RFlintstone** [comment]
> ```js
> bot.on("message", (msg) => {
>     if (msg.entities && msg.entities.some((e) => e.type === "bot_command")) {
>         // here if the message has bot command
>     }
> });
> ```

Why the `msg.entities &&`?

**Comment by alexandercerutti** [comment]
Because it msg object may not have it, if no entities are available. So, executing `.some` on undefined will report error.
