### ISSUE TITLE
node-telegram-bot-api doesn't work in Russia without VPN

### ISSUE THREAD

**Issue by urcosmos** [yagop/node-telegram-bot-api#710]
If you are using bot-api from Russia you should use it with VPN. Otherwise your bot may not work in Telegram.

Using VSCode. When I print command "node index.js" in terminal, each second I have error messages like:
`error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: unable to verify first certificate"}`
and my Bot doesn't work.
![2019-03-28 23_35_09-index js - BOT - Visual Studio Code](https://user-images.githubusercontent.com/47459065/55191088-52ff4380-51b2-11e9-8427-5e770bdf93b2.png)

Somethimes Error maybe like this:
`error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: self signed certificate"}`

So, after several efforts I found that this problem disappeared when I use VPN on my computer.
It happenes because Telegram is blocked in Russia by goverment.

I don't have any questions. Just want to people see this solution.

**Comment by mashed-potatoes** [comment]
At the moment, Roskomnadzor has unlocked `api.telegram.org`. You can freely use this module.
