### ISSUE TITLE
'reply_to_message' section missing from a reply-to message?

### ISSUE THREAD

**Issue by elboertjie** [yagop/node-telegram-bot-api#711]
What prevents a bot from receiving the 'reply_to_message' section in a message? 

My bot uses the username of the user from the original message that was responded to, but this section from the message is missing for this in some telegram groups.

user1: hi
user2: (reply to user1's message) /welcome Have a look here:  xxx

nodejs console.log(msg): 

Message structure in a working group:
message_id:
from:
chat:
date:
reply_to_message:
text:
entities:

Message structure in a non-working group:
message_id:
from:
chat:
date:
text:
entities:

I have even added the bot as an 'admin' and also removed the privacy with the /setprivacy (disable) command in BotFather, but all to no avail.

Why can I see the 'reply_to_message' section in one group, but not in other groups?

Thanks

**Comment by elboertjie** [comment]
To clarify, the bots only needs to listen to the slash commands (/xxx) and therefor does not need group admin rights.

I created a two person group and added the bot into it and there it works, but if I add the bot into another group of around 50 people, there it does not work, because the 'reply_to_message' secton of the message is missing.

Is this something to do with privacy in a specific group that the original message that was responded to cannot be seen and only the response itself?

**Comment by kirkins** [comment]
Also wondering about this. I can only see `reply_to_message` when a reply is to admin.

**Comment by duckyb** [comment]
This issue still appears with todays telegram servers and node-telegram-bot-api v0.50.0

**Comment by duckyb** [comment]
# Workaround

1. Open group settings
2. Change the chat history for new members setting (it doesn't matter which of the two the group is using)
3. Hit "Save" on the chat visibility menu
4. Hit "Save" on the group settings menu
5. Repeat the above steps one more time

After editing these settings your bot should start receiving `reply_to_message` data in that group.
I tested this with my bot as **NOT admin** and **privacy mode ON**

**Comment by procarrera** [comment]
Hi guys, any updates on this issue?
Sometimes I receive the reply_to_message some times not...
