### ISSUE TITLE
can_send_message permission problem

### ISSUE THREAD

**Issue by RRafer** [yagop/node-telegram-bot-api#712]
Hi, I'm doing a bot that verify a user when he clic on an inline button. 

When a member join, the bot revoke permissions to send message (can_send_message, can_send_media_message, etc). Then, the user need to clic on the inline button and the bot delete these message and send that he is verified and need to give permission to this user (This is my problem, the bot send the message that the user is verified, but he doesn't give the permissions to send the message). The bot is admin on the group. 

This is the code:

`bot.on('message', function(msg){
 
    var verify = {
            "inline_keyboard": [
                [
                    {text: "Haga clic aquí", callback_data: 'verificarbot'}
                ]
            ]
        };
 
    var data = {
        "reply_markup": JSON.stringify(verify)
    };
 
    RemPerms = {
      perms:can_send_message = false,
      perms:can_send_media_messages = false,
      perms:can_send_other_messages = false,
      perms:can_add_web_page_previews = false,
  };

    GivePerms = {
      perms:can_send_message = true,
      perms:can_send_media_messages = true,
      perms:can_send_other_messages = true,
      perms:can_add_web_page_previews = true,
  };
    var userId = msg.new_chat_members[0].id;
    if (msg.new_chat_members !== undefined){
        bot.restrictChatMember(msg.chat.id, userId, RemPerms).then(function(result){
            bot.sendMessage(msg.chat.id, "Hola " + msg.new_chat_members[0].first_name + ", bienvenido al grupo de consultas " + msg.chat.title + " de la UTN - FRBA\n\nHaga clic en el boton de abajo para verificar que no sea un bot.", data);
       console.log(msg.new_chat_members[0].id)
        })
    }

    bot.on('callback_query', function onCallbackQuery(accionboton){
      const data = accionboton.data;
      const msg = accionboton.message;
       console.log(accionboton);

      if (data === 'verificarbot'){
          bot.restrictChatMember(msg.chat.id, userId, GivePerms).then(function(result){
                bot.deleteMessage(msg.chat.id, msg.message_id);
              bot.sendMessage(msg.chat.id, "¡Has sido verificado! \u2705\n\nEste mensaje se borrara en unos minutos").then(function (data){
            setTimeout(function(){
                bot.deleteMessage(data.chat.id, data.message_id);
            }, 10000);
        }
        })
      }
  })  
});`

Edit: As Github doesn't insert well the code, I submited to pastebin https://pastebin.com/xm4gQsyx

**Comment by RRafer** [comment]
Close it. I solved with "bot.promoteChatMember"

**Comment by alexandercerutti** [comment]
@RRafer you can close yourself as you are the author.

**Comment by RRafer** [comment]
How? I never pulled an issue.

**Comment by alexandercerutti** [comment]
Just click "close" near the comment button 😉
