### ISSUE TITLE
How to get timestamp from message (readable format)

### ISSUE THREAD

**Issue by RFlintstone** [yagop/node-telegram-bot-api#713]
How do I get date as string (in readable format) to insert it into database?

This doesn't seem to work:
`let timestamp = String(msg.message.date);
`

**Comment by alexandercerutti** [comment]
There are a lot of formats a database can accept. Which one do you want? (e.g. YYYY-MM-DD, DD-MM-YYYY, UTC String -> {YYYY}-{MM}-{DD}T{hh}:{mm}:{ss})

**Comment by RFlintstone** [comment]
> DD-MM-YYYY

Day; Month; Year; Hour; Min; Sec

**Comment by alexandercerutti** [comment]
If you need all the info (except the timezone), probably it is better to store it as ISO DateTime string (the last one).

Anyway, you have to convert the UNIX format with [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) native object.

If you want to convert to ISO DateTime, you can use: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString;

Anyway, probabily using some external library, like `moment.js` may help you.

**Comment by kamikazechaser** [comment]
As stated above, its advisable to use ISO format or Epoch when working with stroring time.

PS:

Use Stackoverflow for general js questions. Since this issue tracker is related to the ntba library.
