### ISSUE TITLE
Sending N files as N commands run

### ISSUE THREAD

**Issue by RRafer** [yagop/node-telegram-bot-api#714]
Hi,

When I run the command "/horarios" send a message with an inline keyboard. The callback data is an file_id, and send the file correctly. If I send the same command again, it send twice the same file, 3 times sends three times the same file, etc...

This is the code

In the main .js
`bot.onText(/^\/horarios/,schedulesUtils.sendSchedules(bot));`

```
exports.sendSchedules = bot => msg => {
    bot.sendMessage(msg.chat.id, "HORARIOS", {
        reply_markup: {
            inline_keyboard: require('../resources/schedules.json')
        },
    });

    bot.on('callback_query', (schedules) => {
        bot.sendDocument(msg.chat.id, schedules.data);
    })
}
```

An image of the [problem](https://i.imgur.com/6nuAx7e.png)

**Comment by alexandercerutti** [comment]
I don't get what you would like to get instead.
