### ISSUE TITLE
Is it possible to remove a listener added for callback_query

### ISSUE THREAD

**Issue by tigermarques** [yagop/node-telegram-bot-api#715]
> Question

Hi, I'm using the `on` method that the main bot instance provides to listen for the `callback_query` event.

I would like to know if there is any way to remove this listener after it is no longer needed.

My use case is:
1. The user issues a command
2. The bot answers with a question and a list of choices
3. The user chooses the answer
4. The interaction ends

I'm using the `callback_query` event to access the user's response. However, after the interaction finishes, I would like the event handler to be removed. Otherwise, I will be leaving a lot of "dead" listeners in the code.

Is this possible?

Thanks a lot!

**Comment by kamikazechaser** [comment]
It definitely is possible to remove an even listener. I am on mobile so I can test it out at the moment. However it should be something like 

```js
bot.removeListener("callback_query");
```

**Comment by tigermarques** [comment]
Hi, thanks for your response.
I've looked at the documentation and in the `telegram.js` file and can't find that method. Could it be because it is still a development/experimental feature?
Thanks!

**Comment by alexandercerutti** [comment]
It is a method inherited by the Event Emitter 3

**Comment by tigermarques** [comment]
I've been able to use this method. I was not aware of it. I thought the framework extended the node netive Event Emitter.
Thanks for you help!
