### ISSUE TITLE
How to catch GIFs and empty replies?

### ISSUE THREAD

**Issue by elboertjie** [yagop/node-telegram-bot-api#717]
**1. What method can be used to catch group messages that are GIFs?**

The bot.onText() method does not catch GIFs of course, since a GIF is not on 'onText' message, but neither does the bot.on('sticker'..) nor the bot.on('video'...).

**2. What method can be used to catch empty replies?**

People reply to a someone else's messages, but does not add any text to their response and then simply post the empty reply.  Is there a method to catch this empty reply?

Thanks in advance

**Comment by sidelux** [comment]
If you debug a message when you send a sticker it prints something like:
```
{ message_id: 19160505,
  from:
   { id: 20471035,
     is_bot: false,
     first_name: 'Edo ⚡️',
     username: 'fenix45',
     language_code: 'it' },
  chat:
   { id: 20471035,
     first_name: 'Edo ⚡️',
     username: 'fenix45',
     type: 'private' },
  date: 1555575053,
  sticker:
   { width: 512,
     height: 512,
     emoji: '😳',
     set_name: 'fudish',
     thumb:
      { file_id: 'AAQEABMIzqoZAATd8_1kNtPFScEJAAIC',
        file_size: 5160,
        width: 128,
        height: 128 },
     file_id: 'CAADBAADTBIAAqH2LQEEKHjuFVFy5wI',
     file_size: 55788 } }
```
So as you can see, you need to check `message.sticker` object.
For example:
```
bot.on('message', function (message) {
    if (message.sticker != undefined){
        console.log(message.sticker.file_id);
    }
});
```

What do you mean with empty reply? Telegram allow to send message only if there is a message.
Maybe you mean empty _text_, so you can do something like:
```
if (message.text != undefined)
    console.log("Empty text message");
```

**Comment by elboertjie** [comment]
Thank you for your thorough reply.  I appreciate it.  Thumbs up!
