### ISSUE TITLE
sendMessage happens before sendPhoto even it is nested.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [yagop/node-telegram-bot-api#72]
Hello. I think I have encountered something interesting. If I write this:

```
bot.sendPhoto(user.chat_id, imagePath).then(
    bot.sendMessage(user.chat_id, responseMessage, options)
);
```

In telegram I receive first MESSAGE and then only PHOTO. Do I have misunderstanding of javascript promises? Or is there other method to send multiple messages from backend one after another?

**Comment by idchlife** [comment]
Hi! I think that problem is not with bot itself, but with telegram queues for messages.

sendPhoto and sendMessage resolves after request being sent, so basically promises work just fine. They are for sending requests, not receiving update that they were sent to telegram chat ;)

**Comment by GochoMugo** [comment]
First, am hoping your code is just a typo. It should read:

```js
bot.sendPhoto(user.chat_id, imagePath).then(function() {
    bot.sendMessage(user.chat_id, responseMessage, options)
});
```

You should pass a `function` to the `.then()`!

Second, the promise is resolved **after** we receive a successful response from the API. There **may** be an occurrence of messages being delivered, from the Telegram servers, to a chat in a different order! But that can **not** be handled by this library! You may want to contact [Telegram BotSupport](https://telegram.me/BotSupport) for more inquiries in this issue!
