### ISSUE TITLE
How do you send an image stored locally?

### ISSUE THREAD

**Issue by Lunacat20** [yagop/node-telegram-bot-api#725]
I am attempting to create a png image and send it to the user. I would prefer to create and access it locally. Is this possible, or must I first upload it to Telegram, and then forward it to the user? More information and code below.

I am creating a png image at the filepath listed below: (The image appears at the specified filepath)

`var filePath = ___dirname + '/..1.png`

I have attempted to read the image at the specified location using multiple methods, including that which is listed below:

`var readStream = fs.createReadStream(filePath)`
`bot.sendPhoto(msg.chat.id, readStream)`

I receive the following error message:

Unhandled rejection Error: ETELEGRAM: 400 Bad Request: file must be non-empty

**Comment by alexandercerutti** [comment]
If you upload it to Telegram by sending it to the user, you'll receive an ID so you'll be able to send it again.
If I remember it right, that ID is valid for all Telegram... but I'm not sure.

Anyway, what you are going to do is right. Are you sure the file exists and is correct?
Have you tried to read it like with `fs.readFile` and check if it gives any error?

**Comment by Lunacat20** [comment]
The image is being created properly, and fs.readFile does not give any error

**Comment by ricustr** [comment]
Try send all params to sendPhoto. like 
         ```  bot.sendPhoto(msg.chat.id,
            './test/test_1.png',
            {},
            {
              caption: "Caption text",
              "contentType": "image/png"
            }
          ).catch(err => {
            console.error(err);
          });```

**Comment by Lunacat20** [comment]
> Try send all params to sendPhoto. like
> ` bot.sendPhoto(msg.chat.id, './test/test_1.png', {}, { caption: "Caption text", "contentType": "image/png" } ).catch(err => { console.error(err); });`

After trying the method with all parameters, it throws a "Host is invalid" error

**Comment by Lunacat20** [comment]
Found the issue, The file was being created after I tried to return it due to the asynchronous nature of the language.

**Comment by Fusseldieb** [comment]
> Try send all params to sendPhoto. like ` bot.sendPhoto(msg.chat.id, './test/test_1.png', {}, { caption: "Caption text", "contentType": "image/png" } ).catch(err => { console.error(err); });`

This works for me! However, the caption is not present at the end.
