### ISSUE TITLE
Having trouble with launching bot

### ISSUE THREAD

**Issue by ItsPey** [yagop/node-telegram-bot-api#726]
Hello.
I installed bot with `npm install --save node-telegram-bot-api` but I can't see any folder with `node-telegram-bot-api` name in my directory...
by the way, I created `index.js` file with [this tutorial](https://github.com/hosein2398/node-telegram-bot-api-tutorial) and when I tried to launch bot it showed me this error:
```
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal/modules/cjs/loader.js:774:30
```
Then I wrote *node* and hit enter and wrote commands line by line and worked fine!
So the library installed success. But I have no idea how to fix this error. And also I don't know where is `node-telegram-bot-api` located.
Thank you for reading my issue and sorry for my bad English :)

**Comment by alexandercerutti** [comment]
That's a warning about Promises Cancellation.
That tutorial assumes that you know how to create a node.js project.

Run first `npm init` and follow the instruction.
Install the package `npm install --save node-telegram-bot-api`
Then create `index.js` (`touch index.js`)
Open it and create your application
Start it with `node index.js`.

**Comment by ItsPey** [comment]
@alexandercerutti I used `npm init` and created a project with my name.
Here you can see codes:
```json
{
  "name": "peyman",
  "version": "1.0.0",
  "description": "hello",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/yagop/node-telegram-bot-api.git"
  },
  "author": "pey",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/yagop/node-telegram-bot-api/issues"
  },
  "homepage": "https://github.com/yagop/node-telegram-bot-api#readme",
  "dependencies": {
    "node-telegram-bot-api": "^0.30.0"
  }
}
```
Then when I wanted to launch the code, it showed me the previous error.

**Comment by alexandercerutti** [comment]
Show me your index.js without the bot token.

**Comment by ItsPey** [comment]
```javascript
const TelegramBot = require('node-telegram-bot-api'); 
const token = '';
const bot = new TelegramBot(token, {polling: true});
    
bot.on('message', (msg) => {
    
	var Hi = "hi";
	if (msg.text.toString().toLowerCase().indexOf(Hi) === 0) {
		bot.sendMessage(msg.chat.id,"Hello dear user");
	} 
    
});
```

**Comment by alexandercerutti** [comment]
What's the full error?

Also, try to add a listener (like you did with message) for "polling_error" and log what it says in it's parameter

**Comment by ItsPey** [comment]
This is the full error:
```
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal/modules/cjs/loader.js:774:30
```
Also I'm using this snippet code for polling errors:
```javascript
bot.on('polling_error', (error) => {
  console.log(error.code);  // => 'EFATAL'
});
```

**Comment by alexandercerutti** [comment]
Logging the whole error was preferred.
Anyway, I don't have many ideas...

What happens when you start your process with `NTBA_FIX_319=1`? `NTBA_FIX_319=1 node index.js`
Also, wait, does the process stops there?

**Comment by ItsPey** [comment]
oh. It's working now!
I used `NTBA_FIX_319=1 node index.js` and now it's working fine. Thank you.
But what is `NTBA_FIX_319=1` ?
And one more question... Where `node-telegram-bot-api` located?

**Comment by alexandercerutti** [comment]
There is a whole topic about that. I'll edit this message once I find it.
Anyway, NTBA_FIX_319 message should be a warning, not an error.

The package is located in a folder in your project directory, called "node_modues"

**Comment by ItsPey** [comment]
Thank you

**Comment by Fusseldieb** [comment]
Yep, getting this error also with the latest (at the time of writing) version using npm install.

I'm literally using the same code as in the README.md example. Nothing more, nothing less. The import is at the very top. 

```
$ node index.js 
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal\modules\cjs\loader.js:1063:30
```
