### ISSUE TITLE
Question: How can I get getMe() and insert it into a variable?

### ISSUE THREAD

**Issue by ItsPey** [yagop/node-telegram-bot-api#727]
Hello.
I don't know how to get `getMe()` and insert it into a variable.
For example I want insert `getMe()` into `user` variable and get first_name of bot.
```javasctipt
var user = bot.getMe();
bot.sendMessage(msg.chat.id, "Hi. My name is " + user.first_name);
```
is that possible?

**Comment by alexandercerutti** [comment]
You are pleased to use Telegram Official supporrt group for questions. You find the link in among the pinned issues. Thank you 😊

**Comment by ItsPey** [comment]
@alexandercerutti Oh I'm sorry.
