### ISSUE TITLE
Does NTBA Support parse_down on Send Invoices?

### ISSUE THREAD

**Issue by ErKiran** [yagop/node-telegram-bot-api#728]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by kamikazechaser** [comment]
I don't see such an option in https://core.telegram.org/bots/api#sendinvoice, could you clarify a bit more?
