### ISSUE TITLE
Enhancement for bad requests.

### ISSUE THREAD

**Issue by roccomuso** [yagop/node-telegram-bot-api#73]
Wouldn't be useful to let the user handle in a different way the bad request on the server?

https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegramWebHook.js#L42

Why this? in production with heroku you can't listen on more than one single port <code>process.env.PORT</code>. And this would be pretty useful if your app should handle also requests from client and not just the telegram webhooks.

My advice is to expose a new method like <code>bot.onBadRequest(function(req, res) { ... })</code> that let the user handles all the non-matching HTTP requests.

**Comment by GermanBluefox** [comment]
+1
That will be useful for lost connection detection.

**Comment by yagop** [comment]
> And this would be pretty useful if your app should handle also requests from client and not just the telegram webhooks.
I didn't thought about that, I was focusing on single bot applications.
Maybe a way for supporting that could be accepting a HTTP(S) web server instance as parameter

**Comment by GochoMugo** [comment]
Redirect to #114.
