### ISSUE TITLE
Return promice from processUpdate

### ISSUE THREAD

**Issue by dalor** [yagop/node-telegram-bot-api#730]
> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

For custom webhook(using processUpdate) I need know when event(onText) will be finished and send 200 response to Telegram server. So I need to get Promise. Is there any way to solve this?

**Comment by golergka** [comment]
Same here. `processUpdate` is pretty much the only choice for serverless webhooks, and I want to pass a promise through all the layers of the library back to the original caller before I actually answer the original request.

Here's my sample code:

```Typescript
bot.on('message', async (msg) => { // this function is async, but bot.on() just silently discards the returned promise 
    console.log("Got message: " + msg.text); // My code gets to here...

    const reply = "You said: " + msg.text;
    await bot.sendMessage(msg.chat.id, reply);

    console.log("Sent reply: " + reply); // ...but never here: function is killed already
});

// This is exported as a serverless function
export const processUpdate = (req: any, res: any) => {
    bot.processUpdate(req.body); // I have no way to await here
    res.send("ok"); // This response is sent right away
}
```

And here's what I want it to look like:


```Typescript
bot.on('message', async (msg) => { // this function looks the same as above, but now `bot.on` uses this promise
    console.log("Got message: " + msg.text); // My code gets to here...

    const reply = "You said: " + msg.text;
    await bot.sendMessage(msg.chat.id, reply);

    console.log("Sent reply: " + reply); // ...then here...
});

// This is exported as a serverless function
export const processUpdate = async (req: any, res: any) => {
    await bot.processUpdate(req.body); // processUpdate would return a promise from above (or may be wrapped with some middle layers, I don't care)
    res.send("ok"); // ...and this response is sent only after the sendMessage above finishes
}
```

**Comment by dotcypress** [comment]
@dalor this is impossible, because NTBA uses `EventEmmiter` for update processing.

[See more](https://github.com/yagop/node-telegram-bot-api/issues/705#issuecomment-520631389)

**Comment by feliun** [comment]
@dalor I did this https://github.com/feliun/guajirobot/commit/65229da06d85a76ecf2222c113581e62f5e3110d

As a workaround, I register the callbacks and hold them until the final output from the bot has been confirmed. When that happens (in a transparent way via wrapper), I trigger the callback to let "processUpdate" progress. That way I can simulate the async process in lambda functions. Otherwise as you point out, lambda functions will just die.

Another key thing is - you can and should `await` on message sending functions (bot.sendMessage, etc)

**Comment by FilippoVigani** [comment]
@dalor have you managed to work around it somehow?

**Comment by dalor** [comment]
@FilippoVigani No. Just use telegraf.js: https://telegraf.js.org/v3#/?id=handleupdate

**Comment by mikhail-shekhtman** [comment]
> @dalor @golergka I did this [feliun/guajirobot@65229da](https://github.com/feliun/guajirobot/commit/65229da06d85a76ecf2222c113581e62f5e3110d)
> 
> As a workaround, I register the callbacks thanks to the unique message ID and hold them until the final output from the bot has been confirmed. When that happens (in a transparent way via wrapper), I trigger the callback to let "processUpdate" progress. That way I can simulate the async process in lambda functions. Otherwise as you point out, lambda functions will just die before anything happens.
> 
> Another key thing is - you can and should `await` on message sending functions (bot.sendMessage, etc): [feliun/guajirobot@ba8e1ce](https://github.com/feliun/guajirobot/commit/ba8e1ce6fc7b249b7e4680573939a29ebe324369)

This works pretty well, shouldn't it be part of the solution? Any serverless solution won't work without it.

**Comment by mikhail-shekhtman** [comment]
@dalor I just noticed what happened, can you elaborate a bit why would you recommend to use telegraf over this library. 

I find it very helpful that this lib is following Telegram API very closely. 
Thing that concerns me is the pace of update, it seems that Telegraf is way more alive.

**Comment by Dots220** [comment]
I have the following solution:

`const TelegramBot = require('node-telegram-bot-api');
const bot = new TelegramBot('TG_TOKEN')

let globalResolve = () => {
};
module.exports.handler = async (event) => {
    const bodyParsed = JSON.parse(event.body);
    await new Promise((resolve, reject) => {
        globalResolve = resolve;
        bot.processUpdate(bodyParsed);
        // set timeout to 3 seconds to resolve the promise in case the bot doesn't respond
        setTimeout(() => {
            // make sure to resolve the promise in case of timeout as well
            // do not reject the promise, otherwise the lambda will be marked as failed
            resolve("global timeout");
        }, 3000);
    });

    return {
        statusCode: 200,
        body: JSON.stringify({message: "function executed successfully"}),
    };

};

bot.on('message', async (msg) => {
    const chatId = msg.chat.id;
    await bot.sendMessage(chatId, 'message');
    globalResolve("ok");
});`

**Comment by Dots220** [comment]
I have the following solution:

```
const TelegramBot = require('node-telegram-bot-api');
const bot = new TelegramBot('TG_TOKEN')

let globalResolve = () => {
};
module.exports.handler = async (event) => {
    const bodyParsed = JSON.parse(event.body);
    await new Promise((resolve, reject) => {
        globalResolve = resolve;
        bot.processUpdate(bodyParsed);
        // set timeout to 3 seconds to resolve the promise in case the bot doesn't respond
        setTimeout(() => {
            // make sure to resolve the promise in case of timeout as well
            // do not reject the promise, otherwise the lambda will be marked as failed
            resolve("global timeout");
        }, 3000);
    });



     return {
        statusCode: 200,
        body: JSON.stringify({message: "function executed successfully"}),
    };
};

bot.on('message', async (msg) => {
    const chatId = msg.chat.id;
    await bot.sendMessage(chatId, 'message');
    globalResolve("ok");
});
```
