### ISSUE TITLE
polling_error in calbacks

### ISSUE THREAD

**Issue by kusyka911** [yagop/node-telegram-bot-api#732]
Every time when I'm trying to use an async function in bot callback like this, I've got empty polling error while processing that function.
```
bot.onText(/.*/, (msg, match) => {
    const {text, from, chat} = msg;
    /*
    * .... some code
    * */
    const response = Promise.resolve(*async func*);
    // setTimeout gives the same result
});
```
![image](https://user-images.githubusercontent.com/24293461/60131098-42566d80-97a1-11e9-89e2-7ce32d3e10f4.png)

Is there any way to fix it? I'm often using libraries with async functions in my projects, to send data to other servers

**Comment by alexandercerutti** [comment]
Add a listener to `polling_error` (`bot.on('polling_error', (err) => console.log(err))`) and it will give you more infos about.
