### ISSUE TITLE
message can't be edited

### ISSUE THREAD

**Issue by usama-asfar** [yagop/node-telegram-bot-api#734]
Why I get `message can't be edited` error message

```
bot.on('message', (msg) => {
  let chat_id = msg.chat.id;
  let message_id = msg.message_id;
  bot.editMessageText('hi', { chat_id, message_id})
})
```

> Unhandled rejection Error: ETELEGRAM: 400 Bad Request: message can't be edited
>     at /home/usama/Documents/back-end/telebot/node_modules/node-telegram-bot-api/src/telegram.js:280:15
>     at tryCatcher (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/promise.js:517:31)
>     at Promise._settlePromise (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/promise.js:574:18)
>     at Promise._settlePromise0 (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/promise.js:619:10)
>     at Promise._settlePromises (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/promise.js:699:18)
>     at _drainQueueStep (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/async.js:138:12)
>     at _drainQueue (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/async.js:131:9)
>     at Async._drainQueues (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/async.js:147:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/home/usama/Documents/back-end/telebot/node_modules/bluebird/js/release/async.js:17:14)
>     at processImmediate (internal/timers.js:439:21)
>

**Comment by khode-mohsen** [comment]
after 48 hour you cant edit message or message should be new or message sended by you ?
