### ISSUE TITLE
file is too big 

### ISSUE THREAD

**Issue by FaRzad-845** [yagop/node-telegram-bot-api#736]
how to bypass the file size limitation in bots .
Now we have to work with files under the size of 20 MB, if we want to work with files with more than 20 Mb in size, what should we do?

some projects like [pwrTelegram](https://github.com/pwrtelegram/pwrtelegram)
- Downloading of files up to 1.5 GB in size
- Uploading of files up to 1.5 GB in size

**Comment by kamikazechaser** [comment]
PWRTelegra used the core API to bypass that limit. I believe that has been patched. You have to use a user bot (`td-lib`) to bypass the limit.
