### ISSUE TITLE
TypeError: bot.sendAnimation is not a function

### ISSUE THREAD

**Issue by ELTR11** [yagop/node-telegram-bot-api#738]
When using 
```
bot.sendAnimation(id, msg.animation.file_id, {
            caption: msg.caption,
            parse_mode: 'HTML'
        })
```
Error: `TypeError: bot.sendAnimation is not a function`

**Comment by alexandercerutti** [comment]
This library is still not updated to the most recent bot api updates 😕
Please refer to the API documentation for the supported method.

**Comment by ELTR11** [comment]
But documentation to this library says that this method is supported..

**Comment by alexandercerutti** [comment]
Because development is made on `master` branch. These changes have not been published yet (`release` branch).

**Comment by ELTR11** [comment]
I switched to another library that supports all methods available in telegram api and is constantly updated

**Comment by alipirpiran** [comment]
> I switched to another library that supports all methods available in telegram api and is constantly updated

which library have you switched to ?

**Comment by kamikazechaser** [comment]
I don't have access to push the latest changes to NPM, however you can do this:

`npm i yagop/node-telegram-bot-api`
