### ISSUE TITLE
how to get the JSON payload from a POST?

### ISSUE THREAD

**Issue by Bimblis** [yagop/node-telegram-bot-api#739]
> Question

I can send GET and POST request to the telegram bot, and they are responded and have a 200.

Is it possible for telebot to read this requests and just do a console.log with the contents? Something like:

```
const TelegramBot = require(''node-telegram-bot-api'');
const bot = new TelegramBot ('xxxxxxxxxXXXXXXXXXXxxxxxxxxxxXXXXXXXXXX');

bot.on(['GET'], (bodyJson) => console.log(bodyJson));

bot.start();

```

**Comment by kamikazechaser** [comment]
`['GET']` is not a valid even to listen for. Hence no.
