### ISSUE TITLE
How to get the Inviter id?

### ISSUE THREAD

**Issue by arian51** [yagop/node-telegram-bot-api#744]
Hi everyone, 

Is there any way to get the inviter's id once he invites someone to the group?
I couldn't find any reference for this.

thanks in advance

**Comment by kamikazechaser** [comment]
No, but a potential workaround would be to use [`exportChatInviteLink`](https://core.telegram.org/bots/api#exportchatinvitelink) to generate a link and give it to the user. The way the ethod works is that it revokes the previous link. If you play around this method you may be able to track who invited who.
