### ISSUE TITLE
polling_error whith forwardMessage

### ISSUE THREAD

**Issue by amikitenko2014** [yagop/node-telegram-bot-api#749]
I need to copy all messages from chat 1 to chat 2. When starting, it gives an error
This teprocess.env.NTBA_FIX_319 = 1;

const TelegramBot = require ('node-telegram-bot-api')
const TOKEN = 'XXXXX'
console.log ('Bot has been started')

const bot = new TelegramBot (TOKEN, {
    polling:true
})

bot.on('message', (msg) => {

    console.log(msg)
    bot.forwardMessage('11111','222222', message_id)

})
Error: error: [polling_error] {}

**Comment by kamikazechaser** [comment]
Post the entire error.

**Comment by natiOTW** [comment]
`bot.on(polling_error, err => console.log(err))`

**Comment by kamikazechaser** [comment]
I meant the stack trace.
