### ISSUE TITLE
Support Custom Keyboards

### ISSUE THREAD

**Issue by antony** [yagop/node-telegram-bot-api#75]
I'd love to see Custom Keyboard support. Perhaps you already support it, but I don't see it documented.

**Comment by antony** [comment]
Just spotted your example in another Issue. Sorry!

**Comment by yagop** [comment]
![http://i.giphy.com/RGvwaX6hv8k8M.gif](http://i.giphy.com/RGvwaX6hv8k8M.gif)

**Comment by dj2bee** [comment]
@antony Would you mind linking the issue you found the example in? Thanks!

**Comment by yagop** [comment]
Take a look on this example too: https://github.com/yagop/node-telegram-bot-api/blob/master/examples/polling.js#L38
