### ISSUE TITLE
How can I initate messages with the bot and exit the program after I am done?

### ISSUE THREAD

**Issue by stonetwig** [yagop/node-telegram-bot-api#750]
> Question

I have a simple script that I run with a cronjob that if specific conditions apply, I send messages out to chats.
This works fine but my issue is that the bot is stuck in a loop after it's done and I have to issue a timeout to finish/exit the script.

```
const bot = new TelegramBot(token, {polling: false});
 bot.sendMessage(someid, somemessage);
setTimeout(() => {
    process.exit(0);
}, 15000);
```

Is there any way to make it run without a looping functionality and to exit the script as soon as it has run in a safe way?

**Comment by kamikazechaser** [comment]
Not entirely sure, but this may have something to do with the internals of JS i.e. setTimeout keeping the construct in memory.

You could try:

1. Clearing the timeout.
2. Calling the TG API without the library (better if you are using only a single method i.e. sendMessage)

**Comment by sidelux** [comment]
Maybe you can solve like this:
```
bot.deleteMessage(message.chat.id, message.message_id).then(function (data) {
    // called after message is sent
    process.exit(0);
})
```

**Comment by Ginden** [comment]
Use [.unref](https://nodejs.org/api/timers.html#timers_timeout_unref) method.
