### ISSUE TITLE
send location with /command

### ISSUE THREAD

**Issue by MeredithS** [yagop/node-telegram-bot-api#76]
How can a user send their location with a /command?

Thanks for creating the library!

**Comment by preco21** [comment]
I don't think that is possible. But you can get user's location via `location` event.

**Comment by yagop** [comment]
User have to send you the location and you can check if its a location message. I would use [onReplyToMessage](https://github.com/yagop/node-telegram-bot-api#TelegramBot+onReplyToMessage)
