### ISSUE TITLE
Sendanimation  function seems to have errors

### ISSUE THREAD

**Issue by ShowPenZ** [yagop/node-telegram-bot-api#760]
> Bug Report

hello !  I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

 then,i found source code  there seems to be a mistake in  sendAnimation method
``` javascript
sendAnimation(chatId, animation, options = {}, fileOptions = {}) {
    const opts = {
      qs: options
    };
    opts.qs.chat_id = chatId;
    try {
      const sendData = this._formatSendData('animation', animation, fileOptions);
      opts.formData = sendData[0];
      opts.qs.document = sendData[1]; // ==> opts.qs.animation = sendData[1];   // line 866  
    } catch (ex) {
      return Promise.reject(ex);
    }
    return this._request('sendAnimation', opts);
  } `
 this opts.qs.document  could be opts.qs.animation

**Comment by ItsEcholot** [comment]
Can confirm this bug changing the commented line to `.animation = sendData[1]` fixes the sendAnimation function
