### ISSUE TITLE
is there ways to wait user input and send msg??

### ISSUE THREAD

**Issue by newbieh4cker** [yagop/node-telegram-bot-api#761]
> Question

![image](https://user-images.githubusercontent.com/23703741/71337063-3a7b5880-258d-11ea-9fc0-86c0e68c1019.png)

As you see the code above, I'm trying to
 1. send msg to user
 2. wait user input
 3.  when user input something, send aonther msg.

I've seen some issues about using 'force_reply', but it doesn't help me.

**Comment by kamikazechaser** [comment]
There are several issue regarding this. You can have a look at this [library](https://github.com/alexandercerutti/node-telegram-operation-manager).

**Comment by arrbrk1** [comment]
any updates?

**Comment by Redskullvue** [comment]
Hi there , 
so i don't know if it helps you or not . but I think i have a solution for this 

`

var answerCallbacks = {};
bot.on("message", (msg) => {
  var callback = answerCallbacks[msg.chat.id];
  if (callback) {
    delete answerCallbacks[msg.chat.id];
    return callback(msg);
  }

  const chatId = msg.chat.id;

  if (msg.text.toString().toLowerCase().indexOf("/start") === 0) {
    bot.sendMessage(chatId, "Type Your License Code").then(() => {
      answerCallbacks[msg.chat.id] = function (answer) {
        var userLicenceCode = answer.text;
        if (userLicenceCode === "somthing") {
          bot.sendMessage(chatId, "Your  License Code is Valid");
        } else {
          bot.sendMessage(chatId, "License Code is wrong please try again");
        }
      };
    });
  }
});`

HOPE it helps
