### ISSUE TITLE
what happened to the "replytomessage" ???

### ISSUE THREAD

**Issue by newbieh4cker** [yagop/node-telegram-bot-api#762]
> Question

What happen to the "replytomessage"  ??
https://github.com/yagop/node-telegram-bot-api/blob/master/examples/replyToMessage.js

**Comment by kamikazechaser** [comment]
The file is [here](https://github.com/yagop/node-telegram-bot-api/blob/f10ba246d0fb3ba911b96b2e60f34f856eb920d9/examples/replyToMessage.js)
