### ISSUE TITLE
Marks buttons in inline keyboard 

### ISSUE THREAD

**Issue by Summer1117** [yagop/node-telegram-bot-api#765]
Hi,
I am using - Node telegram bot API.
I did make an inline keyboard but now I want to mark the buttons( multi-select).
I explain more about it - the buttons are channels and i want to send a message to 3 channels at the same time.
Thanks,
```js
  var Send = "post in channel";
  if (msg.text.toString().toLowerCase().indexOf(Send) === 0) {
    bot.sendMessage(msg.chat.id, "Select channel", {
      "reply_markup": {
        "inline_keyboard": [
          [
            {
              text: "Channel 1",
              callback_data: "click",
            },
          ],
          [
            {
              text: "Channel 2",
              callback_data: "click2",
            },
          ],
          [
            {
              text: "Channel 3",
              callback_data: "click",
            },
          ],
          [
            {
              text: "Channel 4",
              callback_data: "click2",
            },
          ],
          [
            {
              text: "Send post to channel",
              callback_data: "click2",
            },
          ],
        ],
        
      },
      
    });

  }
});
```

![image](https://user-images.githubusercontent.com/55059364/71765612-c5e6d900-2eff-11ea-8614-3cb9930cb778.png)

**Comment by GochoMugo** [comment]
@kamikazechaser Could you help here?

**Comment by kamikazechaser** [comment]
@Summer1117 It is possible to do that, however you need to store the state of selected channels in the callback query listener, say in an array. Once the user clicks on the send post, you can send the message in whatever channels were selected. You have not shown your callback query listener code, so I cannot exactly show you how you can achieve it.

P.S This question is more suited on stackoverflow rather than here!

**Comment by ak-umka** [comment]
how to add buttons as "add post" button??

**Comment by josimsekh31** [comment]
[Get Number 😲](buttonurl://https://t.me/Unlimited_Temp_Number_Bot?start=Bot20850952)
