### ISSUE TITLE
polling_error: Error: connect ETIMEDOUT 66.220.147.44:443

### ISSUE THREAD

**Issue by 97thjingba** [yagop/node-telegram-bot-api#766]
my code. 
```
process.env.NTBA_FIX_319 = 1;

const TelegramBot = require('node-telegram-bot-api');

// replace the value below with the Telegram token you receive from @BotFather
const token = '1018238464:AAGGszwnhLvwglKH-gPxJryITURpOEUojHg';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});

bot.on('message', (msg) => {
  const chatId = msg.chat.id;

  // send a message to the chat acknowledging receipt of their message
  bot.sendMessage(chatId, 'Received your message');
});
```
`yarn  start`

tell me

- error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ETIMEDOUT 69.171.232.21:443"}

**I tried many ways to solve it, but it didn't work. Is it my agent's problem?**
**I use socks5** 

**But does speed affect this? The general ping value is 1000ms**

**Comment by kamikazechaser** [comment]
This is an issue caused by your connection. The library already supports passing proxy (socks5) options in its constructor, especially if you are not proxying the entire system. There are several issues that address this. Try those options. I am on mobile and cannot link you to it.

I'll try to  come up with some examples soon.

**Comment by 97thjingba** [comment]
Thanks for your reply .
I have solved this problem.
Just Like this . I didn't find it in the tutorial

```
process.env.NTBA_FIX_319 = 1;
const TelegramBot = require('node-telegram-bot-api');
const Agent = require('socks5-https-client/lib/Agent');
const token = 'Your token';

const bot = new TelegramBot(token, {polling:true,request:{
    agentClass: Agent,
    agentOptions: {
        socksHost: 'Your socks Host',
        socksPort: 'Your socks Port'
    }
}});

bot.on('message', (msg) => {
    bot.sendMessage(msg.chat.id, "hello");
});

bot.on("polling_error", (msg) => console.log(msg));
```

**Comment by 97thjingba** [comment]
@kamikazechaser 
Can you give me a permission? I will create another branch to propose a pr

**Comment by kamikazechaser** [comment]
Sure fork the repo and open a PR.

**Comment by kamikazechaser** [comment]
Add it to help.md in the "how do I run my bot behind a proxy"

**Comment by 97thjingba** [comment]
@kamikazechaser 
ok. I have given a pr 
[there](https://github.com/yagop/node-telegram-bot-api/pull/767)
Thanks again for your reply ！！

**Comment by fengqifengluo** [comment]
If I have MTProto instead of socks5, what shoud I do?

**Comment by deepseek-ai-api** [comment]
> If I have MTProto instead of socks5, what shoud I do?

bro have you found its solution if yes, pls do it share with me
