### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by preco21** [yagop/node-telegram-bot-api#77]
I'm not pretty sure about this. But when I enable [keep-alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection) via [`forever` option of `request` module](https://github.com/request/request#requestoptions-callback), its response speed was much better.

This is simple `console.time` benchmarks:

```
// with keep-alive
t: 503.079ms 
t: 496.879ms 
t: 496.488ms 
t: 494.888ms 
t: 496.991ms 
t: 495.026ms 
t: 496.277ms 
t: 498.538ms 
t: 511.290ms 

// without keep-alive
t: 1116.574ms
t: 1013.224ms
t: 1123.053ms
t: 1045.034ms
t: 1047.880ms
t: 1087.082ms
t: 1058.906ms
t: 1080.411ms
t: 1056.534ms
```

Cause since this module used `request`, monkey patch used (ES6):

``` javascript
import {Request} from 'request';

const initBase = Request.prototype.init;

Request.prototype.init = function(options = {}) {
  options.forever = true;
  return Reflect.apply(initBase, this, [options]);
};
```

How about it?

**Comment by yagop** [comment]
Thanks! I will chek it out.

**Comment by preco21** [comment]
It seems on `master` branch it has already been fixed. 👍 
See: https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegramPolling.js#L105

**Comment by preco21** [comment]
Sorry, repoen because of `_request()` method still does not have `forever` option: https://github.com/yagop/node-telegram-bot-api/blob/master/src/telegram.js#L145

**Comment by preco21** [comment]
Alternative PR: https://github.com/yagop/node-telegram-bot-api/pull/178
