### ISSUE TITLE
How to get user's reply to bot's message?

### ISSUE THREAD

**Issue by Nodirbek3d** [yagop/node-telegram-bot-api#772]
> Question

Great package! My question is, how can I code a bot to get a reply for a its message?
Here what I have got so far:
```
sendImage({ chatName, imagePath }) {
            return new Promise((resolve => {
                bot.sendPhoto(getChatID(chatName), imagePath,
                    {
                        caption: "WHAT DO YOU SEE IN THE IMAGE?",
                        force_reply: true
                    }).then(response => {
                    bot.onText(/.*/, (userResponse) => {
                        resolve(userResponse.text);
                    });
                });
            }))
        }
```
I don't think I am doing it the right way, any best practices here?

**Comment by kamikazechaser** [comment]
> how can code a bot to get a reply for a bot's message?

Another bot? Bots cannot see other bot messages.

But if you are talking about **waiting for a user reply** checkout this helper library https://github.com/alexandercerutti/node-telegram-operation-manager.

**Comment by Nodirbek3d** [comment]
I didn’t mention any other bots, I need to get user’s reply message to bot’s request message.

**Comment by alanhg** [comment]
> I need to get user’s reply message to bot’s request message.

![image](https://user-images.githubusercontent.com/9245110/172051052-0d83e984-4521-4144-9326-726301bb8367.png)



onReplyToMessage meets your need.
