### ISSUE TITLE
Get messages and participants

### ISSUE THREAD

**Issue by skakodube** [yagop/node-telegram-bot-api#779]
> Question

Is it possible to get messages and participants of the channel at all?
By now I can get only admins: 
 - bot.getChatAdministrators(channel.id)

I found something similar in telegram api documentation:
- https://core.telegram.org/method/channels.getParticipants
- https://core.telegram.org/method/channels.getMessages

but don't really understand how to implement it.

Thank you!

**Comment by danielperez9430** [comment]
Hi, this methods that you are talking about are not from the Telegram Bot API, those methods are from the Telegram clients API (regular TG users).

If you want to use these methods you have to create a custom Telegram client and log in to your Telegram account.

The library that you should use to make a "userbot" is TDLib. There are many  frameworks  in different programming languages for it.

I I hope I've helped you 🤗
