### ISSUE TITLE
editMessageMedia error 400

### ISSUE THREAD

**Issue by podpolka** [yagop/node-telegram-bot-api#780]
bot.editMessageMedia
    (
        {type: 'document', media: './media/test.mp4', caption: 'Test'},
        {
            chat_id: callbackQuery.message.chat.id,
            message_id: callbackQuery.message.message_id,
            inline_message_id: callbackQuery.inline_message_id,
        }

The path to the file is correct, but it gives an error: 400 Bad Request: host is invalid

If instead of the path './media/test.mp4' register 'https: //site/test.mp4' - it works, but I do not need through the site

**Comment by danielperez9430** [comment]
This problem is current solve, you can check a example here:
https://github.com/yagop/node-telegram-bot-api/issues/876#issuecomment-963916958
