### ISSUE TITLE
store multiple inputs in the telegram in a single function

### ISSUE THREAD

**Issue by peidrao** [yagop/node-telegram-bot-api#784]
Greetings.
I am a beginner in this tool and would like to ask a question that may be simple.
I'm creating a bot to be able to send emails to other people.
The first step is to receive the email of the person I want to send and the body of the message. But I don't know how to do it, except this way

`bot.onText(/\/start/, function(msg, match) {
  const email = []; // The keyboard array
  bot.sendMessage(msg.chat.id, 'press email ', {
    reply_markup: {
      keyboard: email,
      one_time_keyboard: true
    }
  });
  bot.onText(/.+/g, function(msg, match) {
    bot.sendMessage(msg.chat.id, match);
    const emailText = match.input;
    console.log(emailText);
  })
});`

How do I save two spaces?

**Comment by kamikazechaser** [comment]
You could use this tool => https://github.com/alexandercerutti/node-telegram-operation-manager
