### ISSUE TITLE
error: [polling_error] {}

### ISSUE THREAD

**Issue by roodx5** [yagop/node-telegram-bot-api#787]
var TelegramBot = require('node-telegram-bot-api');
var token = '';

const bot = new TelegramBot(token, {polling:true});
bot.onText('message',function(msg) {

var text = msg.text;
var chatId = msg.chat.id;
var type = msg.chat.type;
var userid = msg.from.id;

if(text == "id"){
bot.sendMessage(chatId+"chtid");

}
});

**Comment by cankilinc** [comment]
var opt = {polling:true};

var bot = new Telegram(token,opt);

**Comment by alexandercerutti** [comment]
Add a listener in your code like:

```javascript
bot.on("polling_error", console.log);
```

It is probably a syntax error in your code. Something undefined or such that makes crash your program.

**Comment by McCrafterIV** [comment]
I also had the same problem. After adding a listener like @alexandercerutti mentioned I got the following exception:
```
TypeError: reg.regexp.exec is not a function
    at D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegram.js:607:37
    at Array.some (<anonymous>)
    at TelegramBot.processUpdate (D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegram.js:605:35)
    at D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegramPolling.js:110:22
    at Array.forEach (<anonymous>)
    at D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegramPolling.js:106:17
    at tryCatcher (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```
To solve this I changed the regexp value from string to a RegExp object, which solved the problem for me. If you've the same error you've to change your call to the following:
```
bot.onText(RegExp('message'), function(msg) {
```

I hope this helps ;)

**Comment by alexandercerutti** [comment]
@McCrafterIV Can you show what you wrote instead of the RegExp object? Because I've never seen that error happening.

**Comment by alexandercerutti** [comment]
Oh freak! I've seen now, in that unformatted piece of code in the first message, that the problem is, of course, the fact that it is being used the method `onText` with a string as parameter instead of a Regex. I think that happened too to you @McCrafterIV. Can you confirm?

**Comment by McCrafterIV** [comment]
> 
> 
> @McCrafterIV Can you show what you wrote instead of the RegExp object? Because I've never seen that error happening.

I've basically removed the quotes and added a valid regex "string":
`bot.onText(RegExp(/message/), function(msg) {`



> 
> 
> Oh freak! I've seen now, in that unformatted piece of code in the first message, that the problem is, of course, the fact that it is being used the method `onText` with a string as parameter instead of a Regex. I think that happened too to you @McCrafterIV. Can you confirm?

Right that was my problem

**Comment by alexandercerutti** [comment]
Of course it was failing. Because it was trying to call `exec` method on a non-Regex Object (strings don't have it).

**Comment by Arrow2004** [comment]
I also have this problem who can help

**Comment by Caike555** [comment]
same problem

**Comment by Caike555** [comment]
> I also had the same problem. After adding a listener like @alexandercerutti mentioned I got the following exception:
> 
> ```
> TypeError: reg.regexp.exec is not a function
>     at D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegram.js:607:37
>     at Array.some (<anonymous>)
>     at TelegramBot.processUpdate (D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegram.js:605:35)
>     at D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegramPolling.js:110:22
>     at Array.forEach (<anonymous>)
>     at D:\Programming\notinglytelegrambot\node_modules\node-telegram-bot-api\src\telegramPolling.js:106:17
>     at tryCatcher (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:547:31)
>     at Promise._settlePromise (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:604:18)
>     at Promise._settlePromise0 (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:649:10)
>     at Promise._settlePromises (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\promise.js:729:18)
>     at _drainQueueStep (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:93:12)
>     at _drainQueue (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:86:9)
>     at Async._drainQueues (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (D:\Programming\notinglytelegrambot\node_modules\bluebird\js\release\async.js:15:14)
>     at processImmediate (internal/timers.js:456:21)
> ```
> 
> To solve this I changed the regexp value from string to a RegExp object, which solved the problem for me. If you've the same error you've to change your call to the following:
> 
> ```
> bot.onText(RegExp('message'), function(msg) {
> ```
> 
> I hope this helps ;)
> 
> Edit: You can also just remove the `'` Semicolon

thanks, issue was this.bot.sendMessage was undefined.

**Comment by VladyslavProtsiuk** [comment]
I had the same problem. To fix it I only used bot.on((msg), () =>{}) instead of bot.onText()

**Comment by AkimbaevTimyr** [comment]
good

**Comment by Vovchik-s** [comment]
First thing - check for syntax errors. You could make a mistake in one letter.
Second - most of the function when you working with bot is async, so write it in async way :

`bot.on('message', async msg => {
    const text = msg.text; // get text from message
    const chatId = msg.chat.id; // id of chat where the message was sent

    if (text === '/start') {
        await bot.sendSticker(chatId, 'https://tlgrm.eu/_/stickers/4dd/300/4dd300fd-0a89-3f3d-ac53-8ec93976495e/9.webp');
        await bot.sendMessage(chatId, 'Welcome to my bot!');
    }
    if (text === '/info') {
        await bot.sendMessage(chatId, `Your name is ${msg.from.first_name} ${msg.from.last_name}`)
    }
})
`

**Comment by Enoch-p** [comment]
![IMG_20230205_022136_394](https://user-images.githubusercontent.com/122446499/216792400-55c4e30e-8134-49ba-9a2f-fa03b86c0a2b.jpg)
I have this error, while building telegram bot, please I need someone to help me out.
