### ISSUE TITLE
Get and Set Bot Commands

### ISSUE THREAD

**Issue by dianjuar** [yagop/node-telegram-bot-api#789]
# Feature Request

### Introduction

Since today, on [BOT API 4.7](https://t.me/BotNews/52) we can get and set the commands of our bot bypassing botfather.

Here is the [changelog](https://core.telegram.org/bots/api-changelog#march-30-2020) of the BOT API
### Example

This is how I think it should be

[Set Commans](https://core.telegram.org/bots/api#setmycommands)

```js
bot.setMyCommands([
  { command: 'command_1', description: 'Description of Command 1' },
  { command: 'command_2', description: 'Description of Command 2' },
  { command: 'command_3', description: 'Description of Command 3' },
])
```

[Get Commans](https://core.telegram.org/bots/api#getmycommands)

```js
bot.getMyCommands()
```

**Comment by AndreoliBR** [comment]
Will someone update the API?

**Comment by danielperez9430** [comment]
@dianjuar and @AndreoliBR  Yes, update soon. It is currently in the Pull Request tab, but it will be soon available for all ❤️

**Comment by kamikazechaser** [comment]
Closed in #796

**Comment by Jaguar1616** [comment]
> # Feature Request
> ### Introduction
> Since today, on [BOT API 4.7](https://t.me/BotNews/52) we can get and set the commands of our bot bypassing botfather.
> 
> Here is the [changelog](https://core.telegram.org/bots/api-changelog#march-30-2020) of the BOT API
> 
> ### Example
> This is how I think it should be
> 
> [Set Commans](https://core.telegram.org/bots/api#setmycommands)
> 
> ```js
> bot.setMyCommands([
>   { command: 'command_1', description: 'Description of Command 1' },
>   { command: 'command_2', description: 'Description of Command 2' },
>   { command: 'command_3', description: 'Description of Command 3' },
> ])
> ```
> 
> [Get Commans](https://core.telegram.org/bots/api#getmycommands)
> 
> ```js
> bot.getMyCommands()
> ```

**I enter this code:**

bot.onText(/\/setcom/, (msg) => {

    bot.setMyCommands([
        {command: "help", description: "Help"}
    ]);

**a message arrives in the console:**

error: [polling_error] {}

**why gives an error?**

**Comment by danielperez9430** [comment]
> > # Feature Request
> > ### Introduction
> > Since today, on [BOT API 4.7](https://t.me/BotNews/52) we can get and set the commands of our bot bypassing botfather.
> > 
> > Here is the [changelog](https://core.telegram.org/bots/api-changelog#march-30-2020) of the BOT API
> > 
> > ### Example
> > This is how I think it should be
> > 
> > [Set Commans](https://core.telegram.org/bots/api#setmycommands)
> > 
> > ```js
> > bot.setMyCommands([
> >   { command: 'command_1', description: 'Description of Command 1' },
> >   { command: 'command_2', description: 'Description of Command 2' },
> >   { command: 'command_3', description: 'Description of Command 3' },
> > ])
> > ```
> > 
> > [Get Commans](https://core.telegram.org/bots/api#getmycommands)
> > 
> > ```js
> > bot.getMyCommands()
> > ```
> 
> **I enter this code:**
> 
> bot.onText(/\/setcom/, (msg) => {
> 
>     bot.setMyCommands([
>         {command: "help", description: "Help"}
>     ]);
> 
> **a message arrives in the console:**
> 
> error: [polling_error] {}
> 
> **why gives an error?**

Add to your code:

```
bot.on('polling_error', function(error){ console.log(error); });
```

Clearly outside the bot.onText (...), using that little code, you will get the best explained error about the problem you have on the console.

Check out this usage example for getMyCommands and setMyCommands:

https://github.com/yagop/node-telegram-bot-api/pull/796#issuecomment-619583326

**Comment by Jaguar1616** [comment]
> Add to your code:
> 
> ```
> bot.on('polling_error', function(error){ console.log(error); });
> ```
> 
> Clearly outside the bot.onText (...), using that little code, you will get the best explained error about the problem you have on the console.
> 
> Check out this usage example for getMyCommands and setMyCommands:
> 
> [#796 (comment)](https://github.com/yagop/node-telegram-bot-api/pull/796#issuecomment-619583326)

```
TypeError: bot.setMyCommands is not a function
    at Object.callback (D:\Install\telegram_project\src\index.js:58:9)
    at D:\Install\telegram_project\node_modules\node-telegram-bot-api\src\telegram.js:614:15
    at Array.some (<anonymous>)
    at TelegramBot.processUpdate (D:\Install\telegram_project\node_modules\node-telegram-bot-api\src\telegram.js:605:35)
    at D:\Install\telegram_project\node_modules\node-telegram-bot-api\src\telegramPolling.js:110:22
    at Array.forEach (<anonymous>)
    at D:\Install\telegram_project\node_modules\node-telegram-bot-api\src\telegramPolling.js:106:17
    at tryCatcher (D:\Install\telegram_project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Install\telegram_project\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Install\telegram_project\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Install\telegram_project\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Install\telegram_project\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Install\telegram_project\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Install\telegram_project\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Install\telegram_project\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Install\telegram_project\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```
**what do you advise?**
