### ISSUE TITLE
Please add getFullUser method

### ISSUE THREAD

**Issue by luddoz-c** [yagop/node-telegram-bot-api#797]
********************************************************************
Feature Request.
*********************************************************************

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

A `getFullUser` method directly on the instance of `TelegramBot`. This can allow to fetch the profile of a user from its id *(to get, for instance, its username, first name...)*

**See :** https://core.telegram.org/method/users.getFullUser

### Example

```js
const bot = new TelegramBot(TOKEN)
const userId = 123456789

bot.getFullUser(userId) // Return: TelegramBot.User
    .then(user => {
        console.log(user.first_name)
    })
```

**Comment by danielperez9430** [comment]
@luddoz-c Hi, this method is no from Telegram Bot API (https://core.telegram.org/bots/api).

The method you are talking about is for Telegram customers, not bots. If you want to do that you must create a userbot and use TDLib

**Comment by fabiomig** [comment]
Actually, bots can call it

https://core.telegram.org/method/users.getFullUser

**Comment by danielperez9430** [comment]
> Actually, bots can call it
> 
> https://core.telegram.org/method/users.getFullUser

But it is not the Telegram bot API, it is a method that you can use if you use TDLib for your bot.
