### ISSUE TITLE
'ready' event ?

### ISSUE THREAD

**Issue by iamludal** [yagop/node-telegram-bot-api#801]
## Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

Would a `'ready'` event would be useful ? *(I think it can).*

This event would be triggered whenever the bot is ready to poll messages.

> I'm suggesting this feature because I've already used it within the **Discord** API.

### Example

```js
bot.on('ready', (msg) => {
    console.log("I'm ready to handle messages!")
})
```

**Comment by kamikazechaser** [comment]
Telegram queues undelivered messages on their server side. So even if the bot boots late, you are guaranteed delivery of messages. If you are using a webhook with say express, you could wrap your logic inside the `app.listen` callback.

Nonetheless there are already 2 methods that could help you achieve this [`startPolling`](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#telegrambotstartpollingoptions--promise) which returns a promise or [`isPolling`](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#telegrambotstartpollingoptions--promise) which returns a truthy value. You could use whichever approach favours you.

**Comment by Albisilo** [comment]
اريد بوت تلغرام يعطي الرهان
