### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by luddoz-c** [yagop/node-telegram-bot-api#802]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Actual Behavior

Here's the error I get:

```
2020-04-30 17:23:16 : EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
```

I've searched for answers in the Issues section, but didn't find something that help me so far...

> Note : I can `ping 149.154.167.220` without any problem. Output:
> ```
> 64 bytes from 149.154.167.220: icmp_seq=1 ttl=57 time=38.9 ms
> 64 bytes from 149.154.167.220: icmp_seq=2 ttl=57 time=37.4 ms
> 64 bytes from 149.154.167.220: icmp_seq=3 ttl=57 time=37.5 ms
> 64 bytes from 149.154.167.220: icmp_seq=4 ttl=57 time=36.5 ms
> ```

Thanks

**Comment by luddoz-c** [comment]
**Update:** I've just tried mobile data and it seems to works. So it looks like my WiFi is the problem, however it is working perfectly fine with everything else.

Any suggestion?

**Comment by kamikazechaser** [comment]
This is related to your internet connection. Sometimes Telegram servers may be blocked by your ISP.
