### ISSUE TITLE
Is automated testing possible for bots made with this api?

### ISSUE THREAD

**Issue by gurrrung** [yagop/node-telegram-bot-api#805]
I made a Telegram bot but right now I am facing an issue is to how to test the bot. I want to test how the bot responds when a message is given to it, how can I simulate that using Node itself and write automated tests based on that. I feel this is not possible but is here anybody who achieved it? I have already tried researching the internet, didn't find anything satisfactory.

**Comment by kamikazechaser** [comment]
Every method resolves to a promise with a Telegram status.

```js
bot.sendMessage(...).then((res) => {
    // assert if res.ok is true
})
```

**Comment by gurrrung** [comment]
So this means I have to write the tests on same file where I have written the bot logic? But that will be so unnecessary I guess.

**Comment by kamikazechaser** [comment]
Yup, maybe in the future we can allow some sort of injection.
