### ISSUE TITLE
Question - DeleteMessage based from list of array

### ISSUE THREAD

**Issue by james-star** [yagop/node-telegram-bot-api#808]
> Question

Hi all master,

how do i do i ask my bot to delete a message send by user based from a list i have.. i tried with the code below but not working :(

Example 1:-

user message : I take orange every morning. 

    var what = ["apple","orange","grape","kiwi","mango","banana"]; 
    or
    var what = "apple,orange,grape,kiwi,mango,banana";
    
    for (let i in what){
        if (msg.text.toSting().toLowerCase().includes(what[i].toString())) {
            //bot.kickChatMember(msg.chat.id,  msg.from.id);
            bot.deleteMessage(msg.chat.id,  msg.message_id)
        }
    }  

please guide 🙏

**Comment by danielperez9430** [comment]
You have use your array with the function "some" is like a "forEach" but if you return "true" stop the loop, so is better. 

```js
var what = ["apple","orange","grape","kiwi","mango","banana"]; 
what.some((item) => "my text with apple orange".includes(item))
```
Console results: 

<img width="446" alt="image" src="https://user-images.githubusercontent.com/10388515/176959384-0c8b064b-2c0e-4a52-ac9b-9015482e8b12.png">

Documentation about "some": https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/some
