### ISSUE TITLE
Create a stop method

### ISSUE THREAD

**Issue by luiz-pereira-movile** [yagop/node-telegram-bot-api#81]
Create a stop method to stop the bot. This could be useful in case of error and we need to stop the polling to save resources.

I was able to stop it with this line `bot._polling.abort = true;` but I don't think it is the ideal solution.

**Comment by conorfennell** [comment]
I see there is a pull request in to stop polling by doing this.

`TelegramBot.prototype.stopPolling = function() {
   if (this._polling) {
     this._polling.abort = true;
     this._polling.lastRequest.cancel('Stop polling');
   }
   this._polling = null;
 };`

Can we have #51 merged in?

**Comment by rapkin** [comment]
I saw PR #95 for this issue, but not merged for long time. I need this feature too, it's really helpful. Dear @yagop when will we see this PR (#95) merged?

**Comment by GochoMugo** [comment]
PR #95 was merged in. Fixes this issue.

```js
bot.stopPolling()
```

Documentation on [TelegramBot#stopPolling()](https://github.com/yagop/node-telegram-bot-api#TelegramBot+stopPolling).
