### ISSUE TITLE
How do I get the userID of the user to whom im replying to when I trigger a specific regex match?

### ISSUE THREAD

**Issue by romanpastu** [yagop/node-telegram-bot-api#810]
> Question

Imagine that theres one user message in the chat, and I, as another user, do the following

Answer to his text with: /tip 50

I basically want to somehow receive , the user to whom I have answered to, (his id) , and the second parameter.
I cant seem how to do so since msg doesnt contain the id of the user who you answered to

I dont really have anything right now, this is my code

```
`bot.onText(/\/tip/,(msg,res) => {
    var tg_chat_id = msg.chat.id
    var tg_ser_id = msg.from.id
    console.log(res)
    console.log(msg)
    // bot.onReplyToMessage(msg.chat.id, msg.from.id)
    
})`
```

I was thinking about logging the msg and finding there the userID to whom I answered. But I cant see it. Maybe I can use bot.onReplyToMessage to achieve it, but I dont understand it.

**Comment by danielperez9430** [comment]
I recommend that you make a console log of the message that Telegram sends you. By doing the console log and responding to a message in question you realize that the ID and information of the user is in: `reply_to_message.from.id`.

Example: User send /tip 50

```js
bot.onText(/\/tip (.+)/, (msg, match) => {
var resp = match[1];  //  Captured "50"
var reply_user_id = reply_to_message.from.id;

if(reply_user_id != undefined && reply_user_id != null) {
// You can do what you want like send a message or store the information
}

// If the user is not responding to a message then you do nothing

});
```
