### ISSUE TITLE
How to get callback query id

### ISSUE THREAD

**Issue by rowdy-hero** [yagop/node-telegram-bot-api#814]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by imdkbj** [comment]
Check this if understand correctly ur question.

```js
bot.on("callback_query", (callbackQuery1) => {
//check this u will find all info of callback
  console.log(callbackQuery);
//this is callback query id.
  bot.answerCallbackQuery(callbackQuery.id).catch((e) => {})
})
```
