### ISSUE TITLE
Making a resilient boot

### ISSUE THREAD

**Issue by eduperez** [yagop/node-telegram-bot-api#815]
> Question

I have a small bot using this API (currently version 1.3.4, but could upgrade if needed), that sends status messages (frequently), and also receives and responds to some commands (infrequently).

The message sending part works like a charm, but the message receiving part seems to fail when it is not used for long periods of time. I cannot provide exact error messages, but I guess that sporadic connection issues leave the bot disconnected, and it does not reconnect automatically.

As this situation must be quite common for anyone running a bot 24/7, is there a recommended "best practice" to cope with this issue?

Many thanks!

**Comment by Sasha2018RL** [comment]
I have issue like this, bot stops after ~1 hour of polling, but process is not killing

**Comment by kamikazechaser** [comment]
Best practice: Switch to webhooks
