### ISSUE TITLE
TelegramBot is not a constructor

### ISSUE THREAD

**Issue by ninjanz** [yagop/node-telegram-bot-api#816]
> Question
I get TypeError: TelegramBot is not a constructor when using the library via import. This is the code I used. Initially, I didn't import the module as a whole using *, and then after visiting [this SO link](https://stackoverflow.com/questions/43422277/telegram-bot-is-not-a-constructor-typescript) I changed it but still getting the same error.

`import * as TelegramBot from 'node-telegram-bot-api';

const bot = new TelegramBot(process.env.TELEGRAM_BOT_TOKEN);`

The exact error I'm getting: 
"const bot = new TelegramBot(process.env.TELEGRAM_BOT_TOKEN);
                      ^
TypeError: TelegramBot is not a constructor"

**Comment by SmpEnd** [comment]
use:

const { TelegramBot } = require('node-telegram-bot-api')

const bot = new TelegramBot(<token>, { <options> })

**Comment by zhenghanlee** [comment]
> use:
> 
> const { TelegramBot } = require('node-telegram-bot-api')
> 
> const bot = new TelegramBot(token, { options })

Facing the same issue here, seems like this doesn't work too...

**Comment by danielperez9430** [comment]
You can use:

`import TelegramBot from "node-telegram-bot-api";`

**Comment by Cosm1cBug** [comment]
@ninjanz Have you got a fix to your issue? 

I'm also having the same issue.
