### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by phantombug** [yagop/node-telegram-bot-api#823]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

I'm making an API that will expect `/start (code)` message from the bot using express backend and request will wait for certain amount of time until it receive the message once it receive the message user will be redirected to another route and send success message to the user on the bot

### Actual Behavior

when making an API request and sending the message on the bot that my API is expecting. the bot is sending duplicate message on every request (+1 message from last request each time)

![Screenshot_2020-08-03_19-05-51](https://user-images.githubusercontent.com/57271212/89203654-95fad380-d5bd-11ea-8f88-4bc8e5f4abac.png)

### Steps to reproduce the Behavior

this is what my code look like...

handlers.js
```
const bot = require('./bot');
...
...

const botSignInHandler = (startId) => {
    return new Promise((resolve, reject) => {
        bot.on("message", (msg) => {
            let user = {
                chat_id: msg.chat.id,
                first_name: msg.chat.first_name,
                last_name: msg.chat.last_name ? msg.chat.last_name : "",
                avatar: uiAvatar(msg.chat.first_name),
            };

            let text = msg.text;
            let _id = text.split(" ")[1];

            bot.sendMessage(user.chat_id, "success"); // duplicate on every request
            if (_id === startId) return resolve(user);
        });
    });
};

```

controller.js
```
router.post('/user/bot', async (req, res) => {
    req.setTimeout(600000); // it will wait for 10min until it get the message back
  
   let user = await botSignInHandler(startId);
   return res.json(user);
});
```

**Comment by kamikazechaser** [comment]
Don't wrap the event listener like that!

**Comment by imdkbj** [comment]
Use something like as below.

```js
const bot = require('./bot');
...
...

const botSignInHandler = (startId) => {
        bot.on("message", ({text,chat:{id,first_name,last_name}}) => {					
            let user = {
                chat_id: id,
                first_name,
                last_name: last_name == undefined ? "":last_name,
                avatar: uiAvatar(first_name)
            };

		let _id = text.split(" ")[1];

            bot.sendMessage(id, "success");
            if (_id === startId) return user;
        }
    };

```
