### ISSUE TITLE
Is there a way to receive all group messages

### ISSUE THREAD

**Issue by soend** [yagop/node-telegram-bot-api#83]
Is the `bot.on('message', function (msg)` ment to receive all the messages from the group chat (also the ones that dont start with /)? If not is there a way doing this?

**Comment by idchlife** [comment]
I presume you discovered that bots are not allowed to get all the messages from group due to security reasons?

**Comment by soend** [comment]
You can disable the privacy settings and then i was able to get all messages.

**Comment by treviergits** [comment]
How did you do this? disabling privacy settings and getting all messages?

**Comment by alexandercerutti** [comment]
@treviergits to disable privacy settings you have to pass through BotFather. Contact it, select your bot and then "Bot Settings" and again Group Privacy. Click "Turn off".

**Comment by treviergits** [comment]
Thanks! Which function did you use to get all the messages?

**Comment by alexandercerutti** [comment]
You just have to set a listener on the bot, like above `bot.on("message", (msg) => { ... });`.
It will receive all the messages in all the groups it have been added into.

**Comment by treviergits** [comment]
But does that include previous messages or just new ones?

**Comment by alexandercerutti** [comment]
No, only the new ones. A bot cannot receive the messages sent before it was added to the group.
Maybe it may receive some of the ones sent within the last 24 hours, but I'm not sure about this.

**Comment by rougerepublic23** [comment]
bot.on("message", (msg) => { ... }); with this can i get previous message before adding function to bot
