### ISSUE TITLE
HOW CAN I CONTACT TELEGRAM CHANNEL ADMIN

### ISSUE THREAD

**Issue by andavas2** [yagop/node-telegram-bot-api#837]
I WANT TO CONTACT AN ADMIN OF A TELEGRAM CHANNEL.. BUT THEY HAVENT LEFT ANY BOT OR USERNAME TO CONTACT.. CAN SOMEONE PLS HELP ME HOW TO FIND ADMIN OF A TELEGRAM CHANNEL..

**Comment by imdkbj** [comment]
Hey!

You are in wrong place. This is not for these type of questions. 😂

**Comment by andavas2** [comment]
I AM NEW TO THIS SO THANKS ANYWAY..
