### ISSUE TITLE
sendAudio always send as audio/mpeg

### ISSUE THREAD

**Issue by voxsoftware** [yagop/node-telegram-bot-api#839]
I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior
```typescript
let file = "...audio.opus"
let msg = await this.bot.sendAudio(msg.chat.id, file, {}, {
    filename: 'audio.opus',
    contentType: "audio/x-opus+ogg"
})
console.info(msg.audio.mime_type) // -> audio/x-opus+ogg
```

### Actual Behavior
```typescript
let msg = await this.bot.sendAudio(msg.chat.id, file, {}, {
    filename: 'audio.opus',
    contentType: "audio/x-opus+ogg"
})
console.info(msg.audio.mime_type) // -> audio/mpeg
```

this modules is always sending audio as audio/mpeg, so Telegram Client cannot recognize at 100% the content of file (example artist, album, etc) but if send the same file using telegram client, the files got the correct mimetype, and the correct metadata. 

I also setted this environment variables before load module, without luck: 

```typescript
process.env.NTBA_FIX_319 = "1"
process.env.NTBA_FIX_350 = "1"
```

### Steps to reproduce the Behavior
Send a .opus file using this module

**Comment by brauliobo** [comment]
sendAudio unfortunetely doesn't support opus, only m4a and mp3 files, see https://core.telegram.org/bots/api#sendaudio
