### ISSUE TITLE
editMessageText

### ISSUE THREAD

**Issue by podpolka** [yagop/node-telegram-bot-api#841]
Hello. When using the method editMessageText - I ran into a problem, namely from yesterday evening
Clicking on inline-keyboard - a list of buttons should open - 10, 20, 50 pieces

If you click from your Russia account - nothing happens
If you click from the account of another country - everything works fine
If I click from the Russian account but observe from the account of another country, then I see that the clicks on the account of another country are successful, but nothing happens on the Russian account (

**Comment by danielperez9430** [comment]
I think you problem is in Telegram it self, no in this library. So if the error still exists open your issure in https://bugs.telegram.org
