### ISSUE TITLE
How to emmit a messages on channel?

### ISSUE THREAD

**Issue by RobyCigar** [yagop/node-telegram-bot-api#842]
## Question
How can I emmit messages on a channel?

I already read along [this](https://github.com/hosein2398/node-telegram-bot-api-tutorial) tutorial, It says you should make the bot as admin. So, I make the bot as admin. Still doesn't work.

Then I do google research for about 3 hours and found [this](https://stackoverflow.com/questions/33126743/how-do-i-add-my-bot-to-a-channel) answer. But I still had no idea how to implement that to this library

My code works well in a group, but it doesn't work in the channel.
here's my code
```
bot.on('message', msg => {
	var greet = 'hi';
	if(msg.text.toString().toLowerCase().includes(greet)) {
		bot.sendMessage(msg.chat.id, `Hello🤗️`)
	}
})
```

Thank you :D

**Comment by sidelux** [comment]
You only need to use username as chat id is channel is public, msg.chat.id if private.
If you don't know how to get ids from a private channel check [here](https://stackoverflow.com/questions/33858927/how-to-obtain-the-chat-id-of-a-private-telegram-channel#:~:text=copy%20the%20link%20of%20any,31%20is%20the%20message%20ID)).

**Comment by RobyCigar** [comment]
wow thats work!!! thank you so much 🙏️🙏️🙏️
