### ISSUE TITLE
Checking of incoming message

### ISSUE THREAD

**Issue by Buzzzatti** [yagop/node-telegram-bot-api#844]
how can i check that message, which i get is number not a text 

case  kb.time.time1:
            bot.sendMessage(ChatId, 'How Much ?',{
                reply_markup: {text: keyboard.text}
            })
        break

**Comment by sidelux** [comment]
Where you get your number or text?
Can you explain better?

**Comment by rawb0t** [comment]
i believe OP was asking about ensuring the message was a number instead of a string, which is out of scope for this project anyway.
