### ISSUE TITLE
Q: forward with reply_to_message as quoted

### ISSUE THREAD

**Issue by suntong** [yagop/node-telegram-bot-api#845]
> Question

When I do message forwarding from one group to another, the "reply_to_message" is lost in the forward, which means a very important part of the conversation is missing, viewed from the receiving group. 

Is there any easy way to include the "reply_to_message" part in the forwarded message? Else, if I need to add that feature on my own, please give me a hint how to do it. 

thanks!

**Comment by rawb0t** [comment]
i know this is a rather late response, but i believe telegram as a whole doesn't preserve the reply when forwarding a message. you would need to forward both the message being replied to as well as the reply and they'll still appear separately

**Comment by suntong** [comment]
Gotya. Thanks!
