### ISSUE TITLE
Parse mode in .editMessageCaption method not working

### ISSUE THREAD

**Issue by hugorplobo** [yagop/node-telegram-bot-api#849]
I need to edit the caption of a photo that has some HTML and was sent by my bot:

```js
const videoDetails = `🎬 <a href="${url}">${info.videoDetails.title}</a>
👤 <a href="${info.videoDetails.ownerProfileUrl}">${info.videoDetails.ownerChannelName}</a>
🕑 <b>${videoLength}</b>   💾 <b>${functions.getVideoSize(audioFormat.contentLength)} MB</b>`
```

When I use the editMessageCaption method, formatting is lost

`
bot.editMessageCaption(
            query.message.caption + "\n\n⚙️ Processing your video...",
            {
                message_id: query.message.message_id,
                chat_id: query.from.id,
                parse_mode: "HTML",
                //caption_entities: query.message.caption_entities
            }
        )
`

Neither parse mode nor caption_entities work. Any idea how to solve?

**Comment by kamikazechaser** [comment]
This is probably not an issue with the library. Your template literal might be broken. Check here:

```js
href="${info.videoDetails.ownerProfileUrl}"
```

**Comment by seeya** [comment]
Facing the same issue here. On the official telegram it states passing in either `parse_mode` or `caption_entites`. 
However neither work using this library.

**Comment by AlonBe** [comment]
I'm using version 0.50 and encountered a problem using "entities" or "caption_entities" properties when sending/editing messages.

I'm not sure if there's another issue about it, the workaround that worked for me is below:
`
const entitiesAsString = JSON.stringify(entitiesArray);
await bot.sendMessage(chatId, 'some text', {
    entities: entitiesAsString,
});
`

**Comment by danielperez9430** [comment]
Fix on next release. Not more need JSON. stringify()
