### ISSUE TITLE
 detection if the telegram is off

### ISSUE THREAD

**Issue by Updour** [yagop/node-telegram-bot-api#850]
********************************************************************
when my telegram is off, or the connection is not stable, how to read the condition?
maybe there is a status of 1,2,3 or something?
*********************************************************************

> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by kamikazechaser** [comment]
You could test by sending a message. But that is usually when the bot is blocked. But for online status, you can't do it.

**Comment by Updour** [comment]
I mean, when a user sends a message to the bot, but the bot doesn't respond, how do I check whether the message has been read or not?

**Comment by kamikazechaser** [comment]
It is not yet possible to get read receipts with bots.

**Comment by Updour** [comment]
oh, oke thanks you
