### ISSUE TITLE
bot.editMessageText does not send callback_data

### ISSUE THREAD

**Issue by xmorhpx** [yagop/node-telegram-bot-api#854]
I have the problem that when I press the button that sends the callback_data "exit" and I also send a url: "https://exe.io/" it only directs me to the page and does not send me the callback_data

f (data == "gg"){
        bot.editMessageText(`text`,{chat_id:msgchatid, message_id:msgid,
         reply_markup: {
                inline_keyboard: [[{text: `text`,callback_data:"exit",url:"https://exe.io/"}]]
           }
            ,parse_mode: "HTML"})
    };    

if (data == "exit"){
        console.log(data);
        bot.editMessageText(`text`,{chat_id:msgchatid, message_id:msgid,parse_mode:"HTML"})
    }

**Comment by leonmak** [comment]
https://core.telegram.org/bots/api#inlinekeyboardbutton 
`This object represents one button of an inline keyboard. You must use exactly one of the optional fields.`, cannot have both callback_data and url

**Comment by xmorhpx** [comment]
Muchas gracias no había leído esa parte
