### ISSUE TITLE
BadHTTPResponse 502

### ISSUE THREAD

**Issue by nockstarr** [yagop/node-telegram-bot-api#86]
Been running the bot for a long time now, and today the bot stopped answering.
I have not modified the code in while. All I get is the error message below when the boot tries to pull new messages. I have testet on 2 diffrents servers and made sure im running the latest version of telepot. Any help?
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 348, in get_from_telegram_server
    result = self.getUpdates(offset=offset, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 273, in getUpdates
    return self._parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 166, in _parse
    raise BadHTTPResponse(response.status_code, response.text)
BadHTTPResponse: (502, u'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n')
`

**Comment by yagop** [comment]
telepot ?

**Comment by nockstarr** [comment]
oh, dont know how i got here. Sorry wrong repo! plz delete :)
