### ISSUE TITLE
Cannot use Inline keyboard and parse mode together in node js telegram bot?

### ISSUE THREAD

**Issue by phantom2152** [yagop/node-telegram-bot-api#863]
> Question
Hey Guys I was making an telegram bot using nodejs telegram bot api when I cam across a problem .
I wanted to dispaly a html parsed message and an inline keyboard below it 

    bot.onText(/\/help/, async (msg) => {
      help_msg = `<b>This is the link for the advanced help</b>`;
      var adv_help = {
        reply_markup: JSON.stringify({
          inline_keyboard: [
            [
              {
                text: "Advanced Help",
                url: "https://telegra.ph/Advanced-Help-for-Cloud-Torrenter-07-31",
              },
            ],
          ],
        }),
      };
      bot.sendMessage(msg.chat.id, help_msg, { parse_mode: "HTML" }, adv_help);
    });

But in this case the inline key board button wont appear at all only the parsed *help_msg* appears
[Picture Here][1]

But if change the last line to 
 

    bot.sendMessage(msg.chat.id, help_msg, adv_help ,{ parse_mode: "HTML" });

The unparsed *help_msg* that is the raw *help_msg* with <b> appears with the inline keyboard
[Picture here][2]

can anyone suggest a method to get both the parsed text and button together

  [1]: https://i.stack.imgur.com/P9HWh.png
  [2]: https://i.stack.imgur.com/ZiqM1.png

**Comment by Rev3rs1d** [comment]
hi, the command sintax is: bot.sendMessage(chatid, message, options)

object "reply_markup", stays within the options

example: 

const adv_help =  {
reply_markup: {
      inline_keyboard: [
        [
          {
            text: "Advanced Help",
            url: "https://telegra.ph/Advanced-Help-for-Cloud-Torrenter-07-31",
          }
        ],
      ],
    }, 
   parse_mode: 'HTML'
}



parse_mode, reply_markup, is the options

**Comment by phantom2152** [comment]
Hey thanks a a lot for the help...
