### ISSUE TITLE
Not all Regex work in groups (vs single user chats)

### ISSUE THREAD

**Issue by beshur** [yagop/node-telegram-bot-api#864]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

I have set multiple `bot.onText` handlers and I want all of them to work with both single user chats and group chats.

### Actual Behavior

✅ `bot.onText(/\/help|Помощь/i, ...)` - works  in both single user chat and  group

❌ Works only in single user chat (when sending a message to a group webhook does not get hit at all):

`bot.onText(/(\d{1,}\/\d{1,}) (\d{1,})/, ...)`

`bot.onText(/.{1,}/, ...)`
### Steps to reproduce the Behavior

1. Add bot with similar config  to a group chat
2. Try to send the message.

Probably I'm missing something.

Could you please help?

**Comment by rawb0t** [comment]
at a quick glance it seems your one that works includes a / at the beginning and the rest do not. is your bots privacy mode disabled? if not it won't be able to see any messages that aren't a) a command or b) explicitly addressed to them

**Comment by beshur** [comment]
Thank you!
Great advice, fixed my problem.
