### ISSUE TITLE
I'm trying inline bot label:help wanted

### ISSUE THREAD

**Issue by coredox** [yagop/node-telegram-bot-api#87]
```
var TelegramBot = require('node-telegram-bot-api');
var figlet = require('figlet');

var token = 'did it correctly';
// See https://developers.openshift.com/en/node-js-environment-variables.html
var port = process.env.OPENSHIFT_NODEJS_PORT;
var host = process.env.OPENSHIFT_NODEJS_IP;
var domain = process.env.OPENSHIFT_APP_DNS;

var bot = new TelegramBot(token, {webHook: {port: port, host: host}});
// OpenShift enroutes :443 request to OPENSHIFT_NODEJS_PORT
bot.setWebHook(domain+':443/bot'+token);

bot.onText(/\/echo (.+)/, function (msg, match) {
  var chatId = msg.chat.id;
  var resp = match[1];
  bot.sendMessage(chatId, resp);
});

bot.on('inline_query', function(query) {
  toSend = [];

  for (var i = 1; i < 4; i++) {

    toSend.push({
      type: 'article',
      id: i,
      title: 'fan',
      message_text : 'something'
    });
  }
  bot.answerInlineQuery(query.id, toSend);
});

```

Inline query isn't working, is the syntax correct? or there is something wrong with openshift?

and the bot is working fine with /echo in personal chat with bot.

**Comment by yagop** [comment]
Try with this first:

```js
bot.on("inline_query", function(inline_query) {
    bot.answerInlineQuery(query.id, [{
      id: '0', 
      type: 'article', 
      title: 'Title', 
      description: 'Markdown', 
      message_text: query.query,
      parse_mode: 'Markdown'
    }]);
});
```

Make sure you have enabled inline mode in Botfather

**Comment by coredox** [comment]
I think Telegram is making a fool out of me. I've a working bot https://telegram.me/bigletterbot u can send "/Standard Hi" to the bot and check for yourself
![image](https://cloud.githubusercontent.com/assets/16400646/13575300/365262a4-e4ae-11e5-86e4-d758bb62da2b.png)

**Comment by edusis** [comment]
@yagop Thanks for your code, this works for me :)

**Comment by coredox** [comment]
@yagop thank you for the code. However it has an error after correction it's working flawless...

```
bot.on("inline_query", function(query) { //you wrote inline_query and refered query.id 
    bot.answerInlineQuery(query.id, [{
      id: '0', 
      type: 'article', 
      title: 'Title', 
      description: 'Markdown', 
      message_text: query.query,
      parse_mode: 'Markdown'
    }]);
});
```

**Comment by edusis** [comment]
@coredox thats correct!. I found a new error if the message_text is blank:

    Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad request: Message text is empty"}
    at /home/ubuntu/workspace/node_modules/node-telegram-bot-api/src/telegram.js:135:15
    at tryCatcher (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
