### ISSUE TITLE
How to use promote chat member

### ISSUE THREAD

**Issue by clintgallivan** [yagop/node-telegram-bot-api#874]
I am trying to use the method (promoteChatMember) but I get back `error: [polling_error] {}`

Here is my code

```
bot.on("message", (msg) => {
  const chatId = msg.chat.id;
  const userId = msg.from.id;
  if (msg.text.includes("hi")) {
    bot.sendMessage(chatId, `Hello ${userId}`);
    bot.promoteChatMember(chatId, userId, false, true);
    console.log(userId);
  }
});
```

here is the telegram API docs:
https://core.telegram.org/bots/api#promotechatmember

go to "promoteChatMember" for the method.

Thank you!!!

**Comment by danielperez9430** [comment]
Hi mate,
Here is an example of use, the tutorial is in Spanish but you can easily translate it.

https://tecnonucleous.com/2020/05/27/como-cambiar-el-titulo-custom-de-administrador-de-un-usuario-mediante-un-bot/

**Comment by AbhijithNT** [comment]
```js
bot.onText(/\/hi/, function onLoveText(msg) {
  bot.sendMessage(msg.chat.id, "Hello, World!");
});

```


https://github.com/yagop/node-telegram-bot-api/blob/master/examples/polling.js
