### ISSUE TITLE
Bug: editMessageMedia does not support upload of local files

### ISSUE THREAD

**Issue by windkh** [yagop/node-telegram-bot-api#876]
First of all thanks for your great work.

### Expected Behavior

I am trying to use editMessageMedia with a local photo file as described here
https://core.telegram.org/bots/api#editmessagemedia
https://core.telegram.org/bots/api#inputmediaphoto
I though that the file would be uploaded when passing a local path (just like when sending photos).

### Actual Behavior

ETELEGRAM: 400 Bad Request: wrong HTTP URL specified when processing message

### Steps to reproduce the Behavior

By sneaking into the code of editMessageMedia I am missing a call to _formatSendData.
Is there a reason why this is missing? Or am I totally wrong?

  editMessageMedia(media, form = {}) {
    form.media = stringify(media);
    return this._request('editMessageMedia', { form });
  }

**Comment by windkh** [comment]
I created a local function which works (see sendMediaGroup), however I am not sure if this would fit into your ideas:

`
editMessageMedia = function (media, form = {}){
            
            const opts = {
                qs: form,
              };
              opts.formData = {};

            const payload = Object.assign({}, media);
            delete payload.media;
            delete payload.fileOptions;

            try {
                const attachName = String(0);
                const [formData, fileId] = this._formatSendData(attachName, media.media, media.fileOptions);
                if (formData) {
                    opts.formData[attachName] = formData[attachName];
                    payload.media = `attach://${attachName}`;
                  } else {
                    payload.media = fileId;
                  }
            } catch (ex) {
                return Promise.reject(ex);
            }

            opts.qs.media = JSON.stringify(payload);
            return this._request('editMessageMedia', opts);
        }`

**Comment by danielperez9430** [comment]
Fixed in version 0.55.0 of the library
