### ISSUE TITLE
Pipe ytdl stream in bot.sendAudio()

### ISSUE THREAD

**Issue by hugorplobo** [yagop/node-telegram-bot-api#879]
Well, I'm coding a bot to download YouTube videos, using this library and ytdl-core. Currently, I'm creating a file for the video and then uploading it, but it's slow, so I tried to use this:

```
const stream = ytdl.downloadFromInfo(videoInfo, { filter: "audioonly" }); // ytdl.downloadFromInfo() return a Readable
bot.sendAudio(chatId, stream);

```

No errors appear, but nothings happens. So, how can I do that?

**Comment by AbhijithNT** [comment]
https://core.telegram.org/bots/api#sendaudio
