### ISSUE TITLE
supergroup support?

### ISSUE THREAD

**Issue by lagleki** [yagop/node-telegram-bot-api#88]
Can it be used to send data to supergroups?

**Comment by yagop** [comment]
I haven't tested, but I've seen bots in supergroups so it should.

**Comment by astrolince** [comment]
It doesn't work with this module.

**Comment by yagop** [comment]
I tested and its working.

Make sure you've enabled inline mode for sending to supergroup directly.

The request is the same for a supergroup except the ID
