### ISSUE TITLE
member_limit on createChatInviteLink doesn't work

### ISSUE THREAD

**Issue by diogo-palma** [yagop/node-telegram-bot-api#884]
I am using the latest version of the library.

And when i call the createChatInviteLink  i use member_limit only 1 person, but when i shared the link to another user of telegram,
he can open the link of group..
Is this a bug of telegram?

**Comment by danielperez9430** [comment]
Invite links have a curious use case. Imagine that you create a link for 1 person and that person uses it by entering the group (the link reached its maximum of 1 use), but then this same person leaves the group. Well, now the link has an available use again.

In my opinion, the best thing is that you put an expiration date on the link and as soon as the user enters, delete that link.
