### ISSUE TITLE
Refefral system in telegraf

### ISSUE THREAD

**Issue by horahir** [yagop/node-telegram-bot-api#885]
Question

I want to ask how can we create Refferal system in Nodejs by telegraf framework
Pls help me 

> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by rawb0t** [comment]
This seems not only out-of-scope, but also rather vague. Do you have a specific question about NTBA or do you just need general coding help?

**Comment by kamikazechaser** [comment]
Open the issue at telegraf/telegraf
