### ISSUE TITLE
I uploaded my code to Heroku but it gives me an error "FatalError: EFATAL: Telegram Bot Token not provided!"

### ISSUE THREAD

**Issue by Marcuuu** [yagop/node-telegram-bot-api#887]
I have provided the token over here.

`require('dotenv').config();
const TelegramBot = require('node-telegram-bot-api');
const moment = require('moment');

const token = process.env.TOKEN;

const bot = new TelegramBot(token, {
  polling: true
});`

However, after deploying into Heroku, the logs tells me that I did not provide the token to the bot.

![image](https://user-images.githubusercontent.com/50865913/124581528-c446fa00-de83-11eb-9f51-ab3870ddcf18.png)

**Comment by omega-u20** [comment]
## Did you set **'Config Vars'**

![cnfig](https://user-images.githubusercontent.com/76775101/124879666-135b6f00-dfeb-11eb-9d38-86558bf836a8.PNG)

or 

update line
```javascript
const token = process.env.TOKEN; 
```
as
```javascript
const token = process.env.TOKEN || /*<put your token here>*/; 
```

In my case this worked

**Comment by AbhijithNT** [comment]
```ts
import * as dotenv from "dotenv";
dotenv.config();
```
