### ISSUE TITLE
Cannot answer inline  query

### ISSUE THREAD

**Issue by ddavlet** [yagop/node-telegram-bot-api#892]
> Why inline query is not working? I've tried the simple example from other issue here, but still cannot get result. Please, show me where I do something wrong. What I want here is simply get article pop up above inline and show article described

bot.on('inline_query', query => {
  bot.answerInlineQuery(query.id, [{
          id: '0',
          type: 'article',
          title: 'Preview Title',
          description: 'Preview Description',
          message_text: 'Inline query data'
      }]
    )
})

**Comment by VanillaTank** [comment]
i think, you could use 'callback_query', not 'inline_query'
