### ISSUE TITLE
Keyboard button "search"

### ISSUE THREAD

**Issue by ddavlet** [yagop/node-telegram-bot-api#895]
Hello! How to make searching button in keyboard? 

In simple example below, when user press "search" button, I want to filter next messages in order to accept them as keywords for searching in databse untill next button (for instance 'main menu') is pressed. 

example:

```javascript
bot.onText (/\/start/, msg => {
    bot.sendMessage(msg.chat.id, 'Main menu',{
      reply_markup: {
    keyboard: [
      ['search','instruction']
    ]
  }})})
bot.on
```

**Comment by kamikazechaser** [comment]
You need to maintains some sort of state in both your `message` and `callback_query` listener.

This is a pseudo-code of how it can be achieved:

```js
bot.on("message")
    if state = search
        // build search query here

bot.on("callback_query")
    if cbq = "search_btn"
        state.set("search")
    if cbq = "done_btn"
        state.unset("search")
```

Also this question is better suited for StackOverflow
