### ISSUE TITLE
pollng after sending location

### ISSUE THREAD

**Issue by Eyobedk** [yagop/node-telegram-bot-api#898]
hi guys i was trying to create a telegram bot that sends a location after receiving some texts, but when ever i tried to send my location(using telegram location button to send location) it keeps throwing polling error please i need help am on a deadline       error: [polling_error] {}
here is my code

bot.onText(/\/start/, (msg) => {

    bot.sendMessage(msg.chat.id, "welcome to app name"){  
        "reply_markup": {
            "keyboard": ["Arada", "Gullele"]
        }
    });

});

bot.on('message', (msg) => {
   var feelings = [
        "Arada", "Gullele"
    ];

    if (msg.text.indexOf(feelings[0]) === 0) {
        bot.sendMessage(msg.chat.id, "Your data is registered");    
    }
      else if (msg.text.indexOf(feelings[1]) === 0) {
        bot.sendMessage(msg.chat.id, "Your data is not registered");    
    }

//  THE PROBLEM IS HERE
bot.on("location",(msg)=>{
    bot.sendMessage(msg.chat.id, "We will deliver your order to " + [msg.location.longitude,msg.location.latitude].join(";"));
});

**Comment by kamikazechaser** [comment]
This is not an issue on NTBA side. I have used your exact code and [it works for me](https://imgur.com/atG8NNC.png). This is probably an issue with your code or network.
