### ISSUE TITLE
Telegram bot payment, sendInvoice method, Pay button don't answer .

### ISSUE THREAD

**Issue by normatov11** [yagop/node-telegram-bot-api#899]
Hi everyone. I have one issue. 
I am using telegram TEST payment . 

why don't answer the pre_checkout_query during press pay button ?

![image](https://user-images.githubusercontent.com/78676106/131086390-b211f7a5-3de7-4f3e-a87a-78b681cb7fe0.png)

after press Pay button no request come my domen...

so don't add any card this payment .
when click Payment Method , get error this like :

![image](https://user-images.githubusercontent.com/78676106/131087008-854c7e84-3f80-4543-8256-cec78db3b904.png)

**Comment by kamikazechaser** [comment]
Problem with Telegram Desktop.
