### ISSUE TITLE
How to create a back button in about me section in telegram bot

### ISSUE THREAD

**Issue by leanardo7994** [yagop/node-telegram-bot-api#900]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by kamikazechaser** [comment]
Check stack-overflow, similar questions have been asked there. Or ask in the group.
