### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Henrique400** [yagop/node-telegram-bot-api#901]
Mjm

**Comment by nagulan51** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/8f94e6d0-4aac-4c50-a609-18e87cd7cc33-e79fbdd1-f4cd-43a6-8776-cce2fa742b30-v1.png?transparent=1&palette=1&width=246)![bitmoji](https://sdk.bitmoji.com/render/panel/8f94e6d0-4aac-4c50-a609-18e87cd7cc33-e79fbdd1-f4cd-43a6-8776-cce2fa742b30-v1.png?transparent=1&palette=1&width=246)
