### ISSUE TITLE
[Feature]: Tests to run on CI (GitHub Actions)

### ISSUE THREAD

**Issue by ShaileshKumar007** [yagop/node-telegram-bot-api#902]
> Feature Request

I have:  Tests to run on CI (GitHub Actions)

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

There is no "workflows" folder and no "test.yml"  file present in Actions folder. Therefore, tests not running on push or pull request.

### Example

We can add it to GitHub Actions. Below is the code snippet that can resolve this issue:
![bot api](https://user-images.githubusercontent.com/71178959/132119675-cfdbfe64-ff61-48d9-8855-bd174db7f082.JPG)

**Comment by danger89** [comment]
Very disappointed that github actions is not being used (if only on top of the existing ci/cd).
