### ISSUE TITLE
I want to add the Top Referral button but how can I get the referral list like this picture. (Node.js)

### ISSUE THREAD

**Issue by earnbuzz** [yagop/node-telegram-bot-api#905]
![iMarkup_20210912_221432](https://user-images.githubusercontent.com/40410758/133015311-df3832cb-9887-4b08-ad85-a77f0f364408.jpg)

> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by kamikazechaser** [comment]
Use Keyboards, you can find several examples in the past issues and Stackoverflow.
