### ISSUE TITLE
feature request: edit multiple messages in one API call

### ISSUE THREAD

**Issue by mikelpr** [yagop/node-telegram-bot-api#908]
> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

A way to batch multiple message edits in one call, to avoid hitting API limits so easily

### Example
```
bot.editMessageText([
  {text1, {message_id_1, chat_id}},
  {text2, {message_id_2, chat_id}},
  {text3, {message_id_3, chat_id}},
  {text4, {message_id_4, chat_id}},
])
```

> Question

is this limited by telegram's API and therefore impossible?

**Comment by toniop99** [comment]
Hello!

This is not allowed by the Telegram API

**Comment by kamikazechaser** [comment]
You could look into https://github.com/gochomugo/tgfancy, maybe fork and update it and use with Promise.all
