### ISSUE TITLE
Can't use bot-api add (members | users) to channel

### ISSUE THREAD

**Issue by Jinghao1209** [yagop/node-telegram-bot-api#910]
Its sounds like a protection mechanism....Any information I have checked so far, I have not seen that you can use bot-api to add users to <channel>....it is a protection mechanism to protect user? or have method to do this but i don't know....pls tell me, i have post same of this question in stackoverflow, at: [here](https://stackoverflow.com/questions/69785752/telegram-how-can-i-add-user-to-channel)

it is have any method? using user_id or username? is this fixed?

**Comment by danielperez9430** [comment]
Hi @Jinghao1209 , you can't do it with the Bot API. You can only do it using your Telegram account as userbot, for do it you need to use any library based on MTProto API or TDLib.  

But remember, adding people without permission to a channel can end up limiting your Telegram account. There is also a limit of 200 people per account

**Comment by Jinghao1209** [comment]
> Hi @Jinghao1209 , you can't do it with the Bot API. You can only do it using your Telegram account as userbot, for do it you need to use any library based on MTProto API or TDLib.  
> 
> But remember, adding people without permission to a channel can end up limiting your Telegram account. There is also a limit of 200 people per account

thank you!
