### ISSUE TITLE
How to download Telegram url 

### ISSUE THREAD

**Issue by mayeaux** [yagop/node-telegram-bot-api#914]
If I have a link on Telegram such as https://t.me/channelName/1234

How can I download the video file?

I've been looking all over and the best I can do is a 400 error.

**Comment by danielperez9430** [comment]
The bot can only download this file if:

- The bot is inside the channel and you pass the message id for download
- You forward the video to the bot an download it

But you can't download the video only using the channelName link if your bot is not and admin in this channel
