### ISSUE TITLE
Inline Calendar

### ISSUE THREAD

**Issue by IliaSmagloy** [yagop/node-telegram-bot-api#917]
Hello everyone,

I'm working with this library and I'm quite satisfied.
Unfortunately I was looking for an inline calendar and I only found such for the telegraf framework,
Does anybody know of a project related to such features? 
Are they in  development here?

Thanks!

**Comment by Jeszpy** [comment]
@IliaSmagloy ,  hello! And then I got the same problem =(

**Comment by VDS13** [comment]
@Jeszpy @IliaSmagloy https://www.npmjs.com/package/telegram-inline-calendar

**Comment by yagop** [comment]
Nice library.

@IliaSmagloy is this solved now?

**Comment by VDS13** [comment]
> Nice library.
> 
> 
> 
> @IliaSmagloy is this solved now?

Thanks)
