### ISSUE TITLE
Why my bot can't get 'new_chat_members' event when the group is over 10k members ?

### ISSUE THREAD

**Issue by sekaiamber** [yagop/node-telegram-bot-api#923]
Hello, bro :)

I have a bot using to manage my group.

And when my group is under 10k members, when a new member join my group, everything work fine:

```typescript
bot.on('message', (message, meta) => {
  console.log(meta)  // { type: "new_chat_members" }
})
bot.on('new_chat_members', (message, meta) => {
  console.log(message)  // Great
})
```

But when my group reach 10k members. `bot` can not get the 'new_chat_members' event, even 'message' event.

Any ideas?

----

By the way, I have tried #918 . Nothing changed.

----

My config:

```typescript
const bot = new Bot(TOKEN, {
  polling: {
    params: {
      allowed_updates: [
        'update_id',
        'message',
        'edited_message',
        'channel_post',
        'edited_channel_post',
        'inline_query',
        'chosen_inline_result',
        'callback_query',
        'shipping_query',
        'pre_checkout_query',
        'poll',
        'poll_answer',
        'my_chat_member',
        'chat_member',
        'chat_join_request',
      ],
    },
  },
})
```

**Comment by danielperez9430** [comment]
Hi @sekaiamber, first stop your bot and put this "url" in the browser. You only need to remplace `<YOUR_BOT_TOKEN>`, before that you can get the updates of the "`chat_member`". You don't need to pass any extra parameter in polling if you do it using this url.

```
https://api.telegram.org/bot<YOUR_BOT_TOKEN>/getUpdates?allowed_updates=["update_id", "message", "edited_message", "channel_post", "edited_channel_post", "inline_query", "chosen_inline_result", "callback_query", "shipping_query", "pre_checkout_query", "poll", "poll_answer", "my_chat_member", "chat_member"]
```

**Comment by Mrsayyed** [comment]
I have this problem too
please explain more

**Comment by danielperez9430** [comment]
@Mrsayyed In summary "chat_member" is a optional update, but if you need this update you need to pass the array of "all updates" that you need. In the end the easy way to do is setup manual 1 time and you can get it easy

**Comment by ljs19923** [comment]
Hey I have a problem around the same topic. For the same channel, for some invitation links, I got the chat_member update from Telegram and for some others users randomly around 10-30%, I don't receive updates... do you know an idea why?

Thanks a lot

I opened a bug
https://bugs.telegram.org/c/27242

<img width="539" alt="Screen Shot 2023-04-15 at 14 03 36" src="https://user-images.githubusercontent.com/5727223/232187772-f5dca2fc-d958-4a7c-afd8-556c55b22a20.png">
