### ISSUE TITLE
Question: How to direct message someone using the id or username of the user?

### ISSUE THREAD

**Issue by doppelgunner** [yagop/node-telegram-bot-api#924]
Question: How to direct message someone using the id or username of the user?
- For example, the user dm the bot for commands, but just in case the user wants to subscribe to a specific notification that only the specific user is suppose to receive. How do I achieve that?

For example, i want the bot to message the user about a specific stock after some days/weeks.
- and i only have the users' id and username stored in db.

**Comment by DesnLee** [comment]
You can add a field to the database like `subscribed: true/false`.

When you send a notification, simply find the specific user and send the message to them.

**Comment by doppelgunner** [comment]
@DesnLee Thanks, but I mean how do  i do that with the api?

**Comment by doppelgunner** [comment]
@DesnLee Saw it, just asked a pretty obvious question sorry my bad
