### ISSUE TITLE
Is selfbotting possible?

### ISSUE THREAD

**Issue by pedrokpp** [yagop/node-telegram-bot-api#926]
> Question

I'm thinking on changing my selfbot from python to node because I'm having some problems that I'll check if they still occur when I run it with node, but I didn't found any examples or material on how to use this library with a selfbot such as a phone number or something like that

Is that possible with this library? If so, how? I've searched a bit for any issue that had something regarding this but didn't find anything.

Sorry if this is a duplicate of some question or you don't support it.

Thank you in advance!

**Comment by danielperez9430** [comment]
Hi @pedrokpp, you can use this library with normal bots (`no userbots`) and you can use self host version of telegram bot api (https://github.com/tdlib/telegram-bot-api).

Using self host telegram bot api you can upload/download files up to 2GB. If you search something for user bots you need to use tdlib.
