### ISSUE TITLE
how i use MessageAutoDeleteTimerChanged ?

### ISSUE THREAD

**Issue by eminyalcin** [yagop/node-telegram-bot-api#929]
i have 2 telegram group. i use only a telegram group for MessageAutoDeleteTimerChanged function.

**Comment by danielperez9430** [comment]
Hi @eminyalcin , 
MessageAutoDeleteTimerChanged is not a fuction, is only a message type `message_auto_delete_timer_changed` that you can listen. The oficial Telegram Bot API don't provide any function to set auto delete timer in chats using bots for the moment.
