### ISSUE TITLE
bot.on("message") not triggered

### ISSUE THREAD

**Issue by christopheSeeka** [yagop/node-telegram-bot-api#931]
Hello,

I installed latest version of the lib and i'm trying to follow the basic example but for some reason, the bot.on("message") is not triggered when i do a /start then "hi" to my bot, here is my code:

```
const TelegramBot = require('node-telegram-bot-api');
const token = '508***0Rg';

const bot = new TelegramBot(token, {polling: true});

bot.on('message', (msg) => {
  console.log(msg)
});
```

then i run node index.js i get the following warning:
"node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated."

and then nothing happens when i /start then message the bot

i tried also NTBA_FIX_319=1 node index.js, it remove the warning but doesnt change the problem.

What can i be doing wrong?

**Comment by PabloFacciano** [comment]
Hello, did you try `bot.on('text', ...)` ?

**Comment by christopheSeeka** [comment]
Hello, thank you for the answer, yes i tried both and they were not working but i finally figured it.
I just created a new bot and it worked... not sure why...
I guess it's because i first didn't set the privacy to the bot and added it to my test group, then i set privacy. Probably would have had to removed it and re add it to the group? Anyway, fixed, thank you very much :)

**Comment by danielperez9430** [comment]
Yes, for read messages in a group that is not a bot command (`/...@botalias`) you need to change the bot privacy in `@BotFather`. In the other case you can only listen the message when the user is talk with the bot (user <-> bot chat 1 to 1)
