### ISSUE TITLE
left_chat_member in supergroup more then 50 members

### ISSUE THREAD

**Issue by dtorov** [yagop/node-telegram-bot-api#933]
hi!

how to get left_chat_member message in supergroup more then 50 members? 
i set manual https://api.telegram.org/bot123/getUpdates?allowed_updates=["update_id", "message", "edited_message", "channel_post", "edited_channel_post", "inline_query", "chosen_inline_result", "callback_query", "shipping_query", "pre_checkout_query", "poll", "poll_answer", "my_chat_member", "chat_member"]
but it does not help...
```
let tmBot = new TelegramBot(bot.config.botToken,
            {
                polling: {
                    params: {allowed_updates: JSON.stringify(["update_id", "message", "edited_message", "channel_post", "edited_channel_post", "inline_query", "chosen_inline_result", "callback_query", "shipping_query", "pre_checkout_query", "poll", "poll_answer", "my_chat_member", "chat_member"])}
                }
            });
```
does not help too...
what can try also?

**Comment by tjhorner** [comment]
If your bot is an administrator in the chat you're targeting, you can use the `chat_member` event: https://core.telegram.org/bots/api#chatmemberupdated

**Comment by danielperez9430** [comment]
```js
const bot = new TelegramBot(TOKEN, {
    polling: {
        params: {
            "allowed_updates": JSON.stringify(["update_id", "message", "edited_message", "channel_post", "edited_channel_post", "inline_query", "chosen_inline_result", "callback_query", "shipping_query", "pre_checkout_query", "poll", "poll_answer", "my_chat_member", "chat_member"])
        }
    }
});
```

bot.on("chat_member", (evt) => {})

**Comment by ljs19923** [comment]
Hey I have a problem around the same topic. For the same channel, for some invitation links, I got the chat_member update from Telegram and for some others users randomly around 10-30%, I don't receive updates... do you know an idea why?

Thanks a lot

I opened a bug
https://bugs.telegram.org/c/27242 

<img width="595" alt="Screen Shot 2023-04-15 at 14 07 07" src="https://user-images.githubusercontent.com/5727223/232188566-88998d81-69bc-46a2-b009-9a583dd8d4de.png">
