### ISSUE TITLE
Looping Broadcast Increament .

### ISSUE THREAD

**Issue by Arjun-M** [yagop/node-telegram-bot-api#936]
let success = 0
let error = 0
for (let x in data.users) { 
      Bot.copyMessage (data.users[x] , data.owner , body.callback_query.data.split(" ")[1] ) 
      .then(options => { success += 1 })
      .catch(err =>{ error += 1 }) 
}
console.log (success)
console.log (error)
        
Broadcast code i used . I want it like it should increment success & error. 

Tried using .then() and .catch()  , but found its not working..

**Comment by kamikazechaser** [comment]
Question better suited for stackoverflow.
