### ISSUE TITLE
Is it possible to read a file ?

### ISSUE THREAD

**Issue by Arjun-M** [yagop/node-telegram-bot-api#939]
I need a code that can help to read a file .
Here the code i used .,

Bot.downloadFile(body.message.reply_to_message.document.file_id , "server/assets/"+body.message.reply_to_message.document.file_name ) .then(qq=>{
          let newFile = JSON.parse( fs.readFileSync("server/assets/"+body.message.reply_to_message.document.file_name , 'utf8') )
          let oldFile = JSON.parse( fs.readFileSync( 'server/history/'+code+'.json' , 'utf8'))
          let merged = { ...newFile ,  ...oldFile }
          fs.writeFileSync( 'server/history/'+code+'.json' , JSON.stringify(merged));
          fs.unlinkSync("server/assets/"+body.message.reply_to_message.document.file_name)
          return Bot.sendDocument(body.message.from.id ,  'server/history/'+code+'.json' , {} , {contentType: 'application/json' , filename: Date.now()+".json"})
        }).catch (err=>{ 
            console.log (err)
            Bot.sendMessage(body.message.from.id , "Unable to merge datas ." , {reply_to_message_id: body.message.message_id}) 
        })

*Recived Error :* [Error: ENOENT: no such file or directory, open 'server/assets/1644634301796.json/file_2.json']

*Is it possible to do using file stream ?*
@yagop  , @GochoMugo , @all

**Comment by ddavlet** [comment]
It seems you are reading file directory, but not the file itself. Try to read file here:
`let newFile = JSON.parse( fs.readFileSync("server/assets/"+body.message.reply_to_message.document.file_name+"FILENAME" , 'utf8') )`
