### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by fengqifengluo** [yagop/node-telegram-bot-api#941]
The console shows:
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ETIMEDOUT 182.50.139.56:443"}

why could it happen? the programm can't connect to the server?

**Comment by danielperez9430** [comment]
You can get better error messages with this piece of code:

```js
 bot.on('polling_error', (err) => {
     console.log(err)
});
```

But yes, in the end you have a internet problem connection to the Telegram servers
