### ISSUE TITLE
aiogram.utils.exceptions.BadRequest: Wrong remote file identifier specified: wrong string length

### ISSUE THREAD

**Issue by jekYT** [yagop/node-telegram-bot-api#946]
![image](https://user-images.githubusercontent.com/74921063/155273053-7ed03900-f902-43ea-8af3-b7555558092f.png)
![image](https://user-images.githubusercontent.com/74921063/155273074-7a6c64dd-b309-47f1-a924-727858504242.png)

**Comment by jekYT** [comment]
How can this problem be solved and what is it? I have already tried all the options, checked all the variables, checked the entire database and don't know what to do?

**Comment by Gerayd** [comment]
Have you solved your problem?

**Comment by danielperez9430** [comment]
Umm, airgram is a python library and this repo is only for node
