### ISSUE TITLE
setMyCommands not working properly

### ISSUE THREAD

**Issue by AdelaFoofur82** [yagop/node-telegram-bot-api#949]
> Bug Report

### Expected Behavior

setMyCommands actual sets the commands of the bot

### Actual Behavior

Not changes, but receiving a true

### Steps to reproduce the Behavior

Using:

```javascript
bot.setMyCommands([
  {command: "prueba", description: "Esto es una prueba"}
], { scope: {type: "all_group_chats"}, language_code: "es"});
```

returns true, but no changes applied.

I guess it's the way is sending the info, because it uses internally  ```x-www-form-urlencoded``` and sending it as JSON works:

```javascript
const fetch = require('node-fetch');

// ....

bot.request = async function (command, json) {
  return fetch(`${bot.options.baseApiUrl}/bot${bot.token}/${command}`, {
    method: 'post',
    body: JSON.stringify(json),
    headers: { 'Content-Type': 'application/json' }
  });
}
  
bot.request('setMyCommands', {
   commands: [{command: "prueba", description: "Esto es una prueba"}],
   scope: {type: "all_group_chats"},
   language_code: "es"
});
```

I think is the mix of sending the array of commands as a stringified JSON while sending everything else as ```x-www-form-urlencoded```  format.

Maybe you should use JSON in the entire library? It seems to be the native way of Telegram API to work.

**Comment by IscoV** [comment]
I don't know how but it was solved 

I tried setting the commands via BotFather, I don't know if this is what fixed the problem.

**Comment by danielperez9430** [comment]
@gladunvv The scope object need to parse a `JSON.stringify()`. We can do it internal in the library the fix and you don't need to put it the stringify. Fix in the next release

**Comment by cleivson** [comment]
I believe the scope part of the setMyCommands and getMyCommands is also broken. The GetMyCommands call doesn't send the scope at all

**Comment by bigbigsir** [comment]
> 

+1

**Comment by renardein** [comment]
+1

**Comment by deulizealand** [comment]
+1 same problem

**Comment by DeadLyBro** [comment]
I tried just now, working for me. ( `setMyCommands` with `node-fetch` )

**Comment by vadimkonovod** [comment]
> I tried just now, working for me. ( `setMyCommands` with `node-fetch` )

Could you please share the payload for setMyCommands request?

**Comment by DeadLyBro** [comment]
> Could you please share the payload for setMyCommands request?

Sure try this; 
```js
const telegramBot = require('node-telegram-bot-api');
const bot = new telegramBot(token, { polling: true });
const fetch = require('node-fetch');

const token = "BOT_TOKEN"

bot.request = async function (command, json) {
    return fetch(`https://api.telegram.org/bot${token}/${command}`, {
      method: 'post',
      body: JSON.stringify(json),
      headers: { 'Content-Type': 'application/json' }
    });
}

bot.request('setMyCommands', {
    commands: [
        {
            command: "Command 1",
            description: "Command 1 Description."
        },
        {
            command: "Command 2",
            description: "Command 2 Description."
        }  
    ],
    scope: {"type": "all_private_chats"}, // This is adding commands for Private Message with Bot. Find Scopes on API.
    language_code: "en" // Language; en = English.
});
```

**Comment by DeadLyBro** [comment]
Oh also you don't need to add slash ( / ) inside command string.

**Comment by royaljacques** [comment]
`js
bot.request = async function (command, json) {
    return fetch(`https://api.telegram.org/bot${token}/${command}`, {
        method: 'post',
        body: JSON.stringify(json),
        headers: { 'Content-Type': 'application/json' }
    });
}
bot.request('setMyCommands', {
    commands: [
        {
            command: "Command 1",
            description: "Command 1 Description."
        },
        {
            command: "Command 2",
            description: "Command 2 Description."
        }
    ],
    scope: {"type": "all_private_chats"}, // This is adding commands for Private Message with Bot. Find Scopes on API.
    language_code: "en" // Language; en = English.
}).then(r => console.log(r));
`
Response {
  [Symbol(realm)]: null,
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: true,
    requestIncludesCredentials: true,
    type: 'default',
    status: 400,
    timingInfo: {
      startTime: 333.6870999969542,
      redirectStartTime: 0,
      redirectEndTime: 0,
      postRedirectStartTime: 333.6870999969542,
      finalServiceWorkerStartTime: 0,
      finalNetworkResponseStartTime: 0,
      finalNetworkRequestStartTime: 0,
      endTime: 0,
      encodedBodySize: 78,
      decodedBodySize: 78,
      finalConnectionTimingInfo: null
    },
    cacheState: '',
    statusText: 'Bad Request',
    headersList: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    body: { stream: undefined }
  },
      'connection' => 'keep-alive',
      'strict-transport-security' => 'max-age=31536000; includeSubDomains; preload',
      'access-control-allow-origin' => '*',
      'access-control-expose-headers' => 'Content-Length,Content-Type,Date,Server,Connection'
    },
    [Symbol(headers map sorted)]: null
  }
}

**Comment by DeadLyBro** [comment]
I'm sending this for who doesn't understand; 
( P.S: If `node-fetch` not work, try with `2.6.7` version. You can install with; `npm install node-fetch@2.6.7` , but don't forget uninstall previous version with; `npm uninstall node-fetch`. ) 
Sorry for my poor English :)

```js
const telegramBot = require('node-telegram-bot-api');

const token = "YOUR_BOT_TOKEN_HERE";

const bot = new telegramBot(token, { polling: true });
const fetch = require('node-fetch');

bot.request = async function (command, json) {
    return fetch(`https://api.telegram.org/bot${token}/${command}`, {
      method: 'post',
      body: JSON.stringify(json),
      headers: { 'Content-Type': 'application/json' }
    });
}

bot.request('setMyCommands', {
    commands: [
        {
            command: "start",
            description: "This is start the game hehe..."
        }
    ],
    scope: {"type": "all_private_chats"},
    language_code: "en"
}).then(r => console.log(r));

bot.onText(/\/start/, (msg) => {

    bot.sendMessage(msg.chat.id, `Welcome.`, {
        "reply_markup": {
            "keyboard": [
                ["Sample text", "Second sample"]
            ]
        }
    });

});
```

**Comment by michael-tordil** [comment]
anyone tried doing this in C#?

**Comment by teolex** [comment]
I'm doing what you guys are trying to do with **java**.
I found [this](https://stackoverflow.com/questions/78558408/telegram-bot-setmycommands-and-getmycommands-implementation) and it gives me, like
![image](https://github.com/user-attachments/assets/498e22f2-9c92-4129-82b9-d23e942e0e5b)
It doesn't even give me true or false. It's because it failed sending the SetMyCommands, obviously.

It seems that using 'https://api.telegram.org/bot${token}/setMyCommands' is the only way to achieve what we want. Isn't it?

**Comment by DeadLyBro** [comment]
> I'm doing what you guys are trying to do with **java**. I found [this](https://stackoverflow.com/questions/78558408/telegram-bot-setmycommands-and-getmycommands-implementation) and it gives me like,
> 
> ![image](https://private-user-images.githubusercontent.com/2646244/376561004-498e22f2-9c92-4129-82b9-d23e942e0e5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODcxMTEsIm5iZiI6MTcyODk4NjgxMSwicGF0aCI6Ii8yNjQ2MjQ0LzM3NjU2MTAwNC00OThlMjJmMi05YzkyLTQxMjktODJiOS1kMjNlOTQyZTBlNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTAwNjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI3NTQ3NzJlMDUwMzBkYzYwY2RhNDQ4N2U4YTQzNWViN2FkOTEzNDIzNTc0MTY2ZjRkZmJiZmIyZWMyOTdjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WeoqFDIGJTXYRJswrmAxCdjxmypyUsAjG1zKfWMB3m8)
> 
> It doesn't even give me true or false. It's because it failed sending the SetMyCommands, obviously.
> 
> It seems that using '[https://api.telegram.org/bot${token}/setMyCommands](https://api.telegram.org/bot$%7Btoken%7D/setMyCommands)' is the only way to achieve what we want. Isn't it?

I use it with fetch (Node Fetch v2.6.7) using this url: 
```
https://api.telegram.org/bot${token}/${command}
```

and set body with JSON strings, you can see my previous messages.
