### ISSUE TITLE
how to remove button menu?

### ISSUE THREAD

**Issue by d1zz7** [yagop/node-telegram-bot-api#952]
There are such buttons near the message input field, how to remove them?
[**View image**](https://imgur.com/a/hmXGB5P)

**Comment by d1zz7** [comment]
It seems to be one_time_keyboard

**Comment by ashiapppppppp** [comment]
> It seems to be `one_time_keyboard`

bot.onText(/\/love/, function onLoveText(msg) {
  const opts = {
    reply_to_message_id: msg.message_id,
    reply_markup: JSON.stringify({
      one_time_keyboard: true,
      keyboard: [
        ['Yes, you are the bot of my life ❤'],
        ['No, sorry there is another one...']
      ]
    }),
  };
  bot.sendMessage(msg.chat.id, 'Do you love me?', opts);
});
