### ISSUE TITLE
How to avoid sending A user's result to B when calling an async result from another nodejs file

### ISSUE THREAD

**Issue by Dsvida1** [yagop/node-telegram-bot-api#956]
My bot gets the message from the user. After getting the message, bot.js will call scan.js. Scan.js is responsible for processing the query transaction. When scan.js is executed, it will call back to bot.js, but I encounter a problem. If I use synchronous means then the bot is very slow in concurrent situation, but if I use asynchronous method to call scan.js callback the result will become as the title describes

**Comment by danielperez9430** [comment]
In the end it is more a matter of programming logic than anything else.

If you also send the user id to that function and then when returning the response you use the id of that asynchronous function. So you are 100% sure that you are sending the data to the correct user
