### ISSUE TITLE
Retrieve channel's list of users

### ISSUE THREAD

**Issue by joao-pedro-alves** [yagop/node-telegram-bot-api#960]
Is it possible to retrieve channel's list of users from a channel my bot is in?

**Comment by danielperez9430** [comment]
Hi @JaakkoLipsanen,
It is not possible, the Telegram bots API doesn't have a method to get that data.

This function could be obtained by using a userbot (using your Telegram account as a bot).

For this you should use a library like Tdlib or Pyrogram (that use MTProto).
