### ISSUE TITLE
make videocall to stream a video

### ISSUE THREAD

**Issue by realrecordzLab** [yagop/node-telegram-bot-api#962]
I'm running a bot on a google cloud VM. 
I want to stream video using it, is possible to start a video call that will have the video to stream as a source that the user can see when it will answer to the videocall?

**Comment by danielperez9430** [comment]
The Telegram Bot API don't have this option, but you can use the stream keys (you can get from the Telegram app) and with this keys and using a command possible you can do create a bot that use this keys a reproduce the stream using other library for streaming the video using the protocol `RTMP`
