### ISSUE TITLE
Support for Telegram Bot Revolution (API 6.0)

### ISSUE THREAD

**Issue by theimo1221** [yagop/node-telegram-bot-api#965]
> Feature Request

### Introduction

Supporting the new [Bot Revolution Features](https://core.telegram.org/bots/webapps) Telegram announced would be helpful to improve Bot functionality.

### Example

Unfortunately as this is quite new, I wasn´t able to find one

**Comment by planecore** [comment]
Looks like @danielperez9430 started adding support in #966

**Comment by danielperez9430** [comment]
In principle, the design of the web bot and the methods that are on that page are inside the script that is used to create the web bot.

The only new methods that have to be added to this library in question are the ones I have in the pull request.

**Comment by xino1010** [comment]
@danielperez9430 would you mind to update typings, please?

**Comment by danielperez9430** [comment]
> @danielperez9430 would you mind to update typings, please?

Types are in another repository:

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node-telegram-bot-api

Right now I don't have too much time to do it, but if someone can do it...  I can't assure you that I will do it soon, because I don't usually have too much time during the week 😅

**Comment by planecore** [comment]
I created a discussion in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60116

**Comment by konstantin24121** [comment]
I create a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60120 , dont know how long it's took

**Comment by konstantin24121** [comment]
Types for 6.0 are published
