### ISSUE TITLE
Listing pending join requests

### ISSUE THREAD

**Issue by joao-pedro-alves** [yagop/node-telegram-bot-api#968]
Is there any way to get the list of pending join requests of a channel?

**Comment by danielperez9430** [comment]
Hi @joao-pedro-alves 

Currently the Telegram bots API does not have any method to obtain the pending requests, you can only listen to the new requests.

**Comment by ndastur** [comment]
Can this be re-opened as looks like there is an API for this https://core.telegram.org/method/messages.getChatInviteImporters

**Comment by danielperez9430** [comment]
> Can this be re-opened as looks like there is an API for this https://core.telegram.org/method/messages.getChatInviteImporters

This url is from the "client" API (MTProto) not the Bot API. So, no is possible to implement this method in the bot API.
