### ISSUE TITLE
Gif compression

### ISSUE THREAD

**Issue by krokofant** [yagop/node-telegram-bot-api#97]
The image quality of the animated image sent via sendDocument ( because sendPhoto doesn't support animations #11 ) is reduced a lot.

First image is the image sent via sendDocument and the other two are from the Telegram OSX client. All three are animated. The first one seems to be received as a mp4.
<img width="348" src="https://cloud.githubusercontent.com/assets/5908498/14006051/774aa60a-f169-11e5-9a30-72bb745a36db.png">

Source image: http://tclhost.com/X5ncR3i.gif

**Comment by yagop** [comment]
What is the point of the issue? Warn users?

PS: An image of an [Alot](https://cloud.githubusercontent.com/assets/5002453/14160341/190eac1c-f6dc-11e5-9d12-22f6cd980197.png)

**Comment by krokofant** [comment]
Is the noticeable quality difference nothing at all to think about? The point of this issue is to highlight the quality degradation which is happening via this API relative to the Telegram OS X client.

**Comment by yagop** [comment]
Well, it's, but isn't matter of this module. The compression is done by the Telegram servers, blame them if you wish.
