### ISSUE TITLE
Can't send inline keyboard 

### ISSUE THREAD

**Issue by rezcoco** [yagop/node-telegram-bot-api#974]
When I trying to send inline keyboard i always get error like this 
can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard

Here is my code
const opts = {
   reply_markup:{
     inline_keyboard: [ [{ text: "Hello", callback_data: "hello"}] ] 
   },
  parse_mode: 'HTML'
};

**Comment by rezcoco** [comment]
Im so dumb, i write data instead of callback_data

**Comment by dobobaie** [comment]
@rezcoco unexpected answer 😄
