### ISSUE TITLE
cannot find module readble-stream/duplex

### ISSUE THREAD

**Issue by im-shamil** [yagop/node-telegram-bot-api#983]
node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'readable-stream/duplex'

**Comment by danielperez9430** [comment]
Hi @im-shamil , can you add more information to your issue?

For example:

- Node version
- Function that you use to send file/...
- Code example

**Comment by im-shamil** [comment]
node version: v18.3.0
npm version: npm@7.6.0
code: 
```javascript
const bot = require ("node-telegram-bot-api")```

**Comment by im-shamil** [comment]
fixed thankyou

**Comment by Joffey** [comment]
> fixed thankyou

can you share how to fix this, thx
