### ISSUE TITLE
Bot messages are not caught

### ISSUE THREAD

**Issue by S0nicB0om** [yagop/node-telegram-bot-api#984]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.
v0.58.0

### Expected Behavior

I would like to catch messages from other bots in my group.

### Actual Behavior

I have a group with 2 bots and my user account.
BotA: is the bot I use to catch messages with:
`this.mTelegramBot.on('message', (message: Message) => {
            // do something
        });`
BotB: just send messages
My user account just send messages as well.

when I send a message from my user account, BotA catch my messages, but when BotB send a message nothing happen on BotA event listener.

I tried with different events such as 'text', but from what I understood 'message' is suppose to catch any kind of messages (audio, video, text...)

### Steps to reproduce the Behavior

* Create a group
* Create a botA and add it to group
* Run a script with node-telegram-bot-api to listen on 'message' event from BotA
* Create a botB and add it to group
* Run a script that just send a message on an interval like every 2s
* Send message from the user account you used to create the group

**Comment by danielperez9430** [comment]
Hi @S0nicB0om , the bots can get/read messages from others bots. Is a `Telegram Bot API limitation` server side.

For example: In method getChatAdministrators you can get other bots in the list the admin list. In your telegram client (as  a user) you can see it, but bots can do it

<img width="823" alt="image" src="https://user-images.githubusercontent.com/10388515/177858961-a685fd24-f9d6-49de-bcfd-257f8894e01b.png">

**Comment by S0nicB0om** [comment]
Hi @danielperez9430 

Thanks for your answer, but I'm still unable to catch messages from bots.
I forgot to mention that BotA, which is suppose to listen all messages going through the group. Must be admin with eventually all the permission checked.
BotB which is just a spammer, is just a member of the group.

I created two repo, if it can help to test it.

[Repo 1](https://github.com/S0nicB0om/spy-bot.git), the spying bot which just listen a display messages caught in the console: https://github.com/S0nicB0om/spy-bot.git
[Repo 2](https://github.com/S0nicB0om/spam-bot.git), the spammer bot that just send the same message every 5s: https://github.com/S0nicB0om/spam-bot.git
Check the REAME.md file to set it up properly.

Best regards

**Comment by S0nicB0om** [comment]
Ok, so if I have a group with 5000 members (humans and bots), my admin bot won't be able to warn me if the current message is from a bot... Is there no other way to do that?

My goal is to remove automatically all messages that come from a bot.

Is there no feature like getChatAdministrators but to get all members? Then I could loop through all members and check if there are bot or not.

**Comment by danielperez9430** [comment]
Hi @S0nicB0om ,

the unique way is use your own account as "bot" (userbot). You create a user bot you need a library based in MTProto API (Clients API). For do this thing you can use Tdlib (Multiplatform - you possible need to search about a wrapper for nodejs), Madeliproto (PHP), Pyrogram (Ptyhon)...

**Comment by S0nicB0om** [comment]
OK, thank you @danielperez9430
