### ISSUE TITLE
call back query send duplicate messages

### ISSUE THREAD

**Issue by developerHet** [yagop/node-telegram-bot-api#985]
> Whenever inline button clicked by user call back query send duplicate messages so what type of changes I need to do to `not` send duplicate messages.

`
          movieRatingList.map((movie, idx) => {
            var movieRating = Math.round(movie.rating * 10) / 10;
            if (movieRating == bestRating) {
              var firstName = movieList[idx].firstName;
              keyboard.push([{ text: firstName, callback_data: idx }]);
            }
          });

          bot.sendMessage(userChatId, userText, {
            reply_markup: JSON.stringify({
              resize_keyboard: true,
              inline_keyboard: keyboard,
            }),
          });

          bot.on("callback_query", (callBackData) => {
            var idx = Number(callBackData.data);

            var fileID = movieList[idx].file_id;
            var firstName = movieList[idx].firstName;
            console.log(fileID);
            console.log(firstName);
            bot.sendDocument(userChatId, fileID, { caption: firstName });
            
          });
`

**Comment by IscoV** [comment]
I do it in the following way and there is no duplication of messages.

I think that in your case duplicity is produced by adding it inside the same function where you send the message.

```js
function send_message(){
    // Listeners
    let listenerCallback;
    let listenerCommand;

    // Actions listeners
    listenerCommand = ((responseCommand) => {
        let {chat, from, message_id} = respondeCommand;

        // More code or send_message with buttons

    });

    listenerCallback = ((responseCallback) => {
        let {id, from, message, data} = responseCallback;

        // More code or actions to buttons

    });
    
    // Commands
    bot.onText(/^\/start/, listenerCommand);
    bot.on("callback_query", listenerCallback);

};
```

The only drawback I see is that this .on() event will be active listening for all buttons and not just specific buttons.

**Comment by developerHet** [comment]
@IscoV thank you for help . I make changes according to your suggestions and my issue got solved.
