### ISSUE TITLE
Support for telegram test environment

### ISSUE THREAD

**Issue by Polm90** [yagop/node-telegram-bot-api#990]
Is there a way to use the testing environment as described in the [official documentation](https://core.telegram.org/bots/webapps#using-bots-in-the-test-environment)?
Thank you

**Comment by danielperez9430** [comment]
Hi Polm90,
for the moment no. But we can implement a option for do it soon !!

**Comment by Polm90** [comment]
I think it would be great!
Thank you!

**Comment by tinsaeDev** [comment]
I have added the feature, please review and merge it.

https://github.com/yagop/node-telegram-bot-api/pull/994

**Comment by danielperez9430** [comment]
Now is merge, tomorrow I will send other changes that I have locally and in a few days we will make the release
