### ISSUE TITLE
setChatMenuButton not working

### ISSUE THREAD

**Issue by tinsaeDev** [yagop/node-telegram-bot-api#995]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior
the setChatMenuButton shall set chat's menu button programatically.
### Actual Behavior

Instead it is just removing existing menu buttons.
### Steps to reproduce the Behavior

```JavaScript
        bot.setChatMenuButton( {
            chat_id : chatId,
            menu_button : {
                text : "Order food",
                type:"web_app",
                web_app:{
                    url : "https://tg.elevator.com.et",                                            
                }
            }
        }   );
```

The above code shall set menu button for the specified chatId        

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Introduction

I am building a bot webapp that needs to have a chat bot menu set dynamically

### Example

> Question

**Comment by danielperez9430** [comment]
Hi, @tinsaeDev you need to do JSON.stringify of the menu_button object

**Comment by sergeycw** [comment]
@danielperez9430 hi! I'm trying to set my menu button like this
`bot.setChatMenuButton(
    JSON.stringify({
      chat_id: msg.chat.id,
      menu_button: {
        text: 'Order food',
        type: 'commands',
      },
    }) as any,
  );
`
and it's not working. I had registered the list of commands with the help of BotFather

**Comment by Borodin** [comment]
> bot.setChatMenuButton(
>     JSON.stringify({
>       chat_id: msg.chat.id,
>       menu_button: {
>         text: 'Order food',
>         type: 'commands',
>       },
>     }),
>   );
>>
```js
bot.setChatMenuButton(
    {
      chat_id: msg.chat.id,
      menu_button: JSON.stringify( {
        text: 'Order food',
        type: 'commands',
      },
    }),
  );
  ```

**Comment by Comandante7s** [comment]
> > bot.setChatMenuButton( 
> > JSON.stringify({ 
> > chat_id: msg.chat.id, 
> > menu_button: { 
> > texto: 'Pedir comida', 
> > tipo: 'comandos', 
> > }, 
> > }), 
> > );
> > >
> 
> ```js
> bot.setChatMenuButton(
>     {
>       chat_id: msg.chat.id,
>       menu_button: JSON.stringify( {
>         text: 'Order food',
>         type: 'commands',
>       },
>     }),
>   );
> ```

Hola, recien agrego, no muestra error alguno pero tampoco el boton. Saludos.
